package hxl

import (
	"encoding/json"
	"fmt"
	"math"
	"os"
	"path/filepath"
	"strconv"
	"testing"
)

// TestGenerateFMACorpus (HXL_CORPUS_GEN_FMA=1) writes tests/corpus/hxl/fma_sensitive.jsonc: inputs
// found by search where fusing the multiply-add into one FMA changes the result (06 §1.2 rule 7).
// Expected values come from the IEEE definition of the unfused expression computed here (every
// product explicitly rounded), not from either VM; both runners re-check the FMA sensitivity.
func TestGenerateFMACorpus(t *testing.T) {
	if os.Getenv("HXL_CORPUS_GEN_FMA") == "" {
		t.Skip("set HXL_CORPUS_GEN_FMA=1 to regenerate fma_sensitive.jsonc")
	}
	rng := splitMix64{0x5eed0f0a}
	randFloat := func(minExp, maxExp int) float64 {
		m := 1 + float64(float64(rng.next()>>11)*0x1p-53)
		e := minExp + int(rng.next()%uint64(maxExp-minExp+1))
		v := math.Ldexp(m, e)
		if rng.next()&1 != 0 {
			v = -v
		}
		return v
	}
	usable := func(v float64) bool {
		return !math.IsNaN(v) && !math.IsInf(v, 0) && (v == 0 || math.Abs(v) >= 0x1p-1022)
	}
	hex := func(v float64) string { return strconv.FormatFloat(v, 'x', -1, 64) }

	type kind struct {
		name, src, fma string
		fields         []string
		count          int
		gen            func() ([]float64, float64, []float64)
	}
	kinds := []kind{
		{"fma.mul_add", "v.a * v.b + v.c", "mul_add", []string{"a", "b", "c"}, 300, func() ([]float64, float64, []float64) {
			a, b := randFloat(-30, 30), randFloat(-30, 30)
			p := float64(a * b)
			c := randFloat(-60, 60)
			if rng.next()%3 == 0 { // near-cancellation: the product's rounding error dominates
				c = -float64(p * (1 + float64(randFloat(-40, -20))))
			}
			return []float64{a, b, c}, p + c, []float64{math.FMA(a, b, c)}
		}},
		{"fma.mul_sub", "v.a * v.b - v.c", "mul_sub", []string{"a", "b", "c"}, 200, func() ([]float64, float64, []float64) {
			a, b := randFloat(-20, 20), randFloat(-20, 20)
			p := float64(a * b)
			c := float64(p * (1 + float64(randFloat(-45, -10))))
			return []float64{a, b, c}, p - c, []float64{math.FMA(a, b, -c)}
		}},
		{"fma.sub_mul", "v.c - v.a * v.b", "sub_mul", []string{"a", "b", "c"}, 200, func() ([]float64, float64, []float64) {
			a, b := randFloat(-25, 25), randFloat(-25, 25)
			p := float64(a * b)
			c := randFloat(-50, 50)
			if rng.next()%2 == 0 {
				c = float64(p * (1 + float64(randFloat(-40, -15))))
			}
			return []float64{a, b, c}, c - p, []float64{math.FMA(-a, b, c)}
		}},
		{"fma.dot2", "v.a * v.b + v.c * v.d", "dot2", []string{"a", "b", "c", "d"}, 200, func() ([]float64, float64, []float64) {
			a, b := randFloat(-15, 15), randFloat(-15, 15)
			c := randFloat(-15, 15)
			ratio := -float64(a*b) / c
			d := float64(ratio * (1 + randFloat(-40, -20)))
			ab, cd := float64(a*b), float64(c*d)
			return []float64{a, b, c, d}, ab + cd, []float64{math.FMA(a, b, cd), math.FMA(c, d, ab)}
		}},
		{"fma.lerp", "lerp(v.a, v.b, v.t)", "lerp", []string{"a", "b", "t"}, 150, func() ([]float64, float64, []float64) {
			a := randFloat(-10, 10)
			b := randFloat(-10, 10)
			tt := math.Abs(randFloat(-8, -1))
			d := b - a
			return []float64{a, b, tt}, a + float64(d*tt), []float64{math.FMA(d, tt, a)}
		}},
	}
	type caseJSON struct {
		Name     string   `json:"name"`
		Src      string   `json:"src"`
		Params   []string `json:"params"`
		Bytecode string   `json:"bytecode"`
		Fma      string   `json:"fma"`
		Rows     struct {
			Param  string     `json:"param"`
			Fields []string   `json:"fields"`
			Data   [][]string `json:"data"`
		} `json:"rows"`
	}
	var cases []caseJSON
	total := 0
	for _, k := range kinds {
		prog, err := Compile(k.src, CompileOptions{Params: []string{"v"}})
		if err != nil {
			t.Fatal(err)
		}
		c := caseJSON{Name: k.name, Src: k.src, Params: []string{"v"}, Fma: k.fma}
		c.Bytecode = fmt.Sprintf("%016x", prog.Hash())
		c.Rows.Param = "v"
		c.Rows.Fields = k.fields
		for tries := 0; len(c.Rows.Data) < k.count; tries++ {
			if tries > 1000000 {
				t.Fatalf("%s: not enough FMA-sensitive vectors", k.name)
			}
			in, want, fusedVals := k.gen()
			ok := usable(want)
			for _, v := range in {
				ok = ok && usable(v)
			}
			for _, f := range fusedVals {
				ok = ok && math.Float64bits(f) != math.Float64bits(want)
			}
			if !ok {
				continue
			}
			row := make([]string, 0, len(in)+1)
			for _, v := range in {
				row = append(row, hex(v))
			}
			row = append(row, hex(want))
			c.Rows.Data = append(c.Rows.Data, row)
		}
		total += len(c.Rows.Data)
		cases = append(cases, c)
	}
	doc := map[string]any{
		"description": "Generated by services/pkg/hxl/fmagen_test.go (HXL_CORPUS_GEN_FMA=1): vectors where fusing a multiply-add into an FMA changes the result (06 §1.2 rule 7). Expected values are the IEEE results of the unfused expressions; both runners re-check with fma() that every row is FMA-sensitive.",
		"cases":       cases,
	}
	out, err := json.MarshalIndent(doc, "", " ")
	if err != nil {
		t.Fatal(err)
	}
	path := filepath.Join(corpusDir(t), "fma_sensitive.jsonc")
	if err := os.WriteFile(path, append(out, '\n'), 0o644); err != nil {
		t.Fatal(err)
	}
	t.Logf("wrote %d FMA-sensitive rows to %s", total, path)
}

type splitMix64 struct{ s uint64 }

func (r *splitMix64) next() uint64 {
	r.s += 0x9e3779b97f4a7c15
	z := r.s
	z = (z ^ (z >> 30)) * 0xbf58476d1ce4e5b9
	z = (z ^ (z >> 27)) * 0x94d049bb133111eb
	return z ^ (z >> 31)
}
