// Seeded violation (review finding (d)): a test generated by a file-local macro at global scope.
#include <doctest/doctest.h>

#define MAKE_TEST(name) TEST_CASE(name) { CHECK(true); }

MAKE_TEST("demo: generated at global scope")

namespace {
TEST_CASE("demo: a plain test") {
    CHECK(true);
}
} // namespace
