# Runs spirv-val (through helios-shaderc --reflect-spirv, which also reflects each module) over every
# SPIR-V module the build cooks (03 §1.7: "spirv-val runs over every cooked shader in Linux CI"):
# exactly the modules helios_shaders() declared, one path per line in MODULES_FILE, so a stale .spv
# left in an output directory is not counted and a declared module that was not built fails. An empty
# list fails. With -DREQUIRE=ON a missing spirv-val fails; otherwise the script prints the line that
# the CTest's SKIP_REGULAR_EXPRESSION reports as Skipped.
# Inputs: -DSHADERC=<exe> -DMODULES_FILE=<file> [-DREQUIRE=ON] [-DSPIRV_VAL=<spirv-val>]

cmake_minimum_required(VERSION 3.28)
if(NOT SHADERC OR NOT MODULES_FILE)
  message(FATAL_ERROR "usage: cmake -DSHADERC=<exe> -DMODULES_FILE=<file> [-DREQUIRE=ON] -P validate_spirv.cmake")
endif()
if(NOT EXISTS "${MODULES_FILE}")
  message(FATAL_ERROR "module list ${MODULES_FILE} does not exist (re-run CMake)")
endif()
file(STRINGS "${MODULES_FILE}" modules)
list(FILTER modules EXCLUDE REGEX "^[ \t]*$")
list(LENGTH modules expected)
if(expected EQUAL 0)
  message(FATAL_ERROR "${MODULES_FILE} lists no SPIR-V modules")
endif()
set(missing "")
foreach(spv IN LISTS modules)
  if(NOT EXISTS "${spv}")
    list(APPEND missing "${spv}")
  endif()
endforeach()
if(missing)
  string(REPLACE ";" "\n  " text "${missing}")
  message(FATAL_ERROR "declared SPIR-V modules were not built (build before testing):\n  ${text}")
endif()

set(mode auto)
if(REQUIRE)
  set(mode on)
endif()
set(validator "")
if(SPIRV_VAL)
  set(validator --spirv-val "${SPIRV_VAL}")
endif()
set(dirs "")
foreach(spv IN LISTS modules)
  execute_process(COMMAND "${SHADERC}" --reflect-spirv "${spv}" --no-hsr --validate ${mode} ${validator}
                  RESULT_VARIABLE rc OUTPUT_VARIABLE out ERROR_VARIABLE err)
  if(NOT rc EQUAL 0)
    message(FATAL_ERROR "${spv}: helios-shaderc/spirv-val failed (${rc}):\n${out}${err}")
  endif()
  if(out MATCHES "validation skipped")
    message(STATUS "spirv-val not found: validation skipped")
    return()
  endif()
  get_filename_component(dir "${spv}" DIRECTORY)
  list(APPEND dirs "${dir}")
endforeach()
# Per output directory, so a helios_shaders() call whose modules went missing stands out.
set(counted "")
foreach(dir IN LISTS dirs)
  if(NOT dir IN_LIST counted)
    list(APPEND counted "${dir}")
    set(n 0)
    foreach(d IN LISTS dirs)
      if(d STREQUAL dir)
        math(EXPR n "${n} + 1")
      endif()
    endforeach()
    get_filename_component(name "${dir}" NAME)
    message(STATUS "spirv-val: ${name}: ${n} module(s) valid")
  endif()
endforeach()
message(STATUS "spirv-val: ${expected} module(s) valid")
