# Seeded violations for `helios-cook check` and the records cook (WP-0.20; 09 §2.1 "Records compile;
# 100 % provenance"). Copies SOURCE's helios.project.jsonc, content/ and schemas/ (which the project file's
# schemas.native names) into WORK, seeds one violation (CASE) and runs helios-cook: every case but `valid`
# must fail (non-zero exit) with its diagnostic, and `valid`, the unchanged copy, must pass both verbs, so
# no case passes because the copy itself is broken.
# The cases find their targets by pattern (the first file of a kind), so they follow the content as it
# grows, and name no content (the IP-name lint keeps reference names out of apps/).
#
#   cmake -DCOOK=<helios-cook> -DSOURCE=<repository root> -DWORK=<scratch dir> -DCASE=<case>
#         -P content_check_test.cmake

cmake_minimum_required(VERSION 3.28)
foreach(v COOK SOURCE WORK CASE)
  if(NOT DEFINED ${v} OR "${${v}}" STREQUAL "")
    message(FATAL_ERROR "content_check_test: pass -D${v}=...")
  endif()
endforeach()

file(REMOVE_RECURSE "${WORK}")
file(MAKE_DIRECTORY "${WORK}")
file(COPY "${SOURCE}/helios.project.jsonc" DESTINATION "${WORK}")
file(COPY "${SOURCE}/content" "${SOURCE}/schemas" DESTINATION "${WORK}")
set(project "${WORK}/helios.project.jsonc")

# The first file (in sorted order) under WORK/content matching `glob`, skipping hidden paths.
function(first_file glob out)
  file(GLOB_RECURSE found LIST_DIRECTORIES false "${WORK}/content/${glob}")
  list(SORT found)
  foreach(f IN LISTS found)
    file(RELATIVE_PATH rel "${WORK}/content" "${f}")
    if(NOT rel MATCHES "(^|/)\\.")
      set(${out} "${f}" PARENT_SCOPE)
      return()
    endif()
  endforeach()
  message(FATAL_ERROR "content_check_test: no ${glob} under content/ to seed case ${CASE}")
endfunction()

# Replaces every match of `pattern` in `file`; a pattern that matches nothing is an error, so a case can
# never pass on an unchanged copy.
function(replace file pattern replacement)
  file(READ "${file}" text)
  string(REGEX REPLACE "${pattern}" "${replacement}" changed "${text}")
  if(changed STREQUAL text)
    message(FATAL_ERROR "content_check_test: '${pattern}' is not in ${file} (case ${CASE})")
  endif()
  file(WRITE "${file}" "${changed}")
endfunction()

# Copies a document and its sidecar into `dir`.
function(copy_with_sidecar file dir)
  file(MAKE_DIRECTORY "${dir}")
  file(COPY "${file}" "${file}.meta" DESTINATION "${dir}")
endfunction()

set(verb check)
set(args "--project-root=${WORK}")
if(CASE STREQUAL "valid")
  set(expect "")
elseif(CASE STREQUAL "missing_sidecar")
  first_file("*.hrec.meta" f)
  file(REMOVE "${f}")
  set(expect "\\.hrec: no sidecar, so the asset has no GUID")
elseif(CASE STREQUAL "bad_licence")
  first_file("*.meta" f)
  replace("${f}" "\"licence\": \"[^\"]*\"" "\"licence\": \"GPL-3.0-only\"")
  set(expect "provenance\\.licence: .*GPL-3\\.0-only.* is not an allowed licence")
elseif(CASE STREQUAL "ai_without_record")
  first_file("*.meta" f)
  replace("${f}" "\"origin\": \"[^\"]*\"" "\"origin\": \"ai-assisted\"")
  set(expect "an ai-assisted asset records the tool, model, prompt and inputs")
elseif(CASE STREQUAL "unknown_type")
  file(WRITE "${WORK}/content/notes.txt" "A file of a type the cook does not know.\n")
  set(expect "content/notes\\.txt: not a content document type the cook knows \\(\\.txt\\)")
elseif(CASE STREQUAL "hidden_file")
  first_file("*.hrec" f)
  get_filename_component(dir "${f}" DIRECTORY)
  file(COPY_FILE "${f}" "${dir}/.stash.hrec")
  set(expect "/\\.stash\\.hrec: hidden, so the provenance scan skips it")
elseif(CASE STREQUAL "undeclared_zone")
  first_file("*.hcont" f)
  copy_with_sidecar("${f}" "${WORK}/content/zones/undeclared")
  set(expect "content/zones/undeclared: not a zone of helios\\.project\\.jsonc")
elseif(CASE STREQUAL "spatial_outside_zone")
  first_file("*.hcont" f)
  copy_with_sidecar("${f}" "${WORK}/content")
  set(expect "a spatial document outside zones/<zone>/")
elseif(CASE STREQUAL "global_in_zone")
  first_file("*.hcont" c)
  get_filename_component(zoneDir "${c}" DIRECTORY)
  first_file("*.hrec" f)
  copy_with_sidecar("${f}" "${zoneDir}")
  set(expect "a \\.hrec document in a zone folder: only spatial documents")
elseif(CASE STREQUAL "container_group")
  first_file("*.hcont" f)
  replace("${f}" "\"group\": \"zone\\." "\"group\": \"zonex.")
  set(expect "streaming\\.group: 'zonex\\.[a-z0-9_]*' is not its zone's group")
elseif(CASE STREQUAL "container_identity")
  first_file("*.hcont" f)
  file(READ "${f}.meta" text)
  string(REGEX MATCH "\"guid\": \"([0-9a-f])" m "${text}")
  set(other 0)
  if(CMAKE_MATCH_1 STREQUAL "0")
    set(other 1)
  endif()
  replace("${f}.meta" "\"guid\": \"[0-9a-f]" "\"guid\": \"${other}")
  set(expect "its sidecar's GUID [0-9a-f-]+ differs from \\$container")
elseif(CASE STREQUAL "entity_name")
  first_file("*.hent" f)
  get_filename_component(dir "${f}" DIRECTORY)
  set(renamed "${dir}/00000000-0000-4000-8000-000000000001.hent")
  file(RENAME "${f}" "${renamed}")
  file(RENAME "${f}.meta" "${renamed}.meta")
  set(expect "\\$entity: '[0-9a-f-]+' differs from the file name's GUID '00000000-0000-4000-8000-000000000001'")
elseif(CASE STREQUAL "project_unknown_key")
  replace("${project}" "\"\\$project\": 0," "\"$project\": 0, \"bogus\": 1,")
  set(expect "helios\\.project\\.jsonc: bogus: unknown key")
elseif(CASE STREQUAL "project_tick_rate")
  replace("${project}" "\"tickHz\": [0-9]+" "\"tickHz\": 61")
  set(expect "zones\\[0\\]\\.tickHz: a tick rate is an integer in 1\\.\\.60 Hz")
elseif(CASE STREQUAL "project_reserved_scheme")
  replace("${project}" "\"uriScheme\": \"[^\"]*\"" "\"uriScheme\": \"https\"")
  set(expect "product\\.uriScheme: 'https' is reserved")
elseif(CASE STREQUAL "hidden_directory")
  first_file("*.hrec" f)
  file(MAKE_DIRECTORY "${WORK}/content/.stash")
  file(COPY_FILE "${f}" "${WORK}/content/.stash/kept.hrec")
  set(expect "content/\\.stash: hidden, so the provenance scan skips it")
elseif(CASE STREQUAL "cook_then_check")
  # The records cook's default output (<root>/.cooked) is ignored by git and skipped by the check.
  execute_process(COMMAND "${COOK}" records "--project-root=${WORK}/content" RESULT_VARIABLE rc OUTPUT_QUIET
                  ERROR_VARIABLE err)
  if(NOT rc EQUAL 0 OR NOT EXISTS "${WORK}/content/.cooked/records.server.hrdb")
    message(FATAL_ERROR "content_check_test: the default cook did not write content/.cooked (exit ${rc}):\n${err}")
  endif()
  set(expect "")
elseif(CASE STREQUAL "record_outside_records")
  first_file("*.hrec" f)
  copy_with_sidecar("${f}" "${WORK}/content/loose")
  set(expect "a record outside records/<table>/, which the records cook never reads")
elseif(CASE STREQUAL "container_guid_form")
  first_file("*.hcont" f)
  replace("${f}" "\"\\$container\": \"guid:" "\"$container\": \"")
  set(expect "\\$container: expected \"guid:<GUID>\"")
elseif(CASE STREQUAL "container_name")
  first_file("*.hcont" f)
  replace("${f}" "\"name\": \"" "\"name\": \"renamed_")
  set(expect "name: 'renamed_[a-z0-9_]+' differs from the file name's")
elseif(CASE STREQUAL "container_frame_parent")
  first_file("*.hcont" f)
  replace("${f}" "\"parent\": \"[a-z]+:" "\"parent\": \"planet:")
  set(expect "frame\\.parent: expected \"<kind>:<name>\"")
elseif(CASE STREQUAL "entity_outside_folder")
  first_file("*.hcont" c)
  get_filename_component(zoneDir "${c}" DIRECTORY)
  first_file("*.hent" f)
  copy_with_sidecar("${f}" "${zoneDir}")
  set(expect "an entity sits in its container's <name>\\.entities/ folder")
elseif(CASE STREQUAL "entity_without_container")
  first_file("*.hent" f)
  get_filename_component(dir "${f}" DIRECTORY)
  string(REGEX REPLACE "\\.entities$" ".hcont" container "${dir}")
  file(REMOVE "${container}" "${container}.meta")
  set(expect "its container .*\\.hcont does not exist")
elseif(CASE STREQUAL "project_missing")
  file(REMOVE "${project}")
  set(expect "helios\\.project\\.jsonc: missing")
elseif(CASE STREQUAL "project_version")
  replace("${project}" "\"\\$project\": 0" "\"$project\": 1")
  set(expect "\\$project: format version 1 is newer than this build's")
elseif(CASE STREQUAL "project_duplicate_key")
  replace("${project}" "\"\\$project\": 0," "\"$project\": 0, \"channels\": [\"dev\"],")
  set(expect "channels: duplicate key")
elseif(CASE STREQUAL "project_engine_version")
  replace("${project}" "\"engineVersion\": \"[^\"]*\"" "\"engineVersion\": \"0.1\"")
  set(expect "engineVersion: expected MAJOR\\.MINOR\\.PATCH")
elseif(CASE STREQUAL "project_gem")
  replace("${project}" "\"gems\": {[^}]*}" "\"gems\": {\"client\": [\"nosuchgem\"], \"server\": []}")
  set(expect "gems\\.client: gem 'nosuchgem' has no gems/nosuchgem/gem\\.jsonc.*gems\\.server: not a build target")
elseif(CASE STREQUAL "project_native_package")
  replace("${project}" "\"native\": \\[" "\"native\": [\"nosuchpackage\", ")
  set(expect "package 'nosuchpackage' has no \\.hschema files")
elseif(CASE STREQUAL "project_content_root")
  replace("${project}" "\"contentRoots\": \\[" "\"contentRoots\": [\"missing\", \"../outside\", ")
  set(expect "contentRoots: '\\.\\./outside'.*contentRoots: 'missing' is not a directory")
elseif(CASE STREQUAL "project_zone_frame")
  replace("${project}" "\"frame\": \"[a-z]+:" "\"frame\": \"galaxy:")
  set(expect "zones\\[0\\]\\.frame: a zone's root frame is")
elseif(CASE STREQUAL "project_zone_id")
  replace("${project}" "\"id\": [0-9]+" "\"id\": 7")
  replace("${project}" "\"zones\": \\["
          "\"zones\": [{\"name\": \"second\", \"id\": 7, \"tickHz\": 1, \"frame\": \"system:second\"}, ")
  set(expect "zones\\[1\\]\\.id: zone id 7 is used twice")
elseif(CASE STREQUAL "project_product_id")
  replace("${project}" "\"productId\": \"[^\"]*\"" "\"productId\": \"helios-game\"")
  set(expect "product\\.productId: ids that start with 'helios' are the engine's own products")
elseif(CASE STREQUAL "project_install_name")
  replace("${project}" "\"installName\": \"[^\"]*\"" "\"installName\": \"COM1\"")
  set(expect "product\\.installName: a Windows reserved device name")
elseif(CASE STREQUAL "project_display_name")
  replace("${project}" "\"displayName\": {[^}]*}" "\"displayName\": {}")
  set(expect "product\\.displayName: needs one entry per shipped language")
elseif(CASE STREQUAL "broken_record")
  # A record the cook must refuse, beside the real ones (with a sidecar, so only the cook can catch it).
  first_file("*.hrec" f)
  get_filename_component(dir "${f}" DIRECTORY)
  get_filename_component(table "${dir}" NAME)
  file(WRITE "${dir}/broken_fixture.hrec"
       "{\n  \"$rid\": 4611686018427387905,\n  \"$name\": \"${table}/broken_fixture\",\n  \"noSuchField\": 1\n}\n")
  file(COPY_FILE "${f}.meta" "${dir}/broken_fixture.hrec.meta")
  set(verb records)
  set(args "--project-root=${WORK}/content" "--out=${WORK}/cooked")
  set(expect "broken_fixture\\.hrec: .*noSuchField.*nothing written")
else()
  message(FATAL_ERROR "content_check_test: unknown case '${CASE}'")
endif()

execute_process(COMMAND "${COOK}" ${verb} ${args} RESULT_VARIABLE rc OUTPUT_VARIABLE out ERROR_VARIABLE err)
set(all "${out}${err}")
if(CASE STREQUAL "valid" OR CASE STREQUAL "cook_then_check")
  if(NOT rc EQUAL 0)
    message(FATAL_ERROR "content_check_test: the unchanged copy fails `check` (exit ${rc}):\n${all}")
  endif()
  execute_process(COMMAND "${COOK}" records "--project-root=${WORK}/content" "--out=${WORK}/cooked"
                  RESULT_VARIABLE rc OUTPUT_VARIABLE out2 ERROR_VARIABLE err2)
  if(NOT rc EQUAL 0)
    message(FATAL_ERROR "content_check_test: the unchanged copy fails `records` (exit ${rc}):\n${out2}${err2}")
  endif()
  message(STATUS "the unchanged copy passes:\n${out}${out2}")
  return()
endif()
if(rc EQUAL 0)
  message(FATAL_ERROR "content_check_test: helios-cook ${verb} succeeded on case ${CASE} (expected '${expect}'). Output:\n${all}")
endif()
if(NOT all MATCHES "${expect}")
  message(FATAL_ERROR "content_check_test: helios-cook ${verb} failed on case ${CASE}, but without '${expect}'. Output:\n${all}")
endif()
message(STATUS "failed as expected (exit ${rc}): ${expect}")
