# Seeded violations for `helios-cook check` and the records cook (WP-0.20; 09 §2.1 "Records compile;
# 100 % provenance"). Copies SOURCE's helios.project.jsonc, content/ and schemas/ (which the project file's
# schemas.native names) into WORK, seeds one violation (CASE) and runs helios-cook: every case but `valid`
# must fail (non-zero exit) with its diagnostic, and `valid`, the unchanged copy, must pass both verbs, so
# no case passes because the copy itself is broken.
# The cases find their targets by pattern (the first file of a kind), so they follow the content as it
# grows, and name no content (the IP-name lint keeps reference names out of apps/).
#
#   cmake -DCOOK=<helios-cook> -DSOURCE=<repository root> -DWORK=<scratch dir> -DCASE=<case>
#         -P content_check_test.cmake

cmake_minimum_required(VERSION 3.28)
foreach(v COOK SOURCE WORK CASE)
  if(NOT DEFINED ${v} OR "${${v}}" STREQUAL "")
    message(FATAL_ERROR "content_check_test: pass -D${v}=...")
  endif()
endforeach()

file(REMOVE_RECURSE "${WORK}")
file(MAKE_DIRECTORY "${WORK}")
file(COPY "${SOURCE}/helios.project.jsonc" DESTINATION "${WORK}")
file(COPY "${SOURCE}/content" "${SOURCE}/schemas" DESTINATION "${WORK}")
set(project "${WORK}/helios.project.jsonc")

# The first file (in sorted order) under WORK/content matching `glob`, skipping hidden paths.
function(first_file glob out)
  file(GLOB_RECURSE found LIST_DIRECTORIES false "${WORK}/content/${glob}")
  list(SORT found)
  foreach(f IN LISTS found)
    file(RELATIVE_PATH rel "${WORK}/content" "${f}")
    if(NOT rel MATCHES "(^|/)\\.")
      set(${out} "${f}" PARENT_SCOPE)
      return()
    endif()
  endforeach()
  message(FATAL_ERROR "content_check_test: no ${glob} under content/ to seed case ${CASE}")
endfunction()

# Replaces every match of `pattern` in `file`; a pattern that matches nothing is an error, so a case can
# never pass on an unchanged copy.
function(replace file pattern replacement)
  file(READ "${file}" text)
  string(REGEX REPLACE "${pattern}" "${replacement}" changed "${text}")
  if(changed STREQUAL text)
    message(FATAL_ERROR "content_check_test: '${pattern}' is not in ${file} (case ${CASE})")
  endif()
  file(WRITE "${file}" "${changed}")
endfunction()

# Copies a document and its sidecar into `dir`.
function(copy_with_sidecar file dir)
  file(MAKE_DIRECTORY "${dir}")
  file(COPY "${file}" "${file}.meta" DESTINATION "${dir}")
endfunction()

set(verb check)
set(args "--project-root=${WORK}")
if(CASE STREQUAL "valid")
  set(expect "")
elseif(CASE STREQUAL "missing_sidecar")
  first_file("*.hrec.meta" f)
  file(REMOVE "${f}")
  set(expect "\\.hrec: no sidecar, so the asset has no GUID")
elseif(CASE STREQUAL "bad_licence")
  first_file("*.meta" f)
  replace("${f}" "\"licence\": \"[^\"]*\"" "\"licence\": \"GPL-3.0-only\"")
  set(expect "provenance\\.licence: .*GPL-3\\.0-only.* is not an allowed licence")
elseif(CASE STREQUAL "ai_without_record")
  first_file("*.meta" f)
  replace("${f}" "\"origin\": \"[^\"]*\"" "\"origin\": \"ai-assisted\"")
  set(expect "an ai-assisted asset records the tool, model, prompt and inputs")
elseif(CASE STREQUAL "unknown_type")
  file(WRITE "${WORK}/content/notes.txt" "A file of a type the cook does not know.\n")
  set(expect "content/notes\\.txt: not a content document type the cook knows \\(\\.txt\\)")
elseif(CASE STREQUAL "hidden_file")
  first_file("*.hrec" f)
  get_filename_component(dir "${f}" DIRECTORY)
  file(COPY_FILE "${f}" "${dir}/.stash.hrec")
  set(expect "/\\.stash\\.hrec: hidden, so the provenance scan skips it")
elseif(CASE STREQUAL "undeclared_zone")
  first_file("*.hcont" f)
  copy_with_sidecar("${f}" "${WORK}/content/zones/undeclared")
  set(expect "content/zones/undeclared: not a zone of helios\\.project\\.jsonc")
elseif(CASE STREQUAL "spatial_outside_zone")
  first_file("*.hcont" f)
  copy_with_sidecar("${f}" "${WORK}/content")
  set(expect "a spatial document outside zones/<zone>/")
elseif(CASE STREQUAL "global_in_zone")
  first_file("*.hcont" c)
  get_filename_component(zoneDir "${c}" DIRECTORY)
  first_file("*.hrec" f)
  copy_with_sidecar("${f}" "${zoneDir}")
  set(expect "a \\.hrec document in a zone folder: only spatial documents")
elseif(CASE STREQUAL "container_group")
  first_file("*.hcont" f)
  replace("${f}" "\"group\": \"zone\\." "\"group\": \"zonex.")
  set(expect "streaming\\.group: 'zonex\\.[a-z0-9_]*' is not its zone's group")
elseif(CASE STREQUAL "container_identity")
  first_file("*.hcont" f)
  file(READ "${f}.meta" text)
  string(REGEX MATCH "\"guid\": \"([0-9a-f])" m "${text}")
  set(other 0)
  if(CMAKE_MATCH_1 STREQUAL "0")
    set(other 1)
  endif()
  replace("${f}.meta" "\"guid\": \"[0-9a-f]" "\"guid\": \"${other}")
  set(expect "its sidecar's GUID [0-9a-f-]+ differs from \\$container")
elseif(CASE STREQUAL "entity_name")
  first_file("*.hent" f)
  get_filename_component(dir "${f}" DIRECTORY)
  set(renamed "${dir}/00000000-0000-4000-8000-000000000001.hent")
  file(RENAME "${f}" "${renamed}")
  file(RENAME "${f}.meta" "${renamed}.meta")
  set(expect "\\$entity: '[0-9a-f-]+' differs from the file name's GUID '00000000-0000-4000-8000-000000000001'")
elseif(CASE STREQUAL "project_unknown_key")
  replace("${project}" "\"\\$project\": 0," "\"$project\": 0, \"bogus\": 1,")
  set(expect "helios\\.project\\.jsonc: bogus: unknown key")
elseif(CASE STREQUAL "project_tick_rate")
  replace("${project}" "\"tickHz\": [0-9]+" "\"tickHz\": 61")
  set(expect "zones\\[0\\]\\.tickHz: a tick rate is an integer in 1\\.\\.60 Hz")
elseif(CASE STREQUAL "project_reserved_scheme")
  replace("${project}" "\"uriScheme\": \"[^\"]*\"" "\"uriScheme\": \"https\"")
  set(expect "product\\.uriScheme: 'https' is reserved")
elseif(CASE STREQUAL "broken_record")
  # A record the cook must refuse, beside the real ones (with a sidecar, so only the cook can catch it).
  first_file("*.hrec" f)
  get_filename_component(dir "${f}" DIRECTORY)
  get_filename_component(table "${dir}" NAME)
  file(WRITE "${dir}/broken_fixture.hrec"
       "{\n  \"$rid\": 4611686018427387905,\n  \"$name\": \"${table}/broken_fixture\",\n  \"noSuchField\": 1\n}\n")
  file(COPY_FILE "${f}.meta" "${dir}/broken_fixture.hrec.meta")
  set(verb records)
  set(args "--project-root=${WORK}/content" "--out=${WORK}/cooked")
  set(expect "broken_fixture\\.hrec: .*noSuchField.*nothing written")
else()
  message(FATAL_ERROR "content_check_test: unknown case '${CASE}'")
endif()

execute_process(COMMAND "${COOK}" ${verb} ${args} RESULT_VARIABLE rc OUTPUT_VARIABLE out ERROR_VARIABLE err)
set(all "${out}${err}")
if(CASE STREQUAL "valid")
  if(NOT rc EQUAL 0)
    message(FATAL_ERROR "content_check_test: the unchanged copy fails `check` (exit ${rc}):\n${all}")
  endif()
  execute_process(COMMAND "${COOK}" records "--project-root=${WORK}/content" "--out=${WORK}/cooked"
                  RESULT_VARIABLE rc OUTPUT_VARIABLE out2 ERROR_VARIABLE err2)
  if(NOT rc EQUAL 0)
    message(FATAL_ERROR "content_check_test: the unchanged copy fails `records` (exit ${rc}):\n${out2}${err2}")
  endif()
  message(STATUS "the unchanged copy passes:\n${out}${out2}")
  return()
endif()
if(rc EQUAL 0)
  message(FATAL_ERROR "content_check_test: helios-cook ${verb} succeeded on case ${CASE} (expected '${expect}'). Output:\n${all}")
endif()
if(NOT all MATCHES "${expect}")
  message(FATAL_ERROR "content_check_test: helios-cook ${verb} failed on case ${CASE}, but without '${expect}'. Output:\n${all}")
endif()
message(STATUS "failed as expected (exit ${rc}): ${expect}")
