# Seeded violations for `helios-cook check` and the records cook (WP-0.20; 09 §2.1 "Records compile;
# 100 % provenance"). Copies SOURCE's helios.project.jsonc, content/ and schemas/ (which the project file's
# schemas.native names) into WORK, seeds one violation (CASE) and runs helios-cook: every case that sets
# `expect` must fail (non-zero exit) with that diagnostic. The cases without one (`valid`, the unchanged
# copy, `cook_then_check` and `ignored_cache`) must pass both verbs, so no case fails because the copy itself
# is broken. There is a case per rule of content_check.cpp that a project can break (the two I/O failures,
# a content root that cannot be listed or scanned, are not seeded).
# The cases find their targets by pattern (the first file of a kind), so they follow the content as it
# grows, and name no content (the IP-name lint keeps reference names out of apps/).
#
#   cmake -DCOOK=<helios-cook> -DSOURCE=<repository root> -DWORK=<scratch dir> -DCASE=<case>
#         -P content_check_test.cmake

cmake_minimum_required(VERSION 3.28)
foreach(v COOK SOURCE WORK CASE)
  if(NOT DEFINED ${v} OR "${${v}}" STREQUAL "")
    message(FATAL_ERROR "content_check_test: pass -D${v}=...")
  endif()
endforeach()

file(REMOVE_RECURSE "${WORK}")
file(MAKE_DIRECTORY "${WORK}")
file(COPY "${SOURCE}/helios.project.jsonc" DESTINATION "${WORK}")
file(COPY "${SOURCE}/content" "${SOURCE}/schemas" DESTINATION "${WORK}")
set(project "${WORK}/helios.project.jsonc")

# The first file (in sorted order) under WORK/content matching `glob`, skipping hidden paths.
function(first_file glob out)
  file(GLOB_RECURSE found LIST_DIRECTORIES false "${WORK}/content/${glob}")
  list(SORT found)
  foreach(f IN LISTS found)
    file(RELATIVE_PATH rel "${WORK}/content" "${f}")
    if(NOT rel MATCHES "(^|/)\\.")
      set(${out} "${f}" PARENT_SCOPE)
      return()
    endif()
  endforeach()
  message(FATAL_ERROR "content_check_test: no ${glob} under content/ to seed case ${CASE}")
endfunction()

# Replaces every match of `pattern` in `file`; a pattern that matches nothing is an error, so a case can
# never pass on an unchanged copy.
function(replace file pattern replacement)
  file(READ "${file}" text)
  string(REGEX REPLACE "${pattern}" "${replacement}" changed "${text}")
  if(changed STREQUAL text)
    message(FATAL_ERROR "content_check_test: '${pattern}' is not in ${file} (case ${CASE})")
  endif()
  file(WRITE "${file}" "${changed}")
endfunction()

# Changes the first hex digit of `file`'s sidecar GUID, so the sidecar names another document.
function(change_sidecar_guid file)
  file(READ "${file}.meta" text)
  string(REGEX MATCH "\"guid\": \"([0-9a-f])" m "${text}")
  set(other 0)
  if(CMAKE_MATCH_1 STREQUAL "0")
    set(other 1)
  endif()
  replace("${file}.meta" "\"guid\": \"[0-9a-f]" "\"guid\": \"${other}")
endfunction()

# Appends 1 MiB of spaces, which takes `file` past helios-cook's 1 MiB document limit.
function(pad_past_limit file)
  string(REPEAT " " 1048576 pad)
  file(APPEND "${file}" "${pad}")
endfunction()

# Copies a document and its sidecar into `dir`.
function(copy_with_sidecar file dir)
  file(MAKE_DIRECTORY "${dir}")
  file(COPY "${file}" "${file}.meta" DESTINATION "${dir}")
endfunction()

set(verb check)
set(args "--project-root=${WORK}")
if(CASE STREQUAL "valid")
  set(expect "")
elseif(CASE STREQUAL "missing_sidecar")
  first_file("*.hrec.meta" f)
  file(REMOVE "${f}")
  set(expect "\\.hrec: no sidecar, so the asset has no GUID")
elseif(CASE STREQUAL "bad_licence")
  first_file("*.meta" f)
  replace("${f}" "\"licence\": \"[^\"]*\"" "\"licence\": \"GPL-3.0-only\"")
  set(expect "provenance\\.licence: .*GPL-3\\.0-only.* is not an allowed licence")
elseif(CASE STREQUAL "ai_without_record")
  first_file("*.meta" f)
  replace("${f}" "\"origin\": \"[^\"]*\"" "\"origin\": \"ai-assisted\"")
  set(expect "an ai-assisted asset records the tool, model, prompt and inputs")
elseif(CASE STREQUAL "unknown_type")
  file(WRITE "${WORK}/content/notes.txt" "A file of a type the cook does not know.\n")
  set(expect "content/notes\\.txt: not a content document type the cook knows \\(\\.txt\\)")
elseif(CASE STREQUAL "hidden_file")
  first_file("*.hrec" f)
  get_filename_component(dir "${f}" DIRECTORY)
  file(COPY_FILE "${f}" "${dir}/.stash.hrec")
  set(expect "/\\.stash\\.hrec: hidden, so the provenance scan skips it")
elseif(CASE STREQUAL "undeclared_zone")
  first_file("*.hcont" f)
  copy_with_sidecar("${f}" "${WORK}/content/zones/undeclared")
  set(expect "content/zones/undeclared: not a zone of helios\\.project\\.jsonc")
elseif(CASE STREQUAL "spatial_outside_zone")
  first_file("*.hcont" f)
  copy_with_sidecar("${f}" "${WORK}/content")
  set(expect "a spatial document outside zones/<zone>/")
elseif(CASE STREQUAL "global_in_zone")
  first_file("*.hcont" c)
  get_filename_component(zoneDir "${c}" DIRECTORY)
  first_file("*.hrec" f)
  copy_with_sidecar("${f}" "${zoneDir}")
  set(expect "a \\.hrec document in a zone folder: only spatial documents")
elseif(CASE STREQUAL "container_group")
  first_file("*.hcont" f)
  replace("${f}" "\"group\": \"zone\\." "\"group\": \"zonex.")
  set(expect "streaming\\.group: 'zonex\\.[a-z0-9_]*' is not its zone's group")
elseif(CASE STREQUAL "container_identity")
  first_file("*.hcont" f)
  change_sidecar_guid("${f}")
  set(expect "its sidecar's GUID [0-9a-f-]+ differs from \\$container")
elseif(CASE STREQUAL "entity_name")
  first_file("*.hent" f)
  get_filename_component(dir "${f}" DIRECTORY)
  set(renamed "${dir}/00000000-0000-4000-8000-000000000001.hent")
  file(RENAME "${f}" "${renamed}")
  file(RENAME "${f}.meta" "${renamed}.meta")
  set(expect "\\$entity: '[0-9a-f-]+' differs from the file name's GUID '00000000-0000-4000-8000-000000000001'")
elseif(CASE STREQUAL "project_unknown_key")
  replace("${project}" "\"\\$project\": 0," "\"$project\": 0, \"bogus\": 1,")
  set(expect "helios\\.project\\.jsonc: bogus: unknown key")
elseif(CASE STREQUAL "project_tick_rate")
  replace("${project}" "\"tickHz\": [0-9]+" "\"tickHz\": 61")
  set(expect "zones\\[0\\]\\.tickHz: a tick rate is an integer in 1\\.\\.60 Hz")
elseif(CASE STREQUAL "project_reserved_scheme")
  replace("${project}" "\"uriScheme\": \"[^\"]*\"" "\"uriScheme\": \"https\"")
  set(expect "product\\.uriScheme: 'https' is reserved")
elseif(CASE STREQUAL "hidden_directory")
  first_file("*.hrec" f)
  file(MAKE_DIRECTORY "${WORK}/content/.stash")
  file(COPY_FILE "${f}" "${WORK}/content/.stash/kept.hrec")
  set(expect "content/\\.stash: hidden, so the provenance scan skips it")
elseif(CASE STREQUAL "cook_then_check")
  # The records cook's default output (<root>/.cooked) is ignored by git and skipped by the check.
  execute_process(COMMAND "${COOK}" records "--project-root=${WORK}/content" RESULT_VARIABLE rc OUTPUT_QUIET
                  ERROR_VARIABLE err)
  if(NOT rc EQUAL 0 OR NOT EXISTS "${WORK}/content/.cooked/records.server.hrdb")
    message(FATAL_ERROR "content_check_test: the default cook did not write content/.cooked (exit ${rc}):\n${err}")
  endif()
  set(expect "")
elseif(CASE STREQUAL "record_outside_records")
  first_file("*.hrec" f)
  copy_with_sidecar("${f}" "${WORK}/content/loose")
  set(expect "a record outside records/<table>/, which the records cook never reads")
elseif(CASE STREQUAL "container_guid_form")
  first_file("*.hcont" f)
  replace("${f}" "\"\\$container\": \"guid:" "\"$container\": \"")
  set(expect "\\$container: expected \"guid:<GUID>\"")
elseif(CASE STREQUAL "container_name")
  first_file("*.hcont" f)
  replace("${f}" "\"name\": \"" "\"name\": \"renamed_")
  set(expect "name: 'renamed_[a-z0-9_]+' differs from the file name's")
elseif(CASE STREQUAL "container_frame_parent")
  first_file("*.hcont" f)
  replace("${f}" "\"parent\": \"[a-z]+:" "\"parent\": \"planet:")
  set(expect "frame\\.parent: expected \"<kind>:<name>\"")
elseif(CASE STREQUAL "entity_outside_folder")
  first_file("*.hcont" c)
  get_filename_component(zoneDir "${c}" DIRECTORY)
  first_file("*.hent" f)
  copy_with_sidecar("${f}" "${zoneDir}")
  set(expect "an entity sits in its container's <name>\\.entities/ folder")
elseif(CASE STREQUAL "entity_without_container")
  first_file("*.hent" f)
  get_filename_component(dir "${f}" DIRECTORY)
  string(REGEX REPLACE "\\.entities$" ".hcont" container "${dir}")
  file(REMOVE "${container}" "${container}.meta")
  set(expect "its container .*\\.hcont does not exist")
elseif(CASE STREQUAL "project_missing")
  file(REMOVE "${project}")
  set(expect "helios\\.project\\.jsonc: missing")
elseif(CASE STREQUAL "project_version")
  replace("${project}" "\"\\$project\": 0" "\"$project\": 1")
  set(expect "\\$project: format version 1 is newer than this build's")
elseif(CASE STREQUAL "project_duplicate_key")
  replace("${project}" "\"\\$project\": 0," "\"$project\": 0, \"channels\": [\"dev\"],")
  set(expect "channels: duplicate key")
elseif(CASE STREQUAL "project_engine_version")
  replace("${project}" "\"engineVersion\": \"[^\"]*\"" "\"engineVersion\": \"0.1\"")
  set(expect "engineVersion: expected MAJOR\\.MINOR\\.PATCH")
elseif(CASE STREQUAL "project_gem")
  replace("${project}" "\"gems\": {[^}]*}" "\"gems\": {\"client\": [\"nosuchgem\"], \"server\": []}")
  set(expect "gems\\.client: gem 'nosuchgem' has no gems/nosuchgem/gem\\.jsonc.*gems\\.server: not a build target")
elseif(CASE STREQUAL "project_native_package")
  replace("${project}" "\"native\": \\[" "\"native\": [\"nosuchpackage\", ")
  set(expect "package 'nosuchpackage' has no \\.hschema files")
elseif(CASE STREQUAL "project_content_root")
  replace("${project}" "\"contentRoots\": \\[" "\"contentRoots\": [\"missing\", \"../outside\", ")
  set(expect "contentRoots: '\\.\\./outside'.*contentRoots: 'missing' is not a directory")
elseif(CASE STREQUAL "project_zone_frame")
  replace("${project}" "\"frame\": \"[a-z]+:" "\"frame\": \"galaxy:")
  set(expect "zones\\[0\\]\\.frame: a zone's root frame is")
elseif(CASE STREQUAL "project_zone_id")
  replace("${project}" "\"id\": [0-9]+" "\"id\": 7")
  replace("${project}" "\"zones\": \\["
          "\"zones\": [{\"name\": \"second\", \"id\": 7, \"tickHz\": 1, \"frame\": \"system:second\"}, ")
  set(expect "zones\\[1\\]\\.id: zone id 7 is used twice")
elseif(CASE STREQUAL "project_product_id")
  replace("${project}" "\"productId\": \"[^\"]*\"" "\"productId\": \"helios-game\"")
  set(expect "product\\.productId: ids that start with 'helios' are the engine's own products")
elseif(CASE STREQUAL "project_install_name")
  replace("${project}" "\"installName\": \"[^\"]*\"" "\"installName\": \"COM1\"")
  set(expect "product\\.installName: a Windows reserved device name")
elseif(CASE STREQUAL "project_display_name")
  replace("${project}" "\"displayName\": {[^}]*}" "\"displayName\": {}")
  set(expect "product\\.displayName: needs one entry per shipped language")
elseif(CASE STREQUAL "unknown_type_no_extension")
  file(WRITE "${WORK}/content/NOTES" "A file without an extension.\n")
  set(expect "content/NOTES: not a content document type the cook knows \\(no extension\\)")
elseif(CASE STREQUAL "nested_gitattributes")
  # Only the root's own .gitattributes is exempt: a deeper one could mark content binary or -text.
  first_file("*.hrec" f)
  get_filename_component(dir "${f}" DIRECTORY)
  file(WRITE "${dir}/.gitattributes" "*.hrec -text\n")
  set(expect "/\\.gitattributes: hidden, so the provenance scan skips it")
elseif(CASE STREQUAL "ignored_cache")
  # The cook's cache at the root's top (.gitignore: /content/.cache/) is not content.
  file(WRITE "${WORK}/content/.cache/state.bin" "cache\n")
  set(expect "")
elseif(CASE STREQUAL "file_directly_in_zones")
  first_file("*.hcont" f)
  copy_with_sidecar("${f}" "${WORK}/content/zones")
  set(expect "directly in zones/: a zone's documents go in zones/<zone>/")
elseif(CASE STREQUAL "container_too_large")
  first_file("*.hcont" f)
  pad_past_limit("${f}")
  set(expect "\\.hcont: [0-9]+ bytes is above the 1048576-byte limit")
elseif(CASE STREQUAL "container_parse_error")
  first_file("*.hcont" f)
  file(APPEND "${f}" "trailing text\n")
  set(expect "\\.hcont: [a-z0-9_]+\\.hcont:[0-9]+:[0-9]+: ")
elseif(CASE STREQUAL "container_not_object")
  first_file("*.hcont" f)
  file(WRITE "${f}" "[]\n")
  set(expect "\\.hcont: expected an object, got array")
elseif(CASE STREQUAL "container_frame_missing")
  first_file("*.hcont" f)
  replace("${f}" "\"frame\": {" "\"placement\": {")
  set(expect "\\.hcont: frame: missing")
elseif(CASE STREQUAL "container_streaming_missing")
  first_file("*.hcont" f)
  replace("${f}" "\"streaming\": {" "\"loading\": {")
  set(expect "\\.hcont: streaming: missing")
elseif(CASE STREQUAL "entity_file_name")
  first_file("*.hent" f)
  get_filename_component(dir "${f}" DIRECTORY)
  file(RENAME "${f}" "${dir}/marker.hent")
  file(RENAME "${f}.meta" "${dir}/marker.hent.meta")
  set(expect "/marker\\.hent: an entity's file name is its GUID in canonical lower case")
elseif(CASE STREQUAL "entity_identity")
  first_file("*.hent" f)
  change_sidecar_guid("${f}")
  set(expect "its sidecar's GUID [0-9a-f-]+ differs from the entity's")
elseif(CASE STREQUAL "project_too_large")
  pad_past_limit("${project}")
  set(expect "helios\\.project\\.jsonc: [0-9]+ bytes is above the 1048576-byte limit")
elseif(CASE STREQUAL "project_parse_error")
  replace("${project}" "\"\\$project\": 0," "\"$project\": 0,,")
  set(expect "helios\\.project\\.jsonc: helios\\.project\\.jsonc:[0-9]+:[0-9]+: ")
elseif(CASE STREQUAL "project_not_object")
  file(WRITE "${project}" "[]\n")
  set(expect "helios\\.project\\.jsonc: expected an object, got array")
elseif(CASE STREQUAL "project_version_form")
  replace("${project}" "\"\\$project\": 0" "\"$project\": 0.5")
  set(expect "\\$project: expected a format version")
elseif(CASE STREQUAL "project_wrong_type")
  replace("${project}" "\"engineVersion\": \"[^\"]*\"" "\"engineVersion\": 1")
  set(expect "engineVersion: expected string, got number")
elseif(CASE STREQUAL "project_missing_member")
  replace("${project}" "\"productId\": \"[^\"]*\"," "")
  set(expect "product\\.productId: missing")
elseif(CASE STREQUAL "project_gem_not_list")
  replace("${project}" "\"gems\": {[^}]*}" "\"gems\": {\"client\": \"nosuchgem\"}")
  set(expect "gems\\.client: expected array, got string")
elseif(CASE STREQUAL "project_gem_name")
  replace("${project}" "\"gems\": {[^}]*}" "\"gems\": {\"client\": [\"No Such Gem\"]}")
  set(expect "gems\\.client: a gem name is a string of")
elseif(CASE STREQUAL "project_gem_twice")
  replace("${project}" "\"gems\": {[^}]*}" "\"gems\": {\"client\": [\"nosuchgem\", \"nosuchgem\"]}")
  set(expect "gems\\.client: gem 'nosuchgem' is listed twice")
elseif(CASE STREQUAL "project_channels_empty")
  replace("${project}" "\"channels\": \\[[^]]*\\]" "\"channels\": []")
  set(expect "channels: a project publishes to at least one channel")
elseif(CASE STREQUAL "project_channel_name")
  replace("${project}" "\"channels\": \\[" "\"channels\": [\"Not A Channel\", ")
  set(expect "channels: a channel name is 1-32 characters")
elseif(CASE STREQUAL "project_channel_twice")
  replace("${project}" "\"channels\": \\[([^]]*)\\]" "\"channels\": [\\1, \\1]")
  set(expect "channels: channel '[a-z0-9-]+' is listed twice")
elseif(CASE STREQUAL "project_schemas_unknown_key")
  replace("${project}" "\"native\": \\[" "\"cpp\": [], \"native\": [")
  set(expect "schemas\\.cpp: unknown key")
elseif(CASE STREQUAL "project_native_name")
  replace("${project}" "\"native\": \\[" "\"native\": [\"Not-A-Package\", ")
  set(expect "schemas\\.native: a package name is a string of")
elseif(CASE STREQUAL "project_native_twice")
  replace("${project}" "\"native\": \\[([^]]*)\\]" "\"native\": [\\1, \\1]")
  set(expect "schemas\\.native: package '[a-z0-9_]+' is listed twice")
elseif(CASE STREQUAL "project_content_roots_empty")
  replace("${project}" "\"contentRoots\": \\[[^]]*\\]" "\"contentRoots\": []")
  set(expect "contentRoots: a project has at least one content root")
elseif(CASE STREQUAL "project_content_root_type")
  replace("${project}" "\"contentRoots\": \\[" "\"contentRoots\": [1, ")
  set(expect "contentRoots: expected string, got number")
elseif(CASE STREQUAL "project_content_root_twice")
  replace("${project}" "\"contentRoots\": \\[([^]]*)\\]" "\"contentRoots\": [\\1, \\1]")
  set(expect "contentRoots: '[^']+' is listed twice")
elseif(CASE STREQUAL "project_content_root_nested")
  # A second root inside the first: a record's folder.
  first_file("*.hrec" f)
  get_filename_component(dir "${f}" DIRECTORY)
  file(RELATIVE_PATH inner "${WORK}" "${dir}")
  replace("${project}" "\"contentRoots\": \\[([^]]*)\\]" "\"contentRoots\": [\\1, \"${inner}\"]")
  set(expect "contentRoots: '[^']+' is inside '[^']+'")
elseif(CASE STREQUAL "project_zone_not_object")
  replace("${project}" "\"zones\": \\[" "\"zones\": [1, ")
  set(expect "zones\\[0\\]: expected object, got number")
elseif(CASE STREQUAL "project_zone_unknown_key")
  replace("${project}" "\"tickHz\": " "\"weather\": 1, \"tickHz\": ")
  set(expect "zones\\[0\\]\\.weather: unknown key")
elseif(CASE STREQUAL "project_zone_name")
  replace("${project}" "\"name\": \"[^\"]*\"" "\"name\": \"Not-A-Zone\"")
  set(expect "zones\\[0\\]\\.name: a zone name is 1-32 characters")
elseif(CASE STREQUAL "project_zone_twice")
  replace("${project}" "\"zones\": \\[([^]]*)\\]" "\"zones\": [\\1, \\1]")
  set(expect "zones\\[1\\]\\.name: zone '[a-z0-9_]+' is declared twice")
elseif(CASE STREQUAL "project_zone_id_zero")
  replace("${project}" "\"id\": [0-9]+" "\"id\": 0")
  set(expect "zones\\[0\\]\\.id: a zone id is an integer in 1\\.\\.4294967295")
elseif(CASE STREQUAL "project_zone_id_large")
  replace("${project}" "\"id\": [0-9]+" "\"id\": 4294967296")
  set(expect "zones\\[0\\]\\.id: a zone id is an integer in 1\\.\\.4294967295")
elseif(CASE STREQUAL "project_product_unknown_key")
  replace("${project}" "\"productId\": " "\"publisher\": \"x\", \"productId\": ")
  set(expect "product\\.publisher: unknown key")
elseif(CASE STREQUAL "project_product_id_form")
  replace("${project}" "\"productId\": \"[^\"]*\"" "\"productId\": \"Not_An_Id\"")
  set(expect "product\\.productId: a product id matches")
elseif(CASE STREQUAL "project_display_name_tag")
  replace("${project}" "\"displayName\": {[^}]*}" "\"displayName\": {\"English\": \"A Name\"}")
  set(expect "product\\.displayName\\.English: not a language tag")
elseif(CASE STREQUAL "project_display_name_empty")
  replace("${project}" "\"displayName\": {[^}]*}" "\"displayName\": {\"en\": \"\"}")
  set(expect "product\\.displayName\\.en: a display name is a non-empty string")
elseif(CASE STREQUAL "project_install_name_form")
  replace("${project}" "\"installName\": \"[^\"]*\"" "\"installName\": \"Not An Install Name\"")
  set(expect "product\\.installName: an install name matches")
elseif(CASE STREQUAL "project_install_name_prefix")
  replace("${project}" "\"installName\": \"[^\"]*\"" "\"installName\": \"HeliosGame\"")
  set(expect "product\\.installName: names that start with 'helios' are the engine's own products")
elseif(CASE STREQUAL "project_uri_scheme_form")
  replace("${project}" "\"uriScheme\": \"[^\"]*\"" "\"uriScheme\": \"Not A Scheme\"")
  set(expect "product\\.uriScheme: a URI scheme is lower case")
elseif(CASE STREQUAL "project_scheme_helios_prefix")
  replace("${project}" "\"uriScheme\": \"[^\"]*\"" "\"uriScheme\": \"helios-game\"")
  set(expect "product\\.uriScheme: 'helios-game' is reserved")
elseif(CASE STREQUAL "project_scheme_ms_prefix")
  replace("${project}" "\"uriScheme\": \"[^\"]*\"" "\"uriScheme\": \"ms-settings\"")
  set(expect "product\\.uriScheme: 'ms-settings' is reserved")
elseif(CASE STREQUAL "project_product_version")
  replace("${project}" "\"version\": \"[^\"]*\"" "\"version\": \"1.0\"")
  set(expect "product\\.version: expected MAJOR\\.MINOR\\.PATCH")
elseif(CASE STREQUAL "broken_record")
  # A record the cook must refuse, beside the real ones (with a sidecar, so only the cook can catch it).
  first_file("*.hrec" f)
  get_filename_component(dir "${f}" DIRECTORY)
  get_filename_component(table "${dir}" NAME)
  file(WRITE "${dir}/broken_fixture.hrec"
       "{\n  \"$rid\": 4611686018427387905,\n  \"$name\": \"${table}/broken_fixture\",\n  \"noSuchField\": 1\n}\n")
  file(COPY_FILE "${f}.meta" "${dir}/broken_fixture.hrec.meta")
  set(verb records)
  set(args "--project-root=${WORK}/content" "--out=${WORK}/cooked")
  set(expect "broken_fixture\\.hrec: .*noSuchField.*nothing written")
else()
  message(FATAL_ERROR "content_check_test: unknown case '${CASE}'")
endif()

execute_process(COMMAND "${COOK}" ${verb} ${args} RESULT_VARIABLE rc OUTPUT_VARIABLE out ERROR_VARIABLE err)
set(all "${out}${err}")
if(expect STREQUAL "")
  if(NOT rc EQUAL 0)
    message(FATAL_ERROR "content_check_test: the unchanged copy fails `check` (exit ${rc}):\n${all}")
  endif()
  execute_process(COMMAND "${COOK}" records "--project-root=${WORK}/content" "--out=${WORK}/cooked"
                  RESULT_VARIABLE rc OUTPUT_VARIABLE out2 ERROR_VARIABLE err2)
  if(NOT rc EQUAL 0)
    message(FATAL_ERROR "content_check_test: the unchanged copy fails `records` (exit ${rc}):\n${out2}${err2}")
  endif()
  message(STATUS "the unchanged copy passes:\n${out}${out2}")
  return()
endif()
if(rc EQUAL 0)
  message(FATAL_ERROR "content_check_test: helios-cook ${verb} succeeded on case ${CASE} (expected '${expect}'). Output:\n${all}")
endif()
if(NOT all MATCHES "${expect}")
  message(FATAL_ERROR "content_check_test: helios-cook ${verb} failed on case ${CASE}, but without '${expect}'. Output:\n${all}")
endif()
message(STATUS "failed as expected (exit ${rc}): ${expect}")
