#include "test_util.h"

#include "helios/math/noise.h"

#include <chrono>

using namespace helios;
using helios::test::Rng;
namespace nz = helios::noise;

namespace {

struct Sample {
    f64 x, y, z, w;
};
// Fixed sample points: small, negative, fractional, lattice-aligned and large coordinates.
constexpr Sample kSamples[20] = {{0.0, 0.0, 0.0, 0.0},
                                 {0.5, 0.5, 0.5, 0.5},
                                 {1.25, -2.75, 3.125, -0.0625},
                                 {-7.3, 4.1, -0.9, 2.2},
                                 {12.5, 7.75, -3.5, 9.0},
                                 {-0.001, 0.002, -0.003, 0.004},
                                 {3.0, -4.0, 5.0, -6.0},
                                 {100.123, -200.456, 300.789, 1.5},
                                 {-1234.5678, 876.54321, 42.4242, -3.3},
                                 {0.3333, 0.6666, 0.9999, 0.1111},
                                 {-15.2, -15.2, -15.2, -15.2},
                                 {65536.5, -65536.25, 131072.125, 7.0},
                                 {2.718281828, 3.141592654, 1.414213562, 1.732050808},
                                 {-0.5, -0.5, -0.5, -0.5},
                                 {8.8, -9.9, 10.1, -11.2},
                                 {1.0e5 + 0.37, -2.0e5 + 0.61, 3.0e5 + 0.29, 0.83},
                                 {-3.75, 0.25, 6.5, -1.125},
                                 {19.99, 29.99, 39.99, 49.99},
                                 {-100.0, 50.5, -25.25, 12.625},
                                 {1.0e6 + 0.5, 1.0e6 + 0.25, -1.0e6 + 0.75, 3.5}};

constexpr u32 kSeed = 0xC0FFEEu;

struct Golden64 {
    f64 perlin2, perlin3, perlin4, simplex2, simplex3, simplex4, fbm2, fbm3, fbm4, fbm3Perlin, ridged2,
        ridged3;
    f64 warp2x, warp2y, warp3x, warp3y, warp3z, cell2f1, cell2f2, cell3f1, cell3f2;
    u32 cell2id, cell3id;
};
struct Golden32 {
    f32 perlin2, perlin3, perlin4, simplex2, simplex3, simplex4, fbm3, ridged3, warp3x, cell3f1, cell3f2;
    u32 cell3id;
};

// Generated by evaluating the implementation (Linux GCC 13, x86-64) and verified bit-identical with
// GCC 13 and Clang 18 at -O0, -O2, -O3 -march=native and -O2 -mavx2 -mfma. Regenerated once when the
// lattice hash was made non-linear (the old linear hash repeated every ~1.6k units in 3D, ~220 in
// 4D). A mismatch on any platform means the noise is no longer bit-identical across platforms:
// fix the compiler flags / code, never regenerate the table to make a platform pass.
// clang-format off
constexpr Golden64 kGolden64[20] = {
    {0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 1.0,
     0.0, 0.0, 0.0, 0.0, 0.0, 0.58232508753178047, 0.81511814439144015, 0.8393497020241506, 0.88163714779496427, 0x88803ddfu, 0x67e1e520u},
    {0.25000000000000006, -0.375, 0.4325, 0.43001911907810297, 0.0, -0.56072907467786592, 0.52520624227095514, -0.37408644153225806, 0.16325728983352988, -0.27014445616320398, 0.18693728155877543, 1.0,
     -0.30499738690105893, -2.002878141953258, 0.5, -0.92151478358677452, -1.3308283942086356, 0.38164177669177624, 0.95982747700053217, 0.52891445377177215, 0.64907540995901536, 0xffeb886bu, 0x1aa98f59u},
    {-0.41320760506641208, -0.35468050409690477, -0.083806192090437798, 0.89998166583747774, -0.0011314093576043557, -0.12223619655574583, -0.065052379037319946, -0.2232007581529698, 0.076253494336933486, 0.13589462629969876, 0.0063694071428082354, 0.68629287295420782,
     3.8680819699477738, -3.8733699337263379, 1.5409360480712015, -3.3770107402324285, 3.2202171782042983, 0.53984986059737028, 0.58089044156912895, 0.723644337903388, 0.73297313258237806, 0x199d3d81u, 0x1560a16eu},
    {-0.46956726335999949, 0.059918382268723015, 0.30992319479121361, -0.53232920383967941, -0.26201820237037199, 0.037428647718934623, -0.069078609768945934, -0.12133380060530305, 0.025758371864311437, 0.036734533692529887, 0.17456634893472309, 0.58943094431175191,
     -9.1996917137359375, 4.5462123118732807, -7.7348287150197104, 4.2271504101508892, -0.22552441885534369, 0.10887822280548572, 0.7444575368643106, 0.34314905367473464, 0.53213191204828758, 0x891199bau, 0xd0445304u},
    {-0.2187802795725711, 0.14013671875, -0.42130737304687499, -0.68885114155974436, 0.0, -0.099174690851301039, 0.34973050007834894, 0.42569581063069473, 0.079645618347698358, 0.18293201913639576, 0.050272751882146478, 0.74969211580509121,
     13.971930146729983, 10.343629261896762, 11.90248465839651, 7.4847754792018453, -3.4272741110982277, 0.22606410195472793, 0.65170519700439278, 0.36667541643804497, 0.7315529828728653, 0xa79353bau, 0x2fea5d5bu},
    {0.0010000654838758518, 0.0010000701232445969, 0.005190369211153581, 0.0043308557962046974, 0.0047494680223433231, 0.023244420502180365, -0.0080897331210341532, 0.0012504149313452386, 0.013941907255388299, -6.3745024519541095e-05, 0.95073436221724317, 0.94217283528519313,
     0.0129997812523708, -0.010374189244187799, 0.012570991585143514, 0.0291414131957222, -0.005713468751740676, 0.58207872100920188, 0.81704338189604653, 0.84087239602650676, 0.8787945908633219, 0x88803ddfu, 0x67e1e520u},
    {0.0, 0.0, 0.0, 0.48511451053413845, 0.039094650205759557, 0.25304919430460993, 0.024247934286848443, 0.063804676091863563, -0.028204666733423714, -0.11556153734794043, 0.13745740456868119, 0.83777744183147307,
     1.8004056082014297, -4.429712160167524, 3.0582056510875955, -3.2163616990005868, 5.2247069738389191, 0.2377570749878769, 0.57887254069360528, 0.78049635791181771, 0.83410223213537471, 0x16f7cccfu, 0xe8cdbf47u},
    {0.39273862049410602, 0.46445427097676018, -0.062588137332762334, 0.42090990435497866, -0.040783717360433652, 0.23095112946011104, 0.21680336270960232, -0.062023640703517999, -0.027844805489928147, -0.074798581987777057, 0.34782728925141798, 0.51351095943021585,
     98.356211619354738, -202.52391684418802, 98.338416268120852, -201.83599762912934, 302.22507518562708, 0.38616585810379972, 0.48425839799059084, 0.49183565466447055, 0.5340906391636312, 0xa62b6c41u, 0xec387db1u},
    {-0.17041754017646418, 0.018506295145572005, -0.18803246849080826, 0.71248607009437559, 0.02182972135973809, 0.95983073507722516, 0.17271197806846253, -0.071635049614147475, -0.041383145366773441, -0.042088609219609135, 0.062030292483004387, 0.73897105200699387,
     -1234.5954371264327, 876.29911490368841, -1234.9874511625669, 877.3749754804943, 43.563898721513937, 0.25255798215628555, 0.65233453091954974, 0.43456080984966877, 0.58339158016461834, 0x47131f5du, 0x91260343u},
    {0.28071775877857846, -0.49741818506170171, 0.40360491821171707, 0.79969804636931952, 0.072636116217713098, 0.059303651713940281, 0.44333503694236437, -0.21873066201232649, 0.019526649669523284, -0.30763664434732285, 0.026986838206382441, 0.71383524401113674,
     0.69251390794309653, -1.557787540201621, 0.037452459845068065, -0.80432848210234231, -1.5038158665330397, 0.61686946767533346, 0.78724556122093781, 0.66930255115755799, 0.71982366104056172, 0xffeb886bu, 0x8f4a3d90u},
    {0.099840286367773992, 0.15927123189432169, -0.51222076555077989, 0.96682085917601412, -0.12760749599999743, 0.020373144070642848, 0.014050669406438079, 0.065089886193547719, 0.01644401394497676, 0.11985182954526825, 0.00086677588027765065, 0.42175244127543121,
     -16.521536992040762, -16.756773052757488, -17.494178125714281, -16.047670299428567, -17.567074459428568, 0.60272543014995639, 0.88414403347616788, 0.24795529659329898, 0.59651525352090562, 0xfeffd1aeu, 0x82466767u},
    {0.21565952457201013, 0.1282697468996048, -0.0916189519688487, 0.13564475568104098, -0.089717650977672411, -0.035615757450238782, -0.33712244353198934, 0.20224203601897664, 0.068299388209130396, 0.12551422826253064, 0.38789608856377372, 0.72320005838314749,
     65537.736046745791, -65535.873004554167, 65538.196800873789, -65538.46302967261, 131073.37849241379, 0.28511168224720623, 0.74487351839818938, 0.32070157725022252, 0.53463281163152965, 0x8ecf8e50u, 0x03e34fabu},
    {0.35712097603840492, -0.34019317341517008, -0.075544007943424793, 0.72049894922017066, -0.33403133187854755, 0.020487964099741234, -0.30350431250363874, 0.26681401881424188, -0.11311663271454225, -0.12259008231581141, 0.072710287375584756, 0.48502332542720011,
     3.9753273347157343, 3.3660560604608549, 1.5810344806362213, 3.6011166909707253, 2.460283013688755, 0.31331811010077715, 0.48315850713342251, 0.72556569655860559, 0.78206093951104283, 0x4bed97ffu, 0xe2cfefabu},
    {-0.78033008588991071, -0.125, -0.054062499999999999, -0.43001911907810281, 0.0, -0.18690969155928863, -0.64878618848124814, 0.18704322076612903, 0.20922838160065582, 0.10302067481739498, 0.41377787930417859, 1.0,
     0.40141553166439914, 1.6477835681328803, -0.5, 1.3308283942086356, 0.91666126251220703, 0.30321715376033859, 0.90708503219722736, 0.56273172555166295, 0.59529289871333557, 0x88803ddfu, 0x9fa006f3u},
    {0.30917859588850516, -0.31551958397788055, -0.36969107704678128, 0.42877957628588947, 0.85456588800000022, -0.31193790550640366, -0.18310297065320866, -0.037076883569893165, -0.13131408908001338, 0.10106018534929015, 0.32836955851751859, 0.019212413408236585,
     8.9036328921944179, -11.194836624299288, 6.480841494028283, -7.6138851487410744, 7.4901168648859748, 0.4196541705792296, 0.53381195386542513, 0.3539294015025492, 0.63197613826251975, 0x0562c41fu, 0x155d0b45u},
    {0.37236715839721574, -0.07309967163076253, -0.10471421026147731, -0.10777123191936529, 0.07483373917653792, -0.012756784994270416, 0.54900288724494373, -0.24179795863915912, 0.081844650072512029, 0.14214468019211121, 0.47956522781146294, 0.59288640065090359,
     99997.971603193189, -200000.8128541465, 100000.71366347962, -199999.87790344807, 299999.68615799875, 0.3513318665340967, 0.89747707998536619, 0.50458898501845373, 0.60679758341245882, 0xa26b35e5u, 0x4f705836u},
    {-0.29773555202720242, -0.11034488677978516, -0.067240809073191479, -0.10937318825113843, -0.24584960937500019, 0.059472706156957662, -0.40644919423685977, 0.20769435103221667, -0.044087867869648009, 0.030967071904810631, 0.58006700157948499, 0.73317122753755459,
     -3.8243120873116734, 2.238603894699045, -2.87314620543094, -0.95890451329095172, 6.5432274944725481, 0.44539370758389718, 0.85991747921991291, 0.46154253506871129, 0.54247382174521863, 0xa01e29cbu, 0x742aa6beu},
    {9.9898101145045374e-06, -0.020018912775509157, -0.025923416392574328, 0.90100761985634992, 0.0, -0.28255866633445953, 0.085428947192506627, 0.02799691069937324, -0.099994258728176535, 0.1472654855211076, 0.0055065168579026521, 0.89724546949099671,
     21.523714222003832, 30.721616413615134, 19.525178599962842, 29.778304992730028, 40.346412704070495, 0.86635351081506495, 0.91969488304379143, 0.54879694881267227, 0.67787161088105208, 0x671cf2c8u, 0xfa929eceu},
    {0.25000000000000006, 0.27587890625, 0.36385711815208194, -0.36573951132306659, 0.25196053461773005, 0.013972477003886159, -1.2041321233891011e-05, -0.47628806245987854, 0.048562749733977582, -0.21136989980057935, 0.24236339722268266, 0.41142745819101967,
     -98.994282769211225, 51.252233718208892, -100.06764593136621, 50.152949917794849, -24.349672056182118, 0.32589209429582572, 0.58445127865568902, 0.5020112421942321, 0.53605539817418257, 0x36e7a742u, 0x6d990354u},
    {-0.3794778839470101, -0.15452098846435547, 0.26751805543899537, 0.44583330352695122, -0.35192820872477792, 0.62955590596925415, -0.45844518458013034, -0.21323839299109684, 0.16965081951106911, 0.21504402022883437, 0.32889246064429001, 0.4388786825678313,
     1000002.8676658461, 999998.85976516258, 1000000.6731359126, 999999.79179385398, -999997.65591206611, 0.29950888739355508, 0.72461094335555953, 0.19777354154710258, 0.86612664141013751, 0x047a190au, 0x6624c6d4u},
};
constexpr Golden32 kGolden32[20] = {
    {0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 1.0f, 0.0f, 0.839349687f, 0.881637156f, 0x67e1e520u},
    {0.24999997f, -0.375f, 0.432500005f, 0.430019021f, 0.0f, -0.560729146f, -0.37408644f, 1.0f, 0.5f, 0.528914452f, 0.649075389f, 0x1aa98f59u},
    {-0.41320762f, -0.354680508f, -0.0838061646f, 0.899981797f, -0.00113157427f, -0.122236118f, -0.223200917f, 0.686292768f, 1.54093575f, 0.723644316f, 0.732973158f, 0x1560a16eu},
    {-0.469567358f, 0.0599182621f, 0.309923202f, -0.532329261f, -0.262016714f, 0.0374287553f, -0.121333584f, 0.589430809f, -7.73482847f, 0.343149155f, 0.53213191f, 0xd0445304u},
    {-0.218780234f, 0.140136719f, -0.421307385f, -0.688851953f, 0.0f, -0.0991743729f, 0.42569539f, 0.749691427f, 11.9024839f, 0.366675436f, 0.731553018f, 0x2fea5d5bu},
    {0.000998791307f, 0.000999172917f, 0.00518970191f, 0.00433092844f, 0.00474968925f, 0.0232442357f, 0.00125063641f, 0.942172468f, 0.012570817f, 0.840872407f, 0.878794611f, 0x67e1e520u},
    {0.0f, 0.0f, 0.0f, 0.485114604f, 0.0390956216f, 0.253049344f, 0.0638040751f, 0.837775826f, 3.05820584f, 0.780496359f, 0.834102213f, 0xe8cdbf47u},
    {0.392740518f, 0.464456797f, -0.062588729f, 0.420926839f, -0.0407849625f, 0.230956763f, -0.0620242469f, 0.513506889f, 98.3383865f, 0.491833031f, 0.534084916f, 0xec387db1u},
    {-0.170434877f, 0.0185245946f, -0.188033223f, 0.712464273f, 0.0218679383f, 0.95976764f, -0.0715128779f, 0.73865211f, -1234.98718f, 0.434523672f, 0.583439469f, 0x91260343u},
    {0.28071776f, -0.497418255f, 0.403604835f, 0.799698114f, 0.0726360306f, 0.0593036339f, -0.218730643f, 0.713835359f, 0.0374525785f, 0.669302583f, 0.719823658f, 0x8f4a3d90u},
    {0.0998399854f, 0.159270704f, -0.512220442f, 0.966821074f, -0.127606824f, 0.0203699563f, 0.0650897101f, 0.421752751f, -17.4941788f, 0.247955576f, 0.596515119f, 0x82466767u},
    {0.215659514f, 0.128269747f, -0.0916189551f, 0.1347536f, -0.0897176638f, -0.0342631191f, 0.207571074f, 0.712854922f, 65538.1875f, 0.320701569f, 0.534632802f, 0x03e34fabu},
    {0.357121021f, -0.340193272f, -0.0755439848f, 0.720498264f, -0.334031403f, 0.0204880275f, 0.266814113f, 0.485023528f, 1.58103514f, 0.725565732f, 0.7820611f, 0xe2cfefabu},
    {-0.780330062f, -0.125f, -0.0540625006f, -0.430019021f, 0.0f, -0.186909705f, 0.18704322f, 1.0f, -0.5f, 0.562731743f, 0.595292926f, 0x9fa006f3u},
    {0.309178293f, -0.315519601f, -0.369691312f, 0.428778887f, 0.854565859f, -0.311937273f, -0.0370765217f, 0.0192124881f, 6.48083591f, 0.353929818f, 0.631975889f, 0x155d0b45u},
    {0.373081058f, -0.0731305629f, -0.102193691f, -0.0984694511f, 0.0649447367f, -0.0092373807f, -0.255525857f, 0.615353107f, 100000.703f, 0.513428688f, 0.600716472f, 0x4f705836u},
    {-0.297735542f, -0.110344887f, -0.0672408044f, -0.109373376f, -0.245849624f, 0.0594727285f, 0.207694113f, 0.733171582f, -2.87314606f, 0.461542547f, 0.542473793f, 0x742aa6beu},
    {1.01995374e-05f, -0.0200194716f, -0.0259205215f, 0.901007652f, 0.0f, -0.282556802f, 0.0279927012f, 0.897244394f, 19.5251808f, 0.548797071f, 0.677869976f, 0xfa929eceu},
    {0.249999985f, 0.275878906f, 0.36385709f, -0.365736693f, 0.251962692f, 0.0139714638f, -0.476282895f, 0.411425382f, -100.067642f, 0.50201124f, 0.536055386f, 0x6d990354u},
    {-0.379477859f, -0.154520988f, 0.267518044f, 0.199150562f, -0.276440561f, 0.627328932f, -0.151694179f, 0.520180345f, 1000000.75f, 0.197773531f, 0.866126657f, 0x6624c6d4u},
};
// clang-format on

const nz::FbmParams kFbm{5, 0.5, 2.0, 0.5, nz::Basis::Simplex};
const nz::FbmParams kFbmPerlin{5, 0.5, 2.03, 0.55, nz::Basis::Perlin};
const nz::RidgedParams kRidged{};
const nz::WarpParams kWarp{4.0, {3, 0.25, 2.0, 0.5, nz::Basis::Simplex}};

}  // namespace

TEST_CASE("noise: golden values are bit-identical (f64)") {
    for (int i = 0; i < 20; ++i) {
        const Sample& s = kSamples[i];
        const Golden64& g = kGolden64[i];
        const DVec2 p2{s.x, s.y};
        const DVec3 p3{s.x, s.y, s.z};
        const DVec4 p4{s.x, s.y, s.z, s.w};
        CAPTURE(i);
        CHECK(nz::perlin(p2, kSeed) == g.perlin2);
        CHECK(nz::perlin(p3, kSeed) == g.perlin3);
        CHECK(nz::perlin(p4, kSeed) == g.perlin4);
        CHECK(nz::simplex(p2, kSeed) == g.simplex2);
        CHECK(nz::simplex(p3, kSeed) == g.simplex3);
        CHECK(nz::simplex(p4, kSeed) == g.simplex4);
        CHECK(nz::fbm(p2, kSeed, kFbm) == g.fbm2);
        CHECK(nz::fbm(p3, kSeed, kFbm) == g.fbm3);
        CHECK(nz::fbm(p4, kSeed, kFbm) == g.fbm4);
        CHECK(nz::fbm(p3, kSeed, kFbmPerlin) == g.fbm3Perlin);
        CHECK(nz::ridged(p2, kSeed, kRidged) == g.ridged2);
        CHECK(nz::ridged(p3, kSeed, kRidged) == g.ridged3);
        const DVec2 w2 = nz::domainWarp(p2, kSeed, kWarp);
        CHECK(w2.x == g.warp2x);
        CHECK(w2.y == g.warp2y);
        const DVec3 w3 = nz::domainWarp(p3, kSeed, kWarp);
        CHECK(w3.x == g.warp3x);
        CHECK(w3.y == g.warp3y);
        CHECK(w3.z == g.warp3z);
        const nz::DCellular c2 = nz::cellular(p2, kSeed);
        CHECK(c2.f1 == g.cell2f1);
        CHECK(c2.f2 == g.cell2f2);
        CHECK(c2.cellId == g.cell2id);
        const nz::DCellular c3 = nz::cellular(p3, kSeed);
        CHECK(c3.f1 == g.cell3f1);
        CHECK(c3.f2 == g.cell3f2);
        CHECK(c3.cellId == g.cell3id);
    }
}

TEST_CASE("noise: golden values are bit-identical (f32)") {
    for (int i = 0; i < 20; ++i) {
        const Sample& s = kSamples[i];
        const Golden32& g = kGolden32[i];
        const Vec4 p4{static_cast<f32>(s.x), static_cast<f32>(s.y), static_cast<f32>(s.z),
                      static_cast<f32>(s.w)};
        const Vec3 p3 = p4.xyz();
        const Vec2 p2 = p4.xy();
        CAPTURE(i);
        CHECK(nz::perlin(p2, kSeed) == g.perlin2);
        CHECK(nz::perlin(p3, kSeed) == g.perlin3);
        CHECK(nz::perlin(p4, kSeed) == g.perlin4);
        CHECK(nz::simplex(p2, kSeed) == g.simplex2);
        CHECK(nz::simplex(p3, kSeed) == g.simplex3);
        CHECK(nz::simplex(p4, kSeed) == g.simplex4);
        CHECK(nz::fbm(p3, kSeed, kFbm) == g.fbm3);
        CHECK(nz::ridged(p3, kSeed, kRidged) == g.ridged3);
        CHECK(nz::domainWarp(p3, kSeed, kWarp).x == g.warp3x);
        const nz::Cellular c3 = nz::cellular(p3, kSeed);
        CHECK(c3.f1 == g.cell3f1);
        CHECK(c3.f2 == g.cell3f2);
        CHECK(c3.cellId == g.cell3id);
    }
}

TEST_CASE("noise: ranges and statistics") {
    Rng rng(90);
    constexpr int kN = 200000;
    f64 lo[6] = {1, 1, 1, 1, 1, 1}, hi[6] = {-1, -1, -1, -1, -1, -1}, sum[6] = {}, sumSq[6] = {};
    f64 ridgedLo = 1.0, ridgedHi = 0.0, fbmLo = 1.0, fbmHi = -1.0;
    for (int i = 0; i < kN; ++i) {
        const DVec4 p{rng.range(-1000.0, 1000.0), rng.range(-1000.0, 1000.0), rng.range(-1000.0, 1000.0),
                      rng.range(-1000.0, 1000.0)};
        const u32 seed = static_cast<u32>(i);
        const f64 v[6] = {
            nz::perlin(DVec2(p.x, p.y), seed),  nz::perlin(p.xyz(), seed),  nz::perlin(p, seed),
            nz::simplex(DVec2(p.x, p.y), seed), nz::simplex(p.xyz(), seed), nz::simplex(p, seed)};
        for (int k = 0; k < 6; ++k) {
            lo[k] = min(lo[k], v[k]);
            hi[k] = max(hi[k], v[k]);
            sum[k] += v[k];
            sumSq[k] += v[k] * v[k];
        }
        const f64 r = nz::ridged(p.xyz(), seed);
        ridgedLo = min(ridgedLo, r);
        ridgedHi = max(ridgedHi, r);
        const f64 f = nz::fbm(p.xyz(), seed);
        fbmLo = min(fbmLo, f);
        fbmHi = max(fbmHi, f);
    }
    const char* names[6] = {"perlin2", "perlin3", "perlin4", "simplex2", "simplex3", "simplex4"};
    for (int k = 0; k < 6; ++k) {
        const f64 mean = sum[k] / kN, sd = std::sqrt(sumSq[k] / kN - mean * mean);
        MESSAGE(std::string(names[k])
                << ": [" << lo[k] << ", " << hi[k] << "] mean " << mean << " sd " << sd);
        CHECK(lo[k] >= -1.0);
        CHECK(hi[k] <= 1.0);
        CHECK(lo[k] < -0.75);  // uses most of the range
        CHECK(hi[k] > 0.75);
        CHECK(std::fabs(mean) < 0.01);
        CHECK(sd > 0.1);
    }
    CHECK(ridgedLo >= 0.0);
    CHECK(ridgedHi <= 1.0);
    CHECK(ridgedHi > 0.5);
    CHECK(fbmLo >= -1.0);
    CHECK(fbmHi <= 1.0);
}

TEST_CASE("noise: structural properties") {
    // Perlin noise is zero on the integer lattice.
    for (int i = -3; i <= 3; ++i) {
        CHECK(nz::perlin(DVec2(i, 2 * i), 7u) == 0.0);
        CHECK(nz::perlin(DVec3(i, -i, 5), 7u) == 0.0);
        CHECK(nz::perlin(DVec4(i, 1, -2, 3 * i), 7u) == 0.0);
        CHECK(nz::perlin(Vec3(static_cast<f32>(i), 4.0f, -1.0f), 7u) == 0.0f);
    }
    // Seeds decorrelate; the same seed repeats.
    const DVec3 p{1.37, -2.71, 0.59};
    CHECK(nz::simplex(p, 1u) != nz::simplex(p, 2u));
    CHECK(nz::perlin(p, 1u) != nz::perlin(p, 2u));
    CHECK(nz::simplex(p, 99u) == nz::simplex(p, 99u));
    // A single fbm octave is the basis noise itself.
    const nz::FbmParams one{1, 1.0, 2.0, 0.5, nz::Basis::Perlin};
    CHECK(nz::fbm(p, 5u, one) == nz::perlin(p, 5u));
    CHECK(nz::fbm(DVec2(p.x, p.y), 5u, nz::FbmParams{1, 1.0, 2.0, 0.5, nz::Basis::Simplex}) ==
          nz::simplex(DVec2(p.x, p.y), 5u));
    // Octave count is clamped, not UB.
    CHECK(std::isfinite(nz::fbm(p, 5u, nz::FbmParams{0, 1.0, 2.0, 0.5, nz::Basis::Simplex})));
    CHECK(std::isfinite(nz::fbm(p, 5u, nz::FbmParams{1000, 1.0, 2.0, 0.5, nz::Basis::Simplex})));
    // f32 and f64 agree closely at moderate coordinates (different but consistent algorithms).
    Rng rng(91);
    for (int i = 0; i < 2000; ++i) {
        const DVec3 q = rng.dvec3(-50.0, 50.0);
        const Vec3 qf = toF32(q);
        CHECK(std::fabs(nz::perlin(toF64(qf), 3u) - nz::perlin(qf, 3u)) < 1e-4);
        CHECK(std::fabs(nz::simplex(toF64(qf), 3u) - nz::simplex(qf, 3u)) < 1e-4);
    }
    // Domain warp displacement is bounded by the amplitude (fbm is in [-1, 1]).
    for (int i = 0; i < 2000; ++i) {
        const DVec3 q = rng.dvec3(-100.0, 100.0);
        CHECK(maxComponent(abs(nz::domainWarp(q, 4u, kWarp) - q)) <= kWarp.amplitude);
    }
}

TEST_CASE("noise: no short lattice periods") {
    // Regression: the lattice hash used to be ONE mix of s + x*Px + y*Py (+ z*Pz + w*Pw) mod 2^32,
    // which is constant along the kernel of that linear form. For its multipliers these integer
    // vectors were exact periods: 4D noise repeated after ~221 units, 3D after ~1566 (LLL-reduced
    // kernel vectors; src/noise.cpp explains why the per-axis hash has no such structure).
    const DVec2 v2{-11319.0, 26149.0};
    const DVec3 v3{-1039.0, 243.0, -1146.0};
    const DVec4 v4{-137.0, 94.0, -142.0, -33.0};
    // Simplex noise lives on a skewed lattice: the same integer cell step in world space.
    const DVec2 t2 = v2 - DVec2((v2.x + v2.y) * 0.21132486540518711775);
    const DVec3 t3 = v3 - DVec3((v3.x + v3.y + v3.z) / 6.0);
    const DVec4 t4 = v4 - DVec4((v4.x + v4.y + v4.z + v4.w) * 0.13819660112501051518);
    constexpr int kN = 256;
    int same[9] = {};
    // A repeat is an equal, non-zero value (lattice-aligned samples are 0 on both sides by design).
    auto equal = [](f64 a, f64 b) { return a != 0.0 && a == b; };
    auto close = [](f64 a, f64 b) { return a != 0.0 && std::fabs(a - b) < 1e-9; };
    for (int i = 0; i < kN; ++i) {
        // Dyadic sample points, so p + v is exact for the lattice-aligned noises.
        const DVec4 p{(i * 731 % 4096) / 1024.0 - 2.0, (i * 377 % 4096) / 1024.0 + 1.0,
                      -(i * 513 % 4096) / 1024.0, (i * 97 % 4096) / 1024.0 + 0.5};
        const DVec2 p2{p.x, p.y};
        const DVec3 p3 = p.xyz();
        same[0] += equal(nz::perlin(p2, kSeed), nz::perlin(p2 + v2, kSeed)) ? 1 : 0;
        same[1] += equal(nz::perlin(p3, kSeed), nz::perlin(p3 + v3, kSeed)) ? 1 : 0;
        same[2] += equal(nz::perlin(p, kSeed), nz::perlin(p + v4, kSeed)) ? 1 : 0;
        same[3] += equal(nz::cellular(p2, kSeed).f1, nz::cellular(p2 + v2, kSeed).f1) ? 1 : 0;
        same[4] += equal(nz::cellular(p3, kSeed).f1, nz::cellular(p3 + v3, kSeed).f1) ? 1 : 0;
        const IVec3 cell{i, -i, 3 * i};
        same[5] += nz::cellularSite(cell, kSeed).id == nz::cellularSite(cell + IVec3(-1039, 243, -1146), kSeed).id
                       ? 1
                       : 0;
        // Simplex offsets are not exact in f64; a period would still match to ~1e-12.
        same[6] += close(nz::simplex(p2, kSeed), nz::simplex(p2 + t2, kSeed)) ? 1 : 0;
        same[7] += close(nz::simplex(p3, kSeed), nz::simplex(p3 + t3, kSeed)) ? 1 : 0;
        same[8] += close(nz::simplex(p, kSeed), nz::simplex(p + t4, kSeed)) ? 1 : 0;
    }
    for (int k = 0; k < 9; ++k) {
        CAPTURE(k);
        // The old linear hash matched on (nearly) all 256 samples. Chance matches stay rare but not
        // zero: 2D simplex has only 8 gradients and often just one or two contributing corners
        // (8/256 matches with this seed); everything else has 0. Deterministic inputs: no flakes.
        CHECK(same[k] < kN / 8);
    }
}

TEST_CASE("noise: continuity (no seams at cell or simplex boundaries)") {
    // Walk long random lines in tiny steps; any discontinuity would show up as a jump far above
    // the Lipschitz bound of the smooth noise.
    Rng rng(92);
    const f64 step = 1e-4;
    f64 worst[7] = {};
    for (int line = 0; line < 40; ++line) {
        const DVec4 o{rng.range(-50.0, 50.0), rng.range(-50.0, 50.0), rng.range(-50.0, 50.0),
                      rng.range(-50.0, 50.0)};
        DVec4 d{rng.range(-1.0, 1.0), rng.range(-1.0, 1.0), rng.range(-1.0, 1.0), rng.range(-1.0, 1.0)};
        d = d / length(d);
        f64 prev[7] = {};
        for (int k = 0; k < 20000; ++k) {  // 2 units per line, crossing many cells
            const DVec4 p = o + d * (k * step);
            const f64 v[7] = {nz::perlin(DVec2(p.x, p.y), 1u),  nz::perlin(p.xyz(), 1u),  nz::perlin(p, 1u),
                              nz::simplex(DVec2(p.x, p.y), 1u), nz::simplex(p.xyz(), 1u), nz::simplex(p, 1u),
                              nz::cellular(p.xyz(), 1u).f1};
            if (k > 0) {
                for (int t = 0; t < 7; ++t) worst[t] = max(worst[t], std::fabs(v[t] - prev[t]) / step);
            }
            for (int t = 0; t < 7; ++t) prev[t] = v[t];
        }
    }
    for (int t = 0; t < 7; ++t) {
        CAPTURE(t);
        CHECK(worst[t] < 8.0);  // max gradient magnitudes are ~2-4; a seam would give ~1/step
    }
}

TEST_CASE("noise: cellular search is exact") {
    // The pruned ring search must agree with brute force over a 9x9(x9) block of sites.
    auto brute3 = [](const DVec3& p, u32 seed, f64 jitter) {
        f64 d1 = kInfinityD, d2 = kInfinityD;
        u32 id = 0;
        const IVec3 c = floorToI32(p);
        for (int dz = -4; dz <= 4; ++dz) {
            for (int dy = -4; dy <= 4; ++dy) {
                for (int dx = -4; dx <= 4; ++dx) {
                    const nz::CellularSite3 site = nz::cellularSite(c + IVec3(dx, dy, dz), seed, jitter);
                    const f64 d = distance(site.position, p);
                    if (d < d1) {
                        d2 = d1;
                        d1 = d;
                        id = site.id;
                    } else if (d < d2) {
                        d2 = d;
                    }
                }
            }
        }
        return nz::DCellular{d1, d2, id};
    };
    auto brute2 = [](const DVec2& p, u32 seed, f64 jitter) {
        f64 d1 = kInfinityD, d2 = kInfinityD;
        u32 id = 0;
        const IVec2 c = floorToI32(p);
        for (int dy = -4; dy <= 4; ++dy) {
            for (int dx = -4; dx <= 4; ++dx) {
                const nz::CellularSite2 site = nz::cellularSite(c + IVec2(dx, dy), seed, jitter);
                const f64 d = distance(site.position, p);
                if (d < d1) {
                    d2 = d1;
                    d1 = d;
                    id = site.id;
                } else if (d < d2) {
                    d2 = d;
                }
            }
        }
        return nz::DCellular{d1, d2, id};
    };
    Rng rng(93);
    for (int i = 0; i < 3000; ++i) {
        const f64 jitter = (i % 3 == 0) ? 1.0 : rng.uniform();
        const DVec3 p = rng.dvec3(-40.0, 40.0);
        const nz::DCellular fast = nz::cellular(p, 11u, jitter);
        const nz::DCellular ref = brute3(p, 11u, jitter);
        CHECK(approxEqual(fast.f1, ref.f1, 1e-12));
        CHECK(approxEqual(fast.f2, ref.f2, 1e-12));
        if (ref.f2 - ref.f1 > 1e-9) CHECK(fast.cellId == ref.cellId);
        const DVec2 q{p.x, p.y};
        const nz::DCellular fast2 = nz::cellular(q, 12u, jitter);
        const nz::DCellular ref2 = brute2(q, 12u, jitter);
        CHECK(approxEqual(fast2.f1, ref2.f1, 1e-12));
        CHECK(approxEqual(fast2.f2, ref2.f2, 1e-12));
        if (ref2.f2 - ref2.f1 > 1e-9) CHECK(fast2.cellId == ref2.cellId);
        CHECK(fast.f1 <= fast.f2);
    }
    // Sites stay inside their cells and jitter 0 puts them at the cell centres.
    for (int i = 0; i < 2000; ++i) {
        const IVec3 cell{static_cast<i32>(rng.range(-1e6, 1e6)), static_cast<i32>(rng.range(-1e6, 1e6)), -7};
        const nz::CellularSite3 s = nz::cellularSite(cell, 4u, 1.0);
        CHECK(floorToI32(s.position) == cell);
        CHECK(nz::cellularSite(cell, 4u, 0.0).position == toF64(cell) + DVec3(0.5));
        CHECK(nz::cellularSite(cell, 4u, 0.3).id == s.id);  // the id does not depend on jitter
    }
    // Jitter 0: F1 is the distance to the nearest cell centre.
    for (int i = 0; i < 2000; ++i) {
        const DVec2 p{rng.range(-10.0, 10.0), rng.range(-10.0, 10.0)};
        CHECK(approxEqual(nz::cellular(p, 3u, 0.0).f1, distance(p, floor(p) + DVec2(0.5)), 1e-12));
    }
    // F1 and F2 are 1-Lipschitz (continuous).
    for (int i = 0; i < 5000; ++i) {
        const DVec3 p = rng.dvec3(-30.0, 30.0);
        const DVec3 d = rng.unitD() * 0.01;
        const nz::DCellular a = nz::cellular(p, 21u), b = nz::cellular(p + d, 21u);
        CHECK(std::fabs(a.f1 - b.f1) <= 0.01 + 1e-12);
        CHECK(std::fabs(a.f2 - b.f2) <= 0.01 + 1e-12);
    }
}

TEST_CASE("noise throughput (budget report)") {
    // Budget (noise.h): 3D perlin/simplex <= 60 ns and cellular 3D <= 350 ns per sample on a 3 GHz
    // x64 core in an optimized build. The assertion is deliberately generous so Debug, sanitizer
    // and shared CI machines pass; the measured numbers are printed for tracking.
    constexpr int kN = 200000;
    f64 sink = 0.0;
    auto measure = [&](auto&& fn) {
        const auto t0 = std::chrono::steady_clock::now();
        for (int i = 0; i < kN; ++i) sink += fn(i);
        const auto t1 = std::chrono::steady_clock::now();
        return std::chrono::duration<f64, std::nano>(t1 - t0).count() / kN;
    };
    const f64 perlin3 = measure([](int i) { return nz::perlin(DVec3(i * 0.013, i * 0.007, i * 0.011), 1u); });
    const f64 simplex3 =
        measure([](int i) { return nz::simplex(DVec3(i * 0.013, i * 0.007, i * 0.011), 1u); });
    const f64 simplex2f = measure([](int i) {
        const f32 fi = static_cast<f32>(i);
        return nz::simplex(Vec2(fi * 0.013f, fi * 0.007f), 1u);
    });
    const f64 cell3 =
        measure([](int i) { return nz::cellular(DVec3(i * 0.013, i * 0.007, i * 0.011), 1u).f1; });
    const f64 fbm3 = measure([](int i) { return nz::fbm(DVec3(i * 0.013, i * 0.007, i * 0.011), 1u); });
    MESSAGE("ns/sample: perlin3 " << perlin3 << ", simplex3 " << simplex3 << ", simplex2f " << simplex2f
                                  << ", cellular3 " << cell3 << ", fbm3(6 oct) " << fbm3 << " (sink " << sink
                                  << ")");
    CHECK(perlin3 < 2000.0);
    CHECK(simplex3 < 2000.0);
    CHECK(cell3 < 5000.0);
}
