# Concept-reference lint (01 §5.2 provenance; docs/concept/README.md). Checks docs/concept/:
#
#   cmake -DSOURCE_DIR=<repository root> -P concept_refs.cmake
#
# Fails on:
#  * a file type the folder does not take (images .png/.webp/.jpg/.jpeg, `<image>.concept.jsonc`
#    sidecars, Markdown, .gitattributes), or an upper-case extension;
#  * an image outside editor/, client/, launcher/ or world/, or not named
#    `<tool-or-area>-<subject>[-<variant>]-vNN.<ext>`, or whose concept name is not in README.md's index;
#  * an image over 1 MB (1,048,576 bytes) or 2,560 px on its long side, or whose bytes do not match
#    its extension;
#  * an image without a sidecar, a sidecar without an image, and a sidecar (or TEMPLATE.concept.jsonc)
#    that is not JSONC, lacks a required field, has an unknown one, a value of the wrong type or
#    outside its set, or a sha256 that does not match the image;
#  * a missing README.md (the index).
# The files: in a git checkout those git tracks or would track (an ignored .DS_Store does not count);
# elsewhere every file. Findings are `path: message`, or `path:line: message` in a sidecar (the line
# of the field, best effort). JSONC is read with CMake's JSON parser, which takes comments and trailing
# commas (the `ok` fixture pins that) but keeps only the last of duplicate keys and ignores text after
# the closing brace.

cmake_minimum_required(VERSION 3.28)
if(NOT IS_DIRECTORY "${SOURCE_DIR}")
  message(FATAL_ERROR "concept_refs: SOURCE_DIR is not a directory: '${SOURCE_DIR}'")
endif()
get_filename_component(SOURCE_DIR "${SOURCE_DIR}" ABSOLUTE)
set(concept "${SOURCE_DIR}/docs/concept")

# The rules (docs/concept/README.md). Change them there first.
set(kAreas editor client launcher world)
set(kMaxBytes 1048576)
set(kMaxSide 2560)
set(kMaxSidecarBytes 65536)   # a sidecar is a few KB; this bounds the work on a hostile one
set(kStatuses binding directional mood-only)
set(kSourceKinds owner commissioned cc0 ai-assisted)
set(kInputSources owner commissioned cc0 ai-assisted)
set(kLicences MIT CC0-1.0)
set(kKeys image sha256 title author created source tools ai licence ipReview status elements phase planRefs
          deviations review)
set(kNamePattern "^[a-z0-9]+(-[a-z0-9]+)+-v[0-9][0-9]\\.(png|webp|jpg|jpeg)$")
string(REPEAT "[0-9a-f]" 64 kHex64)
set(kSha "^${kHex64}$")
set(kSha_DESC "64 lower-case hex digits")
set(kDate "^[0-9][0-9][0-9][0-9]-[01][0-9]-[0-3][0-9]$")
set(kDate_DESC "a YYYY-MM-DD date")
set(kPhase "^Ph[0-5]$")
set(kPhase_DESC "Ph0 to Ph5")

set_property(GLOBAL PROPERTY _CR_FINDINGS "")
set_property(GLOBAL PROPERTY _CR_COUNT 0)

# Records one finding. A function, not a macro: messages carry sidecar text, which a macro would
# re-expand.
function(_cr_find msg)
  string(REPLACE "\n" " " msg "${msg}")
  set_property(GLOBAL APPEND_STRING PROPERTY _CR_FINDINGS "\n  ${msg}")
  get_property(n GLOBAL PROPERTY _CR_COUNT)
  math(EXPR n "${n} + 1")
  set_property(GLOBAL PROPERTY _CR_COUNT ${n})
endfunction()

# Quotes a value from a sidecar for a message, cut to 60 characters.
function(_cr_quote value out)
  string(LENGTH "${value}" n)
  if(n GREATER 60)
    string(SUBSTRING "${value}" 0 57 value)
    string(APPEND value "...")
  endif()
  set(${out} "'${value}'" PARENT_SCOPE)
endfunction()

# Sets <out> to the 1-based line of the first `"<key>":` in `text` (the caller's sidecar), or 1.
function(_cr_line key out)
  set(line 1)
  string(REGEX MATCH "\"${key}\"[ \t\r\n]*:" m "${text}")
  if(m)
    string(FIND "${text}" "${m}" pos)
    string(SUBSTRING "${text}" 0 ${pos} head)
    string(REGEX MATCHALL "\n" nl "${head}")
    list(LENGTH nl n)
    math(EXPR line "${n} + 1")
  endif()
  set(${out} ${line} PARENT_SCOPE)
endfunction()

# Reports `msg` against the caller's sidecar (`shown`), at the line of `key`.
function(_cr_field_find key msg)
  _cr_line("${key}" line)
  _cr_find("${shown}:${line}: ${msg}")
endfunction()

# Sets <out> to the value at the path ARGN of `json` and <out>_type to its JSON type (MISSING if absent).
function(_cr_get out json)
  string(JSON type ERROR_VARIABLE err TYPE "${json}" ${ARGN})
  if(err)
    set(${out}_type MISSING PARENT_SCOPE)
    set(${out} "" PARENT_SCOPE)
    return()
  endif()
  string(JSON value ERROR_VARIABLE err GET "${json}" ${ARGN})
  set(${out}_type "${type}" PARENT_SCOPE)
  set(${out} "${value}" PARENT_SCOPE)
endfunction()

# Reports unknown members of the object at the path ARGN of `json` (allowed: the list `allowedVar`).
function(_cr_unknown_keys label allowedVar json)
  string(JSON n ERROR_VARIABLE err LENGTH "${json}" ${ARGN})
  if(err OR n EQUAL 0)
    return()
  endif()
  math(EXPR last "${n} - 1")
  foreach(i RANGE ${last})
    string(JSON k MEMBER "${json}" ${ARGN} ${i})
    if(NOT "${k}" IN_LIST ${allowedVar})
      _cr_quote("${k}" q)
      string(REPLACE ";" ", " allowed "${${allowedVar}}")
      _cr_field_find("${k}" "unknown field ${q} in ${label} (allowed: ${allowed})")
    endif()
  endforeach()
endfunction()

# Checks that the value at the path ARGN of `json` is a non-empty string. `check` is "" (any), `IN:<list
# variable>` (one of its entries) or `RE:<variable>` (matches the regex in it; <variable>_DESC says what
# that is). Sets <out> to the value if it passes, else "".
function(_cr_string out label key check json)
  set(${out} "" PARENT_SCOPE)
  _cr_get(v "${json}" ${ARGN})
  if(v_type STREQUAL "MISSING")
    list(GET ARGN 0 top)   # point at the enclosing top-level field (line 1 if that is missing too)
    _cr_field_find("${top}" "missing required field '${label}'")
    return()
  elseif(NOT v_type STREQUAL "STRING")
    _cr_field_find("${key}" "'${label}' must be a string, not ${v_type}")
    return()
  elseif("${v}" STREQUAL "")
    _cr_field_find("${key}" "'${label}' is empty")
    return()
  endif()
  _cr_quote("${v}" q)
  if(check MATCHES "^IN:(.*)$")
    set(listVar "${CMAKE_MATCH_1}")
    if(NOT "${v}" IN_LIST ${listVar})
      string(REPLACE ";" ", " allowed "${${listVar}}")
      _cr_field_find("${key}" "'${label}' is ${q}, not one of ${allowed}")
      return()
    endif()
  elseif(check MATCHES "^RE:(.*)$")
    set(reVar "${CMAKE_MATCH_1}")
    if(NOT "${v}" MATCHES "${${reVar}}")
      _cr_field_find("${key}" "'${label}' is ${q}, not ${${reVar}_DESC}")
      return()
    endif()
  endif()
  set(${out} "${v}" PARENT_SCOPE)
endfunction()

# Checks that the value at the path ARGN of `json` is an array (of strings when `elementType` is
# STRING, each non-empty) and, with `minCount`, has that many entries. Sets <out> to its length.
function(_cr_array out label key elementType minCount json)
  set(${out} 0 PARENT_SCOPE)
  _cr_get(v "${json}" ${ARGN})
  if(v_type STREQUAL "MISSING")
    list(GET ARGN 0 top)
    _cr_field_find("${top}" "missing required field '${label}'")
    return()
  elseif(NOT v_type STREQUAL "ARRAY")
    _cr_field_find("${key}" "'${label}' must be an array, not ${v_type}")
    return()
  endif()
  string(JSON n LENGTH "${json}" ${ARGN})
  if(n LESS minCount)
    _cr_field_find("${key}" "'${label}' needs at least ${minCount} entry")
  endif()
  if(n GREATER 0)
    math(EXPR last "${n} - 1")
    foreach(i RANGE ${last})
      _cr_get(e "${json}" ${ARGN} ${i})
      if(NOT e_type STREQUAL elementType)
        _cr_field_find("${key}" "'${label}[${i}]' must be ${elementType}, not ${e_type}")
      elseif(elementType STREQUAL "STRING" AND "${e}" STREQUAL "")
        _cr_field_find("${key}" "'${label}[${i}]' is empty")
      endif()
    endforeach()
  endif()
  set(${out} ${n} PARENT_SCOPE)
endfunction()

# Checks a sidecar (or, with `imageAbs` empty, the template) at docs/concept/<rel>.
function(_cr_sidecar rel imageAbs)
  set(shown "docs/concept/${rel}")
  file(SIZE "${concept}/${rel}" bytes)
  if(bytes GREATER kMaxSidecarBytes)
    _cr_find("${shown}: ${bytes} bytes, over the ${kMaxSidecarBytes}-byte limit for a sidecar")
    return()
  endif()
  file(READ "${concept}/${rel}" text)
  string(JSON rootType ERROR_VARIABLE err TYPE "${text}")
  if(err)
    set(line 1)
    if(err MATCHES "Line ([0-9]+), Column")
      set(line ${CMAKE_MATCH_1})
    endif()
    string(REGEX REPLACE "^failed parsing json string: (\\* Line [0-9]+, Column [0-9]+)?[ \t\n]*" "" err "${err}")
    string(STRIP "${err}" err)
    _cr_find("${shown}:${line}: not valid JSONC: ${err}")
    return()
  endif()
  if(NOT rootType STREQUAL "OBJECT")
    _cr_find("${shown}:1: not a JSON object (the sidecar is one object, see TEMPLATE.concept.jsonc)")
    return()
  endif()
  _cr_unknown_keys("the sidecar" kKeys "${text}")

  _cr_string(image "image" image "" "${text}" image)
  if(imageAbs AND NOT image STREQUAL "")
    get_filename_component(imageName "${imageAbs}" NAME)
    if(NOT image STREQUAL imageName)
      _cr_quote("${image}" q)
      _cr_field_find(image "'image' is ${q}, not this sidecar's image '${imageName}'")
    endif()
  endif()
  _cr_string(sha "sha256" sha256 "RE:kSha" "${text}" sha256)
  if(imageAbs AND NOT sha STREQUAL "")
    file(SHA256 "${imageAbs}" actual)
    if(NOT sha STREQUAL actual)
      _cr_field_find(sha256 "sha256 ${sha} does not match the image (${actual}): a changed image is a new version")
    endif()
  endif()
  _cr_string(ignored "title" title "" "${text}" title)
  _cr_string(ignored "author" author "" "${text}" author)
  _cr_string(ignored "created" created "RE:kDate" "${text}" created)
  _cr_string(ignored "ipReview" ipReview "" "${text}" ipReview)
  _cr_string(ignored "status" status "IN:kStatuses" "${text}" status)
  _cr_string(ignored "phase" phase "RE:kPhase" "${text}" phase)
  _cr_array(ignored "tools" tools STRING 0 "${text}" tools)
  _cr_array(ignored "planRefs" planRefs STRING 1 "${text}" planRefs)
  _cr_array(ignored "deviations" deviations STRING 0 "${text}" deviations)

  # source: what the image is made from (01 §5.2), and the evidence each kind needs.
  set(kind "")
  _cr_get(src "${text}" source)
  if(src_type STREQUAL "MISSING")
    _cr_field_find(source "missing required field 'source'")
  elseif(NOT src_type STREQUAL "OBJECT")
    _cr_field_find(source "'source' must be an object, not ${src_type}")
  else()
    set(kSourceKeys kind url rights)
    _cr_unknown_keys("'source'" kSourceKeys "${text}" source)
    _cr_string(kind "source.kind" kind "IN:kSourceKinds" "${text}" source kind)
    foreach(pair "cc0|url|where the CC0 image was obtained" "commissioned|rights|how the rights were assigned")
      string(REPLACE "|" ";" parts "${pair}")
      list(GET parts 0 needKind)
      list(GET parts 1 needKey)
      list(GET parts 2 why)
      _cr_get(extra "${text}" source ${needKey})
      if(kind STREQUAL needKind AND NOT (extra_type STREQUAL "STRING" AND NOT "${extra}" STREQUAL ""))
        _cr_field_find(kind "source.kind '${needKind}' needs 'source.${needKey}' (${why})")
      elseif(NOT extra_type STREQUAL "MISSING" AND NOT extra_type STREQUAL "STRING")
        _cr_field_find(${needKey} "'source.${needKey}' must be a string, not ${extra_type}")
      endif()
    endforeach()
  endif()

  _cr_string(licence "licence" licence "IN:kLicences" "${text}" licence)
  if(kind STREQUAL "cc0" AND NOT licence STREQUAL "" AND NOT licence STREQUAL "CC0-1.0")
    _cr_field_find(licence "a CC0 image keeps licence 'CC0-1.0', not '${licence}'")
  endif()

  # ai: null unless source.kind is ai-assisted; then the generator, the prompt and every input.
  _cr_get(ai "${text}" ai)
  if(ai_type STREQUAL "MISSING")
    _cr_field_find(ai "missing required field 'ai' (null unless source.kind is ai-assisted)")
  elseif(kind STREQUAL "ai-assisted")
    if(NOT ai_type STREQUAL "OBJECT")
      _cr_field_find(ai "source.kind 'ai-assisted' needs 'ai' to be an object (tool, model, prompt, inputs)")
    else()
      set(kAiKeys tool model prompt settings inputs)
      _cr_unknown_keys("'ai'" kAiKeys "${text}" ai)
      _cr_string(ignored "ai.tool" tool "" "${text}" ai tool)
      _cr_string(ignored "ai.model" model "" "${text}" ai model)
      _cr_string(ignored "ai.prompt" prompt "" "${text}" ai prompt)
      _cr_get(settings "${text}" ai settings)
      if(NOT settings_type STREQUAL "MISSING" AND NOT settings_type STREQUAL "STRING")
        _cr_field_find(settings "'ai.settings' must be a string, not ${settings_type}")
      endif()
      _cr_array(nInputs "ai.inputs" inputs OBJECT 0 "${text}" ai inputs)
      if(nInputs GREATER 0)
        set(kInputKeys file sha256 source)
        math(EXPR last "${nInputs} - 1")
        foreach(i RANGE ${last})
          _cr_unknown_keys("'ai.inputs[${i}]'" kInputKeys "${text}" ai inputs ${i})
          _cr_string(inFile "ai.inputs[${i}].file" inputs "" "${text}" ai inputs ${i} file)
          _cr_string(inSha "ai.inputs[${i}].sha256" inputs "RE:kSha" "${text}" ai inputs ${i} sha256)
          _cr_string(inSource "ai.inputs[${i}].source" inputs "IN:kInputSources" "${text}" ai inputs ${i} source)
          # An input committed here (a path relative to docs/concept) must be the bytes recorded.
          set(inAbs "${concept}/${inFile}")
          if(NOT inFile STREQUAL "" AND NOT IS_ABSOLUTE "${inFile}" AND EXISTS "${inAbs}"
             AND NOT IS_DIRECTORY "${inAbs}")
            file(SHA256 "${inAbs}" inActual)
            if(NOT inSha STREQUAL "" AND NOT inSha STREQUAL inActual)
              _cr_field_find(inputs "'ai.inputs[${i}].sha256' does not match docs/concept/${inFile}")
            endif()
          elseif(inSource STREQUAL "ai-assisted")
            _cr_field_find(inputs "'ai.inputs[${i}]' is ai-assisted, so it must be an image in docs/concept (with its own sidecar)")
          endif()
        endforeach()
      endif()
    endif()
  elseif(NOT ai_type STREQUAL "NULL")
    _cr_field_find(ai "'ai' must be null unless source.kind is 'ai-assisted'")
  endif()

  # elements: per-element status overrides.
  _cr_array(nElements "elements" elements OBJECT 0 "${text}" elements)
  if(nElements GREATER 0)
    set(kElementKeys element status note)
    math(EXPR last "${nElements} - 1")
    foreach(i RANGE ${last})
      _cr_unknown_keys("'elements[${i}]'" kElementKeys "${text}" elements ${i})
      _cr_string(ignored "elements[${i}].element" element "" "${text}" elements ${i} element)
      _cr_string(ignored "elements[${i}].status" elements "IN:kStatuses" "${text}" elements ${i} status)
      _cr_get(note "${text}" elements ${i} note)
      if(NOT note_type STREQUAL "MISSING" AND NOT note_type STREQUAL "STRING")
        _cr_field_find(elements "'elements[${i}].note' must be a string, not ${note_type}")
      endif()
    endforeach()
  endif()

  # review: "" or a Markdown file, relative to docs/concept.
  _cr_get(review "${text}" review)
  if(review_type STREQUAL "MISSING")
    _cr_field_find(review "missing required field 'review' (\"\" until a review exists)")
  elseif(NOT review_type STREQUAL "STRING")
    _cr_field_find(review "'review' must be a string, not ${review_type}")
  elseif(NOT "${review}" STREQUAL "")
    _cr_quote("${review}" q)
    if(IS_ABSOLUTE "${review}" OR NOT review MATCHES "\\.md$")
      _cr_field_find(review "'review' is ${q}: a .md file relative to docs/concept")
    elseif(NOT EXISTS "${concept}/${review}" OR IS_DIRECTORY "${concept}/${review}")
      _cr_field_find(review "'review' names docs/concept/${review}, which does not exist")
    endif()
  endif()
endfunction()

# Reads an image's pixel size from its header. Sets <out>_w and <out>_h, or <out>_err.
function(_cr_dimensions path ext out)
  set(${out}_err "" PARENT_SCOPE)
  set(w 0)
  set(h 0)
  if(ext STREQUAL "png")
    file(READ "${path}" hex LIMIT 24 HEX)
    if(NOT hex MATCHES "^89504e470d0a1a0a........49484452(........)(........)$")
      set(${out}_err "is not a readable PNG file (signature and IHDR header)" PARENT_SCOPE)
      return()
    endif()
    math(EXPR w "0x${CMAKE_MATCH_1}")
    math(EXPR h "0x${CMAKE_MATCH_2}")
  elseif(ext STREQUAL "webp")
    file(READ "${path}" hex LIMIT 30 HEX)
    if(NOT hex MATCHES "^52494646........57454250(........)")
      set(${out}_err "is not a WebP file (no RIFF/WEBP header)" PARENT_SCOPE)
      return()
    endif()
    set(fourcc "${CMAKE_MATCH_1}")
    string(LENGTH "${hex}" hexLen)
    if(hexLen LESS 60)
      set(${out}_err "is a truncated WebP file" PARENT_SCOPE)
      return()
    endif()
    # Byte i of the file is hex digits 2i and 2i+1; the fields are little-endian.
    string(REPEAT ".." 23 at23)
    string(REPEAT ".." 20 at20)
    string(REPEAT ".." 24 at24)
    if(fourcc STREQUAL "56503820" AND hex MATCHES "^${at23}9d012a(..)(..)(..)(..)")
      # "VP8 " (lossy): 14-bit width and height after the key-frame start code (bytes 23-25).
      math(EXPR w "0x${CMAKE_MATCH_2}${CMAKE_MATCH_1} & 0x3fff")
      math(EXPR h "0x${CMAKE_MATCH_4}${CMAKE_MATCH_3} & 0x3fff")
    elseif(fourcc STREQUAL "5650384c" AND hex MATCHES "^${at20}2f(..)(..)(..)(..)")
      # "VP8L" (lossless): signature 0x2f at byte 20, then 14 bits of width-1 and 14 of height-1.
      math(EXPR bits "0x${CMAKE_MATCH_4}${CMAKE_MATCH_3}${CMAKE_MATCH_2}${CMAKE_MATCH_1}")
      math(EXPR w "(${bits} & 0x3fff) + 1")
      math(EXPR h "((${bits} >> 14) & 0x3fff) + 1")
    elseif(fourcc STREQUAL "56503858" AND hex MATCHES "^${at24}(..)(..)(..)(..)(..)(..)")
      # "VP8X" (extended): 24-bit canvas width-1 and height-1 at bytes 24-29.
      math(EXPR w "0x${CMAKE_MATCH_3}${CMAKE_MATCH_2}${CMAKE_MATCH_1} + 1")
      math(EXPR h "0x${CMAKE_MATCH_6}${CMAKE_MATCH_5}${CMAKE_MATCH_4} + 1")
    else()
      set(${out}_err "is a WebP file whose size cannot be read (chunk ${fourcc})" PARENT_SCOPE)
      return()
    endif()
  else()
    # JPEG: walk the marker segments to the first frame header (SOF0-15 but DHT, JPG and DAC).
    file(READ "${path}" hex LIMIT 2 HEX)
    if(NOT hex STREQUAL "ffd8")
      set(${out}_err "is not a JPEG file (no SOI marker)" PARENT_SCOPE)
      return()
    endif()
    file(SIZE "${path}" size)
    set(offset 2)
    set(found OFF)
    foreach(step RANGE 1000)
      if(offset GREATER_EQUAL size)
        break()
      endif()
      file(READ "${path}" seg OFFSET ${offset} LIMIT 9 HEX)
      if(NOT seg MATCHES "^ff(..)")
        break()
      endif()
      set(marker "${CMAKE_MATCH_1}")
      if(marker STREQUAL "ff")
        math(EXPR offset "${offset} + 1")   # fill byte
        continue()
      endif()
      if(marker MATCHES "^(d[0-7]|01)$")
        math(EXPR offset "${offset} + 2")   # standalone marker
        continue()
      endif()
      if(marker MATCHES "^(d8|d9|da)$")
        break()                              # SOI again, EOI or scan data before any frame header
      endif()
      if(NOT seg MATCHES "^ff..(....)")
        break()                              # truncated
      endif()
      math(EXPR len "0x${CMAKE_MATCH_1}")
      if(marker MATCHES "^c[0-35-79abd-f]$")
        if(seg MATCHES "^ff........(....)(....)$")
          math(EXPR h "0x${CMAKE_MATCH_1}")
          math(EXPR w "0x${CMAKE_MATCH_2}")
          set(found ON)
        endif()
        break()
      endif()
      if(len LESS 2)
        break()
      endif()
      math(EXPR offset "${offset} + 2 + ${len}")
    endforeach()
    if(NOT found)
      set(${out}_err "is a JPEG file without a readable frame header" PARENT_SCOPE)
      return()
    endif()
  endif()
  if(w EQUAL 0 OR h EQUAL 0)
    set(${out}_err "has a zero width or height in its header" PARENT_SCOPE)
    return()
  endif()
  set(${out}_w ${w} PARENT_SCOPE)
  set(${out}_h ${h} PARENT_SCOPE)
endfunction()

# --------------------------------------------------------------------------------------------------
if(NOT IS_DIRECTORY "${concept}")
  message(FATAL_ERROR "Concept-reference lint failed: ${concept} does not exist (wrong SOURCE_DIR?)")
endif()

# The files, relative to docs/concept. Names with ';', '[' or ']' cannot be told apart in a CMake list.
set(files "")
set(how "git")
find_program(_crGit git)
if(_crGit)
  execute_process(COMMAND "${_crGit}" -c core.quotePath=false ls-files --cached --others --exclude-standard
                          -- docs/concept
                  WORKING_DIRECTORY "${SOURCE_DIR}" RESULT_VARIABLE rc OUTPUT_VARIABLE out ERROR_QUIET)
  if(rc EQUAL 0)
    string(REGEX MATCHALL "[^\n]*[][;][^\n]*" odd "${out}")
    if(odd)
      _cr_find("docs/concept: a file name contains ';', '[' or ']' (rename it)")
      string(REGEX REPLACE "[^\n]*[][;][^\n]*\n?" "" out "${out}")
    endif()
    string(REPLACE "\n" ";" files "${out}")
  endif()
endif()
list(FILTER files EXCLUDE REGEX "^$")
if(files STREQUAL "")
  set(how "every file")
  file(GLOB_RECURSE files LIST_DIRECTORIES false RELATIVE "${SOURCE_DIR}" "${concept}/*")
  foreach(f IN LISTS files)
    if(NOT EXISTS "${SOURCE_DIR}/${f}" OR f MATCHES "[][]")
      _cr_find("docs/concept: a file name contains ';', '[' or ']' (rename it)")
      list(REMOVE_ITEM files "${f}")
    endif()
  endforeach()
endif()
set(rels "")
foreach(f IN LISTS files)
  string(REGEX REPLACE "^docs/concept/" "" rel "${f}")
  if(EXISTS "${concept}/${rel}")   # a tracked file deleted in the working tree is skipped
    list(APPEND rels "${rel}")
  endif()
endforeach()
list(REMOVE_DUPLICATES rels)
list(SORT rels)

set(readme "")
if(EXISTS "${concept}/README.md")
  file(READ "${concept}/README.md" readme)
else()
  _cr_find("docs/concept/README.md: missing (the index and the rules)")
endif()

set(images "")
set(sidecars "")
foreach(rel IN LISTS rels)
  set(shown "docs/concept/${rel}")
  if(rel STREQUAL "README.md" OR rel STREQUAL ".gitattributes")
    continue()
  elseif(rel STREQUAL "TEMPLATE.concept.jsonc")
    _cr_sidecar("${rel}" "")
  elseif(rel MATCHES "\\.concept\\.jsonc$")
    list(APPEND sidecars "${rel}")
  elseif(rel MATCHES "\\.md$")
    continue()
  elseif(rel MATCHES "\\.(png|webp|jpg|jpeg)$")
    list(APPEND images "${rel}")
  else()
    _cr_find("${shown}: not allowed here: images are .png, .webp, .jpg or .jpeg (lower case), next to a .concept.jsonc sidecar; notes are .md")
  endif()
endforeach()

foreach(rel IN LISTS images)
  set(shown "docs/concept/${rel}")
  set(path "${concept}/${rel}")
  get_filename_component(name "${rel}" NAME)
  string(REGEX MATCH "[a-z]+$" ext "${name}")
  if(NOT rel MATCHES "^([^/]+)/[^/]+$" OR NOT CMAKE_MATCH_1 IN_LIST kAreas)
    string(REPLACE ";" "/, " areas "${kAreas}")
    _cr_find("${shown}: not directly in an area directory (${areas}/)")
  endif()
  if(NOT name MATCHES "${kNamePattern}")
    _cr_find("${shown}: name is not <tool-or-area>-<subject>[-<variant>]-vNN.<ext> in lower case")
  else()
    string(REGEX REPLACE "-v[0-9][0-9]\\.[a-z]+$" "" conceptName "${name}")
    if(NOT readme MATCHES "(^|[^a-z0-9-])${conceptName}([^a-z0-9-]|$)")
      _cr_find("${shown}: concept '${conceptName}' is not in the index (docs/concept/README.md)")
    endif()
  endif()
  file(SIZE "${path}" bytes)
  if(bytes GREATER kMaxBytes)
    _cr_find("${shown}: ${bytes} bytes, over the ${kMaxBytes}-byte (1 MB) limit")
  endif()
  _cr_dimensions("${path}" "${ext}" dim)
  if(dim_err)
    _cr_find("${shown}: ${dim_err}")
  else()
    set(side ${dim_w})
    if(dim_h GREATER side)
      set(side ${dim_h})
    endif()
    if(side GREATER kMaxSide)
      _cr_find("${shown}: ${dim_w} x ${dim_h} px, over ${kMaxSide} px on the long side")
    endif()
  endif()
  if(NOT EXISTS "${path}.concept.jsonc")
    _cr_find("${shown}: no sidecar (add ${name}.concept.jsonc from TEMPLATE.concept.jsonc)")
  endif()
endforeach()

foreach(rel IN LISTS sidecars)
  string(REGEX REPLACE "\\.concept\\.jsonc$" "" imageRel "${rel}")
  if(NOT EXISTS "${concept}/${imageRel}" OR IS_DIRECTORY "${concept}/${imageRel}")
    _cr_find("docs/concept/${rel}: orphan sidecar: docs/concept/${imageRel} does not exist")
    continue()
  endif()
  _cr_sidecar("${rel}" "${concept}/${imageRel}")
endforeach()

list(LENGTH images nImages)
list(LENGTH sidecars nSidecars)
get_property(count GLOBAL PROPERTY _CR_COUNT)
if(count GREATER 0)
  get_property(text GLOBAL PROPERTY _CR_FINDINGS)
  message(FATAL_ERROR "Concept-reference lint failed (${count} finding(s); rules in docs/concept/README.md, "
                      "01 §5.2):${text}\n")
endif()
message(STATUS "Concept-reference lint passed: ${nImages} image(s), ${nSidecars} sidecar(s) (${how})")
