# Content asset manifest lint (WP-0.20b; 01 §5.2, 07 §1.7). content/ASSETS.md lists every binary source under
# content/ with the byte count and SHA-256 of the committed file, and each of its rows names a file that is
# there with that size and hash. A binary source is any content file that is not one of the text document
# types below, so a new binary type needs its row without a change here. A file that is a Git LFS pointer (a
# checkout without the LFS objects, as in CI) is compared through the pointer's oid and size: the lint needs
# neither git nor git-lfs and never fetches an object. The rest of an asset's provenance (origin, licence,
# source URL) is its `.meta` sidecar's, which `helios-cook check` validates.
#
#   cmake -DSOURCE_DIR=<repository root> -P content_assets.cmake
#
# Rows are the manifest's table lines of the form | `<path under content/>` | ... | <bytes> | `<sha256>` |.

cmake_minimum_required(VERSION 3.28)
get_filename_component(SOURCE_DIR "${SOURCE_DIR}" ABSOLUTE)
if(NOT IS_DIRECTORY "${SOURCE_DIR}/content")
  message(FATAL_ERROR "content_assets failed:\n  ${SOURCE_DIR}/content is not a directory\n")
endif()
set(content "${SOURCE_DIR}/content")
set(manifest "${content}/ASSETS.md")
# Text document types (helios-cook's contentTypes() and the sidecars); the root's .gitattributes is git's.
set(textExtensions .hrec .hcont .hent .md .meta .jsonc)
set(lfsVersion "version https://git-lfs.github.com/spec/v1")

set(errors "")
set(rowPaths "")
set(rowBytes "")
set(rowShas "")
if(EXISTS "${manifest}")
  file(STRINGS "${manifest}" lines ENCODING UTF-8)
  foreach(line IN LISTS lines)
    if(line MATCHES "^\\| `([^`]+)` \\|.*\\| ([0-9]+) \\| `([0-9a-f]+)` \\|$")
      set(path "${CMAKE_MATCH_1}")
      set(sha "${CMAKE_MATCH_3}")
      string(LENGTH "${sha}" shaLength)
      list(FIND rowPaths "${path}" at)
      if(NOT at EQUAL -1)
        list(APPEND errors "content/ASSETS.md: '${path}' is listed twice")
      elseif(NOT shaLength EQUAL 64)
        list(APPEND errors "content/ASSETS.md: '${path}': '${sha}' is not a SHA-256 (64 lower-case hex digits)")
      else()
        list(APPEND rowPaths "${path}")
        list(APPEND rowBytes "${CMAKE_MATCH_2}")
        list(APPEND rowShas "${sha}")
      endif()
    endif()
  endforeach()
endif()

file(GLOB_RECURSE files LIST_DIRECTORIES false RELATIVE "${content}" "${content}/*")
list(SORT files)
set(binaries "")
set(pointers 0)
foreach(rel IN LISTS files)
  # Hidden files and the cook's ignored output are helios-cook check's business, not sources.
  if(rel MATCHES "(^|/)\\.")
    continue()
  endif()
  get_filename_component(ext "${rel}" LAST_EXT)
  string(TOLOWER "${ext}" ext)
  if(ext IN_LIST textExtensions)
    continue()
  endif()
  list(APPEND binaries "${rel}")
  set(file "${content}/${rel}")
  file(SIZE "${file}" size)
  set(isPointer OFF)
  if(size LESS_EQUAL 1024)
    file(READ "${file}" text)
    if(text MATCHES "^${lfsVersion}\noid sha256:([0-9a-f]+)\nsize ([0-9]+)\n$")
      set(isPointer ON)
      set(sha "${CMAKE_MATCH_1}")
      set(size "${CMAKE_MATCH_2}")
      math(EXPR pointers "${pointers} + 1")
    endif()
  endif()
  if(NOT isPointer)
    file(SHA256 "${file}" sha)
  endif()
  list(FIND rowPaths "${rel}" at)
  if(at EQUAL -1)
    list(APPEND errors "content/${rel}: not listed in content/ASSETS.md (a binary source has a row with its bytes and SHA-256)")
    continue()
  endif()
  list(GET rowBytes ${at} wantBytes)
  list(GET rowShas ${at} wantSha)
  if(NOT sha STREQUAL wantSha)
    list(APPEND errors "content/${rel}: SHA-256 ${sha} differs from content/ASSETS.md's ${wantSha}")
  endif()
  if(NOT size STREQUAL wantBytes)
    list(APPEND errors "content/${rel}: ${size} bytes, content/ASSETS.md says ${wantBytes}")
  endif()
endforeach()
foreach(path IN LISTS rowPaths)
  list(FIND binaries "${path}" at)
  if(NOT at EQUAL -1)
    continue()
  elseif(EXISTS "${content}/${path}")
    list(APPEND errors "content/${path}: listed in content/ASSETS.md but not a binary source")
  else()
    list(APPEND errors "content/${path}: listed in content/ASSETS.md but missing")
  endif()
endforeach()

list(LENGTH binaries count)
if(errors)
  # Indented lines are not word-wrapped by message(), so each finding stays on one line.
  list(LENGTH errors n)
  string(REPLACE ";" "\n  " text "${errors}")
  message(FATAL_ERROR "content_assets failed (${n} finding(s); rules in content/README.md):\n  ${text}\n")
endif()
message(STATUS "content_assets: ${count} binary source(s) match content/ASSETS.md (${pointers} as Git LFS pointers)")
