# IP-name lint (WP-0.2; 01 §4.1 rule 2 and §5.2). Policy: tools/lint/ip_names_policy.cmake.
#
#   cmake -DSOURCE_DIR=<repository root> -DLINT_POLICY=<ip_names_policy.cmake> -P ip_names.cmake
#
# Fails on:
#  * a reference-content name (Cinder Reach: Kestrel, Harrow, Tallis, ...) outside content/;
#  * an in-universe name from another franchise (Star Wars, EVE, Destiny, Star Citizen) anywhere;
#  * a franchise title ("Star Wars", "EVE Online", ...) inside content/.
# Word and identifier-word matches (camelCase, snake_case, UPPER_CASE, paths) in text files;
# findings are reported as path:line: name.

cmake_minimum_required(VERSION 3.28)
if(NOT LINT_POLICY OR NOT EXISTS "${LINT_POLICY}")
  message(FATAL_ERROR "ip_names: LINT_POLICY file missing: '${LINT_POLICY}'")
endif()
include("${LINT_POLICY}")
if(NOT IS_DIRECTORY "${SOURCE_DIR}")
  message(FATAL_ERROR "ip_names: SOURCE_DIR is not a directory: '${SOURCE_DIR}'")
endif()
get_filename_component(SOURCE_DIR "${SOURCE_DIR}" ABSOLUTE)

set(findings "")
set(fileCount 0)

function(_ip_waived rel name out)
  set(hit OFF)
  foreach(w IN LISTS HELIOS_IP_WAIVERS)
    # "<path>|<name>|<reason>": split at the first two bars only (the reason is free text).
    # A path ending in '/' waives the whole directory (test data of a module being renamed).
    if(w MATCHES "^([^|]*)\\|([^|]*)\\|")
      set(wpath "${CMAKE_MATCH_1}")
      set(wname "${CMAKE_MATCH_2}")
      if(wname STREQUAL name)
        if(wpath STREQUAL rel)
          set(hit ON)
        elseif(wpath MATCHES "/$")
          string(LENGTH "${wpath}" wlen)
          string(SUBSTRING "${rel}" 0 ${wlen} relHead)
          if(relHead STREQUAL wpath)
            set(hit ON)
          endif()
        endif()
      endif()
    else()
      message(FATAL_ERROR "ip_names: malformed waiver (expected <path>|<name>|<reason>, no ';'): ${w}")
    endif()
  endforeach()
  set(${out} ${hit} PARENT_SCOPE)
endfunction()

# Finds occurrences of `needle` in `text` (the file, possibly lower-cased) that stand as a word or
# as a word of an identifier: the characters around it (in `original`) are not letters, or the
# boundary is a camelCase one (lower-case letter followed by upper-case). So "Kestrel",
# "kestrel_hull", "KESTREL_SPEED", "makeKestrel()" and "hull/kestrel" match, while "Harrowing" and
# "kiosk" do not. Digits and '_' separate words. Appends "rel:line: <kind> 'spelling'" findings to
# _ip_new. `name` (the policy spelling) is what waivers refer to.
function(_ip_scan text original rel name needle kind)
  string(FIND "${text}" "${needle}" pos)
  if(pos EQUAL -1)
    return()
  endif()
  _ip_waived("${rel}" "${name}" waived)
  if(waived)
    set_property(GLOBAL APPEND PROPERTY _IP_WAIVED "${rel}: ${name}")
    return()
  endif()
  set(out "")
  string(LENGTH "${needle}" nameLen)
  string(LENGTH "${text}" textLen)
  set(offset 0)
  while(TRUE)
    string(SUBSTRING "${text}" ${offset} -1 rest)
    string(FIND "${rest}" "${needle}" at)
    if(at EQUAL -1)
      break()
    endif()
    math(EXPR abs "${offset} + ${at}")
    math(EXPR after "${abs} + ${nameLen}")
    string(SUBSTRING "${original}" ${abs} 1 firstCh)
    math(EXPR lastIdx "${after} - 1")
    string(SUBSTRING "${original}" ${lastIdx} 1 lastCh)
    set(beforeOk ON)
    if(abs GREATER 0)
      math(EXPR b "${abs} - 1")
      string(SUBSTRING "${original}" ${b} 1 ch)
      if(ch MATCHES "[A-Za-z]" AND NOT (ch MATCHES "[a-z]" AND firstCh MATCHES "[A-Z]"))
        set(beforeOk OFF)
      endif()
    endif()
    set(afterOk ON)
    if(after LESS textLen)
      string(SUBSTRING "${original}" ${after} 1 ch)
      if(ch MATCHES "[A-Za-z]" AND NOT (ch MATCHES "[A-Z]" AND lastCh MATCHES "[a-z]"))
        set(afterOk OFF)
      endif()
    endif()
    if(beforeOk AND afterOk)
      string(SUBSTRING "${original}" 0 ${abs} head)
      string(REGEX MATCHALL "\n" nl "${head}")
      list(LENGTH nl line)
      math(EXPR line "${line} + 1")
      string(SUBSTRING "${original}" ${abs} ${nameLen} spelled)
      list(APPEND out "${rel}:${line}: ${kind} '${spelled}'")
    endif()
    set(offset ${after})
  endwhile()
  set(_ip_new "${out}" PARENT_SCOPE)
endfunction()

# Spellings of a reference-content name to look for: the name itself (case-sensitive), and for
# names of five or more letters also the lower- and upper-case identifier forms (matched on the
# lower-cased text): "kestrel", "KESTREL", "cinder_reach", "CinderReach", "cinderreach". Short names
# (Osk, Keth) stay case-sensitive: "OSK" is also the Windows on-screen keyboard.
function(_ip_reference_needles name out)
  set(cased "${name}")
  set(lower "")
  string(LENGTH "${name}" n)
  if(n GREATER_EQUAL 5)
    string(TOLOWER "${name}" l)
    list(APPEND lower "${l}")
    if(name MATCHES " ")
      string(REPLACE " " "" joined "${name}")
      list(APPEND cased "${joined}")
      string(REPLACE " " "_" snake "${l}")
      string(REPLACE " " "" flat "${l}")
      list(APPEND lower "${snake}" "${flat}")
    endif()
  endif()
  set(${out}_cased "${cased}" PARENT_SCOPE)
  set(${out}_lower "${lower}" PARENT_SCOPE)
endfunction()

set(files "")
foreach(dir IN LISTS HELIOS_IP_SCAN_DIRS)
  if(IS_DIRECTORY "${SOURCE_DIR}/${dir}")
    file(GLOB_RECURSE found LIST_DIRECTORIES false RELATIVE "${SOURCE_DIR}" "${SOURCE_DIR}/${dir}/*")
    list(APPEND files ${found})
  endif()
endforeach()
file(GLOB topFiles LIST_DIRECTORIES false RELATIVE "${SOURCE_DIR}" "${SOURCE_DIR}/*")
list(APPEND files ${topFiles})
list(SORT files)

foreach(rel IN LISTS files)
  set(skip OFF)
  foreach(p IN LISTS HELIOS_IP_EXCLUDE_PATTERNS)
    if(rel MATCHES "${p}")
      set(skip ON)
    endif()
  endforeach()
  get_filename_component(ext "${rel}" LAST_EXT)
  string(TOLOWER "${ext}" ext)
  get_filename_component(fname "${rel}" NAME)
  if(skip OR (NOT ext IN_LIST HELIOS_IP_TEXT_EXTENSIONS AND NOT fname STREQUAL "CMakeLists.txt"))
    continue()
  endif()
  math(EXPR fileCount "${fileCount} + 1")
  file(READ "${SOURCE_DIR}/${rel}" original)
  string(TOLOWER "${original}" lower)
  set(inContent OFF)
  foreach(c IN LISTS HELIOS_IP_CONTENT_DIRS)
    if(rel MATCHES "^${c}/")
      set(inContent ON)
    endif()
  endforeach()
  if(NOT inContent)
    foreach(name IN LISTS HELIOS_IP_REFERENCE_NAMES)
      _ip_reference_needles("${name}" needles)
      foreach(needle IN LISTS needles_cased)
        set(_ip_new "")
        _ip_scan("${original}" "${original}" "${rel}" "${name}" "${needle}" "reference-content name")
        list(APPEND findings ${_ip_new})
      endforeach()
      foreach(needle IN LISTS needles_lower)
        set(_ip_new "")
        _ip_scan("${lower}" "${original}" "${rel}" "${name}" "${needle}" "reference-content name")
        list(APPEND findings ${_ip_new})
      endforeach()
    endforeach()
  endif()
  foreach(name IN LISTS HELIOS_IP_FRANCHISE_NAMES_ANYCASE)
    set(_ip_new "")
    _ip_scan("${lower}" "${original}" "${rel}" "${name}" "${name}" "franchise name")
    list(APPEND findings ${_ip_new})
  endforeach()
  foreach(name IN LISTS HELIOS_IP_FRANCHISE_NAMES_CASED)
    set(_ip_new "")
    _ip_scan("${original}" "${original}" "${rel}" "${name}" "${name}" "franchise name")
    list(APPEND findings ${_ip_new})
  endforeach()
  if(inContent)
    foreach(name IN LISTS HELIOS_IP_FRANCHISE_TITLES)
      set(_ip_new "")
      _ip_scan("${lower}" "${original}" "${rel}" "${name}" "${name}" "franchise title")
      list(APPEND findings ${_ip_new})
    endforeach()
  endif()
endforeach()

get_property(waivedHits GLOBAL PROPERTY _IP_WAIVED)
if(waivedHits)
  list(REMOVE_DUPLICATES waivedHits)
  foreach(w IN LISTS waivedHits)
    message(STATUS "waived: ${w} (tools/lint/ip_names_policy.cmake)")
  endforeach()
endif()
if(fileCount EQUAL 0)
  list(APPEND findings "${SOURCE_DIR}: no files scanned (wrong SOURCE_DIR?)")
endif()
list(REMOVE_DUPLICATES findings)
if(findings)
  list(LENGTH findings n)
  string(REPLACE ";" "\n  " text "${findings}")
  message(FATAL_ERROR "IP-name lint failed (${n} finding(s), 01 §4.1 / §5.2, policy tools/lint/ip_names_policy.cmake):\n  ${text}\n")
endif()
message(STATUS "IP-name lint passed: ${fileCount} files")
