# Licence scanner (WP-0.2; CLAUDE.md allowlist, policy in tools/lint/license_policy.cmake).
#
#   cmake -DTHIRD_PARTY_DIR=<dir> -DMANIFEST=<MANIFEST.md> -DLINT_POLICY=<license_policy.cmake> -P licenses.cmake
#
# Checks, for every vendored dependency third_party/<dep>:
#  1. it has a licence file at its top level (LICENSE*, LICENCE*, COPYING*, UNLICENSE*);
#  2. every licence file in it (nested ones included) is recognized as an allowed family, or offers
#     an allowed licence as one option of a multi-licence choice, or is waived by the policy;
#  3. it has a row in third_party/MANIFEST.md, and every licence identifier in that row's licence
#     column is allowed (or waived).
# Exits non-zero with one line per finding.

cmake_minimum_required(VERSION 3.28)
if(NOT LINT_POLICY OR NOT EXISTS "${LINT_POLICY}")
  message(FATAL_ERROR "licenses: LINT_POLICY file missing: '${LINT_POLICY}'")
endif()
include("${LINT_POLICY}")
if(NOT IS_DIRECTORY "${THIRD_PARTY_DIR}")
  message(FATAL_ERROR "licenses: THIRD_PARTY_DIR is not a directory: '${THIRD_PARTY_DIR}'")
endif()
get_filename_component(THIRD_PARTY_DIR "${THIRD_PARTY_DIR}" ABSOLUTE)
if(MANIFEST)
  get_filename_component(MANIFEST "${MANIFEST}" ABSOLUTE)
endif()

set(findings "")
set(waived "")

# Waiver lookup: sets <out> to the reason or "".
function(_lic_waiver key out)
  set(reason "")
  foreach(w IN LISTS HELIOS_LICENSE_WAIVERS)
    string(FIND "${w}" "|" bar)
    string(SUBSTRING "${w}" 0 ${bar} wkey)
    if(wkey STREQUAL key)
      math(EXPR start "${bar} + 1")
      string(SUBSTRING "${w}" ${start} -1 reason)
    endif()
  endforeach()
  set(${out} "${reason}" PARENT_SCOPE)
endfunction()

# Normalized, lower-case text of a licence file (first 256 KiB).
function(_lic_normalize path out)
  file(READ "${path}" text LIMIT 262144)
  string(REPLACE ";" "," text "${text}")
  string(TOLOWER "${text}" text)
  # Comment markers at line starts (#, *, //, --, ;;) would split phrases across lines.
  string(REGEX REPLACE "\n[ \t]*(#|\\*|//|--|;)+" "\n" text "${text}")
  string(REGEX REPLACE "[ \t\r\n]+" " " text "${text}")
  set(${out} "${text}" PARENT_SCOPE)
endfunction()

function(_lic_classify path out)
  _lic_normalize("${path}" text)
  set(families "")
  foreach(fam IN LISTS HELIOS_LICENSE_FAMILIES)
    if(text MATCHES "${HELIOS_LICENSE_FP_${fam}}")
      list(APPEND families ${fam})
    endif()
  endforeach()
  set(forbidden OFF)
  if(text MATCHES "${HELIOS_LICENSE_FORBIDDEN}")
    set(forbidden ON)
  endif()
  set(choice OFF)
  if(text MATCHES "${HELIOS_LICENSE_CHOICE}" AND text MATCHES "${HELIOS_LICENSE_ALLOWED_NAMES}")
    set(choice ON)
  endif()
  set(font OFF)
  if(text MATCHES "${HELIOS_LICENSE_FP_OFL}")
    set(font ON)
  endif()
  set(${out}_families "${families}" PARENT_SCOPE)
  set(${out}_forbidden ${forbidden} PARENT_SCOPE)
  set(${out}_choice ${choice} PARENT_SCOPE)
  set(${out}_font ${font} PARENT_SCOPE)
endfunction()

file(GLOB deps LIST_DIRECTORIES true RELATIVE "${THIRD_PARTY_DIR}" "${THIRD_PARTY_DIR}/*")
list(SORT deps)
set(depCount 0)
set(fileCount 0)
set(manifestText "")
if(MANIFEST AND EXISTS "${MANIFEST}")
  file(READ "${MANIFEST}" manifestText)
  string(REPLACE ";" "," manifestText "${manifestText}")
  # Unbalanced square brackets (markdown links) would stop CMake's list splitting.
  string(REPLACE "[" "(" manifestText "${manifestText}")
  string(REPLACE "]" ")" manifestText "${manifestText}")
else()
  list(APPEND findings "MANIFEST.md not found at '${MANIFEST}'")
endif()
string(REGEX MATCHALL "[^\n]+" manifestLines "${manifestText}")

foreach(dep IN LISTS deps)
  if(NOT IS_DIRECTORY "${THIRD_PARTY_DIR}/${dep}")
    continue()
  endif()
  math(EXPR depCount "${depCount} + 1")

  # --- licence files ------------------------------------------------------------------------
  file(GLOB_RECURSE all LIST_DIRECTORIES false RELATIVE "${THIRD_PARTY_DIR}" "${THIRD_PARTY_DIR}/${dep}/*")
  set(licenseFiles "")
  set(topLevel OFF)
  foreach(f IN LISTS all)
    get_filename_component(name "${f}" NAME)
    string(TOLOWER "${name}" lname)
    if(lname MATCHES "^(licen[cs]e|copying|unlicense)([-._].*)?$")
      list(APPEND licenseFiles "${f}")
      get_filename_component(parent "${f}" DIRECTORY)
      if(parent STREQUAL dep)
        set(topLevel ON)
      endif()
    endif()
  endforeach()
  if(NOT topLevel)
    list(APPEND findings "third_party/${dep} has no licence file at its top level (LICENSE, LICENCE, COPYING or UNLICENSE)")
  endif()
  foreach(f IN LISTS licenseFiles)
    math(EXPR fileCount "${fileCount} + 1")
    _lic_classify("${THIRD_PARTY_DIR}/${f}" c)
    _lic_waiver("${f}" reason)
    if(reason)
      list(APPEND waived "third_party/${f}: ${reason}")
      continue()
    endif()
    if(c_font AND f MATCHES "${HELIOS_LICENSE_FONT_PATH_PATTERN}")
      continue()
    endif()
    if(c_forbidden)
      if(c_choice)
        continue() # one option of a multi-licence choice that includes an allowed licence
      endif()
      list(APPEND findings "third_party/${f}: forbidden licence (copyleft or non-permissive). Only MIT, BSD, zlib, Apache-2.0, Boost, ISC, PostgreSQL and public domain (CC0) are allowed (01 §5.2)")
    elseif(NOT c_families)
      if(c_font)
        list(APPEND findings "third_party/${f}: SIL OFL is allowed for fonts only (path must contain a fonts/ directory)")
      else()
        list(APPEND findings "third_party/${f}: unrecognized licence text. Classify it in tools/lint/license_policy.cmake (with sign-off) or remove the dependency")
      endif()
    endif()
  endforeach()

  # --- MANIFEST.md row ----------------------------------------------------------------------
  set(manifestName "${dep}")
  foreach(a IN LISTS HELIOS_LICENSE_MANIFEST_ALIASES)
    if(a MATCHES "^${dep}=(.+)$")
      set(manifestName "${CMAKE_MATCH_1}")
    endif()
  endforeach()
  string(TOLOWER "${manifestName}" lowerName)
  set(row "")
  foreach(line IN LISTS manifestLines)
    string(TOLOWER "${line}" lowerLine)
    if(lowerLine MATCHES "^\\|" AND NOT lowerLine MATCHES "^\\|[- |]+\\|$")
      # The row must be the dependency's own: its Name cell, the first word of that cell
      # ("Jolt Physics", "Recast/Detour", "ozz-animation") or the upstream repository name
      # ("ocornut/imgui"). A substring match anywhere in the row let another dependency's row
      # (whose "Used for" text mentions this name) stand in for a missing one.
      string(REGEX MATCH "^\\|([^|]*)\\|([^|]*)\\|" first "${lowerLine}")
      set(cell "${CMAKE_MATCH_1}")
      set(upstream "${CMAKE_MATCH_2}")
      string(REGEX REPLACE "[`*_]" "" cell "${cell}")
      string(STRIP "${cell}" cell)
      string(STRIP "${upstream}" upstream)
      string(REGEX REPLACE "^.*/" "" upstreamRepo "${upstream}")
      string(REGEX REPLACE "[ /()-].*$" "" firstWord "${cell}")
      if(row STREQUAL "" AND (cell STREQUAL lowerName OR firstWord STREQUAL lowerName OR upstreamRepo STREQUAL lowerName))
        set(row "${line}")
      endif()
    endif()
  endforeach()
  if(row STREQUAL "")
    list(APPEND findings "third_party/${dep} is not listed in ${MANIFEST}")
    continue()
  endif()
  # Columns: | Name | Upstream | Pinned ref | License | Used for |
  string(REGEX MATCHALL "[^|]+" cols "${row}")
  list(LENGTH cols ncols)
  if(ncols LESS 4)
    list(APPEND findings "MANIFEST.md row for ${dep} has no licence column: ${row}")
    continue()
  endif()
  list(GET cols 3 licenseCol)
  string(STRIP "${licenseCol}" licenseCol)
  # Licence identifiers mentioned in the column.
  string(REGEX MATCHALL "MIT-0|MIT|BSD-[0-9]|BSD|[Zz]lib|Apache-[0-9.]+|Boost|BSL-[0-9.]+|CC0|[Pp]ublic domain|Unlicense|ISC|PostgreSQL|L?A?GPL-?[0-9.]*|MPL-?[0-9.]*|EPL-?[0-9.]*|OFL-?[0-9.]*|SSPL|BUSL|CC-BY[-A-Z0-9.]*|Artistic[-0-9.]*|JSON" ids "${licenseCol}")
  if(NOT ids)
    list(APPEND findings "MANIFEST.md lists no recognizable licence for ${dep}: '${licenseCol}'")
  endif()
  foreach(id IN LISTS ids)
    if(id STREQUAL "Public domain")
      set(id "public domain")
    elseif(id STREQUAL "Zlib")
      set(id "zlib")
    endif()
    if(id IN_LIST HELIOS_LICENSE_MANIFEST_IDS)
      continue()
    endif()
    _lic_waiver("MANIFEST:${dep}:${id}" reason)
    if(reason)
      list(APPEND waived "MANIFEST.md ${dep} ${id}: ${reason}")
    else()
      list(APPEND findings "MANIFEST.md lists licence '${id}' for ${dep}, which is not on the allowlist")
    endif()
  endforeach()
endforeach()

if(depCount EQUAL 0)
  list(APPEND findings "no dependency directories found under '${THIRD_PARTY_DIR}' (wrong path?)")
endif()
foreach(w IN LISTS waived)
  message(STATUS "waived: ${w}")
endforeach()
if(findings)
  list(LENGTH findings n)
  string(REPLACE ";" "\n  " text "${findings}")
  message(FATAL_ERROR "Licence scan failed (${n} finding(s)):\n  ${text}\n")
endif()
message(STATUS "Licence scan passed: ${depCount} dependencies, ${fileCount} licence files")
