# Test-namespace lint (WP-0.1, AAA-PLT-1): a doctest test source keeps what it declares in an unnamed
# namespace.
#
#   cmake -DSOURCE_DIR=<repository root> [-DREQUIRE_TESTS=ON] -P test_namespaces.cmake
#
# Why: doctest names each test function DOCTEST_ANON_FUNC_<n>, with n counted per file, so the test
# files of one executable define functions of the same names. MSVC's cl names a lambda or local class
# in such a function after the function alone, and emits a static member variable template
# instantiated with it (helios::jobs::Job::kInlineOps<Fn>, for one) as an external COMDAT: two objects
# define a symbol of the same name, the linker keeps one, and a test silently runs another file's
# lambda (#15: "jobs: higher priorities run first" hung). A same-named helper at file scope in two
# files collides the same way. Names in an unnamed namespace carry a per-file hash on MSVC.
# engine/core/tests/test_tu_isolation_{a,b}.cpp are the regression probe.
#
# Scans the files under a tests/ or test/ directory of engine/, tools/ and apps/, except tools/prebuilt/
# and the lint fixtures in tools/lint/tests/: in a git checkout, those git tracks or would track
# (untracked and not ignored); otherwise every file. Findings are reported as path:line. It fails on:
#  * a doctest test macro (TEST_CASE*, TEST_SUITE*, SCENARIO*, SUBCASE, GIVEN, WHEN, THEN, AND_WHEN,
#    AND_THEN, or its DOCTEST_ form, followed by '(') outside an unnamed namespace, in any scanned
#    file, headers included. No waiver applies to test macros;
#  * in a test source (a *.cpp, *.cc or *.cxx file with a test macro), a declaration or definition at
#    namespace scope outside an unnamed namespace (it may sit in a named namespace nested in one),
#    including a macro call that ends one without a ';'. Preprocessor lines, comments,
#    using-directives, using-declarations, alias declarations and the `namespace x {` lines
#    themselves are exempt. Code that cannot live in an unnamed namespace (an explicit
#    specialization, the definition of a function a shared header declares, a name whose qualified
#    spelling a test checks) goes in a waiver region, whose reason must hold a letter or digit and
#    which is printed on every run:
#        // helios-lint: outside-anon-namespace begin (<reason>)
#        ...
#        // helios-lint: outside-anon-namespace end
#  * anything the lexer cannot follow: unbalanced braces, an #endif without its #if or an #if
#    without its #endif, an unterminated block comment, literal, raw string or waiver region, a
#    malformed helios-lint comment, a line the lexer tokenizes that is over 500 characters and has
#    more than 500 backslashes, asterisks and apostrophes, counted in its comments too (each can be
#    a level of recursion in CMake's regex engine, which overflows a 1 MB stack at about 2500; long
#    lines are fine otherwise), and with REQUIRE_TESTS=ON a scan that finds no test macro at all.
# A '#' first on its line, after blanks and comments, starts a preprocessing directive; on a line
# that a splice continues it does not. Only the comments and literals of a directive and of a line
# in an `#if 0` group are lexed, so a block comment that a directive opens, or an #endif inside a
# comment, is seen as the compiler sees it.
# Threat model: this is a best-effort textual check against accidental omissions (a new test file,
# a helper left outside the namespace). It is not a guarantee against deliberately adversarial
# source: the limits below are documented, and code review and the MSVC TU-isolation probe on the
# Windows CI jobs are the backstops.
# Limits:
#  * macros are not expanded. A test generated by a macro is seen only as the macro call, which the
#    declaration rule catches at namespace scope in a test source, but not in a waiver region, a
#    header, or a file whose only tests come from macros (it is not a test source then). A macro
#    that expands to a brace or to `namespace {` is not seen either (`#define CLOSE }` before a
#    global TEST_CASE passes);
#  * conditional compilation is not evaluated, except that `#if 0` groups are skipped: both branches
#    of any other #if are lexed (an opener in each is reported as unbalanced braces);
#  * a directive the lint does not recognize can pair #if and #endif differently from the compiler
#    and pass: a directive name split by a line splice (`#en\` then `dif`), a `%:` digraph, or a
#    form feed or vertical tab before the '#'. A directive inside a macro call's arguments is
#    undefined behaviour in C++; the lint treats it as a directive, as GCC does, and a compiler
#    that does not can differ;
#  * support sources without a test macro (mains, child processes, shared helpers) and headers are
#    held to the test-macro rule only: the declaration rule is for test sources.

cmake_minimum_required(VERSION 3.28)
if(NOT IS_DIRECTORY "${SOURCE_DIR}")
  message(FATAL_ERROR "test_namespaces: SOURCE_DIR is not a directory: '${SOURCE_DIR}'")
endif()
get_filename_component(SOURCE_DIR "${SOURCE_DIR}" ABSOLUTE)

# The text is split into a CMake list of lines, so the characters that are special in lists (';',
# '[', ']') and '\' (which escapes a ';') are replaced by control characters that do not occur in
# sources. Every line stays one list element, so line numbers are exact.
string(ASCII 28 _BS)
string(ASCII 29 _SC)
string(ASCII 30 _LB)
string(ASCII 31 _RB)
set(_maxDepth 500)

# The tokens of a line (or of what follows a comment or raw string that closed on it), tried
# leftmost-first. Every character is covered, so the tokens concatenate to the line. The repeated
# groups repeat once per escape or per run of '*', never once per character, because CMake's regex
# engine recurses once per repetition of a group. In order: // comment (the rest of the line),
# /* comment */ closed on the line, /* comment left open, raw string opener (with its encoding
# prefix), string literal, string continued by a line splice, character literal, pp-number (so
# 1'000 is not a character literal), identifier (whole, so a u8 or L prefix never glues to a
# literal), brace, blanks, other punctuation, any single character.
set(_lex "//.*")
string(APPEND _lex "|/\\*[^*]*\\*+([^*/][^*]*\\*+)*/")
string(APPEND _lex "|/\\*.*")
string(APPEND _lex "|(u8|u|U|L)?R\"[^()${_BS} \t\"]*\\(")
string(APPEND _lex "|\"[^\"${_BS}]*(${_BS}.[^\"${_BS}]*)*\"")
string(APPEND _lex "|\"[^\"${_BS}]*(${_BS}.[^\"${_BS}]*)*${_BS}$")
string(APPEND _lex "|'[^'${_BS}]*(${_BS}.[^'${_BS}]*)*'")
string(APPEND _lex "|\\.?[0-9][0-9A-Za-z_.]*('[0-9A-Za-z_][0-9A-Za-z_.]*)*")
string(APPEND _lex "|[A-Za-z_$][A-Za-z0-9_$]*")
string(APPEND _lex "|[{}]")
set(_lexNoBlanks "${_lex}|[^A-Za-z0-9_$ \t\r\"'/{}.]+|[^ \t\r]")
string(APPEND _lex "|[ \t\r]+")
string(APPEND _lex "|[^A-Za-z0-9_$ \t\r\"'/{}.]+")
string(APPEND _lex "|.")
set(_macroRe "^(DOCTEST_)?((TEST_CASE|TEST_SUITE|SCENARIO)(_[A-Z_]+)?")
string(APPEND _macroRe "|SUBCASE|GIVEN|WHEN|THEN|AND_WHEN|AND_THEN)$")
set(_cannot "(the lint cannot follow this file)")
set(_quickRe "TEST_CASE|TEST_SUITE|SCENARIO|SUBCASE|GIVEN|WHEN|THEN")
set(_waiverRe "^//[ \t]*helios-lint:[ \t]*outside-anon-namespace[ \t]+")
# Inside an unnamed namespace only these matter: braces, comments, raw strings, lone quotes, splices
# (in comments and literals) and test macros; a nested namespace is a block like any other there. A
# line or token with none of them is skipped.
set(_lineInterestRe "[{}/\"']|${_quickRe}|${_BS}$")
set(_tokInterestRe "^([{}]|/[*/]|(u8|u|U|L)?R\"|[\"']$|(DOCTEST_)?(${_quickRe}))|${_BS}$")

# Maps the placeholder characters back, for messages (a ';' is dropped: it would split the list).
function(_tn_unmask var)
  set(s "${${var}}")
  string(REPLACE "${_BS}" "\\" s "${s}")
  string(REPLACE "${_SC}" "" s "${s}")
  string(REPLACE "${_LB}" "[" s "${s}")
  string(REPLACE "${_RB}" "]" s "${s}")
  set(${var} "${s}" PARENT_SCOPE)
endfunction()

# Records a finding at `line` whose message is the concatenation of the other arguments, and the
# open top-level declaration as a finding. Macros: they run in the caller's scope.
macro(_tn_err line)
  string(CONCAT _tnMsg ${ARGN})
  list(APPEND errs "${rel}:${line}: ${_tnMsg}")
endmacro()
macro(_tn_decl)
  _tn_unmask(stmtFirst)
  string(CONCAT _tnMsg "${rel}:${stmtLine}: declaration outside an unnamed namespace "
                       "(starts with '${stmtFirst}')")
  list(APPEND decls "${_tnMsg}")
endmacro()

# Scans one file. `isSource`: the declaration rule applies if the file also has a test macro.
# Appends to the parent's `findings` and `waivers`, and adds to its `macroCount`.
function(_tn_scan_file path rel isSource)
  file(READ "${path}" text)
  if(NOT text MATCHES "${_quickRe}")
    return()
  endif()
  string(REPLACE "\r\n" "\n" text "${text}")
  string(REPLACE "\\" "${_BS}" text "${text}")
  string(REPLACE ";" "${_SC}" text "${text}")
  string(REPLACE "[" "${_LB}" text "${text}")
  string(REPLACE "]" "${_RB}" text "${text}")
  string(REPLACE "\n" ";" lines "${text}")

  set(errs "")          # test-macro and lexer findings, always reported
  set(decls "")         # declaration findings, reported for test sources
  set(waived "")
  set(fatal OFF)        # the lexer lost track: stop scanning the file
  set(macros 0)
  set(mode code)        # code, block, raw, splice (a spliced // comment), string (a spliced literal)
  set(modeLine 0)
  set(rawEnd "")
  set(lineStart ON)     # only blanks and comments so far on the logical line
  set(inDir OFF)        # the logical line is a preprocessing directive
  set(cont OFF)         # ... continued on the next physical line by a line splice
  set(ppLines "")       # the line of each open conditional (#if, #ifdef, #ifndef)
  set(skipping OFF)     # inside an `#if 0` group, with skipDepth conditionals nested in it
  set(skipDepth 0)
  set(stack "")         # one entry per open brace: A unnamed namespace, N named namespace, O other
  set(openLines "")
  set(top "")
  set(anonDepth 0)
  set(pendingNs "")     # after `namespace`: A until a name follows, then N
  set(pendingNsLine 0)
  set(pendingMacro "")  # a test macro's name; a following '(' confirms it
  set(pendingMacroLine 0)
  set(stmt OFF)         # a top-level declaration is open: since stmtLine, starting with stmtFirst
  set(stmtLine 0)
  set(stmtFirst "")
  set(stmtCount 0)
  set(stmtMacro OFF)    # ... it holds a test macro (reported as such)
  set(stmtAlias OFF)    # ... it is a namespace alias (a declaration after a block's '}', as in
                        # `struct S {...} s;`, is reported again: harmless, the block was already)
  set(waiver OFF)
  set(waiverLine 0)
  set(waiverDepth 0)
  set(waiverReason "")
  set(waiverTail OFF)   # a declaration (a macro call) was open at the last waiver end
  set(waiverEnd 0)
  set(lineNo 0)

  foreach(line IN LISTS lines)
    math(EXPR lineNo "${lineNo} + 1")
    set(seg "${line}")
    if(mode STREQUAL "raw")
      string(FIND "${seg}" "${rawEnd}" at)
      if(at EQUAL -1)
        continue()
      endif()
      string(LENGTH "${rawEnd}" n)
      math(EXPR at "${at} + ${n}")
      string(SUBSTRING "${seg}" ${at} -1 seg)
      set(mode code)
    elseif(mode STREQUAL "block")
      string(FIND "${seg}" "*/" at)
      if(at EQUAL -1)
        continue()
      endif()
      math(EXPR at "${at} + 2")
      string(SUBSTRING "${seg}" ${at} -1 seg)
      set(mode code)
    elseif(mode STREQUAL "splice")
      if(NOT seg MATCHES "${_BS}$")
        set(mode code)
      endif()
      continue()
    elseif(mode STREQUAL "string")
      # The match below repeats a group once per escape: the same bound as for the lexer (below).
      string(LENGTH "${seg}" n)
      if(n GREATER _maxDepth)
        string(REGEX REPLACE "[^${_BS}]" "" deep "${seg}")
        string(LENGTH "${deep}" n)
        if(n GREATER _maxDepth)
          _tn_err(${lineNo} "more than ${_maxDepth} escapes on one line "
                            "(the lint's regex recursion bound: split the line)")
          set(fatal ON)
          break()
        endif()
      endif()
      if(seg MATCHES "^[^\"${_BS}]*(${_BS}.[^\"${_BS}]*)*\"")
        string(LENGTH "${CMAKE_MATCH_0}" n)
        string(SUBSTRING "${seg}" ${n} -1 seg)
        set(mode code)
      elseif(NOT seg MATCHES "${_BS}$")
        list(APPEND errs "${rel}:${modeLine}: unterminated string literal ${_cannot}")
        set(fatal ON)
        break()
      else()
        continue()
      endif()
    elseif(cont)
      set(cont OFF)
    else()
      set(inDir OFF)
      set(lineStart ON)
    endif()

    # Preprocessing directives: a '#' that comes first on its logical line, after blanks and
    # comments. A directive and a line in an `#if 0` group are lexed only for their comments and
    # literals (a directive may open a block comment that hides the next line); the conditionals
    # are counted, so a file whose conditionals do not pair up as the lint sees them fails.
    if(lineStart)
      if(seg MATCHES "^[ \t]*[/#]")
        while(seg MATCHES "^[ \t]*/[*]")
          string(FIND "${seg}" "/*" at)
          math(EXPR at "${at} + 2")
          string(SUBSTRING "${seg}" ${at} -1 seg)
          string(FIND "${seg}" "*/" at)
          if(at EQUAL -1)
            set(mode block)
            set(modeLine ${lineNo})
            set(seg "")
            break()
          endif()
          math(EXPR at "${at} + 2")
          string(SUBSTRING "${seg}" ${at} -1 seg)
        endwhile()
        if(seg MATCHES "^[ \t]*#")
          set(inDir ON)
          string(REGEX MATCH "^[ \t]*#[ \t]*([A-Za-z_]*)" dirName "${seg}")
          set(dirName "${CMAKE_MATCH_1}")
          if(skipping)
            if(dirName MATCHES "^if")
              math(EXPR skipDepth "${skipDepth} + 1")
            elseif(dirName STREQUAL "endif" AND skipDepth GREATER 0)
              math(EXPR skipDepth "${skipDepth} - 1")
            elseif(dirName STREQUAL "endif")
              set(skipping OFF)
              list(POP_BACK ppLines)
            elseif(skipDepth EQUAL 0 AND dirName MATCHES "^(else|elif)")
              set(skipping OFF)
            endif()
          elseif(dirName MATCHES "^if")
            list(APPEND ppLines ${lineNo})
            if(seg MATCHES "^[ \t]*#[ \t]*if[ \t]+(0|false)[ \t]*(//.*)?$")
              set(skipping ON)
              set(skipDepth 0)
            endif()
          elseif(dirName STREQUAL "endif")
            if(ppLines STREQUAL "")
              list(APPEND errs "${rel}:${lineNo}: #endif without #if ${_cannot}")
            else()
              list(POP_BACK ppLines)
            endif()
          endif()
        endif()
      endif()
      if(seg MATCHES "[^ \t]")
        set(lineStart OFF)
      endif()
    endif()
    if(seg STREQUAL "")
      continue()
    endif()
    if(inDir OR skipping)
      if(NOT seg MATCHES "[/\"']")
        if(line MATCHES "${_BS}$")
          set(cont ON)  # a line splice continues the directive or skipped line
        endif()
        continue()
      endif()
    elseif(anonDepth GREATER 0)
      if(pendingNs STREQUAL "" AND pendingMacro STREQUAL "")
        if(NOT seg MATCHES "${_lineInterestRe}")
          continue()
        endif()
      endif()
    endif()
    # The lexer's groups repeat once per escape, '*' or digit separator, and each repetition is a
    # level of recursion in CMake's regex engine: bound them (long lines are fine otherwise).
    string(LENGTH "${seg}" n)
    if(n GREATER _maxDepth)
      string(REGEX REPLACE "[^${_BS}*']" "" deep "${seg}")
      string(LENGTH "${deep}" n)
      if(n GREATER _maxDepth)
        _tn_err(${lineNo} "more than ${_maxDepth} escapes, '*' or digit separators on "
                          "one line (the lint's regex recursion bound: split the line)")
        set(fatal ON)
        break()
      endif()
    endif()

    # The segment's tokens. A raw string that closes on this line restarts the loop after it.
    set(again ON)
    while(again)
      set(again OFF)
      set(pos 0)
      set(trackPos OFF)
      if(seg MATCHES "R\"")
        set(trackPos ON)
        string(REGEX MATCHALL "${_lex}" toks "${seg}")
      else()
        string(REGEX MATCHALL "${_lexNoBlanks}" toks "${seg}")
      endif()
      foreach(tok IN LISTS toks)
        if(trackPos)
          string(LENGTH "${tok}" n)
          math(EXPR pos "${pos} + ${n}")
        endif()
        if(anonDepth GREATER 0)
          if(pendingNs STREQUAL "" AND pendingMacro STREQUAL "")
            if(NOT tok MATCHES "${_tokInterestRe}")
              continue()
            endif()
          endif()
        endif()
        if(tok MATCHES "^[ \t\r]")
          continue()
        endif()
        if(tok MATCHES "^/[*/]")
          if(tok MATCHES "^/[*]")
            if(NOT tok MATCHES "^/[*].*[*]/$" OR tok STREQUAL "/*/")
              set(mode block)
              set(modeLine ${lineNo})
            endif()
          elseif(tok MATCHES "^//[ \t]*helios-lint:" AND NOT inDir AND NOT skipping)
            set(reason "")
            if(tok MATCHES "${_waiverRe}begin[ \t]*\\((.*[^ \t(])\\)[ \t]*$")
              set(reason "${CMAKE_MATCH_1}")
            endif()
            if(reason MATCHES "[A-Za-z0-9]")
              if(waiver)
                _tn_err(${lineNo} "waiver regions do not nest "
                                  "(one is open since line ${waiverLine})")
              else()
                # A declaration still open at the begin had no ';' (a macro call): it is not waived.
                if(stmt AND NOT stmtMacro AND NOT stmtAlias AND NOT stmtFirst STREQUAL "using")
                  _tn_decl()
                  set(stmt OFF)
                endif()
                set(waiver ON)
                set(waiverLine ${lineNo})
                list(LENGTH stack waiverDepth)
                set(waiverReason "${reason}")
              endif()
            elseif(tok MATCHES "${_waiverRe}end[ \t]*$")
              list(LENGTH stack depth)
              if(NOT waiver)
                list(APPEND errs "${rel}:${lineNo}: waiver end without a begin")
              elseif(NOT depth EQUAL waiverDepth)
                _tn_err(${lineNo} "waiver end at another brace depth than its begin "
                                  "(line ${waiverLine})")
              else()
                _tn_unmask(waiverReason)
                list(APPEND waived "${rel}:${waiverLine}-${lineNo}: ${waiverReason}")
                set(waiver OFF)
                # A declaration still open here (a macro call) is part of the region; a block right
                # after the end is its body, which the region does not cover.
                set(waiverTail ${stmt})
                set(waiverEnd ${lineNo})
                set(stmt OFF)
              endif()
            else()
              _tn_err(${lineNo} "malformed helios-lint comment (expected '// helios-lint: "
                                "outside-anon-namespace begin (<reason>)', the reason with a letter "
                                "or digit, or '... end')")
            endif()
          elseif(tok MATCHES "${_BS}$")
            set(mode splice)
          endif()
          continue()
        endif()

        if(trackPos AND tok MATCHES "^(u8|u|U|L)?R\"")
          # A raw string (in code, a directive or a skipped group): its terminator is on this line or
          # a later one.
          string(REGEX REPLACE "^(u8|u|U|L)?R\"(.*)\\($" "\\2" delim "${tok}")
          string(LENGTH "${delim}" n)
          if(n GREATER 16)
            _tn_err(${lineNo} "raw string delimiter longer than 16 characters ${_cannot}")
            set(fatal ON)
            break()
          endif()
          set(rawEnd ")${delim}\"")
          string(SUBSTRING "${seg}" ${pos} -1 rest)
          string(FIND "${rest}" "${rawEnd}" at)
          if(at EQUAL -1)
            set(mode raw)
            set(modeLine ${lineNo})
          else()
            string(LENGTH "${rawEnd}" n)
            math(EXPR at "${at} + ${n}")
            string(SUBSTRING "${rest}" ${at} -1 seg)
            set(again ON)  # the tokens after this one lexed the raw string's body: re-lex the rest
          endif()
        endif()

        if(inDir OR skipping)
          # Only comments and literals matter in a directive or a skipped group, and a lone quote
          # is a lone character there (as the preprocessor treats it).
          if(tok MATCHES "^\"" AND tok MATCHES "${_BS}$")
            set(mode string)
            set(modeLine ${lineNo})
          endif()
          if(NOT mode STREQUAL "code" OR again)
            break()
          endif()
          continue()
        endif()

        # Code. Braces open and close scopes.
        if(tok STREQUAL "{")
          if(NOT pendingNs STREQUAL "")
            list(APPEND stack ${pendingNs})
            list(APPEND openLines ${pendingNsLine})
            set(top ${pendingNs})
            if(pendingNs STREQUAL "A")
              math(EXPR anonDepth "${anonDepth} + 1")
            endif()
          else()
            if(stmt AND NOT stmtMacro AND NOT waiver AND anonDepth EQUAL 0 AND NOT top STREQUAL "O")
              _tn_decl()
            elseif(waiverTail)
              string(CONCAT _tnMsg "${rel}:${lineNo}: declaration outside an unnamed namespace (the "
                                   "body of a declaration waived up to line ${waiverEnd})")
              list(APPEND decls "${_tnMsg}")
            endif()
            list(APPEND stack O)
            list(APPEND openLines ${lineNo})
            set(top O)
          endif()
          set(pendingNs "")
          set(pendingMacro "")
          set(stmt OFF)
          set(waiverTail OFF)
          continue()
        endif()
        set(waiverTail OFF)
        if(tok STREQUAL "}")
          list(LENGTH stack depth)
          if(depth EQUAL 0)
            list(APPEND errs "${rel}:${lineNo}: unbalanced braces: '}' closes nothing ${_cannot}")
            set(fatal ON)
            break()
          endif()
          if(waiver AND depth EQUAL waiverDepth)
            _tn_err(${lineNo} "this '}' closes the scope of the waiver opened on line "
                              "${waiverLine}")
          endif()
          # A declaration still open at a namespace's '}' had no ';': a macro call.
          if(stmt AND NOT stmtMacro AND NOT stmtAlias AND NOT waiver AND NOT stmtFirst STREQUAL "using")
            _tn_decl()
          endif()
          list(POP_BACK stack closed)
          list(POP_BACK openLines)
          if(closed STREQUAL "A")
            math(EXPR anonDepth "${anonDepth} - 1")
          endif()
          set(top "")
          if(depth GREATER 1)
            list(GET stack -1 top)
          endif()
          set(pendingNs "")
          set(pendingMacro "")
          set(stmt OFF)
          continue()
        endif()

        # A test macro is confirmed by the '(' after its name.
        if(NOT pendingMacro STREQUAL "")
          if(tok MATCHES "^\\(")
            math(EXPR macros "${macros} + 1")
            set(stmtMacro ON)
            if(anonDepth EQUAL 0)
              list(APPEND errs "${rel}:${pendingMacroLine}: ${pendingMacro} outside an unnamed namespace")
            endif()
          endif()
          set(pendingMacro "")
        endif()

        if(tok MATCHES "^[A-Za-z_$]")
          if(tok STREQUAL "namespace")
            # An open top-level declaration that `namespace` interrupts had no ';': a macro call.
            if(stmt AND NOT stmtMacro AND NOT waiver AND anonDepth EQUAL 0 AND NOT top STREQUAL "O"
               AND NOT stmtFirst STREQUAL "using" AND NOT (stmtCount EQUAL 1 AND stmtFirst STREQUAL "inline"))
              _tn_decl()
              set(stmt OFF)
            endif()
            set(pendingNs A)
            set(pendingNsLine ${lineNo})
          elseif(pendingNs STREQUAL "A")
            set(pendingNs N)
          elseif(tok MATCHES "${_macroRe}")
            set(pendingMacro "${tok}")
            set(pendingMacroLine ${lineNo})
          endif()
          if(trackPos AND tok MATCHES "^(u8|u|U|L)?R\"")
            set(pendingNs "")
          endif()
        elseif(NOT pendingNs STREQUAL "" AND tok STREQUAL "::")
          # a nested namespace name: namespace a::b {
        else()
          if(pendingNs STREQUAL "N" AND tok MATCHES "^=")
            set(stmtAlias ON)
          endif()
          set(pendingNs "")
          if(tok STREQUAL "\"" OR tok STREQUAL "'")
            list(APPEND errs "${rel}:${lineNo}: unterminated literal ${_cannot}")
            set(fatal ON)
            break()
          elseif(tok MATCHES "^\"" AND tok MATCHES "${_BS}$")
            set(mode string)
            set(modeLine ${lineNo})
          endif()
        endif()
        # Top-level declarations: a code token outside every unnamed namespace and outside any other
        # block opens a declaration, or extends the open one; a ';' ends it.
        if(anonDepth EQUAL 0 AND NOT top STREQUAL "O")
          if(NOT stmt)
            set(stmt ON)
            set(stmtLine ${lineNo})
            string(SUBSTRING "${tok}" 0 40 stmtFirst)
            set(stmtCount 0)
            set(stmtMacro OFF)
            set(stmtAlias OFF)
          endif()
          math(EXPR stmtCount "${stmtCount} + 1")
          if(tok MATCHES "${_SC}" AND NOT tok MATCHES "^[\"'A-Za-z]")  # a ';' outside literals
            if(stmt AND NOT stmtMacro AND NOT stmtAlias AND NOT waiver AND NOT stmtFirst STREQUAL "using"
               AND NOT stmtFirst MATCHES "^${_SC}")
              _tn_decl()
            endif()
            set(stmt OFF)
            set(stmtAlias OFF)
          endif()
        endif()
        if(NOT mode STREQUAL "code" OR again)
          break()
        endif()
      endforeach()
    endwhile()
    if(fatal)
      break()
    endif()
    if(mode STREQUAL "code" AND line MATCHES "${_BS}$")
      set(cont ON)
    endif()
  endforeach()

  if(NOT fatal)
    if(mode STREQUAL "block")
      list(APPEND errs "${rel}:${modeLine}: unterminated block comment ${_cannot}")
    elseif(mode STREQUAL "raw")
      list(APPEND errs "${rel}:${modeLine}: unterminated raw string literal ${_cannot}")
    endif()
    if(waiver)
      list(APPEND errs "${rel}:${waiverLine}: waiver region not closed")
    endif()
    if(NOT ppLines STREQUAL "")
      list(GET ppLines -1 ppLine)
      list(APPEND errs "${rel}:${ppLine}: #if without #endif ${_cannot}")
    endif()
    list(LENGTH stack depth)
    if(depth GREATER 0 AND mode STREQUAL "code")
      list(GET openLines -1 openLine)
      _tn_err(${openLine} "unbalanced braces: this '{' is still open at the end of the file "
                          "${_cannot}")
    endif()
    if(stmt AND NOT stmtMacro AND NOT stmtAlias AND NOT waiver AND NOT stmtFirst STREQUAL "using")
      _tn_decl()
    endif()
  endif()
  if(isSource AND macros GREATER 0)
    list(APPEND errs ${decls})
  endif()
  set(findings "${findings};${errs}" PARENT_SCOPE)
  set(waivers "${waivers};${waived}" PARENT_SCOPE)
  math(EXPR total "${macroCount} + ${macros}")
  set(macroCount ${total} PARENT_SCOPE)
endfunction()

# The files: when SOURCE_DIR is a git checkout, those git tracks and those it would track (untracked
# and not ignored: a new test file counts before it is added, an ignored download does not).
set(files "")
set(how "git ls-files")
find_program(_tnGit git)
if(_tnGit)
  execute_process(COMMAND "${_tnGit}" -c core.quotePath=false ls-files --cached --others --exclude-standard
                          -- engine tools apps
                  WORKING_DIRECTORY "${SOURCE_DIR}" RESULT_VARIABLE rc OUTPUT_VARIABLE out ERROR_QUIET)
  if(rc EQUAL 0)
    string(REPLACE "\n" ";" files "${out}")
  endif()
endif()
list(FILTER files EXCLUDE REGEX "^$")
list(REMOVE_DUPLICATES files)
if(files STREQUAL "")
  set(how "every file: not a git checkout, or git lists none of them")
  foreach(dir engine tools apps)
    file(GLOB_RECURSE found RELATIVE "${SOURCE_DIR}" "${SOURCE_DIR}/${dir}/*")
    list(APPEND files ${found})
  endforeach()
endif()
list(FILTER files INCLUDE REGEX "(^|/)tests?/.*\\.(cpp|cc|cxx|h|hh|hpp|inl)$")
list(FILTER files EXCLUDE REGEX "^tools/lint/tests/|^tools/prebuilt/")
list(SORT files)

set(findings "")
set(waivers "")
set(macroCount 0)
set(fileCount 0)
foreach(rel IN LISTS files)
  if(NOT EXISTS "${SOURCE_DIR}/${rel}")
    continue()  # tracked, but deleted in the working tree
  endif()
  math(EXPR fileCount "${fileCount} + 1")
  set(isSource OFF)
  if(rel MATCHES "\\.(cpp|cc|cxx)$")
    set(isSource ON)
  endif()
  _tn_scan_file("${SOURCE_DIR}/${rel}" "${rel}" ${isSource})
endforeach()
list(FILTER waivers EXCLUDE REGEX "^$")
foreach(w IN LISTS waivers)
  message(STATUS "test namespaces: waiver ${w}")
endforeach()
list(FILTER findings EXCLUDE REGEX "^$")
list(LENGTH findings n)
if(n GREATER 0)
  foreach(f IN LISTS findings)
    message("${f}")
  endforeach()
  message(FATAL_ERROR "test-namespace lint failed (${n} finding(s)). Keep a test file's tests and helpers in "
                      "one unnamed namespace, as tools/lint/README.md explains.")
endif()
if(REQUIRE_TESTS AND macroCount EQUAL 0)
  message(FATAL_ERROR "test_namespaces: no doctest test macro under ${SOURCE_DIR} (${fileCount} test files, "
                      "${how}); is SOURCE_DIR the repository root?")
endif()
message(STATUS "test namespaces: ${macroCount} test macros in ${fileCount} test files (${how}); "
               "declarations in unnamed namespaces or waived")
