# Test-namespace lint (WP-0.1, AAA-PLT-1): doctest tests live in an unnamed namespace.
#
#   cmake -DSOURCE_DIR=<repository root> [-DREQUIRE_TESTS=ON] -P test_namespaces.cmake
#
# REQUIRE_TESTS=ON (the repository run) also fails when no test macro is found at all, so a scan of
# the wrong directory cannot pass by checking nothing.
#
# doctest names each test function DOCTEST_ANON_FUNC_<n>, with n counted per file, so the test files of
# one executable define functions of the same names. MSVC's cl mangles a lambda or local class in such
# a function with nothing unique to the file. A template instantiated with it is then a COMDAT of the
# same name in two objects, the linker keeps one copy, and a test silently runs another file's lambda
# (#15: "jobs: higher priorities run first" hung). Names in an unnamed namespace are unique per file.
#
# Scans the *.cpp, *.cc and *.cxx files under a tests/ directory of engine/, tools/ and apps/ (not the
# lint fixtures in tools/lint/tests/) and fails on:
#  * a doctest test macro (TEST_CASE*, TEST_SUITE*, SUBCASE, SCENARIO*, or its DOCTEST_ form) that is
#    not inside an unnamed namespace, reported as path:line;
#  * a file whose braces do not balance once comments, string and character literals (raw strings
#    included) and preprocessor lines are set aside: the lint cannot vouch for a file it cannot follow.
# Macros are not expanded, so a test macro used inside another macro's definition is not checked.

cmake_minimum_required(VERSION 3.28)
if(NOT IS_DIRECTORY "${SOURCE_DIR}")
  message(FATAL_ERROR "test_namespaces: SOURCE_DIR is not a directory: '${SOURCE_DIR}'")
endif()
get_filename_component(SOURCE_DIR "${SOURCE_DIR}" ABSOLUTE)

# Lexical elements, tried leftmost-first, so a comment, literal or directive swallows any brace,
# `namespace` or macro name inside it. In order: // comment (with line splices), /* comment */,
# string literal, a number with digit separators (so 1'000 is not a character literal), character
# literal, preprocessor line (with splices), unnamed namespace opener, named namespace opener, an
# identifier containing a keyword (compared exactly below), a brace, a newline.
set(_ws "[ \t\n]")
set(_splice "([^\\\\\n]|\\\\[^\n]|\\\\\n)*")
set(_lexRe "//${_splice}")
string(APPEND _lexRe "|/\\*([^*]|\\*+[^*/])*\\*+/")
string(APPEND _lexRe "|\"([^\"\\\\\n]|\\\\[^\n]|\\\\\n)*\"")
string(APPEND _lexRe "|[0-9][0-9A-Za-z_.]*'[0-9A-Za-z_.']*")
string(APPEND _lexRe "|'([^'\\\\\n]|\\\\[^\n])*'")
string(APPEND _lexRe "|#${_splice}")
string(APPEND _lexRe "|namespace${_ws}*{")
string(APPEND _lexRe "|namespace${_ws}+[A-Za-z_][A-Za-z0-9_:]*${_ws}*{")
string(APPEND _lexRe "|[A-Za-z0-9_]*(TEST_CASE|TEST_SUITE|SUBCASE|SCENARIO|namespace)[A-Za-z0-9_]*")
string(APPEND _lexRe "|[{}]|\n")
set(_testMacroRe "^(DOCTEST_)?((TEST_CASE|TEST_SUITE|SCENARIO)(_[A-Z_]+)?|SUBCASE)$")

# Replaces every raw string literal (R"d(...)d", with an optional u8/u/U/L prefix) in `var` by ""
# plus the newlines it spanned, so line numbers stay right. A candidate R" must follow a character
# that cannot end an identifier (or the prefix must), and be followed by a delimiter of at most 16
# characters and '('; an unterminated one is an error.
function(_tn_strip_raw_strings var rel)
  set(text "${${var}}")
  set(out "")
  while(TRUE)
    string(FIND "${text}" "R\"" at)
    if(at EQUAL -1)
      break()
    endif()
    math(EXPR afterQuote "${at} + 2")
    set(start ${at})
    set(isRaw OFF)
    # The character(s) before R: nothing, a non-identifier character, or a u8/u/U/L prefix that
    # itself follows one.
    set(prefixOk OFF)
    if(at EQUAL 0)
      set(prefixOk ON)
    else()
      math(EXPR b "${at} - 1")
      string(SUBSTRING "${text}" ${b} 1 ch)
      if(NOT ch MATCHES "[A-Za-z0-9_]")
        set(prefixOk ON)
      elseif(ch MATCHES "[uUL8]")
        set(p ${b})
        if(ch STREQUAL "8" AND b GREATER 0)
          math(EXPR p "${b} - 1")
          string(SUBSTRING "${text}" ${p} 1 ch8)
          if(NOT ch8 STREQUAL "u")
            set(p -1)
          endif()
        elseif(ch STREQUAL "8")
          set(p -1)
        endif()
        if(p GREATER_EQUAL 0)
          if(p EQUAL 0)
            set(prefixOk ON)
          else()
            math(EXPR pb "${p} - 1")
            string(SUBSTRING "${text}" ${pb} 1 chb)
            if(NOT chb MATCHES "[A-Za-z0-9_]")
              set(prefixOk ON)
            endif()
          endif()
          set(start ${p})
        endif()
      endif()
    endif()
    string(SUBSTRING "${text}" ${afterQuote} 17 head)
    if(prefixOk AND head MATCHES "^([^()\\\\ \t\n\"]*)\\(")
      set(delim "${CMAKE_MATCH_1}")
      string(LENGTH "${delim}" dlen)
      if(dlen LESS_EQUAL 16)
        set(isRaw ON)
      endif()
    endif()
    if(NOT isRaw)
      # Not a raw string: keep everything up to and including the R, go on after it.
      math(EXPR keep "${at} + 1")
      string(SUBSTRING "${text}" 0 ${keep} part)
      string(APPEND out "${part}")
      string(SUBSTRING "${text}" ${keep} -1 text)
      continue()
    endif()
    math(EXPR bodyStart "${afterQuote} + ${dlen} + 1")
    string(SUBSTRING "${text}" ${bodyStart} -1 body)
    string(FIND "${body}" ")${delim}\"" close)
    if(close EQUAL -1)
      message(FATAL_ERROR "test_namespaces: ${rel}: unterminated raw string literal R\"${delim}(")
    endif()
    string(SUBSTRING "${body}" 0 ${close} inside)
    string(REGEX REPLACE "[^\n]" "" newlines "${inside}")
    string(SUBSTRING "${text}" 0 ${start} part)
    string(APPEND out "${part}\"\"${newlines}")
    string(LENGTH "${delim}" dlen)
    math(EXPR resume "${close} + ${dlen} + 2")
    string(SUBSTRING "${body}" ${resume} -1 text)
  endwhile()
  string(APPEND out "${text}")
  set(${var} "${out}" PARENT_SCOPE)
endfunction()

# Checks one file; appends findings to the parent's `findings` and counts test macros in `macroCount`.
function(_tn_check_file path rel)
  file(READ "${path}" text)
  string(REPLACE "\r\n" "\n" text "${text}")
  if(NOT text MATCHES "(TEST_CASE|TEST_SUITE|SUBCASE|SCENARIO)")
    return()
  endif()
  # CMake list separators and brackets would split or glue tokens; none of them matters here.
  string(REPLACE ";" " " text "${text}")
  string(REPLACE "[" " " text "${text}")
  string(REPLACE "]" " " text "${text}")
  _tn_strip_raw_strings(text "${rel}")
  string(REGEX MATCHALL "${_lexRe}" tokens "${text}")

  set(out "")
  set(line 1)
  set(stack "")      # one entry per open brace: A (unnamed namespace), N (named namespace), O (other)
  set(openLines "")  # the line of each open brace
  set(anonDepth 0)
  set(macros 0)
  foreach(tok IN LISTS tokens)
    if(tok STREQUAL "\n")
      math(EXPR line "${line} + 1")
      continue()
    endif()
    set(tokLine ${line})
    string(FIND "${tok}" "\n" nl)
    if(NOT nl EQUAL -1)
      string(REGEX REPLACE "[^\n]" "" nls "${tok}")
      string(LENGTH "${nls}" n)
      math(EXPR line "${line} + ${n}")
    endif()
    if(tok STREQUAL "{")
      list(APPEND stack O)
      list(APPEND openLines ${tokLine})
    elseif(tok STREQUAL "}")
      list(LENGTH stack depth)
      if(depth EQUAL 0)
        list(APPEND out "${rel}:${tokLine}: unbalanced braces: '}' closes nothing (the lint cannot follow this file)")
        break()
      endif()
      list(POP_BACK stack top)
      list(POP_BACK openLines)
      if(top STREQUAL "A")
        math(EXPR anonDepth "${anonDepth} - 1")
      endif()
    elseif(tok MATCHES "^namespace${_ws}*{$")
      list(APPEND stack A)
      list(APPEND openLines ${line})
      math(EXPR anonDepth "${anonDepth} + 1")
    elseif(tok MATCHES "^namespace${_ws}+[A-Za-z_]")
      list(APPEND stack N)
      list(APPEND openLines ${line})
    elseif(tok MATCHES "${_testMacroRe}")
      math(EXPR macros "${macros} + 1")
      if(anonDepth EQUAL 0)
        list(APPEND out "${rel}:${tokLine}: ${tok} outside an unnamed namespace")
      endif()
    endif()
  endforeach()
  list(LENGTH stack depth)
  if(depth GREATER 0 AND NOT out MATCHES "unbalanced braces")
    list(GET openLines -1 openLine)
    list(APPEND out "${rel}:${openLine}: unbalanced braces: this '{' is still open at the end of the file (the lint cannot follow this file)")
  endif()
  set(findings "${findings};${out}" PARENT_SCOPE)
  math(EXPR total "${macroCount} + ${macros}")
  set(macroCount ${total} PARENT_SCOPE)
endfunction()

set(files "")
foreach(top engine tools apps)
  foreach(ext cpp cc cxx)
    file(GLOB_RECURSE found RELATIVE "${SOURCE_DIR}" "${SOURCE_DIR}/${top}/*.${ext}")
    list(APPEND files ${found})
  endforeach()
endforeach()
list(FILTER files INCLUDE REGEX "(^|/)tests/")
list(FILTER files EXCLUDE REGEX "^tools/lint/tests/")
list(SORT files)

set(findings "")
set(macroCount 0)
list(LENGTH files fileCount)
foreach(rel IN LISTS files)
  _tn_check_file("${SOURCE_DIR}/${rel}" "${rel}")
endforeach()
list(FILTER findings EXCLUDE REGEX "^$")
list(LENGTH findings n)
if(n GREATER 0)
  foreach(f IN LISTS findings)
    message("${f}")
  endforeach()
  message(FATAL_ERROR "test-namespace lint failed (${n} finding(s)). Put each test file's tests (and their "
                      "helpers) in one unnamed namespace, as tools/lint/README.md explains.")
endif()
if(REQUIRE_TESTS AND macroCount EQUAL 0)
  message(FATAL_ERROR "test_namespaces: no doctest test macro under ${SOURCE_DIR} (${fileCount} test sources); "
                      "is SOURCE_DIR the repository root?")
endif()
message(STATUS "test namespaces: ${macroCount} test macros in ${fileCount} test sources, all in unnamed namespaces")
