# Vendored-patch check (WP-0.10r; CLAUDE.md: vendored code is never edited in place, changes are
# patches applied by tools/vendor/fetch_third_party.sh and documented in third_party/MANIFEST.md).
#
#   cmake -DTHIRD_PARTY_DIR=<dir> -DMANIFEST=<MANIFEST.md> -P vendor_patches.cmake
#
# For every third_party/<dep>/patches/*.patch (a git diff relative to third_party/<dep>):
#  1. the file is named NNNN-<slug>.patch (applied in that order) and is named in MANIFEST.md;
#  2. every hunk is applied to the committed tree: its post-image (context and added lines) appears
#     in the target file, hunks in order; a file the patch deletes is absent.
# No network, git or build is needed, and CRLF checkouts pass (line endings are normalized). A tree
# re-vendored without its patches, or edited so that a patch no longer describes it, fails.
# Exits non-zero with one line per finding.

cmake_minimum_required(VERSION 3.28)
if(NOT IS_DIRECTORY "${THIRD_PARTY_DIR}")
  message(FATAL_ERROR "vendor-patches: THIRD_PARTY_DIR is not a directory: '${THIRD_PARTY_DIR}'")
endif()
get_filename_component(THIRD_PARTY_DIR "${THIRD_PARTY_DIR}" ABSOLUTE)
set(manifestText "")
if(MANIFEST)
  if(NOT EXISTS "${MANIFEST}")
    message(FATAL_ERROR "vendor-patches: MANIFEST not found: '${MANIFEST}'")
  endif()
  file(READ "${MANIFEST}" manifestText)
endif()

# CMake lists split on ';' (not after '\', not inside [...]), so text is escaped before it is split
# into lines: ';', '\', '[' and ']' become control characters that sources do not contain.
string(ASCII 26 _vpSemi)
string(ASCII 28 _vpBackslash)
string(ASCII 29 _vpOpen)
string(ASCII 30 _vpClose)

function(_vp_escape text out)
  string(REPLACE "\r\n" "\n" text "${text}")
  string(REPLACE ";" "${_vpSemi}" text "${text}")
  string(REPLACE "\\" "${_vpBackslash}" text "${text}")
  string(REPLACE "[" "${_vpOpen}" text "${text}")
  string(REPLACE "]" "${_vpClose}" text "${text}")
  set(${out} "${text}" PARENT_SCOPE)
endfunction()

function(_vp_unescape text out)
  string(REPLACE "${_vpSemi}" ";" text "${text}")
  string(REPLACE "${_vpBackslash}" "\\" text "${text}")
  string(REPLACE "${_vpOpen}" "[" text "${text}")
  string(REPLACE "${_vpClose}" "]" text "${text}")
  set(${out} "${text}" PARENT_SCOPE)
endfunction()

set(findings "")
set(patchCount 0)
set(hunkCount 0)

file(GLOB deps LIST_DIRECTORIES true RELATIVE "${THIRD_PARTY_DIR}" "${THIRD_PARTY_DIR}/*")
list(SORT deps)
foreach(dep IN LISTS deps)
  if(NOT IS_DIRECTORY "${THIRD_PARTY_DIR}/${dep}/patches")
    continue()
  endif()
  set(depRoot "${THIRD_PARTY_DIR}/${dep}")
  file(GLOB patches RELATIVE "${depRoot}/patches" "${depRoot}/patches/*")
  list(SORT patches)
  foreach(patch IN LISTS patches)
    set(rel "third_party/${dep}/patches/${patch}")
    if(NOT patch MATCHES "^[0-9][0-9][0-9][0-9]-[a-z0-9][a-z0-9-]*\\.patch$")
      list(APPEND findings "${rel}: not named NNNN-<slug>.patch (lower-case slug), so its order is undefined")
      continue()
    endif()
    math(EXPR patchCount "${patchCount} + 1")
    if(MANIFEST)
      string(FIND "${manifestText}" "${patch}" listed)
      if(listed EQUAL -1)
        list(APPEND findings "${rel}: not listed in third_party/MANIFEST.md (Patches: what, why, upstream status)")
      endif()
    endif()

    file(READ "${depRoot}/patches/${patch}" patchText)
    _vp_escape("${patchText}" patchText)
    string(REPLACE "\n" ";" lines "${patchText}")
    set(target "")        # file the current hunks apply to ("" before the first +++ line)
    set(skipFile FALSE)   # its hunks are not checked (the file is missing, already reported)
    set(deleted "")
    set(targetText "")    # its escaped, normalized content
    set(searchFrom 0)     # offset after the previous hunk of this file
    set(inHunk FALSE)
    set(preLeft 0)
    set(postLeft 0)
    set(post "")
    set(lineNo 0)
    set(hunkLine 0)
    set(fileHunks 0)
    foreach(line IN LISTS lines)
      math(EXPR lineNo "${lineNo} + 1")
      if(inHunk)
        string(SUBSTRING "${line}" 0 1 tag)
        string(LENGTH "${line}" len)
        if(len GREATER 0)
          string(SUBSTRING "${line}" 1 -1 body)
        else()
          set(body "") # an empty context line whose leading space was stripped
        endif()
        if(tag STREQUAL " " OR len EQUAL 0)
          string(APPEND post "${body}\n")
          math(EXPR preLeft "${preLeft} - 1")
          math(EXPR postLeft "${postLeft} - 1")
        elseif(tag STREQUAL "-")
          math(EXPR preLeft "${preLeft} - 1")
        elseif(tag STREQUAL "+")
          string(APPEND post "${body}\n")
          math(EXPR postLeft "${postLeft} - 1")
        elseif(tag STREQUAL "${_vpBackslash}")
          # "\ No newline at end of file": the last line has no newline.
          string(REGEX REPLACE "\n$" "" post "${post}")
        else()
          list(APPEND findings "${rel}:${lineNo}: malformed hunk line (hunk at line ${hunkLine})")
          set(inHunk FALSE)
          continue()
        endif()
        if(preLeft LESS_EQUAL 0 AND postLeft LESS_EQUAL 0)
          set(inHunk FALSE)
          math(EXPR hunkCount "${hunkCount} + 1")
          math(EXPR fileHunks "${fileHunks} + 1")
          if(skipFile)
            # reported with the +++ line
          elseif(target STREQUAL "")
            list(APPEND findings "${rel}:${hunkLine}: hunk before any +++ line")
          elseif(NOT post STREQUAL "")
            string(SUBSTRING "${targetText}" ${searchFrom} -1 rest)
            string(FIND "${rest}" "${post}" at)
            if(at EQUAL -1)
              list(APPEND findings "${rel}:${hunkLine}: hunk ${fileHunks} of third_party/${dep}/${target} is not applied (its post-image is not in the committed file, after the previous hunk)")
            else()
              string(LENGTH "${post}" postLen)
              math(EXPR searchFrom "${searchFrom} + ${at} + ${postLen}")
            endif()
          endif()
        endif()
        continue()
      endif()

      if(line MATCHES "^diff --git ")
        set(target "")
      elseif(line MATCHES "^\\+\\+\\+ (.*)$")
        set(path "${CMAKE_MATCH_1}")
        string(REGEX REPLACE "\t.*$" "" path "${path}")
        set(fileHunks 0)
        set(searchFrom 0)
        set(skipFile FALSE)
        if(path STREQUAL "/dev/null")
          set(target "")
          if(deleted AND EXISTS "${depRoot}/${deleted}")
            list(APPEND findings "${rel}:${lineNo}: third_party/${dep}/${deleted} should be deleted by this patch but exists")
          endif()
        else()
          string(REGEX REPLACE "^b/" "" path "${path}")
          _vp_unescape("${path}" target)
          if(NOT EXISTS "${depRoot}/${target}")
            list(APPEND findings "${rel}:${lineNo}: patched file third_party/${dep}/${target} does not exist")
            set(skipFile TRUE)
          else()
            file(READ "${depRoot}/${target}" targetText)
            _vp_escape("${targetText}" targetText)
          endif()
        endif()
      elseif(line MATCHES "^--- (.*)$")
        set(deleted "${CMAKE_MATCH_1}")
        string(REGEX REPLACE "\t.*$" "" deleted "${deleted}")
        string(REGEX REPLACE "^a/" "" deleted "${deleted}")
        _vp_unescape("${deleted}" deleted)
      elseif(line MATCHES "^@@ -[0-9]+(,([0-9]+))? \\+[0-9]+(,([0-9]+))? @@")
        set(preLeft 1)
        set(postLeft 1)
        if(NOT "${CMAKE_MATCH_2}" STREQUAL "")
          set(preLeft ${CMAKE_MATCH_2})
        endif()
        if(NOT "${CMAKE_MATCH_4}" STREQUAL "")
          set(postLeft ${CMAKE_MATCH_4})
        endif()
        set(post "")
        set(hunkLine ${lineNo})
        set(inHunk TRUE)
      endif()
    endforeach()
    if(inHunk)
      list(APPEND findings "${rel}:${hunkLine}: truncated hunk")
    endif()
  endforeach()
endforeach()

list(LENGTH findings n)
if(n GREATER 0)
  foreach(f IN LISTS findings)
    _vp_unescape("${f}" f)
    string(APPEND text "\n  ${f}")
  endforeach()
  message(FATAL_ERROR "Vendored-patch check failed (${n} finding(s)):${text}\n")
endif()
message(STATUS "Vendored-patch check passed: ${patchCount} patch(es), ${hunkCount} hunk(s) applied")
