# Vendored-patch check (WP-0.10r; CLAUDE.md: vendored code is never edited in place, changes are
# patches applied by tools/vendor/fetch_third_party.sh and documented in third_party/MANIFEST.md).
#
#   cmake -DTHIRD_PARTY_DIR=<dir> -DMANIFEST=<MANIFEST.md> -P vendor_patches.cmake
#
# For every third_party/<dep>/patches/* (each a git diff relative to third_party/<dep>):
#  1. the file is named NNNN-<slug>.patch (applied in that order), has at least one hunk, and is the
#     first cell of a row of the table under MANIFEST.md's "### ... (`third_party/<dep>/patches/`)"
#     heading; every patch that table lists exists;
#  2. every hunk is applied to the committed tree: its post-image (context and added lines) appears
#     in the target file, hunks in order; a file the patch deletes is absent.
# No network, git or build is needed, CRLF checkouts pass (line endings are normalized), and a hunk
# that reaches the unterminated last line of a file ("\ No newline at end of file") must match at the
# file's end. A tree re-vendored without its patches, or edited inside a patched hunk, fails. An
# in-place edit outside every hunk is not detected: re-running fetch_third_party.sh and diffing
# third_party/ is the full proof that the tree is upstream plus its patches (third_party/MANIFEST.md,
# "Patches").
# Exits non-zero with one line per finding.

cmake_minimum_required(VERSION 3.28)
if(NOT IS_DIRECTORY "${THIRD_PARTY_DIR}")
  message(FATAL_ERROR "vendor-patches: THIRD_PARTY_DIR is not a directory: '${THIRD_PARTY_DIR}'")
endif()
get_filename_component(THIRD_PARTY_DIR "${THIRD_PARTY_DIR}" ABSOLUTE)

# CMake lists split on ';' (not after '\', not inside [...]), so text is escaped before it is split
# into lines: ';', '\', '[' and ']' become control characters that sources do not contain.
string(ASCII 26 _vpSemi)
string(ASCII 28 _vpBackslash)
string(ASCII 29 _vpOpen)
string(ASCII 30 _vpClose)

function(_vp_escape text out)
  # file(READ) already drops the CR of each CRLF on CMake 3.28; this keeps the check independent of that.
  string(REPLACE "\r\n" "\n" text "${text}")
  string(REPLACE ";" "${_vpSemi}" text "${text}")
  string(REPLACE "\\" "${_vpBackslash}" text "${text}")
  string(REPLACE "[" "${_vpOpen}" text "${text}")
  string(REPLACE "]" "${_vpClose}" text "${text}")
  set(${out} "${text}" PARENT_SCOPE)
endfunction()

function(_vp_unescape text out)
  string(REPLACE "${_vpSemi}" ";" text "${text}")
  string(REPLACE "${_vpBackslash}" "\\" text "${text}")
  string(REPLACE "${_vpOpen}" "[" text "${text}")
  string(REPLACE "${_vpClose}" "]" text "${text}")
  set(${out} "${text}" PARENT_SCOPE)
endfunction()

set(findings "")
set(patchCount 0)
set(hunkCount 0)

# MANIFEST.md: "<dep>/<patch>" for every table row whose first cell is `NNNN-....patch`, inside a
# "### ... (`third_party/<dep>/patches/`)" section (which ends at the next heading).
set(listedPatches "")
if(MANIFEST)
  if(NOT EXISTS "${MANIFEST}")
    message(FATAL_ERROR "vendor-patches: MANIFEST not found: '${MANIFEST}'")
  endif()
  file(READ "${MANIFEST}" manifestText)
  _vp_escape("${manifestText}" manifestText)
  string(REPLACE "\n" ";" manifestLines "${manifestText}")
  set(section "")
  foreach(line IN LISTS manifestLines)
    if(line MATCHES "^#")
      set(section "")
      if(line MATCHES "^### .*\\(`third_party/([^/`]+)/patches/?`\\)")
        set(section "${CMAKE_MATCH_1}")
      endif()
    elseif(NOT section STREQUAL "" AND line MATCHES "^\\| *`([0-9][0-9][0-9][0-9]-[^`|]*\\.patch)` *\\|")
      list(APPEND listedPatches "${section}/${CMAKE_MATCH_1}")
    endif()
  endforeach()
endif()

# Checks the hunk just read (a macro, so that it updates the loop's variables): its post-image must be
# in the target file after the previous hunk, and at its very end when the post-image has no final
# newline ("\ No newline at end of file" after its last context or added line).
macro(_vp_finish_hunk)
  set(hunkPending FALSE)
  math(EXPR hunkCount "${hunkCount} + 1")
  math(EXPR fileHunks "${fileHunks} + 1")
  if(skipFile)
    # reported with the +++ line (missing file), or nothing to find (deleted file)
  elseif(target STREQUAL "")
    list(APPEND findings "${rel}:${hunkLine}: hunk before any +++ line")
  elseif(NOT post STREQUAL "")
    string(SUBSTRING "${targetText}" ${searchFrom} -1 rest)
    string(LENGTH "${post}" postLen)
    set(at -1)
    if(postNoEol)
      string(LENGTH "${rest}" restLen)
      if(restLen GREATER_EQUAL postLen)
        math(EXPR tailAt "${restLen} - ${postLen}")
        string(SUBSTRING "${rest}" ${tailAt} -1 tail)
        if(tail STREQUAL post)
          set(at ${tailAt})
        endif()
      endif()
    else()
      string(FIND "${rest}" "${post}" at)
    endif()
    if(at EQUAL -1)
      list(APPEND findings "${rel}:${hunkLine}: hunk ${fileHunks} of third_party/${dep}/${target} is not applied (its post-image is not in the committed file, after the previous hunk)")
    else()
      math(EXPR searchFrom "${searchFrom} + ${at} + ${postLen}")
    endif()
  endif()
endmacro()

file(GLOB deps LIST_DIRECTORIES true RELATIVE "${THIRD_PARTY_DIR}" "${THIRD_PARTY_DIR}/*")
list(SORT deps)
foreach(dep IN LISTS deps)
  if(NOT IS_DIRECTORY "${THIRD_PARTY_DIR}/${dep}/patches")
    continue()
  endif()
  set(depRoot "${THIRD_PARTY_DIR}/${dep}")
  file(GLOB patches RELATIVE "${depRoot}/patches" "${depRoot}/patches/*")
  list(SORT patches)
  foreach(patch IN LISTS patches)
    set(rel "third_party/${dep}/patches/${patch}")
    if(NOT patch MATCHES "^[0-9][0-9][0-9][0-9]-[a-z0-9][a-z0-9-]*\\.patch$")
      list(APPEND findings "${rel}: not named NNNN-<slug>.patch (lower-case slug), so its order is undefined")
      continue()
    endif()
    math(EXPR patchCount "${patchCount} + 1")
    if(MANIFEST AND NOT "${dep}/${patch}" IN_LIST listedPatches)
      list(APPEND findings "${rel}: not listed in the table under MANIFEST.md's \"### ... (`third_party/${dep}/patches/`)\" heading (what, why, upstream status)")
    endif()

    file(READ "${depRoot}/patches/${patch}" patchText)
    _vp_escape("${patchText}" patchText)
    string(REPLACE "\n" ";" lines "${patchText}")
    set(target "")        # file the current hunks apply to ("" before the first +++ line)
    set(skipFile FALSE)   # its hunks are not checked (missing or deleted file, reported with +++)
    set(deleted "")
    set(targetText "")    # its escaped, normalized content
    set(searchFrom 0)     # offset after the previous hunk of this file
    set(inHunk FALSE)
    set(hunkPending FALSE) # counts reached 0; a "\ No newline" marker may still follow
    set(lastTag "")        # tag of the hunk's last context, removed or added line
    set(postNoEol FALSE)   # the post-image has no final newline
    set(preLeft 0)
    set(postLeft 0)
    set(post "")
    set(lineNo 0)
    set(hunkLine 0)
    set(fileHunks 0)
    set(patchHunks 0)
    foreach(line IN LISTS lines)
      math(EXPR lineNo "${lineNo} + 1")
      if(hunkPending)
        string(SUBSTRING "${line}" 0 1 tag)
        if(tag STREQUAL "${_vpBackslash}")
          # "\ No newline at end of file" after the hunk's last line.
          if(lastTag STREQUAL " " OR lastTag STREQUAL "+")
            string(REGEX REPLACE "\n$" "" post "${post}")
            set(postNoEol TRUE)
          endif()
          _vp_finish_hunk()
          continue()
        endif()
        _vp_finish_hunk()
      endif()
      if(inHunk)
        string(SUBSTRING "${line}" 0 1 tag)
        string(LENGTH "${line}" len)
        if(len GREATER 0)
          string(SUBSTRING "${line}" 1 -1 body)
        else()
          set(body "") # an empty context line whose leading space was stripped
        endif()
        if(tag STREQUAL " " OR len EQUAL 0)
          string(APPEND post "${body}\n")
          math(EXPR preLeft "${preLeft} - 1")
          math(EXPR postLeft "${postLeft} - 1")
          set(lastTag " ")
        elseif(tag STREQUAL "-")
          math(EXPR preLeft "${preLeft} - 1")
          set(lastTag "-")
        elseif(tag STREQUAL "+")
          string(APPEND post "${body}\n")
          math(EXPR postLeft "${postLeft} - 1")
          set(lastTag "+")
        elseif(tag STREQUAL "${_vpBackslash}")
          # "\ No newline at end of file" describes the line before it: after a removed line it is
          # about the pre-image (ignored); after a context or added line, the post-image ends there.
          if(lastTag STREQUAL " " OR lastTag STREQUAL "+")
            string(REGEX REPLACE "\n$" "" post "${post}")
            set(postNoEol TRUE)
          endif()
        else()
          list(APPEND findings "${rel}:${lineNo}: malformed hunk line (hunk at line ${hunkLine})")
          set(inHunk FALSE)
          continue()
        endif()
        if(preLeft LESS_EQUAL 0 AND postLeft LESS_EQUAL 0)
          set(inHunk FALSE)
          set(hunkPending TRUE) # checked at the next line, which may be a "\ No newline" marker
        endif()
        continue()
      endif()

      if(line MATCHES "^diff --git ")
        set(target "")
        set(deleted "")
        set(skipFile FALSE)
      elseif(line MATCHES "^\\+\\+\\+ (.*)$")
        set(path "${CMAKE_MATCH_1}")
        string(REGEX REPLACE "\t.*$" "" path "${path}")
        set(fileHunks 0)
        set(searchFrom 0)
        set(skipFile FALSE)
        if(path STREQUAL "/dev/null")
          # A deleted file: it must be absent, and its hunks have no post-image to find.
          set(target "")
          set(skipFile TRUE)
          if(deleted STREQUAL "" OR deleted STREQUAL "/dev/null")
            list(APPEND findings "${rel}:${lineNo}: +++ /dev/null without a --- a/<file> line")
          elseif(EXISTS "${depRoot}/${deleted}")
            list(APPEND findings "${rel}:${lineNo}: third_party/${dep}/${deleted} should be deleted by this patch but exists")
          endif()
        else()
          string(REGEX REPLACE "^b/" "" path "${path}")
          _vp_unescape("${path}" target)
          if(NOT EXISTS "${depRoot}/${target}")
            list(APPEND findings "${rel}:${lineNo}: patched file third_party/${dep}/${target} does not exist")
            set(skipFile TRUE)
          else()
            file(READ "${depRoot}/${target}" targetText)
            _vp_escape("${targetText}" targetText)
          endif()
        endif()
      elseif(line MATCHES "^--- (.*)$")
        set(deleted "${CMAKE_MATCH_1}")
        string(REGEX REPLACE "\t.*$" "" deleted "${deleted}")
        string(REGEX REPLACE "^a/" "" deleted "${deleted}")
        _vp_unescape("${deleted}" deleted)
      elseif(line MATCHES "^@@ -[0-9]+(,([0-9]+))? \\+[0-9]+(,([0-9]+))? @@")
        set(preLeft 1)
        set(postLeft 1)
        if(NOT "${CMAKE_MATCH_2}" STREQUAL "")
          set(preLeft ${CMAKE_MATCH_2})
        endif()
        if(NOT "${CMAKE_MATCH_4}" STREQUAL "")
          set(postLeft ${CMAKE_MATCH_4})
        endif()
        set(post "")
        set(lastTag "")
        set(postNoEol FALSE)
        set(hunkLine ${lineNo})
        set(inHunk TRUE)
        math(EXPR patchHunks "${patchHunks} + 1")
      endif()
    endforeach()
    if(hunkPending)
      _vp_finish_hunk()
    endif()
    if(inHunk)
      list(APPEND findings "${rel}:${hunkLine}: truncated hunk")
    elseif(patchHunks EQUAL 0)
      list(APPEND findings "${rel}: has no hunks (git apply rejects an empty patch)")
    endif()
  endforeach()
endforeach()

# Every patch the manifest lists exists.
foreach(entry IN LISTS listedPatches)
  string(REGEX REPLACE "/[^/]*$" "" dep "${entry}")
  string(REGEX REPLACE "^.*/" "" patch "${entry}")
  if(NOT EXISTS "${THIRD_PARTY_DIR}/${dep}/patches/${patch}")
    list(APPEND findings "MANIFEST.md lists third_party/${dep}/patches/${patch}, which does not exist")
  endif()
endforeach()

list(LENGTH findings n)
if(n GREATER 0)
  foreach(f IN LISTS findings)
    _vp_unescape("${f}" f)
    string(APPEND text "\n  ${f}")
  endforeach()
  message(FATAL_ERROR "Vendored-patch check failed (${n} finding(s)):${text}\n")
endif()
message(STATUS "Vendored-patch check passed: ${patchCount} patch(es), ${hunkCount} hunk(s) applied")
