// Code generated by helios-schemac from gameplay/attributes.hschema. DO NOT EDIT.

package gamedef

import (
	"encoding/json"
	"fmt"
	"math"
)

var _ = json.Marshal
var _ = fmt.Errorf
var _ = math.MaxInt8

type ModOp uint8

const (
	ModOpPreAssign ModOp = 0
	ModOpPreMul ModOp = 1
	ModOpPreDiv ModOp = 2
	ModOpModAdd ModOp = 3
	ModOpModSub ModOp = 4
	ModOpPostMul ModOp = 5
	ModOpPostDiv ModOp = 6
	ModOpPostPercent ModOp = 7
	ModOpPostAssign ModOp = 8
)

var namesModOp = []enumName{{"PreAssign", 0}, {"PreMul", 1}, {"PreDiv", 2}, {"ModAdd", 3}, {"ModSub", 4}, {"PostMul", 5}, {"PostDiv", 6}, {"PostPercent", 7}, {"PostAssign", 8}, }

func (v ModOp) MarshalJSON() ([]byte, error) { return enumToJSON(namesModOp, int64(v)) }
func (v *ModOp) UnmarshalJSON(b []byte) error {
	x, err := enumFromJSON(namesModOp, b)
	*v = ModOp(x)
	return err
}
func (v ModOp) MarshalText() ([]byte, error) { return enumToText(namesModOp, int64(v)), nil }
func (v *ModOp) UnmarshalText(b []byte) error {
	x, err := enumFromText(namesModOp, string(b))
	*v = ModOp(x)
	return err
}

// How the PostMul/PostPercent/PostDiv factors combine (06 §1.2): Product = Dogma (with stacking
// penalties when the attribute is stackingPenalised), AdditiveBonus = GAS (two 1.5x give 2.0x).
type MultiplierMode uint8

const (
	MultiplierModeProduct MultiplierMode = 0
	MultiplierModeAdditiveBonus MultiplierMode = 1
)

var namesMultiplierMode = []enumName{{"Product", 0}, {"AdditiveBonus", 1}, }

func (v MultiplierMode) MarshalJSON() ([]byte, error) { return enumToJSON(namesMultiplierMode, int64(v)) }
func (v *MultiplierMode) UnmarshalJSON(b []byte) error {
	x, err := enumFromJSON(namesMultiplierMode, b)
	*v = MultiplierMode(x)
	return err
}
func (v MultiplierMode) MarshalText() ([]byte, error) { return enumToText(namesMultiplierMode, int64(v)), nil }
func (v *MultiplierMode) UnmarshalText(b []byte) error {
	x, err := enumFromText(namesMultiplierMode, string(b))
	*v = MultiplierMode(x)
	return err
}

// Input of a curve magnitude.
type MagnitudeInput uint8

const (
	MagnitudeInputLevel MagnitudeInput = 0
	MagnitudeInputStacks MagnitudeInput = 1
)

var namesMagnitudeInput = []enumName{{"Level", 0}, {"Stacks", 1}, }

func (v MagnitudeInput) MarshalJSON() ([]byte, error) { return enumToJSON(namesMagnitudeInput, int64(v)) }
func (v *MagnitudeInput) UnmarshalJSON(b []byte) error {
	x, err := enumFromJSON(namesMagnitudeInput, b)
	*v = MagnitudeInput(x)
	return err
}
func (v MagnitudeInput) MarshalText() ([]byte, error) { return enumToText(namesMagnitudeInput, int64(v)), nil }
func (v *MagnitudeInput) UnmarshalText(b []byte) error {
	x, err := enumFromText(namesMagnitudeInput, string(b))
	*v = MagnitudeInput(x)
	return err
}

// Which entity an attribute magnitude reads.
type MagnitudeSource uint8

const (
	MagnitudeSourceSource MagnitudeSource = 0
	MagnitudeSourceTarget MagnitudeSource = 1
)

var namesMagnitudeSource = []enumName{{"Source", 0}, {"Target", 1}, }

func (v MagnitudeSource) MarshalJSON() ([]byte, error) { return enumToJSON(namesMagnitudeSource, int64(v)) }
func (v *MagnitudeSource) UnmarshalJSON(b []byte) error {
	x, err := enumFromJSON(namesMagnitudeSource, b)
	*v = MagnitudeSource(x)
	return err
}
func (v MagnitudeSource) MarshalText() ([]byte, error) { return enumToText(namesMagnitudeSource, int64(v)), nil }
func (v *MagnitudeSource) UnmarshalText(b []byte) error {
	x, err := enumFromText(namesMagnitudeSource, string(b))
	*v = MagnitudeSource(x)
	return err
}

// Whether an attribute magnitude is captured when the modifier is applied or read live.
type CaptureMode uint8

const (
	CaptureModeSnapshot CaptureMode = 0
	CaptureModeLive CaptureMode = 1
)

var namesCaptureMode = []enumName{{"Snapshot", 0}, {"Live", 1}, }

func (v CaptureMode) MarshalJSON() ([]byte, error) { return enumToJSON(namesCaptureMode, int64(v)) }
func (v *CaptureMode) UnmarshalJSON(b []byte) error {
	x, err := enumFromJSON(namesCaptureMode, b)
	*v = CaptureMode(x)
	return err
}
func (v CaptureMode) MarshalText() ([]byte, error) { return enumToText(namesCaptureMode, int64(v)), nil }
func (v *CaptureMode) UnmarshalText(b []byte) error {
	x, err := enumFromText(namesCaptureMode, string(b))
	*v = CaptureMode(x)
	return err
}

// Dogma "location" domains of a modifier (06 §1.2). Only Self is resolved in Phase 0; the
// cross-entity domains arrive with WP-2.x (brain snapshots, fitsim).
type ModDomain uint8

const (
	ModDomainSelf ModDomain = 0
	ModDomainOwner ModDomain = 1
	ModDomainPilot ModDomain = 2
	ModDomainShip ModDomain = 3
	ModDomainShipModules ModDomain = 4
	ModDomainFleet ModDomain = 5
	ModDomainGrid ModDomain = 6
	ModDomainAreaVolume ModDomain = 7
	ModDomainFollowers ModDomain = 8
)

var namesModDomain = []enumName{{"Self", 0}, {"Owner", 1}, {"Pilot", 2}, {"Ship", 3}, {"ShipModules", 4}, {"Fleet", 5}, {"Grid", 6}, {"AreaVolume", 7}, {"Followers", 8}, }

func (v ModDomain) MarshalJSON() ([]byte, error) { return enumToJSON(namesModDomain, int64(v)) }
func (v *ModDomain) UnmarshalJSON(b []byte) error {
	x, err := enumFromJSON(namesModDomain, b)
	*v = ModDomain(x)
	return err
}
func (v ModDomain) MarshalText() ([]byte, error) { return enumToText(namesModDomain, int64(v)), nil }
func (v *ModDomain) UnmarshalText(b []byte) error {
	x, err := enumFromText(namesModDomain, string(b))
	*v = ModDomain(x)
	return err
}

// Quantization of a replicated attribute value (04 §4): `bits` spread over [min, max].
type Quantization struct {
	// Bits per value on the wire.
	Bits uint8 `json:"bits"`
	// Lowest encodable value.
	Min float64 `json:"min"`
	// Highest encodable value.
	Max float64 `json:"max"`
}

var dfltQuantizationBits = uint8(16)
// NewQuantization returns a Quantization with every field at its schema default.
func NewQuantization() Quantization {
	return Quantization{Bits: dfltQuantizationBits, Min: zero_f64_2(), Max: zero_f64_2(), }
}

func (m *Quantization) isDefault() bool {
	return m.Bits == dfltQuantizationBits &&
		def_f64_2(m.Min) &&
		def_f64_2(m.Max)
}

func (m *Quantization) appendFields(b []byte) []byte {
	if !(m.Bits == dfltQuantizationBits) {
		b = enc_u8_3(b, 1, m.Bits)
	}
	if !(def_f64_2(m.Min)) {
		b = enc_f64_2(b, 2, m.Min)
	}
	if !(def_f64_2(m.Max)) {
		b = enc_f64_2(b, 3, m.Max)
	}
	return b
}

func (m *Quantization) readFields(r *wireReader) error {
	for !r.atEnd() {
		id, wt, err := r.tag()
		if err != nil {
			return err
		}
		switch id {
			case 1:
				err = dec_u8_3(r, wt, &m.Bits)
			case 2:
				err = dec_f64_2(r, wt, &m.Min)
			case 3:
				err = dec_f64_2(r, wt, &m.Max)
			default:
				err = r.skip(wt)
		}
		if err != nil {
			return err
		}
	}
	return nil
}

// MarshalHelios encodes the tagged binary message (identical bytes to the C++ codec).
func (m *Quantization) MarshalHelios() []byte { return m.appendFields(nil) }

// UnmarshalHelios decodes a tagged message; missing fields take their schema defaults.
func (m *Quantization) UnmarshalHelios(b []byte) error {
	*m = NewQuantization()
	return m.readFields(newWireReader(b))
}

// UnmarshalJSON reads JSON (e.g. canonical JSONC written by the C++ codec); missing fields keep defaults.
func (m *Quantization) UnmarshalJSON(b []byte) error {
	type plain Quantization
	p := plain(NewQuantization())
	if err := json.Unmarshal(b, &p); err != nil {
		return err
	}
	*m = Quantization(p)
	return nil
}

// An attribute definition (06 §1.2). Attributes that native code reads every tick get generated
// slot constants; everything else is looked up by `id` once.
type AttributeDef struct {
	// Identifier used by HXL (`attr(e, Shield.Max)`) and by modifiers; dotted segments.
	Id string `json:"id"`
	// Display name.
	Name LocString `json:"name"`
	// Display unit ("m/s", "GJ"); 06's UnitRef until a UnitDef record type exists.
	Unit string `json:"unit"`
	// Base value of a new entity.
	Default float64 `json:"default"`
	// Lower bound of the final value: a constant or another attribute.
	MinClamp *AttrOrConst `json:"minClamp,omitempty"`
	// Upper bound of the final value (Shield.Current <= Shield.Max).
	MaxClamp *AttrOrConst `json:"maxClamp,omitempty"`
	// Base value computed from other attributes of the same entity (`self`), e.g. EffectiveHP.
	Derived *HxlExpr `json:"derived,omitempty"`
	// How the PostMul/PostPercent/PostDiv factors combine.
	MultiplierMode MultiplierMode `json:"multiplierMode"`
	// Multiplicative modifiers are stacking-penalised (S(i) = e^-(i/2.67)^2) unless exempt.
	StackingPenalised bool `json:"stackingPenalised"`
	// Who receives the final value (06 §1.6).
	Replicate Audience `json:"replicate"`
	// Wire quantization of the replicated value.
	Quant *Quantization `json:"quant,omitempty"`
	// Only persisted attributes save their base value; derived and final values never persist.
	PersistBase bool `json:"persistBase"`
}

var dfltAttributeDefMultiplierMode = MultiplierModeProduct
var dfltAttributeDefReplicate = AudienceServer
// NewAttributeDef returns a AttributeDef with every field at its schema default.
func NewAttributeDef() AttributeDef {
	return AttributeDef{Id: zero_Name_0(), Name: zero_LocString_4(), Unit: zero_Name_0(), Default: zero_f64_2(), MultiplierMode: dfltAttributeDefMultiplierMode, StackingPenalised: zero_bool_5(), Replicate: dfltAttributeDefReplicate, PersistBase: zero_bool_5(), }
}

func (m *AttributeDef) isDefault() bool {
	return def_Name_0(m.Id) &&
		def_LocString_4(m.Name) &&
		def_Name_0(m.Unit) &&
		def_f64_2(m.Default) &&
		def_helios_gameplay_AttrOrConst__6(m.MinClamp) &&
		def_helios_gameplay_AttrOrConst__6(m.MaxClamp) &&
		def_HxlExpr__7(m.Derived) &&
		m.MultiplierMode == dfltAttributeDefMultiplierMode &&
		def_bool_5(m.StackingPenalised) &&
		m.Replicate == dfltAttributeDefReplicate &&
		def_helios_gameplay_Quantization__8(m.Quant) &&
		def_bool_5(m.PersistBase)
}

func (m *AttributeDef) appendFields(b []byte) []byte {
	if !(def_Name_0(m.Id)) {
		b = enc_Name_0(b, 1, m.Id)
	}
	if !(def_LocString_4(m.Name)) {
		b = enc_LocString_4(b, 2, m.Name)
	}
	if !(def_Name_0(m.Unit)) {
		b = enc_Name_0(b, 3, m.Unit)
	}
	if !(def_f64_2(m.Default)) {
		b = enc_f64_2(b, 4, m.Default)
	}
	if !(def_helios_gameplay_AttrOrConst__6(m.MinClamp)) {
		b = enc_helios_gameplay_AttrOrConst__6(b, 5, m.MinClamp)
	}
	if !(def_helios_gameplay_AttrOrConst__6(m.MaxClamp)) {
		b = enc_helios_gameplay_AttrOrConst__6(b, 6, m.MaxClamp)
	}
	if !(def_HxlExpr__7(m.Derived)) {
		b = enc_HxlExpr__7(b, 7, m.Derived)
	}
	if !(m.MultiplierMode == dfltAttributeDefMultiplierMode) {
		b = enc_helios_gameplay_MultiplierMode_9(b, 8, m.MultiplierMode)
	}
	if !(def_bool_5(m.StackingPenalised)) {
		b = enc_bool_5(b, 9, m.StackingPenalised)
	}
	if !(m.Replicate == dfltAttributeDefReplicate) {
		b = enc_helios_gameplay_Audience_1(b, 10, m.Replicate)
	}
	if !(def_helios_gameplay_Quantization__8(m.Quant)) {
		b = enc_helios_gameplay_Quantization__8(b, 11, m.Quant)
	}
	if !(def_bool_5(m.PersistBase)) {
		b = enc_bool_5(b, 12, m.PersistBase)
	}
	return b
}

func (m *AttributeDef) readFields(r *wireReader) error {
	for !r.atEnd() {
		id, wt, err := r.tag()
		if err != nil {
			return err
		}
		switch id {
			case 1:
				err = dec_Name_0(r, wt, &m.Id)
			case 2:
				err = dec_LocString_4(r, wt, &m.Name)
			case 3:
				err = dec_Name_0(r, wt, &m.Unit)
			case 4:
				err = dec_f64_2(r, wt, &m.Default)
			case 5:
				err = dec_helios_gameplay_AttrOrConst__6(r, wt, &m.MinClamp)
			case 6:
				err = dec_helios_gameplay_AttrOrConst__6(r, wt, &m.MaxClamp)
			case 7:
				err = dec_HxlExpr__7(r, wt, &m.Derived)
			case 8:
				err = dec_helios_gameplay_MultiplierMode_9(r, wt, &m.MultiplierMode)
			case 9:
				err = dec_bool_5(r, wt, &m.StackingPenalised)
			case 10:
				err = dec_helios_gameplay_Audience_1(r, wt, &m.Replicate)
			case 11:
				err = dec_helios_gameplay_Quantization__8(r, wt, &m.Quant)
			case 12:
				err = dec_bool_5(r, wt, &m.PersistBase)
			default:
				err = r.skip(wt)
		}
		if err != nil {
			return err
		}
	}
	return nil
}

// MarshalHelios encodes the tagged binary message (identical bytes to the C++ codec).
func (m *AttributeDef) MarshalHelios() []byte { return m.appendFields(nil) }

// UnmarshalHelios decodes a tagged message; missing fields take their schema defaults.
func (m *AttributeDef) UnmarshalHelios(b []byte) error {
	*m = NewAttributeDef()
	return m.readFields(newWireReader(b))
}

// UnmarshalJSON reads JSON (e.g. canonical JSONC written by the C++ codec); missing fields keep defaults.
func (m *AttributeDef) UnmarshalJSON(b []byte) error {
	type plain AttributeDef
	p := plain(NewAttributeDef())
	if err := json.Unmarshal(b, &p); err != nil {
		return err
	}
	*m = AttributeDef(p)
	return nil
}

// AttributeRef references a AttributeDef record by RecordId.
type AttributeRef uint64

// The attribute set of a record template (06 §1.2): the layout of its entities' AttrBlock.
type AttributeSetDef struct {
	// The attributes of the set, in slot order.
	Attrs []AttributeRef `json:"attrs,omitempty"`
}

// NewAttributeSetDef returns a AttributeSetDef with every field at its schema default.
func NewAttributeSetDef() AttributeSetDef {
	return AttributeSetDef{}
}

func (m *AttributeSetDef) isDefault() bool {
	return def_list_Ref_helios_gameplay_AttributeDef___10(m.Attrs)
}

func (m *AttributeSetDef) appendFields(b []byte) []byte {
	if !(def_list_Ref_helios_gameplay_AttributeDef___10(m.Attrs)) {
		b = enc_list_Ref_helios_gameplay_AttributeDef___10(b, 1, m.Attrs)
	}
	return b
}

func (m *AttributeSetDef) readFields(r *wireReader) error {
	for !r.atEnd() {
		id, wt, err := r.tag()
		if err != nil {
			return err
		}
		switch id {
			case 1:
				err = dec_list_Ref_helios_gameplay_AttributeDef___10(r, wt, &m.Attrs)
			default:
				err = r.skip(wt)
		}
		if err != nil {
			return err
		}
	}
	return nil
}

// MarshalHelios encodes the tagged binary message (identical bytes to the C++ codec).
func (m *AttributeSetDef) MarshalHelios() []byte { return m.appendFields(nil) }

// UnmarshalHelios decodes a tagged message; missing fields take their schema defaults.
func (m *AttributeSetDef) UnmarshalHelios(b []byte) error {
	*m = NewAttributeSetDef()
	return m.readFields(newWireReader(b))
}

// UnmarshalJSON reads JSON (e.g. canonical JSONC written by the C++ codec); missing fields keep defaults.
func (m *AttributeSetDef) UnmarshalJSON(b []byte) error {
	type plain AttributeSetDef
	p := plain(NewAttributeSetDef())
	if err := json.Unmarshal(b, &p); err != nil {
		return err
	}
	*m = AttributeSetDef(p)
	return nil
}

// AttributeSetRef references a AttributeSetDef record by RecordId.
type AttributeSetRef uint64

// Target of a modifier (06 §1.2 cross-entity targeting): a domain plus a tag filter.
type ModifierTarget struct {
	// Which entities the modifier applies to (Self in Phase 0).
	Domain ModDomain `json:"domain"`
	// Selects the entities of a cross-entity domain by tag.
	Filter *TagQuery `json:"filter,omitempty"`
}

var dfltModifierTargetDomain = ModDomainSelf
// NewModifierTarget returns a ModifierTarget with every field at its schema default.
func NewModifierTarget() ModifierTarget {
	return ModifierTarget{Domain: dfltModifierTargetDomain, }
}

func (m *ModifierTarget) isDefault() bool {
	return m.Domain == dfltModifierTargetDomain &&
		def_TagQuery__11(m.Filter)
}

func (m *ModifierTarget) appendFields(b []byte) []byte {
	if !(m.Domain == dfltModifierTargetDomain) {
		b = enc_helios_gameplay_ModDomain_12(b, 1, m.Domain)
	}
	if !(def_TagQuery__11(m.Filter)) {
		b = enc_TagQuery__11(b, 2, m.Filter)
	}
	return b
}

func (m *ModifierTarget) readFields(r *wireReader) error {
	for !r.atEnd() {
		id, wt, err := r.tag()
		if err != nil {
			return err
		}
		switch id {
			case 1:
				err = dec_helios_gameplay_ModDomain_12(r, wt, &m.Domain)
			case 2:
				err = dec_TagQuery__11(r, wt, &m.Filter)
			default:
				err = r.skip(wt)
		}
		if err != nil {
			return err
		}
	}
	return nil
}

// MarshalHelios encodes the tagged binary message (identical bytes to the C++ codec).
func (m *ModifierTarget) MarshalHelios() []byte { return m.appendFields(nil) }

// UnmarshalHelios decodes a tagged message; missing fields take their schema defaults.
func (m *ModifierTarget) UnmarshalHelios(b []byte) error {
	*m = NewModifierTarget()
	return m.readFields(newWireReader(b))
}

// UnmarshalJSON reads JSON (e.g. canonical JSONC written by the C++ codec); missing fields keep defaults.
func (m *ModifierTarget) UnmarshalJSON(b []byte) error {
	type plain ModifierTarget
	p := plain(NewModifierTarget())
	if err := json.Unmarshal(b, &p); err != nil {
		return err
	}
	*m = ModifierTarget(p)
	return nil
}

// A modifier (06 §1.2): {attr, op, magnitude, penaltyGroup, exempt, requirement}; the runtime adds
// its source (effect, item or skill) so it can be removed and replicated.
type ModifierDef struct {
	// The modified attribute.
	Attr AttributeRef `json:"attr"`
	// Operator stage (Dogma order).
	Op ModOp `json:"op"`
	// The operand.
	Magnitude Magnitude `json:"magnitude"`
	// PreAssign/PostAssign: the highest priority wins (ties: the larger value).
	Priority int32 `json:"priority"`
	// Stacking-penalty chain; different groups are penalised independently.
	PenaltyGroup uint16 `json:"penaltyGroup"`
	// Never stacking-penalised (S = 1) and not counted in the chain, e.g. skills.
	Exempt bool `json:"exempt"`
	// The modifier applies only while the target's tags match (06 §1.3 ongoing requirements).
	Requirement *TagQuery `json:"requirement,omitempty"`
	// Target domain and filter.
	Target ModifierTarget `json:"target"`
}

// NewModifierDef returns a ModifierDef with every field at its schema default.
func NewModifierDef() ModifierDef {
	return ModifierDef{Attr: zero_Ref_helios_gameplay_AttributeDef__13(), Op: zero_helios_gameplay_ModOp_14(), Magnitude: zero_helios_gameplay_Magnitude_15(), Priority: zero_i32_16(), PenaltyGroup: zero_u16_17(), Exempt: zero_bool_5(), Target: zero_helios_gameplay_ModifierTarget_18(), }
}

func (m *ModifierDef) isDefault() bool {
	return def_Ref_helios_gameplay_AttributeDef__13(m.Attr) &&
		def_helios_gameplay_ModOp_14(m.Op) &&
		def_helios_gameplay_Magnitude_15(m.Magnitude) &&
		def_i32_16(m.Priority) &&
		def_u16_17(m.PenaltyGroup) &&
		def_bool_5(m.Exempt) &&
		def_TagQuery__11(m.Requirement) &&
		def_helios_gameplay_ModifierTarget_18(m.Target)
}

func (m *ModifierDef) appendFields(b []byte) []byte {
	if !(def_Ref_helios_gameplay_AttributeDef__13(m.Attr)) {
		b = enc_Ref_helios_gameplay_AttributeDef__13(b, 1, m.Attr)
	}
	if !(def_helios_gameplay_ModOp_14(m.Op)) {
		b = enc_helios_gameplay_ModOp_14(b, 2, m.Op)
	}
	if !(def_helios_gameplay_Magnitude_15(m.Magnitude)) {
		b = enc_helios_gameplay_Magnitude_15(b, 3, m.Magnitude)
	}
	if !(def_i32_16(m.Priority)) {
		b = enc_i32_16(b, 4, m.Priority)
	}
	if !(def_u16_17(m.PenaltyGroup)) {
		b = enc_u16_17(b, 5, m.PenaltyGroup)
	}
	if !(def_bool_5(m.Exempt)) {
		b = enc_bool_5(b, 6, m.Exempt)
	}
	if !(def_TagQuery__11(m.Requirement)) {
		b = enc_TagQuery__11(b, 7, m.Requirement)
	}
	if !(def_helios_gameplay_ModifierTarget_18(m.Target)) {
		b = enc_helios_gameplay_ModifierTarget_18(b, 8, m.Target)
	}
	return b
}

func (m *ModifierDef) readFields(r *wireReader) error {
	for !r.atEnd() {
		id, wt, err := r.tag()
		if err != nil {
			return err
		}
		switch id {
			case 1:
				err = dec_Ref_helios_gameplay_AttributeDef__13(r, wt, &m.Attr)
			case 2:
				err = dec_helios_gameplay_ModOp_14(r, wt, &m.Op)
			case 3:
				err = dec_helios_gameplay_Magnitude_15(r, wt, &m.Magnitude)
			case 4:
				err = dec_i32_16(r, wt, &m.Priority)
			case 5:
				err = dec_u16_17(r, wt, &m.PenaltyGroup)
			case 6:
				err = dec_bool_5(r, wt, &m.Exempt)
			case 7:
				err = dec_TagQuery__11(r, wt, &m.Requirement)
			case 8:
				err = dec_helios_gameplay_ModifierTarget_18(r, wt, &m.Target)
			default:
				err = r.skip(wt)
		}
		if err != nil {
			return err
		}
	}
	return nil
}

// MarshalHelios encodes the tagged binary message (identical bytes to the C++ codec).
func (m *ModifierDef) MarshalHelios() []byte { return m.appendFields(nil) }

// UnmarshalHelios decodes a tagged message; missing fields take their schema defaults.
func (m *ModifierDef) UnmarshalHelios(b []byte) error {
	*m = NewModifierDef()
	return m.readFields(newWireReader(b))
}

// UnmarshalJSON reads JSON (e.g. canonical JSONC written by the C++ codec); missing fields keep defaults.
func (m *ModifierDef) UnmarshalJSON(b []byte) error {
	type plain ModifierDef
	p := plain(NewModifierDef())
	if err := json.Unmarshal(b, &p); err != nil {
		return err
	}
	*m = ModifierDef(p)
	return nil
}

type AttrOrConstConst struct {
	Value float64 `json:"value"`
}

// NewAttrOrConstConst returns a AttrOrConstConst with every field at its schema default.
func NewAttrOrConstConst() AttrOrConstConst {
	return AttrOrConstConst{Value: zero_f64_2(), }
}

func (m *AttrOrConstConst) isDefault() bool {
	return def_f64_2(m.Value)
}

func (m *AttrOrConstConst) appendFields(b []byte) []byte {
	if !(def_f64_2(m.Value)) {
		b = enc_f64_2(b, 1, m.Value)
	}
	return b
}

func (m *AttrOrConstConst) readFields(r *wireReader) error {
	for !r.atEnd() {
		id, wt, err := r.tag()
		if err != nil {
			return err
		}
		switch id {
			case 1:
				err = dec_f64_2(r, wt, &m.Value)
			default:
				err = r.skip(wt)
		}
		if err != nil {
			return err
		}
	}
	return nil
}

// MarshalHelios encodes the tagged binary message (identical bytes to the C++ codec).
func (m *AttrOrConstConst) MarshalHelios() []byte { return m.appendFields(nil) }

// UnmarshalHelios decodes a tagged message; missing fields take their schema defaults.
func (m *AttrOrConstConst) UnmarshalHelios(b []byte) error {
	*m = NewAttrOrConstConst()
	return m.readFields(newWireReader(b))
}

// UnmarshalJSON reads JSON (e.g. canonical JSONC written by the C++ codec); missing fields keep defaults.
func (m *AttrOrConstConst) UnmarshalJSON(b []byte) error {
	type plain AttrOrConstConst
	p := plain(NewAttrOrConstConst())
	if err := json.Unmarshal(b, &p); err != nil {
		return err
	}
	*m = AttrOrConstConst(p)
	return nil
}

type AttrOrConstAttr struct {
	Attr AttributeRef `json:"attr"`
}

// NewAttrOrConstAttr returns a AttrOrConstAttr with every field at its schema default.
func NewAttrOrConstAttr() AttrOrConstAttr {
	return AttrOrConstAttr{Attr: zero_Ref_helios_gameplay_AttributeDef__13(), }
}

func (m *AttrOrConstAttr) isDefault() bool {
	return def_Ref_helios_gameplay_AttributeDef__13(m.Attr)
}

func (m *AttrOrConstAttr) appendFields(b []byte) []byte {
	if !(def_Ref_helios_gameplay_AttributeDef__13(m.Attr)) {
		b = enc_Ref_helios_gameplay_AttributeDef__13(b, 1, m.Attr)
	}
	return b
}

func (m *AttrOrConstAttr) readFields(r *wireReader) error {
	for !r.atEnd() {
		id, wt, err := r.tag()
		if err != nil {
			return err
		}
		switch id {
			case 1:
				err = dec_Ref_helios_gameplay_AttributeDef__13(r, wt, &m.Attr)
			default:
				err = r.skip(wt)
		}
		if err != nil {
			return err
		}
	}
	return nil
}

// MarshalHelios encodes the tagged binary message (identical bytes to the C++ codec).
func (m *AttrOrConstAttr) MarshalHelios() []byte { return m.appendFields(nil) }

// UnmarshalHelios decodes a tagged message; missing fields take their schema defaults.
func (m *AttrOrConstAttr) UnmarshalHelios(b []byte) error {
	*m = NewAttrOrConstAttr()
	return m.readFields(newWireReader(b))
}

// UnmarshalJSON reads JSON (e.g. canonical JSONC written by the C++ codec); missing fields keep defaults.
func (m *AttrOrConstAttr) UnmarshalJSON(b []byte) error {
	type plain AttrOrConstAttr
	p := plain(NewAttrOrConstAttr())
	if err := json.Unmarshal(b, &p); err != nil {
		return err
	}
	*m = AttrOrConstAttr(p)
	return nil
}

// A constant or another attribute's final value (06 §1.2 AttrOrConst: Shield.Current <= Shield.Max).
// AttrOrConst is a variant: exactly one alternative is set (none set = the first alternative's default).
type AttrOrConst struct {
	Const *AttrOrConstConst
	Attr *AttrOrConstAttr
}

func NewAttrOrConst() AttrOrConst {
	x := NewAttrOrConstConst()
	return AttrOrConst{Const: &x}
}

func (m *AttrOrConst) index() int {
	switch {
		case m.Const != nil:
			return 0
		case m.Attr != nil:
			return 1
	}
	return -1
}

func (m *AttrOrConst) isDefault() bool {
	switch m.index() {
		case -1:
			return true
		case 0:
			return m.Const.isDefault()
	}
	return false
}

func (m *AttrOrConst) appendValue(b []byte) []byte {
	b, mk := beginLen(b)
	switch m.index() {
		case -1:
			b = enc_helios_gameplay_AttrOrConst_Const_19(b, 1, NewAttrOrConstConst())
		case 0:
			b = enc_helios_gameplay_AttrOrConst_Const_19(b, 1, *m.Const)
		case 1:
			b = enc_helios_gameplay_AttrOrConst_Attr_20(b, 2, *m.Attr)
	}
	return endLen(b, mk)
}

func (m *AttrOrConst) readValue(r *wireReader, wt int) error {
	if wt != wireLen {
		return wireMismatch("AttrOrConst", wt, wireLen)
	}
	sub, err := r.message()
	if err != nil {
		return err
	}
	for !sub.atEnd() {
		id, awt, err := sub.tag()
		if err != nil {
			return err
		}
		switch id {
			case 1:
				if m.Const == nil {
					x := NewAttrOrConstConst()
					*m = AttrOrConst{Const: &x}
				}
				err = dec_helios_gameplay_AttrOrConst_Const_19(sub, awt, m.Const)
			case 2:
				if m.Attr == nil {
					x := NewAttrOrConstAttr()
					*m = AttrOrConst{Attr: &x}
				}
				err = dec_helios_gameplay_AttrOrConst_Attr_20(sub, awt, m.Attr)
			default:
				err = sub.skip(awt)
		}
		if err != nil {
			return err
		}
	}
	return nil
}

func (m AttrOrConst) MarshalJSON() ([]byte, error) {
	switch m.index() {
		case 0:
			return json.Marshal(map[string]any{"Const": m.Const})
		case 1:
			return json.Marshal(map[string]any{"Attr": m.Attr})
	}
	return json.Marshal(map[string]any{"Const": NewAttrOrConstConst()})
}

func (m *AttrOrConst) UnmarshalJSON(b []byte) error {
	var name string
	var body json.RawMessage
	if err := json.Unmarshal(b, &name); err != nil {
		var obj map[string]json.RawMessage
		if err := json.Unmarshal(b, &obj); err != nil || len(obj) != 1 {
			return fmt.Errorf("helios: helios.gameplay.AttrOrConst must be an alternative name or {\"Alternative\": {...}}")
		}
		for k, v := range obj {
			name, body = k, v
		}
	}
	switch name {
		case "Const":
			x := NewAttrOrConstConst()
			if body != nil {
				if err := json.Unmarshal(body, &x); err != nil {
					return err
				}
			}
			*m = AttrOrConst{Const: &x}
			return nil
		case "Attr":
			x := NewAttrOrConstAttr()
			if body != nil {
				if err := json.Unmarshal(body, &x); err != nil {
					return err
				}
			}
			*m = AttrOrConst{Attr: &x}
			return nil
	}
	return fmt.Errorf("helios: unknown alternative %q of helios.gameplay.AttrOrConst", name)
}

type MagnitudeConst struct {
	Value float64 `json:"value"`
}

// NewMagnitudeConst returns a MagnitudeConst with every field at its schema default.
func NewMagnitudeConst() MagnitudeConst {
	return MagnitudeConst{Value: zero_f64_2(), }
}

func (m *MagnitudeConst) isDefault() bool {
	return def_f64_2(m.Value)
}

func (m *MagnitudeConst) appendFields(b []byte) []byte {
	if !(def_f64_2(m.Value)) {
		b = enc_f64_2(b, 1, m.Value)
	}
	return b
}

func (m *MagnitudeConst) readFields(r *wireReader) error {
	for !r.atEnd() {
		id, wt, err := r.tag()
		if err != nil {
			return err
		}
		switch id {
			case 1:
				err = dec_f64_2(r, wt, &m.Value)
			default:
				err = r.skip(wt)
		}
		if err != nil {
			return err
		}
	}
	return nil
}

// MarshalHelios encodes the tagged binary message (identical bytes to the C++ codec).
func (m *MagnitudeConst) MarshalHelios() []byte { return m.appendFields(nil) }

// UnmarshalHelios decodes a tagged message; missing fields take their schema defaults.
func (m *MagnitudeConst) UnmarshalHelios(b []byte) error {
	*m = NewMagnitudeConst()
	return m.readFields(newWireReader(b))
}

// UnmarshalJSON reads JSON (e.g. canonical JSONC written by the C++ codec); missing fields keep defaults.
func (m *MagnitudeConst) UnmarshalJSON(b []byte) error {
	type plain MagnitudeConst
	p := plain(NewMagnitudeConst())
	if err := json.Unmarshal(b, &p); err != nil {
		return err
	}
	*m = MagnitudeConst(p)
	return nil
}

type MagnitudeCurve struct {
	Curve string `json:"curve"`
	Input MagnitudeInput `json:"input"`
	Scale float64 `json:"scale"`
}

var dfltMagnitudeCurveInput = MagnitudeInputLevel
var dfltMagnitudeCurveScale = float64(1)
// NewMagnitudeCurve returns a MagnitudeCurve with every field at its schema default.
func NewMagnitudeCurve() MagnitudeCurve {
	return MagnitudeCurve{Curve: zero_Name_0(), Input: dfltMagnitudeCurveInput, Scale: dfltMagnitudeCurveScale, }
}

func (m *MagnitudeCurve) isDefault() bool {
	return def_Name_0(m.Curve) &&
		m.Input == dfltMagnitudeCurveInput &&
		f64Bits(m.Scale, dfltMagnitudeCurveScale)
}

func (m *MagnitudeCurve) appendFields(b []byte) []byte {
	if !(def_Name_0(m.Curve)) {
		b = enc_Name_0(b, 1, m.Curve)
	}
	if !(m.Input == dfltMagnitudeCurveInput) {
		b = enc_helios_gameplay_MagnitudeInput_21(b, 2, m.Input)
	}
	if !(f64Bits(m.Scale, dfltMagnitudeCurveScale)) {
		b = enc_f64_2(b, 3, m.Scale)
	}
	return b
}

func (m *MagnitudeCurve) readFields(r *wireReader) error {
	for !r.atEnd() {
		id, wt, err := r.tag()
		if err != nil {
			return err
		}
		switch id {
			case 1:
				err = dec_Name_0(r, wt, &m.Curve)
			case 2:
				err = dec_helios_gameplay_MagnitudeInput_21(r, wt, &m.Input)
			case 3:
				err = dec_f64_2(r, wt, &m.Scale)
			default:
				err = r.skip(wt)
		}
		if err != nil {
			return err
		}
	}
	return nil
}

// MarshalHelios encodes the tagged binary message (identical bytes to the C++ codec).
func (m *MagnitudeCurve) MarshalHelios() []byte { return m.appendFields(nil) }

// UnmarshalHelios decodes a tagged message; missing fields take their schema defaults.
func (m *MagnitudeCurve) UnmarshalHelios(b []byte) error {
	*m = NewMagnitudeCurve()
	return m.readFields(newWireReader(b))
}

// UnmarshalJSON reads JSON (e.g. canonical JSONC written by the C++ codec); missing fields keep defaults.
func (m *MagnitudeCurve) UnmarshalJSON(b []byte) error {
	type plain MagnitudeCurve
	p := plain(NewMagnitudeCurve())
	if err := json.Unmarshal(b, &p); err != nil {
		return err
	}
	*m = MagnitudeCurve(p)
	return nil
}

type MagnitudeAttr struct {
	Attr AttributeRef `json:"attr"`
	From MagnitudeSource `json:"from"`
	Capture CaptureMode `json:"capture"`
	Coefficient float64 `json:"coefficient"`
}

var dfltMagnitudeAttrFrom = MagnitudeSourceSource
var dfltMagnitudeAttrCapture = CaptureModeSnapshot
var dfltMagnitudeAttrCoefficient = float64(1)
// NewMagnitudeAttr returns a MagnitudeAttr with every field at its schema default.
func NewMagnitudeAttr() MagnitudeAttr {
	return MagnitudeAttr{Attr: zero_Ref_helios_gameplay_AttributeDef__13(), From: dfltMagnitudeAttrFrom, Capture: dfltMagnitudeAttrCapture, Coefficient: dfltMagnitudeAttrCoefficient, }
}

func (m *MagnitudeAttr) isDefault() bool {
	return def_Ref_helios_gameplay_AttributeDef__13(m.Attr) &&
		m.From == dfltMagnitudeAttrFrom &&
		m.Capture == dfltMagnitudeAttrCapture &&
		f64Bits(m.Coefficient, dfltMagnitudeAttrCoefficient)
}

func (m *MagnitudeAttr) appendFields(b []byte) []byte {
	if !(def_Ref_helios_gameplay_AttributeDef__13(m.Attr)) {
		b = enc_Ref_helios_gameplay_AttributeDef__13(b, 1, m.Attr)
	}
	if !(m.From == dfltMagnitudeAttrFrom) {
		b = enc_helios_gameplay_MagnitudeSource_22(b, 2, m.From)
	}
	if !(m.Capture == dfltMagnitudeAttrCapture) {
		b = enc_helios_gameplay_CaptureMode_23(b, 3, m.Capture)
	}
	if !(f64Bits(m.Coefficient, dfltMagnitudeAttrCoefficient)) {
		b = enc_f64_2(b, 4, m.Coefficient)
	}
	return b
}

func (m *MagnitudeAttr) readFields(r *wireReader) error {
	for !r.atEnd() {
		id, wt, err := r.tag()
		if err != nil {
			return err
		}
		switch id {
			case 1:
				err = dec_Ref_helios_gameplay_AttributeDef__13(r, wt, &m.Attr)
			case 2:
				err = dec_helios_gameplay_MagnitudeSource_22(r, wt, &m.From)
			case 3:
				err = dec_helios_gameplay_CaptureMode_23(r, wt, &m.Capture)
			case 4:
				err = dec_f64_2(r, wt, &m.Coefficient)
			default:
				err = r.skip(wt)
		}
		if err != nil {
			return err
		}
	}
	return nil
}

// MarshalHelios encodes the tagged binary message (identical bytes to the C++ codec).
func (m *MagnitudeAttr) MarshalHelios() []byte { return m.appendFields(nil) }

// UnmarshalHelios decodes a tagged message; missing fields take their schema defaults.
func (m *MagnitudeAttr) UnmarshalHelios(b []byte) error {
	*m = NewMagnitudeAttr()
	return m.readFields(newWireReader(b))
}

// UnmarshalJSON reads JSON (e.g. canonical JSONC written by the C++ codec); missing fields keep defaults.
func (m *MagnitudeAttr) UnmarshalJSON(b []byte) error {
	type plain MagnitudeAttr
	p := plain(NewMagnitudeAttr())
	if err := json.Unmarshal(b, &p); err != nil {
		return err
	}
	*m = MagnitudeAttr(p)
	return nil
}

type MagnitudeHxl struct {
	Expr HxlExpr `json:"expr"`
}

// NewMagnitudeHxl returns a MagnitudeHxl with every field at its schema default.
func NewMagnitudeHxl() MagnitudeHxl {
	return MagnitudeHxl{Expr: zero_HxlExpr_24(), }
}

func (m *MagnitudeHxl) isDefault() bool {
	return def_HxlExpr_24(m.Expr)
}

func (m *MagnitudeHxl) appendFields(b []byte) []byte {
	if !(def_HxlExpr_24(m.Expr)) {
		b = enc_HxlExpr_24(b, 1, m.Expr)
	}
	return b
}

func (m *MagnitudeHxl) readFields(r *wireReader) error {
	for !r.atEnd() {
		id, wt, err := r.tag()
		if err != nil {
			return err
		}
		switch id {
			case 1:
				err = dec_HxlExpr_24(r, wt, &m.Expr)
			default:
				err = r.skip(wt)
		}
		if err != nil {
			return err
		}
	}
	return nil
}

// MarshalHelios encodes the tagged binary message (identical bytes to the C++ codec).
func (m *MagnitudeHxl) MarshalHelios() []byte { return m.appendFields(nil) }

// UnmarshalHelios decodes a tagged message; missing fields take their schema defaults.
func (m *MagnitudeHxl) UnmarshalHelios(b []byte) error {
	*m = NewMagnitudeHxl()
	return m.readFields(newWireReader(b))
}

// UnmarshalJSON reads JSON (e.g. canonical JSONC written by the C++ codec); missing fields keep defaults.
func (m *MagnitudeHxl) UnmarshalJSON(b []byte) error {
	type plain MagnitudeHxl
	p := plain(NewMagnitudeHxl())
	if err := json.Unmarshal(b, &p); err != nil {
		return err
	}
	*m = MagnitudeHxl(p)
	return nil
}

// Where a modifier's magnitude comes from (06 §1.2): a constant, a level curve, a source or target
// attribute (captured at apply or read live), or an HXL formula.
// Magnitude is a variant: exactly one alternative is set (none set = the first alternative's default).
type Magnitude struct {
	Const *MagnitudeConst
	Curve *MagnitudeCurve
	Attr *MagnitudeAttr
	Hxl *MagnitudeHxl
}

func NewMagnitude() Magnitude {
	x := NewMagnitudeConst()
	return Magnitude{Const: &x}
}

func (m *Magnitude) index() int {
	switch {
		case m.Const != nil:
			return 0
		case m.Curve != nil:
			return 1
		case m.Attr != nil:
			return 2
		case m.Hxl != nil:
			return 3
	}
	return -1
}

func (m *Magnitude) isDefault() bool {
	switch m.index() {
		case -1:
			return true
		case 0:
			return m.Const.isDefault()
	}
	return false
}

func (m *Magnitude) appendValue(b []byte) []byte {
	b, mk := beginLen(b)
	switch m.index() {
		case -1:
			b = enc_helios_gameplay_Magnitude_Const_25(b, 1, NewMagnitudeConst())
		case 0:
			b = enc_helios_gameplay_Magnitude_Const_25(b, 1, *m.Const)
		case 1:
			b = enc_helios_gameplay_Magnitude_Curve_26(b, 2, *m.Curve)
		case 2:
			b = enc_helios_gameplay_Magnitude_Attr_27(b, 3, *m.Attr)
		case 3:
			b = enc_helios_gameplay_Magnitude_Hxl_28(b, 4, *m.Hxl)
	}
	return endLen(b, mk)
}

func (m *Magnitude) readValue(r *wireReader, wt int) error {
	if wt != wireLen {
		return wireMismatch("Magnitude", wt, wireLen)
	}
	sub, err := r.message()
	if err != nil {
		return err
	}
	for !sub.atEnd() {
		id, awt, err := sub.tag()
		if err != nil {
			return err
		}
		switch id {
			case 1:
				if m.Const == nil {
					x := NewMagnitudeConst()
					*m = Magnitude{Const: &x}
				}
				err = dec_helios_gameplay_Magnitude_Const_25(sub, awt, m.Const)
			case 2:
				if m.Curve == nil {
					x := NewMagnitudeCurve()
					*m = Magnitude{Curve: &x}
				}
				err = dec_helios_gameplay_Magnitude_Curve_26(sub, awt, m.Curve)
			case 3:
				if m.Attr == nil {
					x := NewMagnitudeAttr()
					*m = Magnitude{Attr: &x}
				}
				err = dec_helios_gameplay_Magnitude_Attr_27(sub, awt, m.Attr)
			case 4:
				if m.Hxl == nil {
					x := NewMagnitudeHxl()
					*m = Magnitude{Hxl: &x}
				}
				err = dec_helios_gameplay_Magnitude_Hxl_28(sub, awt, m.Hxl)
			default:
				err = sub.skip(awt)
		}
		if err != nil {
			return err
		}
	}
	return nil
}

func (m Magnitude) MarshalJSON() ([]byte, error) {
	switch m.index() {
		case 0:
			return json.Marshal(map[string]any{"Const": m.Const})
		case 1:
			return json.Marshal(map[string]any{"Curve": m.Curve})
		case 2:
			return json.Marshal(map[string]any{"Attr": m.Attr})
		case 3:
			return json.Marshal(map[string]any{"Hxl": m.Hxl})
	}
	return json.Marshal(map[string]any{"Const": NewMagnitudeConst()})
}

func (m *Magnitude) UnmarshalJSON(b []byte) error {
	var name string
	var body json.RawMessage
	if err := json.Unmarshal(b, &name); err != nil {
		var obj map[string]json.RawMessage
		if err := json.Unmarshal(b, &obj); err != nil || len(obj) != 1 {
			return fmt.Errorf("helios: helios.gameplay.Magnitude must be an alternative name or {\"Alternative\": {...}}")
		}
		for k, v := range obj {
			name, body = k, v
		}
	}
	switch name {
		case "Const":
			x := NewMagnitudeConst()
			if body != nil {
				if err := json.Unmarshal(body, &x); err != nil {
					return err
				}
			}
			*m = Magnitude{Const: &x}
			return nil
		case "Curve":
			x := NewMagnitudeCurve()
			if body != nil {
				if err := json.Unmarshal(body, &x); err != nil {
					return err
				}
			}
			*m = Magnitude{Curve: &x}
			return nil
		case "Attr":
			x := NewMagnitudeAttr()
			if body != nil {
				if err := json.Unmarshal(body, &x); err != nil {
					return err
				}
			}
			*m = Magnitude{Attr: &x}
			return nil
		case "Hxl":
			x := NewMagnitudeHxl()
			if body != nil {
				if err := json.Unmarshal(body, &x); err != nil {
					return err
				}
			}
			*m = Magnitude{Hxl: &x}
			return nil
	}
	return fmt.Errorf("helios: unknown alternative %q of helios.gameplay.Magnitude", name)
}

