// Code generated by helios-schemac from gameplay/economy.hschema. DO NOT EDIT.

package gamedef

import (
	"encoding/json"
	"fmt"
	"math"
)

var _ = json.Marshal
var _ = fmt.Errorf
var _ = math.MaxInt8

type ReasonKind uint8

const (
	ReasonKindFaucet ReasonKind = 0
	ReasonKindSink ReasonKind = 1
	ReasonKindTransfer ReasonKind = 2
)

var namesReasonKind = []enumName{{"Faucet", 0}, {"Sink", 1}, {"Transfer", 2}, }

func (v ReasonKind) MarshalJSON() ([]byte, error) { return enumToJSON(namesReasonKind, int64(v)) }
func (v *ReasonKind) UnmarshalJSON(b []byte) error {
	x, err := enumFromJSON(namesReasonKind, b)
	*v = ReasonKind(x)
	return err
}
func (v ReasonKind) MarshalText() ([]byte, error) { return enumToText(namesReasonKind, int64(v)), nil }
func (v *ReasonKind) UnmarshalText(b []byte) error {
	x, err := enumFromText(namesReasonKind, string(b))
	*v = ReasonKind(x)
	return err
}

// Daily grant cap of a faucet code usable by world scripts (05 §1.23).
type FaucetCap struct {
	// Most value one project may grant under the code per day.
	DailyCap int64 `json:"dailyCap"`
}

// NewFaucetCap returns a FaucetCap with every field at its schema default.
func NewFaucetCap() FaucetCap {
	return FaucetCap{DailyCap: zero_i64_80(), }
}

func (m *FaucetCap) isDefault() bool {
	return def_i64_80(m.DailyCap)
}

func (m *FaucetCap) appendFields(b []byte) []byte {
	if !(def_i64_80(m.DailyCap)) {
		b = enc_i64_80(b, 1, m.DailyCap)
	}
	return b
}

func (m *FaucetCap) readFields(r *wireReader) error {
	for !r.atEnd() {
		id, wt, err := r.tag()
		if err != nil {
			return err
		}
		switch id {
			case 1:
				err = dec_i64_80(r, wt, &m.DailyCap)
			default:
				err = r.skip(wt)
		}
		if err != nil {
			return err
		}
	}
	return nil
}

// MarshalHelios encodes the tagged binary message (identical bytes to the C++ codec).
func (m *FaucetCap) MarshalHelios() []byte { return m.appendFields(nil) }

// UnmarshalHelios decodes a tagged message; missing fields take their schema defaults.
func (m *FaucetCap) UnmarshalHelios(b []byte) error {
	*m = NewFaucetCap()
	return m.readFields(newWireReader(b))
}

// UnmarshalJSON reads JSON (e.g. canonical JSONC written by the C++ codec); missing fields keep defaults.
func (m *FaucetCap) UnmarshalJSON(b []byte) error {
	type plain FaucetCap
	p := plain(NewFaucetCap())
	if err := json.Unmarshal(b, &p); err != nil {
		return err
	}
	*m = FaucetCap(p)
	return nil
}

// Why value moved (06 §4). Every ledger journal entry names one; unknown codes are rejected
// (05 §1.6). Faucets mint from the system account mint:<code>, sinks burn to burn:<code>, and
// transfers touch no system account, so faucet and sink telemetry is correct by construction.
type ReasonCodeDef struct {
	// Dotted code whose first segment names the class: "Faucet.Bounty.NPC", "Sink.Tax.Market.Broker",
	// "Transfer.Trade".
	Code string `json:"code"`
	// Faucet, sink or transfer.
	Kind ReasonKind `json:"kind"`
	// World-script grant cap (faucets only).
	Faucet *FaucetCap `json:"faucet,omitempty"`
	// Economy guard (06 §4): rate thresholds for the telemetry anomaly rules (0 = unlimited).
	MaxTxPerHour int64 `json:"maxTxPerHour"`
	// Largest amount per transaction (0 = unlimited).
	MaxAmountPerTx int64 `json:"maxAmountPerTx"`
	// Named kill switch that disables the code ("econ.trade", 05 §1.15).
	KillSwitch string `json:"killSwitch"`
	// Display text for journals and telemetry.
	Description LocString `json:"description"`
}

// NewReasonCodeDef returns a ReasonCodeDef with every field at its schema default.
func NewReasonCodeDef() ReasonCodeDef {
	return ReasonCodeDef{Code: zero_Name_0(), Kind: zero_helios_gameplay_ReasonKind_81(), MaxTxPerHour: zero_i64_80(), MaxAmountPerTx: zero_i64_80(), KillSwitch: zero_Name_0(), Description: zero_LocString_4(), }
}

func (m *ReasonCodeDef) isDefault() bool {
	return def_Name_0(m.Code) &&
		def_helios_gameplay_ReasonKind_81(m.Kind) &&
		def_helios_gameplay_FaucetCap__82(m.Faucet) &&
		def_i64_80(m.MaxTxPerHour) &&
		def_i64_80(m.MaxAmountPerTx) &&
		def_Name_0(m.KillSwitch) &&
		def_LocString_4(m.Description)
}

func (m *ReasonCodeDef) appendFields(b []byte) []byte {
	if !(def_Name_0(m.Code)) {
		b = enc_Name_0(b, 1, m.Code)
	}
	if !(def_helios_gameplay_ReasonKind_81(m.Kind)) {
		b = enc_helios_gameplay_ReasonKind_81(b, 2, m.Kind)
	}
	if !(def_helios_gameplay_FaucetCap__82(m.Faucet)) {
		b = enc_helios_gameplay_FaucetCap__82(b, 3, m.Faucet)
	}
	if !(def_i64_80(m.MaxTxPerHour)) {
		b = enc_i64_80(b, 4, m.MaxTxPerHour)
	}
	if !(def_i64_80(m.MaxAmountPerTx)) {
		b = enc_i64_80(b, 5, m.MaxAmountPerTx)
	}
	if !(def_Name_0(m.KillSwitch)) {
		b = enc_Name_0(b, 6, m.KillSwitch)
	}
	if !(def_LocString_4(m.Description)) {
		b = enc_LocString_4(b, 7, m.Description)
	}
	return b
}

func (m *ReasonCodeDef) readFields(r *wireReader) error {
	for !r.atEnd() {
		id, wt, err := r.tag()
		if err != nil {
			return err
		}
		switch id {
			case 1:
				err = dec_Name_0(r, wt, &m.Code)
			case 2:
				err = dec_helios_gameplay_ReasonKind_81(r, wt, &m.Kind)
			case 3:
				err = dec_helios_gameplay_FaucetCap__82(r, wt, &m.Faucet)
			case 4:
				err = dec_i64_80(r, wt, &m.MaxTxPerHour)
			case 5:
				err = dec_i64_80(r, wt, &m.MaxAmountPerTx)
			case 6:
				err = dec_Name_0(r, wt, &m.KillSwitch)
			case 7:
				err = dec_LocString_4(r, wt, &m.Description)
			default:
				err = r.skip(wt)
		}
		if err != nil {
			return err
		}
	}
	return nil
}

// MarshalHelios encodes the tagged binary message (identical bytes to the C++ codec).
func (m *ReasonCodeDef) MarshalHelios() []byte { return m.appendFields(nil) }

// UnmarshalHelios decodes a tagged message; missing fields take their schema defaults.
func (m *ReasonCodeDef) UnmarshalHelios(b []byte) error {
	*m = NewReasonCodeDef()
	return m.readFields(newWireReader(b))
}

// UnmarshalJSON reads JSON (e.g. canonical JSONC written by the C++ codec); missing fields keep defaults.
func (m *ReasonCodeDef) UnmarshalJSON(b []byte) error {
	type plain ReasonCodeDef
	p := plain(NewReasonCodeDef())
	if err := json.Unmarshal(b, &p); err != nil {
		return err
	}
	*m = ReasonCodeDef(p)
	return nil
}

// ReasonCodeRef references a ReasonCodeDef record by RecordId.
type ReasonCodeRef uint64

