// Code generated by helios-schemac from gameplay/effects.hschema. DO NOT EDIT.

package gamedef

import (
	"encoding/json"
	"fmt"
	"math"
)

var _ = json.Marshal
var _ = fmt.Errorf
var _ = math.MaxInt8

type EffectClock uint8

const (
	EffectClockZone EffectClock = 0
	EffectClockWall EffectClock = 1
)

var namesEffectClock = []enumName{{"Zone", 0}, {"Wall", 1}, }

func (v EffectClock) MarshalJSON() ([]byte, error) { return enumToJSON(namesEffectClock, int64(v)) }
func (v *EffectClock) UnmarshalJSON(b []byte) error {
	x, err := enumFromJSON(namesEffectClock, b)
	*v = EffectClock(x)
	return err
}
func (v EffectClock) MarshalText() ([]byte, error) { return enumToText(namesEffectClock, int64(v)), nil }
func (v *EffectClock) UnmarshalText(b []byte) error {
	x, err := enumFromText(namesEffectClock, string(b))
	*v = EffectClock(x)
	return err
}

type StackingPolicy uint8

const (
	StackingPolicyNone StackingPolicy = 0
	StackingPolicyBySource StackingPolicy = 1
	StackingPolicyByTarget StackingPolicy = 2
)

var namesStackingPolicy = []enumName{{"None", 0}, {"BySource", 1}, {"ByTarget", 2}, }

func (v StackingPolicy) MarshalJSON() ([]byte, error) { return enumToJSON(namesStackingPolicy, int64(v)) }
func (v *StackingPolicy) UnmarshalJSON(b []byte) error {
	x, err := enumFromJSON(namesStackingPolicy, b)
	*v = StackingPolicy(x)
	return err
}
func (v StackingPolicy) MarshalText() ([]byte, error) { return enumToText(namesStackingPolicy, int64(v)), nil }
func (v *StackingPolicy) UnmarshalText(b []byte) error {
	x, err := enumFromText(namesStackingPolicy, string(b))
	*v = StackingPolicy(x)
	return err
}

type StackExpiry uint8

const (
	StackExpiryClearAll StackExpiry = 0
	StackExpiryRemoveOneAndRefresh StackExpiry = 1
)

var namesStackExpiry = []enumName{{"ClearAll", 0}, {"RemoveOneAndRefresh", 1}, }

func (v StackExpiry) MarshalJSON() ([]byte, error) { return enumToJSON(namesStackExpiry, int64(v)) }
func (v *StackExpiry) UnmarshalJSON(b []byte) error {
	x, err := enumFromJSON(namesStackExpiry, b)
	*v = StackExpiry(x)
	return err
}
func (v StackExpiry) MarshalText() ([]byte, error) { return enumToText(namesStackExpiry, int64(v)), nil }
func (v *StackExpiry) UnmarshalText(b []byte) error {
	x, err := enumFromText(namesStackExpiry, string(b))
	*v = StackExpiry(x)
	return err
}

// Which stack survives when the limit is reached (Strongest: fleet command bursts, 06 §8.3a).
type StackKeep uint8

const (
	StackKeepNewest StackKeep = 0
	StackKeepStrongest StackKeep = 1
)

var namesStackKeep = []enumName{{"Newest", 0}, {"Strongest", 1}, }

func (v StackKeep) MarshalJSON() ([]byte, error) { return enumToJSON(namesStackKeep, int64(v)) }
func (v *StackKeep) UnmarshalJSON(b []byte) error {
	x, err := enumFromJSON(namesStackKeep, b)
	*v = StackKeep(x)
	return err
}
func (v StackKeep) MarshalText() ([]byte, error) { return enumToText(namesStackKeep, int64(v)), nil }
func (v *StackKeep) UnmarshalText(b []byte) error {
	x, err := enumFromText(namesStackKeep, string(b))
	*v = StackKeep(x)
	return err
}

// Cue events (06 §1.5).
type CueEvent uint8

const (
	CueEventExecute CueEvent = 0
	CueEventAdd CueEvent = 1
	CueEventRemove CueEvent = 2
	CueEventBurst CueEvent = 3
)

var namesCueEvent = []enumName{{"Execute", 0}, {"Add", 1}, {"Remove", 2}, {"Burst", 3}, }

func (v CueEvent) MarshalJSON() ([]byte, error) { return enumToJSON(namesCueEvent, int64(v)) }
func (v *CueEvent) UnmarshalJSON(b []byte) error {
	x, err := enumFromJSON(namesCueEvent, b)
	*v = CueEvent(x)
	return err
}
func (v CueEvent) MarshalText() ([]byte, error) { return enumToText(namesCueEvent, int64(v)), nil }
func (v *CueEvent) UnmarshalText(b []byte) error {
	x, err := enumFromText(namesCueEvent, string(b))
	*v = CueEvent(x)
	return err
}

// Binds a cue (a Cue.* tag, 06 §1.5) to an effect event.
type CueBinding struct {
	// Cue.* tag naming the CueDef.
	Cue string `json:"cue"`
	// Effect event that triggers the cue.
	Event CueEvent `json:"event"`
}

var dfltCueBindingEvent = CueEventExecute
// NewCueBinding returns a CueBinding with every field at its schema default.
func NewCueBinding() CueBinding {
	return CueBinding{Cue: zero_Name_0(), Event: dfltCueBindingEvent, }
}

func (m *CueBinding) isDefault() bool {
	return def_Name_0(m.Cue) &&
		m.Event == dfltCueBindingEvent
}

func (m *CueBinding) appendFields(b []byte) []byte {
	if !(def_Name_0(m.Cue)) {
		b = enc_Name_0(b, 1, m.Cue)
	}
	if !(m.Event == dfltCueBindingEvent) {
		b = enc_helios_gameplay_CueEvent_29(b, 2, m.Event)
	}
	return b
}

func (m *CueBinding) readFields(r *wireReader) error {
	for !r.atEnd() {
		id, wt, err := r.tag()
		if err != nil {
			return err
		}
		switch id {
			case 1:
				err = dec_Name_0(r, wt, &m.Cue)
			case 2:
				err = dec_helios_gameplay_CueEvent_29(r, wt, &m.Event)
			default:
				err = r.skip(wt)
		}
		if err != nil {
			return err
		}
	}
	return nil
}

// MarshalHelios encodes the tagged binary message (identical bytes to the C++ codec).
func (m *CueBinding) MarshalHelios() []byte { return m.appendFields(nil) }

// UnmarshalHelios decodes a tagged message; missing fields take their schema defaults.
func (m *CueBinding) UnmarshalHelios(b []byte) error {
	*m = NewCueBinding()
	return m.readFields(newWireReader(b))
}

// UnmarshalJSON reads JSON (e.g. canonical JSONC written by the C++ codec); missing fields keep defaults.
func (m *CueBinding) UnmarshalJSON(b []byte) error {
	type plain CueBinding
	p := plain(NewCueBinding())
	if err := json.Unmarshal(b, &p); err != nil {
		return err
	}
	*m = CueBinding(p)
	return nil
}

// Stacking rules of an effect (06 §1.3).
type EffectStacking struct {
	// How repeated applications stack.
	Policy StackingPolicy `json:"policy"`
	// Maximum stacks (0 = unlimited).
	Limit uint16 `json:"limit"`
	// A new stack refreshes the duration.
	RefreshDuration bool `json:"refreshDuration"`
	// A new stack restarts the periodic timer.
	ResetPeriod bool `json:"resetPeriod"`
	// What expiry removes.
	OnExpire StackExpiry `json:"onExpire"`
	// Effect applied instead when the limit is reached.
	Overflow *EffectRef `json:"overflow,omitempty"`
	// Which stack survives at the limit.
	Keep StackKeep `json:"keep"`
}

var dfltEffectStackingPolicy = StackingPolicyNone
var dfltEffectStackingOnExpire = StackExpiryClearAll
var dfltEffectStackingKeep = StackKeepNewest
// NewEffectStacking returns a EffectStacking with every field at its schema default.
func NewEffectStacking() EffectStacking {
	return EffectStacking{Policy: dfltEffectStackingPolicy, Limit: zero_u16_17(), RefreshDuration: zero_bool_5(), ResetPeriod: zero_bool_5(), OnExpire: dfltEffectStackingOnExpire, Keep: dfltEffectStackingKeep, }
}

func (m *EffectStacking) isDefault() bool {
	return m.Policy == dfltEffectStackingPolicy &&
		def_u16_17(m.Limit) &&
		def_bool_5(m.RefreshDuration) &&
		def_bool_5(m.ResetPeriod) &&
		m.OnExpire == dfltEffectStackingOnExpire &&
		def_Ref_helios_gameplay_EffectDef___30(m.Overflow) &&
		m.Keep == dfltEffectStackingKeep
}

func (m *EffectStacking) appendFields(b []byte) []byte {
	if !(m.Policy == dfltEffectStackingPolicy) {
		b = enc_helios_gameplay_StackingPolicy_31(b, 1, m.Policy)
	}
	if !(def_u16_17(m.Limit)) {
		b = enc_u16_17(b, 2, m.Limit)
	}
	if !(def_bool_5(m.RefreshDuration)) {
		b = enc_bool_5(b, 3, m.RefreshDuration)
	}
	if !(def_bool_5(m.ResetPeriod)) {
		b = enc_bool_5(b, 4, m.ResetPeriod)
	}
	if !(m.OnExpire == dfltEffectStackingOnExpire) {
		b = enc_helios_gameplay_StackExpiry_32(b, 5, m.OnExpire)
	}
	if !(def_Ref_helios_gameplay_EffectDef___30(m.Overflow)) {
		b = enc_Ref_helios_gameplay_EffectDef___30(b, 6, m.Overflow)
	}
	if !(m.Keep == dfltEffectStackingKeep) {
		b = enc_helios_gameplay_StackKeep_33(b, 7, m.Keep)
	}
	return b
}

func (m *EffectStacking) readFields(r *wireReader) error {
	for !r.atEnd() {
		id, wt, err := r.tag()
		if err != nil {
			return err
		}
		switch id {
			case 1:
				err = dec_helios_gameplay_StackingPolicy_31(r, wt, &m.Policy)
			case 2:
				err = dec_u16_17(r, wt, &m.Limit)
			case 3:
				err = dec_bool_5(r, wt, &m.RefreshDuration)
			case 4:
				err = dec_bool_5(r, wt, &m.ResetPeriod)
			case 5:
				err = dec_helios_gameplay_StackExpiry_32(r, wt, &m.OnExpire)
			case 6:
				err = dec_Ref_helios_gameplay_EffectDef___30(r, wt, &m.Overflow)
			case 7:
				err = dec_helios_gameplay_StackKeep_33(r, wt, &m.Keep)
			default:
				err = r.skip(wt)
		}
		if err != nil {
			return err
		}
	}
	return nil
}

// MarshalHelios encodes the tagged binary message (identical bytes to the C++ codec).
func (m *EffectStacking) MarshalHelios() []byte { return m.appendFields(nil) }

// UnmarshalHelios decodes a tagged message; missing fields take their schema defaults.
func (m *EffectStacking) UnmarshalHelios(b []byte) error {
	*m = NewEffectStacking()
	return m.readFields(newWireReader(b))
}

// UnmarshalJSON reads JSON (e.g. canonical JSONC written by the C++ codec); missing fields keep defaults.
func (m *EffectStacking) UnmarshalJSON(b []byte) error {
	type plain EffectStacking
	p := plain(NewEffectStacking())
	if err := json.Unmarshal(b, &p); err != nil {
		return err
	}
	*m = EffectStacking(p)
	return nil
}

type EffectDefDurationInstant struct {
}

// NewEffectDefDurationInstant returns a EffectDefDurationInstant with every field at its schema default.
func NewEffectDefDurationInstant() EffectDefDurationInstant {
	return EffectDefDurationInstant{}
}

func (m *EffectDefDurationInstant) isDefault() bool {
	return true
}

func (m *EffectDefDurationInstant) appendFields(b []byte) []byte {
	return b
}

func (m *EffectDefDurationInstant) readFields(r *wireReader) error {
	for !r.atEnd() {
		id, wt, err := r.tag()
		if err != nil {
			return err
		}
		switch id {
			default:
				err = r.skip(wt)
		}
		if err != nil {
			return err
		}
	}
	return nil
}

// MarshalHelios encodes the tagged binary message (identical bytes to the C++ codec).
func (m *EffectDefDurationInstant) MarshalHelios() []byte { return m.appendFields(nil) }

// UnmarshalHelios decodes a tagged message; missing fields take their schema defaults.
func (m *EffectDefDurationInstant) UnmarshalHelios(b []byte) error {
	*m = NewEffectDefDurationInstant()
	return m.readFields(newWireReader(b))
}

// UnmarshalJSON reads JSON (e.g. canonical JSONC written by the C++ codec); missing fields keep defaults.
func (m *EffectDefDurationInstant) UnmarshalJSON(b []byte) error {
	type plain EffectDefDurationInstant
	p := plain(NewEffectDefDurationInstant())
	if err := json.Unmarshal(b, &p); err != nil {
		return err
	}
	*m = EffectDefDurationInstant(p)
	return nil
}

type EffectDefDurationDuration struct {
	Secs Magnitude `json:"secs"`
}

// NewEffectDefDurationDuration returns a EffectDefDurationDuration with every field at its schema default.
func NewEffectDefDurationDuration() EffectDefDurationDuration {
	return EffectDefDurationDuration{Secs: zero_helios_gameplay_Magnitude_15(), }
}

func (m *EffectDefDurationDuration) isDefault() bool {
	return def_helios_gameplay_Magnitude_15(m.Secs)
}

func (m *EffectDefDurationDuration) appendFields(b []byte) []byte {
	if !(def_helios_gameplay_Magnitude_15(m.Secs)) {
		b = enc_helios_gameplay_Magnitude_15(b, 1, m.Secs)
	}
	return b
}

func (m *EffectDefDurationDuration) readFields(r *wireReader) error {
	for !r.atEnd() {
		id, wt, err := r.tag()
		if err != nil {
			return err
		}
		switch id {
			case 1:
				err = dec_helios_gameplay_Magnitude_15(r, wt, &m.Secs)
			default:
				err = r.skip(wt)
		}
		if err != nil {
			return err
		}
	}
	return nil
}

// MarshalHelios encodes the tagged binary message (identical bytes to the C++ codec).
func (m *EffectDefDurationDuration) MarshalHelios() []byte { return m.appendFields(nil) }

// UnmarshalHelios decodes a tagged message; missing fields take their schema defaults.
func (m *EffectDefDurationDuration) UnmarshalHelios(b []byte) error {
	*m = NewEffectDefDurationDuration()
	return m.readFields(newWireReader(b))
}

// UnmarshalJSON reads JSON (e.g. canonical JSONC written by the C++ codec); missing fields keep defaults.
func (m *EffectDefDurationDuration) UnmarshalJSON(b []byte) error {
	type plain EffectDefDurationDuration
	p := plain(NewEffectDefDurationDuration())
	if err := json.Unmarshal(b, &p); err != nil {
		return err
	}
	*m = EffectDefDurationDuration(p)
	return nil
}

type EffectDefDurationInfinite struct {
}

// NewEffectDefDurationInfinite returns a EffectDefDurationInfinite with every field at its schema default.
func NewEffectDefDurationInfinite() EffectDefDurationInfinite {
	return EffectDefDurationInfinite{}
}

func (m *EffectDefDurationInfinite) isDefault() bool {
	return true
}

func (m *EffectDefDurationInfinite) appendFields(b []byte) []byte {
	return b
}

func (m *EffectDefDurationInfinite) readFields(r *wireReader) error {
	for !r.atEnd() {
		id, wt, err := r.tag()
		if err != nil {
			return err
		}
		switch id {
			default:
				err = r.skip(wt)
		}
		if err != nil {
			return err
		}
	}
	return nil
}

// MarshalHelios encodes the tagged binary message (identical bytes to the C++ codec).
func (m *EffectDefDurationInfinite) MarshalHelios() []byte { return m.appendFields(nil) }

// UnmarshalHelios decodes a tagged message; missing fields take their schema defaults.
func (m *EffectDefDurationInfinite) UnmarshalHelios(b []byte) error {
	*m = NewEffectDefDurationInfinite()
	return m.readFields(newWireReader(b))
}

// UnmarshalJSON reads JSON (e.g. canonical JSONC written by the C++ codec); missing fields keep defaults.
func (m *EffectDefDurationInfinite) UnmarshalJSON(b []byte) error {
	type plain EffectDefDurationInfinite
	p := plain(NewEffectDefDurationInfinite())
	if err := json.Unmarshal(b, &p); err != nil {
		return err
	}
	*m = EffectDefDurationInfinite(p)
	return nil
}

type EffectDefDurationPeriodic struct {
	Period Magnitude `json:"period"`
	Secs *Magnitude `json:"secs,omitempty"`
	ExecuteOnApply bool `json:"executeOnApply"`
}

// NewEffectDefDurationPeriodic returns a EffectDefDurationPeriodic with every field at its schema default.
func NewEffectDefDurationPeriodic() EffectDefDurationPeriodic {
	return EffectDefDurationPeriodic{Period: zero_helios_gameplay_Magnitude_15(), ExecuteOnApply: zero_bool_5(), }
}

func (m *EffectDefDurationPeriodic) isDefault() bool {
	return def_helios_gameplay_Magnitude_15(m.Period) &&
		def_helios_gameplay_Magnitude__34(m.Secs) &&
		def_bool_5(m.ExecuteOnApply)
}

func (m *EffectDefDurationPeriodic) appendFields(b []byte) []byte {
	if !(def_helios_gameplay_Magnitude_15(m.Period)) {
		b = enc_helios_gameplay_Magnitude_15(b, 1, m.Period)
	}
	if !(def_helios_gameplay_Magnitude__34(m.Secs)) {
		b = enc_helios_gameplay_Magnitude__34(b, 2, m.Secs)
	}
	if !(def_bool_5(m.ExecuteOnApply)) {
		b = enc_bool_5(b, 3, m.ExecuteOnApply)
	}
	return b
}

func (m *EffectDefDurationPeriodic) readFields(r *wireReader) error {
	for !r.atEnd() {
		id, wt, err := r.tag()
		if err != nil {
			return err
		}
		switch id {
			case 1:
				err = dec_helios_gameplay_Magnitude_15(r, wt, &m.Period)
			case 2:
				err = dec_helios_gameplay_Magnitude__34(r, wt, &m.Secs)
			case 3:
				err = dec_bool_5(r, wt, &m.ExecuteOnApply)
			default:
				err = r.skip(wt)
		}
		if err != nil {
			return err
		}
	}
	return nil
}

// MarshalHelios encodes the tagged binary message (identical bytes to the C++ codec).
func (m *EffectDefDurationPeriodic) MarshalHelios() []byte { return m.appendFields(nil) }

// UnmarshalHelios decodes a tagged message; missing fields take their schema defaults.
func (m *EffectDefDurationPeriodic) UnmarshalHelios(b []byte) error {
	*m = NewEffectDefDurationPeriodic()
	return m.readFields(newWireReader(b))
}

// UnmarshalJSON reads JSON (e.g. canonical JSONC written by the C++ codec); missing fields keep defaults.
func (m *EffectDefDurationPeriodic) UnmarshalJSON(b []byte) error {
	type plain EffectDefDurationPeriodic
	p := plain(NewEffectDefDurationPeriodic())
	if err := json.Unmarshal(b, &p); err != nil {
		return err
	}
	*m = EffectDefDurationPeriodic(p)
	return nil
}

// EffectDefDuration is a variant: exactly one alternative is set (none set = the first alternative's default).
type EffectDefDuration struct {
	Instant *EffectDefDurationInstant
	Duration *EffectDefDurationDuration
	Infinite *EffectDefDurationInfinite
	Periodic *EffectDefDurationPeriodic
}

func NewEffectDefDuration() EffectDefDuration {
	x := NewEffectDefDurationInstant()
	return EffectDefDuration{Instant: &x}
}

func (m *EffectDefDuration) index() int {
	switch {
		case m.Instant != nil:
			return 0
		case m.Duration != nil:
			return 1
		case m.Infinite != nil:
			return 2
		case m.Periodic != nil:
			return 3
	}
	return -1
}

func (m *EffectDefDuration) isDefault() bool {
	switch m.index() {
		case -1:
			return true
		case 0:
			return m.Instant.isDefault()
	}
	return false
}

func (m *EffectDefDuration) appendValue(b []byte) []byte {
	b, mk := beginLen(b)
	switch m.index() {
		case -1:
			b = enc_lios_gameplay_EffectDef_Duration_Instant_35(b, 1, NewEffectDefDurationInstant())
		case 0:
			b = enc_lios_gameplay_EffectDef_Duration_Instant_35(b, 1, *m.Instant)
		case 1:
			b = enc_ios_gameplay_EffectDef_Duration_Duration_36(b, 2, *m.Duration)
		case 2:
			b = enc_ios_gameplay_EffectDef_Duration_Infinite_37(b, 3, *m.Infinite)
		case 3:
			b = enc_ios_gameplay_EffectDef_Duration_Periodic_38(b, 4, *m.Periodic)
	}
	return endLen(b, mk)
}

func (m *EffectDefDuration) readValue(r *wireReader, wt int) error {
	if wt != wireLen {
		return wireMismatch("Duration", wt, wireLen)
	}
	sub, err := r.message()
	if err != nil {
		return err
	}
	for !sub.atEnd() {
		id, awt, err := sub.tag()
		if err != nil {
			return err
		}
		switch id {
			case 1:
				if m.Instant == nil {
					x := NewEffectDefDurationInstant()
					*m = EffectDefDuration{Instant: &x}
				}
				err = dec_lios_gameplay_EffectDef_Duration_Instant_35(sub, awt, m.Instant)
			case 2:
				if m.Duration == nil {
					x := NewEffectDefDurationDuration()
					*m = EffectDefDuration{Duration: &x}
				}
				err = dec_ios_gameplay_EffectDef_Duration_Duration_36(sub, awt, m.Duration)
			case 3:
				if m.Infinite == nil {
					x := NewEffectDefDurationInfinite()
					*m = EffectDefDuration{Infinite: &x}
				}
				err = dec_ios_gameplay_EffectDef_Duration_Infinite_37(sub, awt, m.Infinite)
			case 4:
				if m.Periodic == nil {
					x := NewEffectDefDurationPeriodic()
					*m = EffectDefDuration{Periodic: &x}
				}
				err = dec_ios_gameplay_EffectDef_Duration_Periodic_38(sub, awt, m.Periodic)
			default:
				err = sub.skip(awt)
		}
		if err != nil {
			return err
		}
	}
	return nil
}

func (m EffectDefDuration) MarshalJSON() ([]byte, error) {
	switch m.index() {
		case 0:
			return json.Marshal("Instant")
		case 1:
			return json.Marshal(map[string]any{"Duration": m.Duration})
		case 2:
			return json.Marshal("Infinite")
		case 3:
			return json.Marshal(map[string]any{"Periodic": m.Periodic})
	}
	return json.Marshal("Instant")
}

func (m *EffectDefDuration) UnmarshalJSON(b []byte) error {
	var name string
	var body json.RawMessage
	if err := json.Unmarshal(b, &name); err != nil {
		var obj map[string]json.RawMessage
		if err := json.Unmarshal(b, &obj); err != nil || len(obj) != 1 {
			return fmt.Errorf("helios: helios.gameplay.EffectDef.Duration must be an alternative name or {\"Alternative\": {...}}")
		}
		for k, v := range obj {
			name, body = k, v
		}
	}
	switch name {
		case "Instant":
			x := NewEffectDefDurationInstant()
			if body != nil {
				if err := json.Unmarshal(body, &x); err != nil {
					return err
				}
			}
			*m = EffectDefDuration{Instant: &x}
			return nil
		case "Duration":
			x := NewEffectDefDurationDuration()
			if body != nil {
				if err := json.Unmarshal(body, &x); err != nil {
					return err
				}
			}
			*m = EffectDefDuration{Duration: &x}
			return nil
		case "Infinite":
			x := NewEffectDefDurationInfinite()
			if body != nil {
				if err := json.Unmarshal(body, &x); err != nil {
					return err
				}
			}
			*m = EffectDefDuration{Infinite: &x}
			return nil
		case "Periodic":
			x := NewEffectDefDurationPeriodic()
			if body != nil {
				if err := json.Unmarshal(body, &x); err != nil {
					return err
				}
			}
			*m = EffectDefDuration{Periodic: &x}
			return nil
	}
	return fmt.Errorf("helios: unknown alternative %q of helios.gameplay.EffectDef.Duration", name)
}

// An effect definition (06 §1.3): timed or instant bundles of modifiers, executions and tags.
type EffectDef struct {
	// Instant, timed (seconds), infinite, or periodic (period, optional total seconds).
	Duration EffectDefDuration `json:"duration"`
	// Zone (dilated) or wall-clock timing.
	Clock EffectClock `json:"clock"`
	// Attribute modifiers active while the effect is.
	Modifiers []ModifierDef `json:"modifiers,omitempty"`
	// Native or HXL executions (damage, healing, custom logic).
	Executions []ExecutionRef `json:"executions,omitempty"`
	// Tags held while the effect is active (timed tags: crimewatch, cooldowns).
	GrantedTags TagSet `json:"grantedTags"`
	// AbilityDef record names until AbilityDef lands (WP-1.15; 06 §1.4 AbilityRef).
	GrantedAbilities []string `json:"grantedAbilities,omitempty"`
	// Required target tags to apply.
	ApplicationReq TagQuery `json:"applicationReq"`
	// Required target tags while active: when they stop matching, the effect is inhibited (its
	// modifiers and tags switch off), not removed (06 §1.3).
	OngoingReq TagQuery `json:"ongoingReq"`
	// Applying removes active effects granting any of these tags.
	RemoveEffectsWithTags TagSet `json:"removeEffectsWithTags"`
	// Targets holding any of these tags are immune.
	ImmunityTags TagSet `json:"immunityTags"`
	// Stacking rules.
	Stacking EffectStacking `json:"stacking"`
	// Cues fired by effect events.
	Cues []CueBinding `json:"cues,omitempty"`
	// The owner client may predict it (self effects of predicted abilities).
	Predictable bool `json:"predictable"`
	// Saved with the character (wounds, long buffs, clone penalties).
	Persist bool `json:"persist"`
	// Replicated to everyone as an icon (others only see public effects).
	PublicIcon bool `json:"publicIcon"`
}

var dfltEffectDefClock = EffectClockZone
// NewEffectDef returns a EffectDef with every field at its schema default.
func NewEffectDef() EffectDef {
	return EffectDef{Duration: zero_helios_gameplay_EffectDef_Duration_39(), Clock: dfltEffectDefClock, GrantedTags: zero_TagSet_40(), ApplicationReq: zero_TagQuery_41(), OngoingReq: zero_TagQuery_41(), RemoveEffectsWithTags: zero_TagSet_40(), ImmunityTags: zero_TagSet_40(), Stacking: zero_helios_gameplay_EffectStacking_42(), Predictable: zero_bool_5(), Persist: zero_bool_5(), PublicIcon: zero_bool_5(), }
}

func (m *EffectDef) isDefault() bool {
	return def_helios_gameplay_EffectDef_Duration_39(m.Duration) &&
		m.Clock == dfltEffectDefClock &&
		def_list_helios_gameplay_ModifierDef__43(m.Modifiers) &&
		def_list_helios_gameplay_ExecutionRef__44(m.Executions) &&
		def_TagSet_40(m.GrantedTags) &&
		def_list_Name__45(m.GrantedAbilities) &&
		def_TagQuery_41(m.ApplicationReq) &&
		def_TagQuery_41(m.OngoingReq) &&
		def_TagSet_40(m.RemoveEffectsWithTags) &&
		def_TagSet_40(m.ImmunityTags) &&
		def_helios_gameplay_EffectStacking_42(m.Stacking) &&
		def_list_helios_gameplay_CueBinding__46(m.Cues) &&
		def_bool_5(m.Predictable) &&
		def_bool_5(m.Persist) &&
		def_bool_5(m.PublicIcon)
}

func (m *EffectDef) appendFields(b []byte) []byte {
	if !(def_helios_gameplay_EffectDef_Duration_39(m.Duration)) {
		b = enc_helios_gameplay_EffectDef_Duration_39(b, 1, m.Duration)
	}
	if !(m.Clock == dfltEffectDefClock) {
		b = enc_helios_gameplay_EffectClock_47(b, 2, m.Clock)
	}
	if !(def_list_helios_gameplay_ModifierDef__43(m.Modifiers)) {
		b = enc_list_helios_gameplay_ModifierDef__43(b, 3, m.Modifiers)
	}
	if !(def_list_helios_gameplay_ExecutionRef__44(m.Executions)) {
		b = enc_list_helios_gameplay_ExecutionRef__44(b, 4, m.Executions)
	}
	if !(def_TagSet_40(m.GrantedTags)) {
		b = enc_TagSet_40(b, 5, m.GrantedTags)
	}
	if !(def_list_Name__45(m.GrantedAbilities)) {
		b = enc_list_Name__45(b, 6, m.GrantedAbilities)
	}
	if !(def_TagQuery_41(m.ApplicationReq)) {
		b = enc_TagQuery_41(b, 7, m.ApplicationReq)
	}
	if !(def_TagQuery_41(m.OngoingReq)) {
		b = enc_TagQuery_41(b, 8, m.OngoingReq)
	}
	if !(def_TagSet_40(m.RemoveEffectsWithTags)) {
		b = enc_TagSet_40(b, 9, m.RemoveEffectsWithTags)
	}
	if !(def_TagSet_40(m.ImmunityTags)) {
		b = enc_TagSet_40(b, 10, m.ImmunityTags)
	}
	if !(def_helios_gameplay_EffectStacking_42(m.Stacking)) {
		b = enc_helios_gameplay_EffectStacking_42(b, 11, m.Stacking)
	}
	if !(def_list_helios_gameplay_CueBinding__46(m.Cues)) {
		b = enc_list_helios_gameplay_CueBinding__46(b, 12, m.Cues)
	}
	if !(def_bool_5(m.Predictable)) {
		b = enc_bool_5(b, 13, m.Predictable)
	}
	if !(def_bool_5(m.Persist)) {
		b = enc_bool_5(b, 14, m.Persist)
	}
	if !(def_bool_5(m.PublicIcon)) {
		b = enc_bool_5(b, 15, m.PublicIcon)
	}
	return b
}

func (m *EffectDef) readFields(r *wireReader) error {
	for !r.atEnd() {
		id, wt, err := r.tag()
		if err != nil {
			return err
		}
		switch id {
			case 1:
				err = dec_helios_gameplay_EffectDef_Duration_39(r, wt, &m.Duration)
			case 2:
				err = dec_helios_gameplay_EffectClock_47(r, wt, &m.Clock)
			case 3:
				err = dec_list_helios_gameplay_ModifierDef__43(r, wt, &m.Modifiers)
			case 4:
				err = dec_list_helios_gameplay_ExecutionRef__44(r, wt, &m.Executions)
			case 5:
				err = dec_TagSet_40(r, wt, &m.GrantedTags)
			case 6:
				err = dec_list_Name__45(r, wt, &m.GrantedAbilities)
			case 7:
				err = dec_TagQuery_41(r, wt, &m.ApplicationReq)
			case 8:
				err = dec_TagQuery_41(r, wt, &m.OngoingReq)
			case 9:
				err = dec_TagSet_40(r, wt, &m.RemoveEffectsWithTags)
			case 10:
				err = dec_TagSet_40(r, wt, &m.ImmunityTags)
			case 11:
				err = dec_helios_gameplay_EffectStacking_42(r, wt, &m.Stacking)
			case 12:
				err = dec_list_helios_gameplay_CueBinding__46(r, wt, &m.Cues)
			case 13:
				err = dec_bool_5(r, wt, &m.Predictable)
			case 14:
				err = dec_bool_5(r, wt, &m.Persist)
			case 15:
				err = dec_bool_5(r, wt, &m.PublicIcon)
			default:
				err = r.skip(wt)
		}
		if err != nil {
			return err
		}
	}
	return nil
}

// MarshalHelios encodes the tagged binary message (identical bytes to the C++ codec).
func (m *EffectDef) MarshalHelios() []byte { return m.appendFields(nil) }

// UnmarshalHelios decodes a tagged message; missing fields take their schema defaults.
func (m *EffectDef) UnmarshalHelios(b []byte) error {
	*m = NewEffectDef()
	return m.readFields(newWireReader(b))
}

// UnmarshalJSON reads JSON (e.g. canonical JSONC written by the C++ codec); missing fields keep defaults.
func (m *EffectDef) UnmarshalJSON(b []byte) error {
	type plain EffectDef
	p := plain(NewEffectDef())
	if err := json.Unmarshal(b, &p); err != nil {
		return err
	}
	*m = EffectDef(p)
	return nil
}

// EffectRef references a EffectDef record by RecordId.
type EffectRef uint64

type ExecutionRefNative struct {
	Id string `json:"id"`
}

// NewExecutionRefNative returns a ExecutionRefNative with every field at its schema default.
func NewExecutionRefNative() ExecutionRefNative {
	return ExecutionRefNative{Id: zero_Name_0(), }
}

func (m *ExecutionRefNative) isDefault() bool {
	return def_Name_0(m.Id)
}

func (m *ExecutionRefNative) appendFields(b []byte) []byte {
	if !(def_Name_0(m.Id)) {
		b = enc_Name_0(b, 1, m.Id)
	}
	return b
}

func (m *ExecutionRefNative) readFields(r *wireReader) error {
	for !r.atEnd() {
		id, wt, err := r.tag()
		if err != nil {
			return err
		}
		switch id {
			case 1:
				err = dec_Name_0(r, wt, &m.Id)
			default:
				err = r.skip(wt)
		}
		if err != nil {
			return err
		}
	}
	return nil
}

// MarshalHelios encodes the tagged binary message (identical bytes to the C++ codec).
func (m *ExecutionRefNative) MarshalHelios() []byte { return m.appendFields(nil) }

// UnmarshalHelios decodes a tagged message; missing fields take their schema defaults.
func (m *ExecutionRefNative) UnmarshalHelios(b []byte) error {
	*m = NewExecutionRefNative()
	return m.readFields(newWireReader(b))
}

// UnmarshalJSON reads JSON (e.g. canonical JSONC written by the C++ codec); missing fields keep defaults.
func (m *ExecutionRefNative) UnmarshalJSON(b []byte) error {
	type plain ExecutionRefNative
	p := plain(NewExecutionRefNative())
	if err := json.Unmarshal(b, &p); err != nil {
		return err
	}
	*m = ExecutionRefNative(p)
	return nil
}

type ExecutionRefHxl struct {
	Expr HxlExpr `json:"expr"`
}

// NewExecutionRefHxl returns a ExecutionRefHxl with every field at its schema default.
func NewExecutionRefHxl() ExecutionRefHxl {
	return ExecutionRefHxl{Expr: zero_HxlExpr_24(), }
}

func (m *ExecutionRefHxl) isDefault() bool {
	return def_HxlExpr_24(m.Expr)
}

func (m *ExecutionRefHxl) appendFields(b []byte) []byte {
	if !(def_HxlExpr_24(m.Expr)) {
		b = enc_HxlExpr_24(b, 1, m.Expr)
	}
	return b
}

func (m *ExecutionRefHxl) readFields(r *wireReader) error {
	for !r.atEnd() {
		id, wt, err := r.tag()
		if err != nil {
			return err
		}
		switch id {
			case 1:
				err = dec_HxlExpr_24(r, wt, &m.Expr)
			default:
				err = r.skip(wt)
		}
		if err != nil {
			return err
		}
	}
	return nil
}

// MarshalHelios encodes the tagged binary message (identical bytes to the C++ codec).
func (m *ExecutionRefHxl) MarshalHelios() []byte { return m.appendFields(nil) }

// UnmarshalHelios decodes a tagged message; missing fields take their schema defaults.
func (m *ExecutionRefHxl) UnmarshalHelios(b []byte) error {
	*m = NewExecutionRefHxl()
	return m.readFields(newWireReader(b))
}

// UnmarshalJSON reads JSON (e.g. canonical JSONC written by the C++ codec); missing fields keep defaults.
func (m *ExecutionRefHxl) UnmarshalJSON(b []byte) error {
	type plain ExecutionRefHxl
	p := plain(NewExecutionRefHxl())
	if err := json.Unmarshal(b, &p); err != nil {
		return err
	}
	*m = ExecutionRefHxl(p)
	return nil
}

// A native or HXL execution of an effect (damage, healing, custom logic).
// ExecutionRef is a variant: exactly one alternative is set (none set = the first alternative's default).
type ExecutionRef struct {
	Native *ExecutionRefNative
	Hxl *ExecutionRefHxl
}

func NewExecutionRef() ExecutionRef {
	x := NewExecutionRefNative()
	return ExecutionRef{Native: &x}
}

func (m *ExecutionRef) index() int {
	switch {
		case m.Native != nil:
			return 0
		case m.Hxl != nil:
			return 1
	}
	return -1
}

func (m *ExecutionRef) isDefault() bool {
	switch m.index() {
		case -1:
			return true
		case 0:
			return m.Native.isDefault()
	}
	return false
}

func (m *ExecutionRef) appendValue(b []byte) []byte {
	b, mk := beginLen(b)
	switch m.index() {
		case -1:
			b = enc_helios_gameplay_ExecutionRef_Native_48(b, 1, NewExecutionRefNative())
		case 0:
			b = enc_helios_gameplay_ExecutionRef_Native_48(b, 1, *m.Native)
		case 1:
			b = enc_helios_gameplay_ExecutionRef_Hxl_49(b, 2, *m.Hxl)
	}
	return endLen(b, mk)
}

func (m *ExecutionRef) readValue(r *wireReader, wt int) error {
	if wt != wireLen {
		return wireMismatch("ExecutionRef", wt, wireLen)
	}
	sub, err := r.message()
	if err != nil {
		return err
	}
	for !sub.atEnd() {
		id, awt, err := sub.tag()
		if err != nil {
			return err
		}
		switch id {
			case 1:
				if m.Native == nil {
					x := NewExecutionRefNative()
					*m = ExecutionRef{Native: &x}
				}
				err = dec_helios_gameplay_ExecutionRef_Native_48(sub, awt, m.Native)
			case 2:
				if m.Hxl == nil {
					x := NewExecutionRefHxl()
					*m = ExecutionRef{Hxl: &x}
				}
				err = dec_helios_gameplay_ExecutionRef_Hxl_49(sub, awt, m.Hxl)
			default:
				err = sub.skip(awt)
		}
		if err != nil {
			return err
		}
	}
	return nil
}

func (m ExecutionRef) MarshalJSON() ([]byte, error) {
	switch m.index() {
		case 0:
			return json.Marshal(map[string]any{"Native": m.Native})
		case 1:
			return json.Marshal(map[string]any{"Hxl": m.Hxl})
	}
	return json.Marshal(map[string]any{"Native": NewExecutionRefNative()})
}

func (m *ExecutionRef) UnmarshalJSON(b []byte) error {
	var name string
	var body json.RawMessage
	if err := json.Unmarshal(b, &name); err != nil {
		var obj map[string]json.RawMessage
		if err := json.Unmarshal(b, &obj); err != nil || len(obj) != 1 {
			return fmt.Errorf("helios: helios.gameplay.ExecutionRef must be an alternative name or {\"Alternative\": {...}}")
		}
		for k, v := range obj {
			name, body = k, v
		}
	}
	switch name {
		case "Native":
			x := NewExecutionRefNative()
			if body != nil {
				if err := json.Unmarshal(body, &x); err != nil {
					return err
				}
			}
			*m = ExecutionRef{Native: &x}
			return nil
		case "Hxl":
			x := NewExecutionRefHxl()
			if body != nil {
				if err := json.Unmarshal(body, &x); err != nil {
					return err
				}
			}
			*m = ExecutionRef{Hxl: &x}
			return nil
	}
	return fmt.Errorf("helios: unknown alternative %q of helios.gameplay.ExecutionRef", name)
}

