// Code generated by helios-schemac. DO NOT EDIT.
//
// Tagged wire helpers per schema type (enc_ = field, encv_ = value, dec_/decv_ = decode,
// def_ = implicit-default test, zero_ = implicit default value).

package gamedef

import (
	"fmt"
	"math"
)

var _ = fmt.Errorf
var _ = math.MaxInt8

func zero_Name_0() string { return "" }

func def_Name_0(v string) bool {
	return v == ""
}

func encv_Name_0(b []byte, v string) []byte {
	return appendString(b, v)
}

func decv_Name_0(r *wireReader, wt int, v *string) error {
	x, err := readStringField(r, wt)
	*v = x
	return err
}

func enc_Name_0(b []byte, id uint32, v string) []byte {
	b = appendTag(b, id, wireLen)
	return encv_Name_0(b, v)
}

func dec_Name_0(r *wireReader, wt int, v *string) error {
	return decv_Name_0(r, wt, v)
}

func zero_helios_gameplay_Audience_1() Audience { return AudienceServer }

func def_helios_gameplay_Audience_1(v Audience) bool {
	return v == AudienceServer
}

func encv_helios_gameplay_Audience_1(b []byte, v Audience) []byte {
	return appendVarint(b, uint64(v))
}

func decv_helios_gameplay_Audience_1(r *wireReader, wt int, v *Audience) error {
	x, err := readUnsigned(r, wt, math.MaxUint8)
	*v = Audience(x)
	return err
}

func enc_helios_gameplay_Audience_1(b []byte, id uint32, v Audience) []byte {
	b = appendTag(b, id, wireVarint)
	return encv_helios_gameplay_Audience_1(b, v)
}

func dec_helios_gameplay_Audience_1(r *wireReader, wt int, v *Audience) error {
	return decv_helios_gameplay_Audience_1(r, wt, v)
}

func zero_f64_2() float64 { return float64(0) }

func def_f64_2(v float64) bool {
	return math.Float64bits(v) == 0
}

func encv_f64_2(b []byte, v float64) []byte {
	return appendF64(b, v)
}

func decv_f64_2(r *wireReader, wt int, v *float64) error {
	x, err := readF64(r, wt)
	*v = x
	return err
}

func enc_f64_2(b []byte, id uint32, v float64) []byte {
	b = appendTag(b, id, wireI64)
	return encv_f64_2(b, v)
}

func dec_f64_2(r *wireReader, wt int, v *float64) error {
	return decv_f64_2(r, wt, v)
}

func zero_u8_3() uint8 { return uint8(0) }

func def_u8_3(v uint8) bool {
	return v == 0
}

func encv_u8_3(b []byte, v uint8) []byte {
	return appendVarint(b, uint64(v))
}

func decv_u8_3(r *wireReader, wt int, v *uint8) error {
	x, err := readUnsigned(r, wt, math.MaxUint8)
	*v = uint8(x)
	return err
}

func enc_u8_3(b []byte, id uint32, v uint8) []byte {
	b = appendTag(b, id, wireVarint)
	return encv_u8_3(b, v)
}

func dec_u8_3(r *wireReader, wt int, v *uint8) error {
	return decv_u8_3(r, wt, v)
}

func zero_LocString_4() LocString { return "" }

func def_LocString_4(v LocString) bool {
	return v == ""
}

func encv_LocString_4(b []byte, v LocString) []byte {
	return appendString(b, string(v))
}

func decv_LocString_4(r *wireReader, wt int, v *LocString) error {
	x, err := readStringField(r, wt)
	*v = LocString(x)
	return err
}

func enc_LocString_4(b []byte, id uint32, v LocString) []byte {
	b = appendTag(b, id, wireLen)
	return encv_LocString_4(b, v)
}

func dec_LocString_4(r *wireReader, wt int, v *LocString) error {
	return decv_LocString_4(r, wt, v)
}

func zero_bool_5() bool { return false }

func def_bool_5(v bool) bool {
	return !v
}

func encv_bool_5(b []byte, v bool) []byte {
	return appendBool(b, v)
}

func decv_bool_5(r *wireReader, wt int, v *bool) error {
	x, err := readVarintField(r, wt, "bool")
	*v = x != 0
	return err
}

func enc_bool_5(b []byte, id uint32, v bool) []byte {
	b = appendTag(b, id, wireVarint)
	return encv_bool_5(b, v)
}

func dec_bool_5(r *wireReader, wt int, v *bool) error {
	return decv_bool_5(r, wt, v)
}

func zero_helios_gameplay_AttrOrConst__6() *AttrOrConst { return (*AttrOrConst)(nil) }

func def_helios_gameplay_AttrOrConst__6(v *AttrOrConst) bool {
	return v == nil
}

func enc_helios_gameplay_AttrOrConst__6(b []byte, id uint32, v *AttrOrConst) []byte {
	if v == nil {
		return b
	}
	return enc_helios_gameplay_AttrOrConst_83(b, id, *v)
}

func dec_helios_gameplay_AttrOrConst__6(r *wireReader, wt int, v **AttrOrConst) error {
	if *v == nil {
		x := zero_helios_gameplay_AttrOrConst_83()
		*v = &x
	}
	return dec_helios_gameplay_AttrOrConst_83(r, wt, *v)
}

func zero_HxlExpr__7() *HxlExpr { return (*HxlExpr)(nil) }

func def_HxlExpr__7(v *HxlExpr) bool {
	return v == nil
}

func enc_HxlExpr__7(b []byte, id uint32, v *HxlExpr) []byte {
	if v == nil {
		return b
	}
	return enc_HxlExpr_24(b, id, *v)
}

func dec_HxlExpr__7(r *wireReader, wt int, v **HxlExpr) error {
	if *v == nil {
		x := zero_HxlExpr_24()
		*v = &x
	}
	return dec_HxlExpr_24(r, wt, *v)
}

func zero_helios_gameplay_Quantization__8() *Quantization { return (*Quantization)(nil) }

func def_helios_gameplay_Quantization__8(v *Quantization) bool {
	return v == nil
}

func enc_helios_gameplay_Quantization__8(b []byte, id uint32, v *Quantization) []byte {
	if v == nil {
		return b
	}
	return enc_helios_gameplay_Quantization_84(b, id, *v)
}

func dec_helios_gameplay_Quantization__8(r *wireReader, wt int, v **Quantization) error {
	if *v == nil {
		x := zero_helios_gameplay_Quantization_84()
		*v = &x
	}
	return dec_helios_gameplay_Quantization_84(r, wt, *v)
}

func zero_helios_gameplay_MultiplierMode_9() MultiplierMode { return MultiplierModeProduct }

func def_helios_gameplay_MultiplierMode_9(v MultiplierMode) bool {
	return v == MultiplierModeProduct
}

func encv_helios_gameplay_MultiplierMode_9(b []byte, v MultiplierMode) []byte {
	return appendVarint(b, uint64(v))
}

func decv_helios_gameplay_MultiplierMode_9(r *wireReader, wt int, v *MultiplierMode) error {
	x, err := readUnsigned(r, wt, math.MaxUint8)
	*v = MultiplierMode(x)
	return err
}

func enc_helios_gameplay_MultiplierMode_9(b []byte, id uint32, v MultiplierMode) []byte {
	b = appendTag(b, id, wireVarint)
	return encv_helios_gameplay_MultiplierMode_9(b, v)
}

func dec_helios_gameplay_MultiplierMode_9(r *wireReader, wt int, v *MultiplierMode) error {
	return decv_helios_gameplay_MultiplierMode_9(r, wt, v)
}

func zero_list_Ref_helios_gameplay_AttributeDef___10() []AttributeRef { return ([]AttributeRef)(nil) }

func def_list_Ref_helios_gameplay_AttributeDef___10(v []AttributeRef) bool {
	return len(v) == 0
}

func enc_list_Ref_helios_gameplay_AttributeDef___10(b []byte, id uint32, v []AttributeRef) []byte {
	if len(v) == 0 {
		return b
	}
	b = appendTag(b, id, wireLen)
	b, mk := beginLen(b)
	for _, e := range v {
		b = encv_Ref_helios_gameplay_AttributeDef__13(b, e)
	}
	return endLen(b, mk)
}

func dec_list_Ref_helios_gameplay_AttributeDef___10(r *wireReader, wt int, v *[]AttributeRef) error {
	if wt == wireLen {
		p, err := r.lenBytes()
		if err != nil {
			return err
		}
		sub := &wireReader{data: p, depth: r.depth}
		for !sub.atEnd() {
			e := zero_Ref_helios_gameplay_AttributeDef__13()
			if err := decv_Ref_helios_gameplay_AttributeDef__13(sub, wireI64, &e); err != nil {
				return err
			}
			*v = append(*v, e)
		}
		return nil
	}
	e := zero_Ref_helios_gameplay_AttributeDef__13()
	if err := decv_Ref_helios_gameplay_AttributeDef__13(r, wt, &e); err != nil {
		return err
	}
	*v = append(*v, e)
	return nil
}

func zero_TagQuery__11() *TagQuery { return (*TagQuery)(nil) }

func def_TagQuery__11(v *TagQuery) bool {
	return v == nil
}

func enc_TagQuery__11(b []byte, id uint32, v *TagQuery) []byte {
	if v == nil {
		return b
	}
	return enc_TagQuery_41(b, id, *v)
}

func dec_TagQuery__11(r *wireReader, wt int, v **TagQuery) error {
	if *v == nil {
		x := zero_TagQuery_41()
		*v = &x
	}
	return dec_TagQuery_41(r, wt, *v)
}

func zero_helios_gameplay_ModDomain_12() ModDomain { return ModDomainSelf }

func def_helios_gameplay_ModDomain_12(v ModDomain) bool {
	return v == ModDomainSelf
}

func encv_helios_gameplay_ModDomain_12(b []byte, v ModDomain) []byte {
	return appendVarint(b, uint64(v))
}

func decv_helios_gameplay_ModDomain_12(r *wireReader, wt int, v *ModDomain) error {
	x, err := readUnsigned(r, wt, math.MaxUint8)
	*v = ModDomain(x)
	return err
}

func enc_helios_gameplay_ModDomain_12(b []byte, id uint32, v ModDomain) []byte {
	b = appendTag(b, id, wireVarint)
	return encv_helios_gameplay_ModDomain_12(b, v)
}

func dec_helios_gameplay_ModDomain_12(r *wireReader, wt int, v *ModDomain) error {
	return decv_helios_gameplay_ModDomain_12(r, wt, v)
}

func zero_Ref_helios_gameplay_AttributeDef__13() AttributeRef { return AttributeRef(0) }

func def_Ref_helios_gameplay_AttributeDef__13(v AttributeRef) bool {
	return v == 0
}

func encv_Ref_helios_gameplay_AttributeDef__13(b []byte, v AttributeRef) []byte {
	return appendFixed64(b, uint64(v))
}

func decv_Ref_helios_gameplay_AttributeDef__13(r *wireReader, wt int, v *AttributeRef) error {
	x, err := readFixed64Field(r, wt, "record reference")
	*v = AttributeRef(x)
	return err
}

func enc_Ref_helios_gameplay_AttributeDef__13(b []byte, id uint32, v AttributeRef) []byte {
	b = appendTag(b, id, wireI64)
	return encv_Ref_helios_gameplay_AttributeDef__13(b, v)
}

func dec_Ref_helios_gameplay_AttributeDef__13(r *wireReader, wt int, v *AttributeRef) error {
	return decv_Ref_helios_gameplay_AttributeDef__13(r, wt, v)
}

func zero_helios_gameplay_ModOp_14() ModOp { return ModOpPreAssign }

func def_helios_gameplay_ModOp_14(v ModOp) bool {
	return v == ModOpPreAssign
}

func encv_helios_gameplay_ModOp_14(b []byte, v ModOp) []byte {
	return appendVarint(b, uint64(v))
}

func decv_helios_gameplay_ModOp_14(r *wireReader, wt int, v *ModOp) error {
	x, err := readUnsigned(r, wt, math.MaxUint8)
	*v = ModOp(x)
	return err
}

func enc_helios_gameplay_ModOp_14(b []byte, id uint32, v ModOp) []byte {
	b = appendTag(b, id, wireVarint)
	return encv_helios_gameplay_ModOp_14(b, v)
}

func dec_helios_gameplay_ModOp_14(r *wireReader, wt int, v *ModOp) error {
	return decv_helios_gameplay_ModOp_14(r, wt, v)
}

func zero_helios_gameplay_Magnitude_15() Magnitude { return NewMagnitude() }

func def_helios_gameplay_Magnitude_15(v Magnitude) bool {
	return v.isDefault()
}

func encv_helios_gameplay_Magnitude_15(b []byte, v Magnitude) []byte {
	return v.appendValue(b)
}

func decv_helios_gameplay_Magnitude_15(r *wireReader, wt int, v *Magnitude) error {
	return v.readValue(r, wt)
}

func enc_helios_gameplay_Magnitude_15(b []byte, id uint32, v Magnitude) []byte {
	b = appendTag(b, id, wireLen)
	return encv_helios_gameplay_Magnitude_15(b, v)
}

func dec_helios_gameplay_Magnitude_15(r *wireReader, wt int, v *Magnitude) error {
	return decv_helios_gameplay_Magnitude_15(r, wt, v)
}

func zero_i32_16() int32 { return int32(0) }

func def_i32_16(v int32) bool {
	return v == 0
}

func encv_i32_16(b []byte, v int32) []byte {
	return appendZigzag(b, int64(v))
}

func decv_i32_16(r *wireReader, wt int, v *int32) error {
	x, err := readSigned(r, wt, math.MinInt32, math.MaxInt32)
	*v = int32(x)
	return err
}

func enc_i32_16(b []byte, id uint32, v int32) []byte {
	b = appendTag(b, id, wireVarint)
	return encv_i32_16(b, v)
}

func dec_i32_16(r *wireReader, wt int, v *int32) error {
	return decv_i32_16(r, wt, v)
}

func zero_u16_17() uint16 { return uint16(0) }

func def_u16_17(v uint16) bool {
	return v == 0
}

func encv_u16_17(b []byte, v uint16) []byte {
	return appendVarint(b, uint64(v))
}

func decv_u16_17(r *wireReader, wt int, v *uint16) error {
	x, err := readUnsigned(r, wt, math.MaxUint16)
	*v = uint16(x)
	return err
}

func enc_u16_17(b []byte, id uint32, v uint16) []byte {
	b = appendTag(b, id, wireVarint)
	return encv_u16_17(b, v)
}

func dec_u16_17(r *wireReader, wt int, v *uint16) error {
	return decv_u16_17(r, wt, v)
}

func zero_helios_gameplay_ModifierTarget_18() ModifierTarget { return NewModifierTarget() }

func def_helios_gameplay_ModifierTarget_18(v ModifierTarget) bool {
	return v.isDefault()
}

func encv_helios_gameplay_ModifierTarget_18(b []byte, v ModifierTarget) []byte {
	b, mk := beginLen(b)
	b = v.appendFields(b)
	return endLen(b, mk)
}

func decv_helios_gameplay_ModifierTarget_18(r *wireReader, wt int, v *ModifierTarget) error {
	if wt != wireLen {
		return wireMismatch("ModifierTarget", wt, wireLen)
	}
	sub, err := r.message()
	if err != nil {
		return err
	}
	return v.readFields(sub)
}

func enc_helios_gameplay_ModifierTarget_18(b []byte, id uint32, v ModifierTarget) []byte {
	b = appendTag(b, id, wireLen)
	return encv_helios_gameplay_ModifierTarget_18(b, v)
}

func dec_helios_gameplay_ModifierTarget_18(r *wireReader, wt int, v *ModifierTarget) error {
	return decv_helios_gameplay_ModifierTarget_18(r, wt, v)
}

func zero_helios_gameplay_AttrOrConst_Const_19() AttrOrConstConst { return NewAttrOrConstConst() }

func def_helios_gameplay_AttrOrConst_Const_19(v AttrOrConstConst) bool {
	return v.isDefault()
}

func encv_helios_gameplay_AttrOrConst_Const_19(b []byte, v AttrOrConstConst) []byte {
	b, mk := beginLen(b)
	b = v.appendFields(b)
	return endLen(b, mk)
}

func decv_helios_gameplay_AttrOrConst_Const_19(r *wireReader, wt int, v *AttrOrConstConst) error {
	if wt != wireLen {
		return wireMismatch("Const", wt, wireLen)
	}
	sub, err := r.message()
	if err != nil {
		return err
	}
	return v.readFields(sub)
}

func enc_helios_gameplay_AttrOrConst_Const_19(b []byte, id uint32, v AttrOrConstConst) []byte {
	b = appendTag(b, id, wireLen)
	return encv_helios_gameplay_AttrOrConst_Const_19(b, v)
}

func dec_helios_gameplay_AttrOrConst_Const_19(r *wireReader, wt int, v *AttrOrConstConst) error {
	return decv_helios_gameplay_AttrOrConst_Const_19(r, wt, v)
}

func zero_helios_gameplay_AttrOrConst_Attr_20() AttrOrConstAttr { return NewAttrOrConstAttr() }

func def_helios_gameplay_AttrOrConst_Attr_20(v AttrOrConstAttr) bool {
	return v.isDefault()
}

func encv_helios_gameplay_AttrOrConst_Attr_20(b []byte, v AttrOrConstAttr) []byte {
	b, mk := beginLen(b)
	b = v.appendFields(b)
	return endLen(b, mk)
}

func decv_helios_gameplay_AttrOrConst_Attr_20(r *wireReader, wt int, v *AttrOrConstAttr) error {
	if wt != wireLen {
		return wireMismatch("Attr", wt, wireLen)
	}
	sub, err := r.message()
	if err != nil {
		return err
	}
	return v.readFields(sub)
}

func enc_helios_gameplay_AttrOrConst_Attr_20(b []byte, id uint32, v AttrOrConstAttr) []byte {
	b = appendTag(b, id, wireLen)
	return encv_helios_gameplay_AttrOrConst_Attr_20(b, v)
}

func dec_helios_gameplay_AttrOrConst_Attr_20(r *wireReader, wt int, v *AttrOrConstAttr) error {
	return decv_helios_gameplay_AttrOrConst_Attr_20(r, wt, v)
}

func zero_helios_gameplay_MagnitudeInput_21() MagnitudeInput { return MagnitudeInputLevel }

func def_helios_gameplay_MagnitudeInput_21(v MagnitudeInput) bool {
	return v == MagnitudeInputLevel
}

func encv_helios_gameplay_MagnitudeInput_21(b []byte, v MagnitudeInput) []byte {
	return appendVarint(b, uint64(v))
}

func decv_helios_gameplay_MagnitudeInput_21(r *wireReader, wt int, v *MagnitudeInput) error {
	x, err := readUnsigned(r, wt, math.MaxUint8)
	*v = MagnitudeInput(x)
	return err
}

func enc_helios_gameplay_MagnitudeInput_21(b []byte, id uint32, v MagnitudeInput) []byte {
	b = appendTag(b, id, wireVarint)
	return encv_helios_gameplay_MagnitudeInput_21(b, v)
}

func dec_helios_gameplay_MagnitudeInput_21(r *wireReader, wt int, v *MagnitudeInput) error {
	return decv_helios_gameplay_MagnitudeInput_21(r, wt, v)
}

func zero_helios_gameplay_MagnitudeSource_22() MagnitudeSource { return MagnitudeSourceSource }

func def_helios_gameplay_MagnitudeSource_22(v MagnitudeSource) bool {
	return v == MagnitudeSourceSource
}

func encv_helios_gameplay_MagnitudeSource_22(b []byte, v MagnitudeSource) []byte {
	return appendVarint(b, uint64(v))
}

func decv_helios_gameplay_MagnitudeSource_22(r *wireReader, wt int, v *MagnitudeSource) error {
	x, err := readUnsigned(r, wt, math.MaxUint8)
	*v = MagnitudeSource(x)
	return err
}

func enc_helios_gameplay_MagnitudeSource_22(b []byte, id uint32, v MagnitudeSource) []byte {
	b = appendTag(b, id, wireVarint)
	return encv_helios_gameplay_MagnitudeSource_22(b, v)
}

func dec_helios_gameplay_MagnitudeSource_22(r *wireReader, wt int, v *MagnitudeSource) error {
	return decv_helios_gameplay_MagnitudeSource_22(r, wt, v)
}

func zero_helios_gameplay_CaptureMode_23() CaptureMode { return CaptureModeSnapshot }

func def_helios_gameplay_CaptureMode_23(v CaptureMode) bool {
	return v == CaptureModeSnapshot
}

func encv_helios_gameplay_CaptureMode_23(b []byte, v CaptureMode) []byte {
	return appendVarint(b, uint64(v))
}

func decv_helios_gameplay_CaptureMode_23(r *wireReader, wt int, v *CaptureMode) error {
	x, err := readUnsigned(r, wt, math.MaxUint8)
	*v = CaptureMode(x)
	return err
}

func enc_helios_gameplay_CaptureMode_23(b []byte, id uint32, v CaptureMode) []byte {
	b = appendTag(b, id, wireVarint)
	return encv_helios_gameplay_CaptureMode_23(b, v)
}

func dec_helios_gameplay_CaptureMode_23(r *wireReader, wt int, v *CaptureMode) error {
	return decv_helios_gameplay_CaptureMode_23(r, wt, v)
}

func zero_HxlExpr_24() HxlExpr { return "" }

func def_HxlExpr_24(v HxlExpr) bool {
	return v == ""
}

func encv_HxlExpr_24(b []byte, v HxlExpr) []byte {
	return appendString(b, v)
}

func decv_HxlExpr_24(r *wireReader, wt int, v *HxlExpr) error {
	x, err := readStringField(r, wt)
	*v = x
	return err
}

func enc_HxlExpr_24(b []byte, id uint32, v HxlExpr) []byte {
	b = appendTag(b, id, wireLen)
	return encv_HxlExpr_24(b, v)
}

func dec_HxlExpr_24(r *wireReader, wt int, v *HxlExpr) error {
	return decv_HxlExpr_24(r, wt, v)
}

func zero_helios_gameplay_Magnitude_Const_25() MagnitudeConst { return NewMagnitudeConst() }

func def_helios_gameplay_Magnitude_Const_25(v MagnitudeConst) bool {
	return v.isDefault()
}

func encv_helios_gameplay_Magnitude_Const_25(b []byte, v MagnitudeConst) []byte {
	b, mk := beginLen(b)
	b = v.appendFields(b)
	return endLen(b, mk)
}

func decv_helios_gameplay_Magnitude_Const_25(r *wireReader, wt int, v *MagnitudeConst) error {
	if wt != wireLen {
		return wireMismatch("Const", wt, wireLen)
	}
	sub, err := r.message()
	if err != nil {
		return err
	}
	return v.readFields(sub)
}

func enc_helios_gameplay_Magnitude_Const_25(b []byte, id uint32, v MagnitudeConst) []byte {
	b = appendTag(b, id, wireLen)
	return encv_helios_gameplay_Magnitude_Const_25(b, v)
}

func dec_helios_gameplay_Magnitude_Const_25(r *wireReader, wt int, v *MagnitudeConst) error {
	return decv_helios_gameplay_Magnitude_Const_25(r, wt, v)
}

func zero_helios_gameplay_Magnitude_Curve_26() MagnitudeCurve { return NewMagnitudeCurve() }

func def_helios_gameplay_Magnitude_Curve_26(v MagnitudeCurve) bool {
	return v.isDefault()
}

func encv_helios_gameplay_Magnitude_Curve_26(b []byte, v MagnitudeCurve) []byte {
	b, mk := beginLen(b)
	b = v.appendFields(b)
	return endLen(b, mk)
}

func decv_helios_gameplay_Magnitude_Curve_26(r *wireReader, wt int, v *MagnitudeCurve) error {
	if wt != wireLen {
		return wireMismatch("Curve", wt, wireLen)
	}
	sub, err := r.message()
	if err != nil {
		return err
	}
	return v.readFields(sub)
}

func enc_helios_gameplay_Magnitude_Curve_26(b []byte, id uint32, v MagnitudeCurve) []byte {
	b = appendTag(b, id, wireLen)
	return encv_helios_gameplay_Magnitude_Curve_26(b, v)
}

func dec_helios_gameplay_Magnitude_Curve_26(r *wireReader, wt int, v *MagnitudeCurve) error {
	return decv_helios_gameplay_Magnitude_Curve_26(r, wt, v)
}

func zero_helios_gameplay_Magnitude_Attr_27() MagnitudeAttr { return NewMagnitudeAttr() }

func def_helios_gameplay_Magnitude_Attr_27(v MagnitudeAttr) bool {
	return v.isDefault()
}

func encv_helios_gameplay_Magnitude_Attr_27(b []byte, v MagnitudeAttr) []byte {
	b, mk := beginLen(b)
	b = v.appendFields(b)
	return endLen(b, mk)
}

func decv_helios_gameplay_Magnitude_Attr_27(r *wireReader, wt int, v *MagnitudeAttr) error {
	if wt != wireLen {
		return wireMismatch("Attr", wt, wireLen)
	}
	sub, err := r.message()
	if err != nil {
		return err
	}
	return v.readFields(sub)
}

func enc_helios_gameplay_Magnitude_Attr_27(b []byte, id uint32, v MagnitudeAttr) []byte {
	b = appendTag(b, id, wireLen)
	return encv_helios_gameplay_Magnitude_Attr_27(b, v)
}

func dec_helios_gameplay_Magnitude_Attr_27(r *wireReader, wt int, v *MagnitudeAttr) error {
	return decv_helios_gameplay_Magnitude_Attr_27(r, wt, v)
}

func zero_helios_gameplay_Magnitude_Hxl_28() MagnitudeHxl { return NewMagnitudeHxl() }

func def_helios_gameplay_Magnitude_Hxl_28(v MagnitudeHxl) bool {
	return v.isDefault()
}

func encv_helios_gameplay_Magnitude_Hxl_28(b []byte, v MagnitudeHxl) []byte {
	b, mk := beginLen(b)
	b = v.appendFields(b)
	return endLen(b, mk)
}

func decv_helios_gameplay_Magnitude_Hxl_28(r *wireReader, wt int, v *MagnitudeHxl) error {
	if wt != wireLen {
		return wireMismatch("Hxl", wt, wireLen)
	}
	sub, err := r.message()
	if err != nil {
		return err
	}
	return v.readFields(sub)
}

func enc_helios_gameplay_Magnitude_Hxl_28(b []byte, id uint32, v MagnitudeHxl) []byte {
	b = appendTag(b, id, wireLen)
	return encv_helios_gameplay_Magnitude_Hxl_28(b, v)
}

func dec_helios_gameplay_Magnitude_Hxl_28(r *wireReader, wt int, v *MagnitudeHxl) error {
	return decv_helios_gameplay_Magnitude_Hxl_28(r, wt, v)
}

func zero_helios_gameplay_CueEvent_29() CueEvent { return CueEventExecute }

func def_helios_gameplay_CueEvent_29(v CueEvent) bool {
	return v == CueEventExecute
}

func encv_helios_gameplay_CueEvent_29(b []byte, v CueEvent) []byte {
	return appendVarint(b, uint64(v))
}

func decv_helios_gameplay_CueEvent_29(r *wireReader, wt int, v *CueEvent) error {
	x, err := readUnsigned(r, wt, math.MaxUint8)
	*v = CueEvent(x)
	return err
}

func enc_helios_gameplay_CueEvent_29(b []byte, id uint32, v CueEvent) []byte {
	b = appendTag(b, id, wireVarint)
	return encv_helios_gameplay_CueEvent_29(b, v)
}

func dec_helios_gameplay_CueEvent_29(r *wireReader, wt int, v *CueEvent) error {
	return decv_helios_gameplay_CueEvent_29(r, wt, v)
}

func zero_Ref_helios_gameplay_EffectDef___30() *EffectRef { return (*EffectRef)(nil) }

func def_Ref_helios_gameplay_EffectDef___30(v *EffectRef) bool {
	return v == nil
}

func enc_Ref_helios_gameplay_EffectDef___30(b []byte, id uint32, v *EffectRef) []byte {
	if v == nil {
		return b
	}
	return enc_Ref_helios_gameplay_EffectDef__85(b, id, *v)
}

func dec_Ref_helios_gameplay_EffectDef___30(r *wireReader, wt int, v **EffectRef) error {
	if *v == nil {
		x := zero_Ref_helios_gameplay_EffectDef__85()
		*v = &x
	}
	return dec_Ref_helios_gameplay_EffectDef__85(r, wt, *v)
}

func zero_helios_gameplay_StackingPolicy_31() StackingPolicy { return StackingPolicyNone }

func def_helios_gameplay_StackingPolicy_31(v StackingPolicy) bool {
	return v == StackingPolicyNone
}

func encv_helios_gameplay_StackingPolicy_31(b []byte, v StackingPolicy) []byte {
	return appendVarint(b, uint64(v))
}

func decv_helios_gameplay_StackingPolicy_31(r *wireReader, wt int, v *StackingPolicy) error {
	x, err := readUnsigned(r, wt, math.MaxUint8)
	*v = StackingPolicy(x)
	return err
}

func enc_helios_gameplay_StackingPolicy_31(b []byte, id uint32, v StackingPolicy) []byte {
	b = appendTag(b, id, wireVarint)
	return encv_helios_gameplay_StackingPolicy_31(b, v)
}

func dec_helios_gameplay_StackingPolicy_31(r *wireReader, wt int, v *StackingPolicy) error {
	return decv_helios_gameplay_StackingPolicy_31(r, wt, v)
}

func zero_helios_gameplay_StackExpiry_32() StackExpiry { return StackExpiryClearAll }

func def_helios_gameplay_StackExpiry_32(v StackExpiry) bool {
	return v == StackExpiryClearAll
}

func encv_helios_gameplay_StackExpiry_32(b []byte, v StackExpiry) []byte {
	return appendVarint(b, uint64(v))
}

func decv_helios_gameplay_StackExpiry_32(r *wireReader, wt int, v *StackExpiry) error {
	x, err := readUnsigned(r, wt, math.MaxUint8)
	*v = StackExpiry(x)
	return err
}

func enc_helios_gameplay_StackExpiry_32(b []byte, id uint32, v StackExpiry) []byte {
	b = appendTag(b, id, wireVarint)
	return encv_helios_gameplay_StackExpiry_32(b, v)
}

func dec_helios_gameplay_StackExpiry_32(r *wireReader, wt int, v *StackExpiry) error {
	return decv_helios_gameplay_StackExpiry_32(r, wt, v)
}

func zero_helios_gameplay_StackKeep_33() StackKeep { return StackKeepNewest }

func def_helios_gameplay_StackKeep_33(v StackKeep) bool {
	return v == StackKeepNewest
}

func encv_helios_gameplay_StackKeep_33(b []byte, v StackKeep) []byte {
	return appendVarint(b, uint64(v))
}

func decv_helios_gameplay_StackKeep_33(r *wireReader, wt int, v *StackKeep) error {
	x, err := readUnsigned(r, wt, math.MaxUint8)
	*v = StackKeep(x)
	return err
}

func enc_helios_gameplay_StackKeep_33(b []byte, id uint32, v StackKeep) []byte {
	b = appendTag(b, id, wireVarint)
	return encv_helios_gameplay_StackKeep_33(b, v)
}

func dec_helios_gameplay_StackKeep_33(r *wireReader, wt int, v *StackKeep) error {
	return decv_helios_gameplay_StackKeep_33(r, wt, v)
}

func zero_helios_gameplay_Magnitude__34() *Magnitude { return (*Magnitude)(nil) }

func def_helios_gameplay_Magnitude__34(v *Magnitude) bool {
	return v == nil
}

func enc_helios_gameplay_Magnitude__34(b []byte, id uint32, v *Magnitude) []byte {
	if v == nil {
		return b
	}
	return enc_helios_gameplay_Magnitude_15(b, id, *v)
}

func dec_helios_gameplay_Magnitude__34(r *wireReader, wt int, v **Magnitude) error {
	if *v == nil {
		x := zero_helios_gameplay_Magnitude_15()
		*v = &x
	}
	return dec_helios_gameplay_Magnitude_15(r, wt, *v)
}

func zero_lios_gameplay_EffectDef_Duration_Instant_35() EffectDefDurationInstant { return NewEffectDefDurationInstant() }

func def_lios_gameplay_EffectDef_Duration_Instant_35(v EffectDefDurationInstant) bool {
	return v.isDefault()
}

func encv_lios_gameplay_EffectDef_Duration_Instant_35(b []byte, v EffectDefDurationInstant) []byte {
	b, mk := beginLen(b)
	b = v.appendFields(b)
	return endLen(b, mk)
}

func decv_lios_gameplay_EffectDef_Duration_Instant_35(r *wireReader, wt int, v *EffectDefDurationInstant) error {
	if wt != wireLen {
		return wireMismatch("Instant", wt, wireLen)
	}
	sub, err := r.message()
	if err != nil {
		return err
	}
	return v.readFields(sub)
}

func enc_lios_gameplay_EffectDef_Duration_Instant_35(b []byte, id uint32, v EffectDefDurationInstant) []byte {
	b = appendTag(b, id, wireLen)
	return encv_lios_gameplay_EffectDef_Duration_Instant_35(b, v)
}

func dec_lios_gameplay_EffectDef_Duration_Instant_35(r *wireReader, wt int, v *EffectDefDurationInstant) error {
	return decv_lios_gameplay_EffectDef_Duration_Instant_35(r, wt, v)
}

func zero_ios_gameplay_EffectDef_Duration_Duration_36() EffectDefDurationDuration { return NewEffectDefDurationDuration() }

func def_ios_gameplay_EffectDef_Duration_Duration_36(v EffectDefDurationDuration) bool {
	return v.isDefault()
}

func encv_ios_gameplay_EffectDef_Duration_Duration_36(b []byte, v EffectDefDurationDuration) []byte {
	b, mk := beginLen(b)
	b = v.appendFields(b)
	return endLen(b, mk)
}

func decv_ios_gameplay_EffectDef_Duration_Duration_36(r *wireReader, wt int, v *EffectDefDurationDuration) error {
	if wt != wireLen {
		return wireMismatch("Duration", wt, wireLen)
	}
	sub, err := r.message()
	if err != nil {
		return err
	}
	return v.readFields(sub)
}

func enc_ios_gameplay_EffectDef_Duration_Duration_36(b []byte, id uint32, v EffectDefDurationDuration) []byte {
	b = appendTag(b, id, wireLen)
	return encv_ios_gameplay_EffectDef_Duration_Duration_36(b, v)
}

func dec_ios_gameplay_EffectDef_Duration_Duration_36(r *wireReader, wt int, v *EffectDefDurationDuration) error {
	return decv_ios_gameplay_EffectDef_Duration_Duration_36(r, wt, v)
}

func zero_ios_gameplay_EffectDef_Duration_Infinite_37() EffectDefDurationInfinite { return NewEffectDefDurationInfinite() }

func def_ios_gameplay_EffectDef_Duration_Infinite_37(v EffectDefDurationInfinite) bool {
	return v.isDefault()
}

func encv_ios_gameplay_EffectDef_Duration_Infinite_37(b []byte, v EffectDefDurationInfinite) []byte {
	b, mk := beginLen(b)
	b = v.appendFields(b)
	return endLen(b, mk)
}

func decv_ios_gameplay_EffectDef_Duration_Infinite_37(r *wireReader, wt int, v *EffectDefDurationInfinite) error {
	if wt != wireLen {
		return wireMismatch("Infinite", wt, wireLen)
	}
	sub, err := r.message()
	if err != nil {
		return err
	}
	return v.readFields(sub)
}

func enc_ios_gameplay_EffectDef_Duration_Infinite_37(b []byte, id uint32, v EffectDefDurationInfinite) []byte {
	b = appendTag(b, id, wireLen)
	return encv_ios_gameplay_EffectDef_Duration_Infinite_37(b, v)
}

func dec_ios_gameplay_EffectDef_Duration_Infinite_37(r *wireReader, wt int, v *EffectDefDurationInfinite) error {
	return decv_ios_gameplay_EffectDef_Duration_Infinite_37(r, wt, v)
}

func zero_ios_gameplay_EffectDef_Duration_Periodic_38() EffectDefDurationPeriodic { return NewEffectDefDurationPeriodic() }

func def_ios_gameplay_EffectDef_Duration_Periodic_38(v EffectDefDurationPeriodic) bool {
	return v.isDefault()
}

func encv_ios_gameplay_EffectDef_Duration_Periodic_38(b []byte, v EffectDefDurationPeriodic) []byte {
	b, mk := beginLen(b)
	b = v.appendFields(b)
	return endLen(b, mk)
}

func decv_ios_gameplay_EffectDef_Duration_Periodic_38(r *wireReader, wt int, v *EffectDefDurationPeriodic) error {
	if wt != wireLen {
		return wireMismatch("Periodic", wt, wireLen)
	}
	sub, err := r.message()
	if err != nil {
		return err
	}
	return v.readFields(sub)
}

func enc_ios_gameplay_EffectDef_Duration_Periodic_38(b []byte, id uint32, v EffectDefDurationPeriodic) []byte {
	b = appendTag(b, id, wireLen)
	return encv_ios_gameplay_EffectDef_Duration_Periodic_38(b, v)
}

func dec_ios_gameplay_EffectDef_Duration_Periodic_38(r *wireReader, wt int, v *EffectDefDurationPeriodic) error {
	return decv_ios_gameplay_EffectDef_Duration_Periodic_38(r, wt, v)
}

func zero_helios_gameplay_EffectDef_Duration_39() EffectDefDuration { return NewEffectDefDuration() }

func def_helios_gameplay_EffectDef_Duration_39(v EffectDefDuration) bool {
	return v.isDefault()
}

func encv_helios_gameplay_EffectDef_Duration_39(b []byte, v EffectDefDuration) []byte {
	return v.appendValue(b)
}

func decv_helios_gameplay_EffectDef_Duration_39(r *wireReader, wt int, v *EffectDefDuration) error {
	return v.readValue(r, wt)
}

func enc_helios_gameplay_EffectDef_Duration_39(b []byte, id uint32, v EffectDefDuration) []byte {
	b = appendTag(b, id, wireLen)
	return encv_helios_gameplay_EffectDef_Duration_39(b, v)
}

func dec_helios_gameplay_EffectDef_Duration_39(r *wireReader, wt int, v *EffectDefDuration) error {
	return decv_helios_gameplay_EffectDef_Duration_39(r, wt, v)
}

func zero_TagSet_40() TagSet { return TagSet{} }

func def_TagSet_40(v TagSet) bool {
	return len(v) == 0
}

func encv_TagSet_40(b []byte, v TagSet) []byte {
	b, mk := beginLen(b)
	for _, tag := range sortedSet([]string(v)) { // canonical: sorted, unique (like refl::TagSet)
		b = appendTag(b, 1, wireLen)
		b = appendString(b, tag)
	}
	return endLen(b, mk)
}

func decv_TagSet_40(r *wireReader, wt int, v *TagSet) error {
	if wt != wireLen {
		return wireMismatch("TagSet", wt, wireLen)
	}
	sub, err := r.message()
	if err != nil {
		return err
	}
	for !sub.atEnd() {
		id, wt2, err := sub.tag()
		if err != nil {
			return err
		}
		if id == 1 && wt2 == wireLen {
			s, err := readStringField(sub, wt2)
			if err != nil {
				return err
			}
			*v = tagSetAdd(*v, s)
		} else if err := sub.skip(wt2); err != nil {
			return err
		}
	}
	return nil
}

func enc_TagSet_40(b []byte, id uint32, v TagSet) []byte {
	b = appendTag(b, id, wireLen)
	return encv_TagSet_40(b, v)
}

func dec_TagSet_40(r *wireReader, wt int, v *TagSet) error {
	return decv_TagSet_40(r, wt, v)
}

func zero_TagQuery_41() TagQuery { return "" }

func def_TagQuery_41(v TagQuery) bool {
	return v == ""
}

func encv_TagQuery_41(b []byte, v TagQuery) []byte {
	return appendString(b, v)
}

func decv_TagQuery_41(r *wireReader, wt int, v *TagQuery) error {
	x, err := readStringField(r, wt)
	*v = x
	return err
}

func enc_TagQuery_41(b []byte, id uint32, v TagQuery) []byte {
	b = appendTag(b, id, wireLen)
	return encv_TagQuery_41(b, v)
}

func dec_TagQuery_41(r *wireReader, wt int, v *TagQuery) error {
	return decv_TagQuery_41(r, wt, v)
}

func zero_helios_gameplay_EffectStacking_42() EffectStacking { return NewEffectStacking() }

func def_helios_gameplay_EffectStacking_42(v EffectStacking) bool {
	return v.isDefault()
}

func encv_helios_gameplay_EffectStacking_42(b []byte, v EffectStacking) []byte {
	b, mk := beginLen(b)
	b = v.appendFields(b)
	return endLen(b, mk)
}

func decv_helios_gameplay_EffectStacking_42(r *wireReader, wt int, v *EffectStacking) error {
	if wt != wireLen {
		return wireMismatch("EffectStacking", wt, wireLen)
	}
	sub, err := r.message()
	if err != nil {
		return err
	}
	return v.readFields(sub)
}

func enc_helios_gameplay_EffectStacking_42(b []byte, id uint32, v EffectStacking) []byte {
	b = appendTag(b, id, wireLen)
	return encv_helios_gameplay_EffectStacking_42(b, v)
}

func dec_helios_gameplay_EffectStacking_42(r *wireReader, wt int, v *EffectStacking) error {
	return decv_helios_gameplay_EffectStacking_42(r, wt, v)
}

func zero_list_helios_gameplay_ModifierDef__43() []ModifierDef { return ([]ModifierDef)(nil) }

func def_list_helios_gameplay_ModifierDef__43(v []ModifierDef) bool {
	return len(v) == 0
}

func enc_list_helios_gameplay_ModifierDef__43(b []byte, id uint32, v []ModifierDef) []byte {
	if len(v) == 0 {
		return b
	}
	for _, e := range v {
		b = appendTag(b, id, wireLen)
		b = encv_helios_gameplay_ModifierDef_86(b, e)
	}
	return b
}

func dec_list_helios_gameplay_ModifierDef__43(r *wireReader, wt int, v *[]ModifierDef) error {
	e := zero_helios_gameplay_ModifierDef_86()
	if err := decv_helios_gameplay_ModifierDef_86(r, wt, &e); err != nil {
		return err
	}
	*v = append(*v, e)
	return nil
}

func zero_list_helios_gameplay_ExecutionRef__44() []ExecutionRef { return ([]ExecutionRef)(nil) }

func def_list_helios_gameplay_ExecutionRef__44(v []ExecutionRef) bool {
	return len(v) == 0
}

func enc_list_helios_gameplay_ExecutionRef__44(b []byte, id uint32, v []ExecutionRef) []byte {
	if len(v) == 0 {
		return b
	}
	for _, e := range v {
		b = appendTag(b, id, wireLen)
		b = encv_helios_gameplay_ExecutionRef_87(b, e)
	}
	return b
}

func dec_list_helios_gameplay_ExecutionRef__44(r *wireReader, wt int, v *[]ExecutionRef) error {
	e := zero_helios_gameplay_ExecutionRef_87()
	if err := decv_helios_gameplay_ExecutionRef_87(r, wt, &e); err != nil {
		return err
	}
	*v = append(*v, e)
	return nil
}

func zero_list_Name__45() []string { return ([]string)(nil) }

func def_list_Name__45(v []string) bool {
	return len(v) == 0
}

func enc_list_Name__45(b []byte, id uint32, v []string) []byte {
	if len(v) == 0 {
		return b
	}
	for _, e := range v {
		b = appendTag(b, id, wireLen)
		b = encv_Name_0(b, e)
	}
	return b
}

func dec_list_Name__45(r *wireReader, wt int, v *[]string) error {
	e := zero_Name_0()
	if err := decv_Name_0(r, wt, &e); err != nil {
		return err
	}
	*v = append(*v, e)
	return nil
}

func zero_list_helios_gameplay_CueBinding__46() []CueBinding { return ([]CueBinding)(nil) }

func def_list_helios_gameplay_CueBinding__46(v []CueBinding) bool {
	return len(v) == 0
}

func enc_list_helios_gameplay_CueBinding__46(b []byte, id uint32, v []CueBinding) []byte {
	if len(v) == 0 {
		return b
	}
	for _, e := range v {
		b = appendTag(b, id, wireLen)
		b = encv_helios_gameplay_CueBinding_88(b, e)
	}
	return b
}

func dec_list_helios_gameplay_CueBinding__46(r *wireReader, wt int, v *[]CueBinding) error {
	e := zero_helios_gameplay_CueBinding_88()
	if err := decv_helios_gameplay_CueBinding_88(r, wt, &e); err != nil {
		return err
	}
	*v = append(*v, e)
	return nil
}

func zero_helios_gameplay_EffectClock_47() EffectClock { return EffectClockZone }

func def_helios_gameplay_EffectClock_47(v EffectClock) bool {
	return v == EffectClockZone
}

func encv_helios_gameplay_EffectClock_47(b []byte, v EffectClock) []byte {
	return appendVarint(b, uint64(v))
}

func decv_helios_gameplay_EffectClock_47(r *wireReader, wt int, v *EffectClock) error {
	x, err := readUnsigned(r, wt, math.MaxUint8)
	*v = EffectClock(x)
	return err
}

func enc_helios_gameplay_EffectClock_47(b []byte, id uint32, v EffectClock) []byte {
	b = appendTag(b, id, wireVarint)
	return encv_helios_gameplay_EffectClock_47(b, v)
}

func dec_helios_gameplay_EffectClock_47(r *wireReader, wt int, v *EffectClock) error {
	return decv_helios_gameplay_EffectClock_47(r, wt, v)
}

func zero_helios_gameplay_ExecutionRef_Native_48() ExecutionRefNative { return NewExecutionRefNative() }

func def_helios_gameplay_ExecutionRef_Native_48(v ExecutionRefNative) bool {
	return v.isDefault()
}

func encv_helios_gameplay_ExecutionRef_Native_48(b []byte, v ExecutionRefNative) []byte {
	b, mk := beginLen(b)
	b = v.appendFields(b)
	return endLen(b, mk)
}

func decv_helios_gameplay_ExecutionRef_Native_48(r *wireReader, wt int, v *ExecutionRefNative) error {
	if wt != wireLen {
		return wireMismatch("Native", wt, wireLen)
	}
	sub, err := r.message()
	if err != nil {
		return err
	}
	return v.readFields(sub)
}

func enc_helios_gameplay_ExecutionRef_Native_48(b []byte, id uint32, v ExecutionRefNative) []byte {
	b = appendTag(b, id, wireLen)
	return encv_helios_gameplay_ExecutionRef_Native_48(b, v)
}

func dec_helios_gameplay_ExecutionRef_Native_48(r *wireReader, wt int, v *ExecutionRefNative) error {
	return decv_helios_gameplay_ExecutionRef_Native_48(r, wt, v)
}

func zero_helios_gameplay_ExecutionRef_Hxl_49() ExecutionRefHxl { return NewExecutionRefHxl() }

func def_helios_gameplay_ExecutionRef_Hxl_49(v ExecutionRefHxl) bool {
	return v.isDefault()
}

func encv_helios_gameplay_ExecutionRef_Hxl_49(b []byte, v ExecutionRefHxl) []byte {
	b, mk := beginLen(b)
	b = v.appendFields(b)
	return endLen(b, mk)
}

func decv_helios_gameplay_ExecutionRef_Hxl_49(r *wireReader, wt int, v *ExecutionRefHxl) error {
	if wt != wireLen {
		return wireMismatch("Hxl", wt, wireLen)
	}
	sub, err := r.message()
	if err != nil {
		return err
	}
	return v.readFields(sub)
}

func enc_helios_gameplay_ExecutionRef_Hxl_49(b []byte, id uint32, v ExecutionRefHxl) []byte {
	b = appendTag(b, id, wireLen)
	return encv_helios_gameplay_ExecutionRef_Hxl_49(b, v)
}

func dec_helios_gameplay_ExecutionRef_Hxl_49(r *wireReader, wt int, v *ExecutionRefHxl) error {
	return decv_helios_gameplay_ExecutionRef_Hxl_49(r, wt, v)
}

func zero_Ref_helios_gameplay_ItemDef___50() *ItemRef { return (*ItemRef)(nil) }

func def_Ref_helios_gameplay_ItemDef___50(v *ItemRef) bool {
	return v == nil
}

func enc_Ref_helios_gameplay_ItemDef___50(b []byte, id uint32, v *ItemRef) []byte {
	if v == nil {
		return b
	}
	return enc_Ref_helios_gameplay_ItemDef__76(b, id, *v)
}

func dec_Ref_helios_gameplay_ItemDef___50(r *wireReader, wt int, v **ItemRef) error {
	if *v == nil {
		x := zero_Ref_helios_gameplay_ItemDef__76()
		*v = &x
	}
	return dec_Ref_helios_gameplay_ItemDef__76(r, wt, *v)
}

func zero_list_helios_gameplay_AttrMinimum__51() []AttrMinimum { return ([]AttrMinimum)(nil) }

func def_list_helios_gameplay_AttrMinimum__51(v []AttrMinimum) bool {
	return len(v) == 0
}

func enc_list_helios_gameplay_AttrMinimum__51(b []byte, id uint32, v []AttrMinimum) []byte {
	if len(v) == 0 {
		return b
	}
	for _, e := range v {
		b = appendTag(b, id, wireLen)
		b = encv_helios_gameplay_AttrMinimum_89(b, e)
	}
	return b
}

func dec_list_helios_gameplay_AttrMinimum__51(r *wireReader, wt int, v *[]AttrMinimum) error {
	e := zero_helios_gameplay_AttrMinimum_89()
	if err := decv_helios_gameplay_AttrMinimum_89(r, wt, &e); err != nil {
		return err
	}
	*v = append(*v, e)
	return nil
}

func zero_f32_52() float32 { return float32(0) }

func def_f32_52(v float32) bool {
	return math.Float32bits(v) == 0
}

func encv_f32_52(b []byte, v float32) []byte {
	return appendF32(b, v)
}

func decv_f32_52(r *wireReader, wt int, v *float32) error {
	x, err := readF32(r, wt)
	*v = x
	return err
}

func enc_f32_52(b []byte, id uint32, v float32) []byte {
	b = appendTag(b, id, wireI32)
	return encv_f32_52(b, v)
}

func dec_f32_52(r *wireReader, wt int, v *float32) error {
	return decv_f32_52(r, wt, v)
}

func zero_u32_53() uint32 { return uint32(0) }

func def_u32_53(v uint32) bool {
	return v == 0
}

func encv_u32_53(b []byte, v uint32) []byte {
	return appendVarint(b, uint64(v))
}

func decv_u32_53(r *wireReader, wt int, v *uint32) error {
	x, err := readUnsigned(r, wt, math.MaxUint32)
	*v = uint32(x)
	return err
}

func enc_u32_53(b []byte, id uint32, v uint32) []byte {
	b = appendTag(b, id, wireVarint)
	return encv_u32_53(b, v)
}

func dec_u32_53(r *wireReader, wt int, v *uint32) error {
	return decv_u32_53(r, wt, v)
}

func zero_list_helios_gameplay_SlotDescriptor__54() []SlotDescriptor { return ([]SlotDescriptor)(nil) }

func def_list_helios_gameplay_SlotDescriptor__54(v []SlotDescriptor) bool {
	return len(v) == 0
}

func enc_list_helios_gameplay_SlotDescriptor__54(b []byte, id uint32, v []SlotDescriptor) []byte {
	if len(v) == 0 {
		return b
	}
	for _, e := range v {
		b = appendTag(b, id, wireLen)
		b = encv_helios_gameplay_SlotDescriptor_90(b, e)
	}
	return b
}

func dec_list_helios_gameplay_SlotDescriptor__54(r *wireReader, wt int, v *[]SlotDescriptor) error {
	e := zero_helios_gameplay_SlotDescriptor_90()
	if err := decv_helios_gameplay_SlotDescriptor_90(r, wt, &e); err != nil {
		return err
	}
	*v = append(*v, e)
	return nil
}

func zero_helios_gameplay_Requirement_55() Requirement { return NewRequirement() }

func def_helios_gameplay_Requirement_55(v Requirement) bool {
	return v.isDefault()
}

func encv_helios_gameplay_Requirement_55(b []byte, v Requirement) []byte {
	b, mk := beginLen(b)
	b = v.appendFields(b)
	return endLen(b, mk)
}

func decv_helios_gameplay_Requirement_55(r *wireReader, wt int, v *Requirement) error {
	if wt != wireLen {
		return wireMismatch("Requirement", wt, wireLen)
	}
	sub, err := r.message()
	if err != nil {
		return err
	}
	return v.readFields(sub)
}

func enc_helios_gameplay_Requirement_55(b []byte, id uint32, v Requirement) []byte {
	b = appendTag(b, id, wireLen)
	return encv_helios_gameplay_Requirement_55(b, v)
}

func dec_helios_gameplay_Requirement_55(r *wireReader, wt int, v *Requirement) error {
	return decv_helios_gameplay_Requirement_55(r, wt, v)
}

func zero_AssetRef_Prefab__56() AssetRef { return AssetRef{} }

func def_AssetRef_Prefab__56(v AssetRef) bool {
	return v == AssetRef{}
}

func encv_AssetRef_Prefab__56(b []byte, v AssetRef) []byte {
	return appendBytes(b, v[:])
}

func decv_AssetRef_Prefab__56(r *wireReader, wt int, v *AssetRef) error {
	x, err := readGuid(r, wt)
	*v = AssetRef(x)
	return err
}

func enc_AssetRef_Prefab__56(b []byte, id uint32, v AssetRef) []byte {
	b = appendTag(b, id, wireLen)
	return encv_AssetRef_Prefab__56(b, v)
}

func dec_AssetRef_Prefab__56(r *wireReader, wt int, v *AssetRef) error {
	return decv_AssetRef_Prefab__56(r, wt, v)
}

func zero_AssetRef_Texture__57() AssetRef { return AssetRef{} }

func def_AssetRef_Texture__57(v AssetRef) bool {
	return v == AssetRef{}
}

func encv_AssetRef_Texture__57(b []byte, v AssetRef) []byte {
	return appendBytes(b, v[:])
}

func decv_AssetRef_Texture__57(r *wireReader, wt int, v *AssetRef) error {
	x, err := readGuid(r, wt)
	*v = AssetRef(x)
	return err
}

func enc_AssetRef_Texture__57(b []byte, id uint32, v AssetRef) []byte {
	b = appendTag(b, id, wireLen)
	return encv_AssetRef_Texture__57(b, v)
}

func dec_AssetRef_Texture__57(r *wireReader, wt int, v *AssetRef) error {
	return decv_AssetRef_Texture__57(r, wt, v)
}

func zero_p_Ref_helios_gameplay_AttributeDef__f64__58() map[AttributeRef]float64 { return (map[AttributeRef]float64)(nil) }

func def_p_Ref_helios_gameplay_AttributeDef__f64__58(v map[AttributeRef]float64) bool {
	return len(v) == 0
}

func enc_p_Ref_helios_gameplay_AttributeDef__f64__58(b []byte, id uint32, v map[AttributeRef]float64) []byte {
	for _, k := range sortedKeys(v) {
		b = appendTag(b, id, wireLen)
		var mk int
		b, mk = beginLen(b)
		b = enc_Ref_helios_gameplay_AttributeDef__13(b, 1, k)
		b = enc_f64_2(b, 2, v[k])
		b = endLen(b, mk)
	}
	return b
}

func dec_p_Ref_helios_gameplay_AttributeDef__f64__58(r *wireReader, wt int, v *map[AttributeRef]float64) error {
	if wt != wireLen {
		return wireMismatch("map entry", wt, wireLen)
	}
	sub, err := r.message()
	if err != nil {
		return err
	}
	key := zero_Ref_helios_gameplay_AttributeDef__13()
	val := zero_f64_2()
	for !sub.atEnd() {
		fid, fwt, err := sub.tag()
		if err != nil {
			return err
		}
		switch fid {
			case 1:
				if err := dec_Ref_helios_gameplay_AttributeDef__13(sub, fwt, &key); err != nil {
					return err
				}
			case 2:
				if err := dec_f64_2(sub, fwt, &val); err != nil {
					return err
				}
			default:
				if err := sub.skip(fwt); err != nil {
					return err
				}
		}
	}
	if *v == nil {
		*v = map[AttributeRef]float64{}
	}
	(*v)[key] = val
	return nil
}

func zero_te_list_Ref_helios_gameplay_EffectDef____59() map[ItemState][]EffectRef { return (map[ItemState][]EffectRef)(nil) }

func def_te_list_Ref_helios_gameplay_EffectDef____59(v map[ItemState][]EffectRef) bool {
	return len(v) == 0
}

func enc_te_list_Ref_helios_gameplay_EffectDef____59(b []byte, id uint32, v map[ItemState][]EffectRef) []byte {
	for _, k := range sortedKeys(v) {
		b = appendTag(b, id, wireLen)
		var mk int
		b, mk = beginLen(b)
		b = enc_helios_gameplay_ItemState_91(b, 1, k)
		b = enc_list_Ref_helios_gameplay_EffectDef___92(b, 2, v[k])
		b = endLen(b, mk)
	}
	return b
}

func dec_te_list_Ref_helios_gameplay_EffectDef____59(r *wireReader, wt int, v *map[ItemState][]EffectRef) error {
	if wt != wireLen {
		return wireMismatch("map entry", wt, wireLen)
	}
	sub, err := r.message()
	if err != nil {
		return err
	}
	key := zero_helios_gameplay_ItemState_91()
	val := zero_list_Ref_helios_gameplay_EffectDef___92()
	for !sub.atEnd() {
		fid, fwt, err := sub.tag()
		if err != nil {
			return err
		}
		switch fid {
			case 1:
				if err := dec_helios_gameplay_ItemState_91(sub, fwt, &key); err != nil {
					return err
				}
			case 2:
				if err := dec_list_Ref_helios_gameplay_EffectDef___92(sub, fwt, &val); err != nil {
					return err
				}
			default:
				if err := sub.skip(fwt); err != nil {
					return err
				}
		}
	}
	if *v == nil {
		*v = map[ItemState][]EffectRef{}
	}
	(*v)[key] = val
	return nil
}

func zero_list_list_Name___60() [][]string { return ([][]string)(nil) }

func def_list_list_Name___60(v [][]string) bool {
	return len(v) == 0
}

func enc_list_list_Name___60(b []byte, id uint32, v [][]string) []byte {
	if len(v) == 0 {
		return b
	}
	for _, e := range v {
		b = appendTag(b, id, wireLen)
		{ var mk int; b, mk = beginLen(b); b = enc_list_Name__45(b, 1, e); b = endLen(b, mk) }
	}
	return b
}

func dec_list_list_Name___60(r *wireReader, wt int, v *[][]string) error {
	e := zero_list_Name__45()
	if wt != wireLen {
		return wireMismatch("wrapped element", wt, wireLen)
	}
	esub, err := r.message()
	if err != nil {
		return err
	}
	for !esub.atEnd() {
		eid, ewt, err := esub.tag()
		if err != nil {
			return err
		}
		if eid == 1 {
			if err := dec_list_Name__45(esub, ewt, &e); err != nil {
				return err
			}
		} else if err := esub.skip(ewt); err != nil {
			return err
		}
	}
	*v = append(*v, e)
	return nil
}

func zero_list_helios_gameplay_SocketEntry__61() []SocketEntry { return ([]SocketEntry)(nil) }

func def_list_helios_gameplay_SocketEntry__61(v []SocketEntry) bool {
	return len(v) == 0
}

func enc_list_helios_gameplay_SocketEntry__61(b []byte, id uint32, v []SocketEntry) []byte {
	if len(v) == 0 {
		return b
	}
	for _, e := range v {
		b = appendTag(b, id, wireLen)
		b = encv_helios_gameplay_SocketEntry_93(b, e)
	}
	return b
}

func dec_list_helios_gameplay_SocketEntry__61(r *wireReader, wt int, v *[]SocketEntry) error {
	e := zero_helios_gameplay_SocketEntry_93()
	if err := decv_helios_gameplay_SocketEntry_93(r, wt, &e); err != nil {
		return err
	}
	*v = append(*v, e)
	return nil
}

func zero_helios_gameplay_ContainerSpec__62() *ContainerSpec { return (*ContainerSpec)(nil) }

func def_helios_gameplay_ContainerSpec__62(v *ContainerSpec) bool {
	return v == nil
}

func enc_helios_gameplay_ContainerSpec__62(b []byte, id uint32, v *ContainerSpec) []byte {
	if v == nil {
		return b
	}
	return enc_helios_gameplay_ContainerSpec_94(b, id, *v)
}

func dec_helios_gameplay_ContainerSpec__62(r *wireReader, wt int, v **ContainerSpec) error {
	if *v == nil {
		x := zero_helios_gameplay_ContainerSpec_94()
		*v = &x
	}
	return dec_helios_gameplay_ContainerSpec_94(r, wt, *v)
}

func zero_helios_gameplay_ItemPortSpec__63() *ItemPortSpec { return (*ItemPortSpec)(nil) }

func def_helios_gameplay_ItemPortSpec__63(v *ItemPortSpec) bool {
	return v == nil
}

func enc_helios_gameplay_ItemPortSpec__63(b []byte, id uint32, v *ItemPortSpec) []byte {
	if v == nil {
		return b
	}
	return enc_helios_gameplay_ItemPortSpec_95(b, id, *v)
}

func dec_helios_gameplay_ItemPortSpec__63(r *wireReader, wt int, v **ItemPortSpec) error {
	if *v == nil {
		x := zero_helios_gameplay_ItemPortSpec_95()
		*v = &x
	}
	return dec_helios_gameplay_ItemPortSpec_95(r, wt, *v)
}

func zero_helios_gameplay_DecaySpec__64() *DecaySpec { return (*DecaySpec)(nil) }

func def_helios_gameplay_DecaySpec__64(v *DecaySpec) bool {
	return v == nil
}

func enc_helios_gameplay_DecaySpec__64(b []byte, id uint32, v *DecaySpec) []byte {
	if v == nil {
		return b
	}
	return enc_helios_gameplay_DecaySpec_96(b, id, *v)
}

func dec_helios_gameplay_DecaySpec__64(r *wireReader, wt int, v **DecaySpec) error {
	if *v == nil {
		x := zero_helios_gameplay_DecaySpec_96()
		*v = &x
	}
	return dec_helios_gameplay_DecaySpec_96(r, wt, *v)
}

func zero_helios_gameplay_BindRule_65() BindRule { return BindRuleNone }

func def_helios_gameplay_BindRule_65(v BindRule) bool {
	return v == BindRuleNone
}

func encv_helios_gameplay_BindRule_65(b []byte, v BindRule) []byte {
	return appendVarint(b, uint64(v))
}

func decv_helios_gameplay_BindRule_65(r *wireReader, wt int, v *BindRule) error {
	x, err := readUnsigned(r, wt, math.MaxUint8)
	*v = BindRule(x)
	return err
}

func enc_helios_gameplay_BindRule_65(b []byte, id uint32, v BindRule) []byte {
	b = appendTag(b, id, wireVarint)
	return encv_helios_gameplay_BindRule_65(b, v)
}

func dec_helios_gameplay_BindRule_65(r *wireReader, wt int, v *BindRule) error {
	return decv_helios_gameplay_BindRule_65(r, wt, v)
}

func zero_helios_gameplay_OwnerKind_66() OwnerKind { return OwnerKindCharacter }

func def_helios_gameplay_OwnerKind_66(v OwnerKind) bool {
	return v == OwnerKindCharacter
}

func encv_helios_gameplay_OwnerKind_66(b []byte, v OwnerKind) []byte {
	return appendVarint(b, uint64(v))
}

func decv_helios_gameplay_OwnerKind_66(r *wireReader, wt int, v *OwnerKind) error {
	x, err := readUnsigned(r, wt, math.MaxUint8)
	*v = OwnerKind(x)
	return err
}

func enc_helios_gameplay_OwnerKind_66(b []byte, id uint32, v OwnerKind) []byte {
	b = appendTag(b, id, wireVarint)
	return encv_helios_gameplay_OwnerKind_66(b, v)
}

func dec_helios_gameplay_OwnerKind_66(r *wireReader, wt int, v *OwnerKind) error {
	return decv_helios_gameplay_OwnerKind_66(r, wt, v)
}

func zero_u64_67() uint64 { return uint64(0) }

func def_u64_67(v uint64) bool {
	return v == 0
}

func encv_u64_67(b []byte, v uint64) []byte {
	return appendVarint(b, uint64(v))
}

func decv_u64_67(r *wireReader, wt int, v *uint64) error {
	x, err := readUnsigned(r, wt, math.MaxUint64)
	*v = uint64(x)
	return err
}

func enc_u64_67(b []byte, id uint32, v uint64) []byte {
	b = appendTag(b, id, wireVarint)
	return encv_u64_67(b, v)
}

func dec_u64_67(r *wireReader, wt int, v *uint64) error {
	return decv_u64_67(r, wt, v)
}

func zero_helios_gameplay_LocationKind_68() LocationKind { return LocationKindItem }

func def_helios_gameplay_LocationKind_68(v LocationKind) bool {
	return v == LocationKindItem
}

func encv_helios_gameplay_LocationKind_68(b []byte, v LocationKind) []byte {
	return appendVarint(b, uint64(v))
}

func decv_helios_gameplay_LocationKind_68(r *wireReader, wt int, v *LocationKind) error {
	x, err := readUnsigned(r, wt, math.MaxUint8)
	*v = LocationKind(x)
	return err
}

func enc_helios_gameplay_LocationKind_68(b []byte, id uint32, v LocationKind) []byte {
	b = appendTag(b, id, wireVarint)
	return encv_helios_gameplay_LocationKind_68(b, v)
}

func dec_helios_gameplay_LocationKind_68(r *wireReader, wt int, v *LocationKind) error {
	return decv_helios_gameplay_LocationKind_68(r, wt, v)
}

func zero_vec3d_69() DVec3 { return DVec3{} }

func def_vec3d_69(v DVec3) bool {
	return func() bool { z := zero_vec3d_69(); return f64TupleBits(v[:], z[:]) }()
}

func encv_vec3d_69(b []byte, v DVec3) []byte {
	return appendF64Tuple(b, v[:])
}

func decv_vec3d_69(r *wireReader, wt int, v *DVec3) error {
	return readF64Tuple(r, wt, v[:])
}

func enc_vec3d_69(b []byte, id uint32, v DVec3) []byte {
	b = appendTag(b, id, wireLen)
	return encv_vec3d_69(b, v)
}

func dec_vec3d_69(r *wireReader, wt int, v *DVec3) error {
	return decv_vec3d_69(r, wt, v)
}

func zero_quatf_70() Quat { return Quat{0, 0, 0, 1} }

func def_quatf_70(v Quat) bool {
	return func() bool { z := zero_quatf_70(); return f32TupleBits(v[:], z[:]) }()
}

func encv_quatf_70(b []byte, v Quat) []byte {
	return appendF32Tuple(b, v[:])
}

func decv_quatf_70(r *wireReader, wt int, v *Quat) error {
	return readF32Tuple(r, wt, v[:])
}

func enc_quatf_70(b []byte, id uint32, v Quat) []byte {
	b = appendTag(b, id, wireLen)
	return encv_quatf_70(b, v)
}

func dec_quatf_70(r *wireReader, wt int, v *Quat) error {
	return decv_quatf_70(r, wt, v)
}

func zero_list_Ref_helios_gameplay_ItemDef___71() []ItemRef { return ([]ItemRef)(nil) }

func def_list_Ref_helios_gameplay_ItemDef___71(v []ItemRef) bool {
	return len(v) == 0
}

func enc_list_Ref_helios_gameplay_ItemDef___71(b []byte, id uint32, v []ItemRef) []byte {
	if len(v) == 0 {
		return b
	}
	b = appendTag(b, id, wireLen)
	b, mk := beginLen(b)
	for _, e := range v {
		b = encv_Ref_helios_gameplay_ItemDef__76(b, e)
	}
	return endLen(b, mk)
}

func dec_list_Ref_helios_gameplay_ItemDef___71(r *wireReader, wt int, v *[]ItemRef) error {
	if wt == wireLen {
		p, err := r.lenBytes()
		if err != nil {
			return err
		}
		sub := &wireReader{data: p, depth: r.depth}
		for !sub.atEnd() {
			e := zero_Ref_helios_gameplay_ItemDef__76()
			if err := decv_Ref_helios_gameplay_ItemDef__76(sub, wireI64, &e); err != nil {
				return err
			}
			*v = append(*v, e)
		}
		return nil
	}
	e := zero_Ref_helios_gameplay_ItemDef__76()
	if err := decv_Ref_helios_gameplay_ItemDef__76(r, wt, &e); err != nil {
		return err
	}
	*v = append(*v, e)
	return nil
}

func zero_helios_gameplay_CraftStamp__72() *CraftStamp { return (*CraftStamp)(nil) }

func def_helios_gameplay_CraftStamp__72(v *CraftStamp) bool {
	return v == nil
}

func enc_helios_gameplay_CraftStamp__72(b []byte, id uint32, v *CraftStamp) []byte {
	if v == nil {
		return b
	}
	return enc_helios_gameplay_CraftStamp_97(b, id, *v)
}

func dec_helios_gameplay_CraftStamp__72(r *wireReader, wt int, v **CraftStamp) error {
	if *v == nil {
		x := zero_helios_gameplay_CraftStamp_97()
		*v = &x
	}
	return dec_helios_gameplay_CraftStamp_97(r, wt, *v)
}

func zero_u64__73() *uint64 { return (*uint64)(nil) }

func def_u64__73(v *uint64) bool {
	return v == nil
}

func enc_u64__73(b []byte, id uint32, v *uint64) []byte {
	if v == nil {
		return b
	}
	return enc_u64_67(b, id, *v)
}

func dec_u64__73(r *wireReader, wt int, v **uint64) error {
	if *v == nil {
		x := zero_u64_67()
		*v = &x
	}
	return dec_u64_67(r, wt, *v)
}

func zero_string__74() *string { return (*string)(nil) }

func def_string__74(v *string) bool {
	return v == nil
}

func enc_string__74(b []byte, id uint32, v *string) []byte {
	if v == nil {
		return b
	}
	return enc_string_98(b, id, *v)
}

func dec_string__74(r *wireReader, wt int, v **string) error {
	if *v == nil {
		x := zero_string_98()
		*v = &x
	}
	return dec_string_98(r, wt, *v)
}

func zero_helios_gameplay_Xform__75() *Xform { return (*Xform)(nil) }

func def_helios_gameplay_Xform__75(v *Xform) bool {
	return v == nil
}

func enc_helios_gameplay_Xform__75(b []byte, id uint32, v *Xform) []byte {
	if v == nil {
		return b
	}
	return enc_helios_gameplay_Xform_99(b, id, *v)
}

func dec_helios_gameplay_Xform__75(r *wireReader, wt int, v **Xform) error {
	if *v == nil {
		x := zero_helios_gameplay_Xform_99()
		*v = &x
	}
	return dec_helios_gameplay_Xform_99(r, wt, *v)
}

func zero_Ref_helios_gameplay_ItemDef__76() ItemRef { return ItemRef(0) }

func def_Ref_helios_gameplay_ItemDef__76(v ItemRef) bool {
	return v == 0
}

func encv_Ref_helios_gameplay_ItemDef__76(b []byte, v ItemRef) []byte {
	return appendFixed64(b, uint64(v))
}

func decv_Ref_helios_gameplay_ItemDef__76(r *wireReader, wt int, v *ItemRef) error {
	x, err := readFixed64Field(r, wt, "record reference")
	*v = ItemRef(x)
	return err
}

func enc_Ref_helios_gameplay_ItemDef__76(b []byte, id uint32, v ItemRef) []byte {
	b = appendTag(b, id, wireI64)
	return encv_Ref_helios_gameplay_ItemDef__76(b, v)
}

func dec_Ref_helios_gameplay_ItemDef__76(r *wireReader, wt int, v *ItemRef) error {
	return decv_Ref_helios_gameplay_ItemDef__76(r, wt, v)
}

func zero_helios_gameplay_OwnerRef_77() OwnerRef { return NewOwnerRef() }

func def_helios_gameplay_OwnerRef_77(v OwnerRef) bool {
	return v.isDefault()
}

func encv_helios_gameplay_OwnerRef_77(b []byte, v OwnerRef) []byte {
	b, mk := beginLen(b)
	b = v.appendFields(b)
	return endLen(b, mk)
}

func decv_helios_gameplay_OwnerRef_77(r *wireReader, wt int, v *OwnerRef) error {
	if wt != wireLen {
		return wireMismatch("OwnerRef", wt, wireLen)
	}
	sub, err := r.message()
	if err != nil {
		return err
	}
	return v.readFields(sub)
}

func enc_helios_gameplay_OwnerRef_77(b []byte, id uint32, v OwnerRef) []byte {
	b = appendTag(b, id, wireLen)
	return encv_helios_gameplay_OwnerRef_77(b, v)
}

func dec_helios_gameplay_OwnerRef_77(r *wireReader, wt int, v *OwnerRef) error {
	return decv_helios_gameplay_OwnerRef_77(r, wt, v)
}

func zero_helios_gameplay_LocationRef_78() LocationRef { return NewLocationRef() }

func def_helios_gameplay_LocationRef_78(v LocationRef) bool {
	return v.isDefault()
}

func encv_helios_gameplay_LocationRef_78(b []byte, v LocationRef) []byte {
	b, mk := beginLen(b)
	b = v.appendFields(b)
	return endLen(b, mk)
}

func decv_helios_gameplay_LocationRef_78(r *wireReader, wt int, v *LocationRef) error {
	if wt != wireLen {
		return wireMismatch("LocationRef", wt, wireLen)
	}
	sub, err := r.message()
	if err != nil {
		return err
	}
	return v.readFields(sub)
}

func enc_helios_gameplay_LocationRef_78(b []byte, id uint32, v LocationRef) []byte {
	b = appendTag(b, id, wireLen)
	return encv_helios_gameplay_LocationRef_78(b, v)
}

func dec_helios_gameplay_LocationRef_78(r *wireReader, wt int, v *LocationRef) error {
	return decv_helios_gameplay_LocationRef_78(r, wt, v)
}

func zero_helios_gameplay_ItemPayload_79() ItemPayload { return NewItemPayload() }

func def_helios_gameplay_ItemPayload_79(v ItemPayload) bool {
	return v.isDefault()
}

func encv_helios_gameplay_ItemPayload_79(b []byte, v ItemPayload) []byte {
	b, mk := beginLen(b)
	b = v.appendFields(b)
	return endLen(b, mk)
}

func decv_helios_gameplay_ItemPayload_79(r *wireReader, wt int, v *ItemPayload) error {
	if wt != wireLen {
		return wireMismatch("ItemPayload", wt, wireLen)
	}
	sub, err := r.message()
	if err != nil {
		return err
	}
	return v.readFields(sub)
}

func enc_helios_gameplay_ItemPayload_79(b []byte, id uint32, v ItemPayload) []byte {
	b = appendTag(b, id, wireLen)
	return encv_helios_gameplay_ItemPayload_79(b, v)
}

func dec_helios_gameplay_ItemPayload_79(r *wireReader, wt int, v *ItemPayload) error {
	return decv_helios_gameplay_ItemPayload_79(r, wt, v)
}

func zero_i64_80() int64 { return int64(0) }

func def_i64_80(v int64) bool {
	return v == 0
}

func encv_i64_80(b []byte, v int64) []byte {
	return appendZigzag(b, int64(v))
}

func decv_i64_80(r *wireReader, wt int, v *int64) error {
	x, err := readSigned(r, wt, math.MinInt64, math.MaxInt64)
	*v = int64(x)
	return err
}

func enc_i64_80(b []byte, id uint32, v int64) []byte {
	b = appendTag(b, id, wireVarint)
	return encv_i64_80(b, v)
}

func dec_i64_80(r *wireReader, wt int, v *int64) error {
	return decv_i64_80(r, wt, v)
}

func zero_helios_gameplay_ReasonKind_81() ReasonKind { return ReasonKindFaucet }

func def_helios_gameplay_ReasonKind_81(v ReasonKind) bool {
	return v == ReasonKindFaucet
}

func encv_helios_gameplay_ReasonKind_81(b []byte, v ReasonKind) []byte {
	return appendVarint(b, uint64(v))
}

func decv_helios_gameplay_ReasonKind_81(r *wireReader, wt int, v *ReasonKind) error {
	x, err := readUnsigned(r, wt, math.MaxUint8)
	*v = ReasonKind(x)
	return err
}

func enc_helios_gameplay_ReasonKind_81(b []byte, id uint32, v ReasonKind) []byte {
	b = appendTag(b, id, wireVarint)
	return encv_helios_gameplay_ReasonKind_81(b, v)
}

func dec_helios_gameplay_ReasonKind_81(r *wireReader, wt int, v *ReasonKind) error {
	return decv_helios_gameplay_ReasonKind_81(r, wt, v)
}

func zero_helios_gameplay_FaucetCap__82() *FaucetCap { return (*FaucetCap)(nil) }

func def_helios_gameplay_FaucetCap__82(v *FaucetCap) bool {
	return v == nil
}

func enc_helios_gameplay_FaucetCap__82(b []byte, id uint32, v *FaucetCap) []byte {
	if v == nil {
		return b
	}
	return enc_helios_gameplay_FaucetCap_100(b, id, *v)
}

func dec_helios_gameplay_FaucetCap__82(r *wireReader, wt int, v **FaucetCap) error {
	if *v == nil {
		x := zero_helios_gameplay_FaucetCap_100()
		*v = &x
	}
	return dec_helios_gameplay_FaucetCap_100(r, wt, *v)
}

func zero_helios_gameplay_AttrOrConst_83() AttrOrConst { return NewAttrOrConst() }

func def_helios_gameplay_AttrOrConst_83(v AttrOrConst) bool {
	return v.isDefault()
}

func encv_helios_gameplay_AttrOrConst_83(b []byte, v AttrOrConst) []byte {
	return v.appendValue(b)
}

func decv_helios_gameplay_AttrOrConst_83(r *wireReader, wt int, v *AttrOrConst) error {
	return v.readValue(r, wt)
}

func enc_helios_gameplay_AttrOrConst_83(b []byte, id uint32, v AttrOrConst) []byte {
	b = appendTag(b, id, wireLen)
	return encv_helios_gameplay_AttrOrConst_83(b, v)
}

func dec_helios_gameplay_AttrOrConst_83(r *wireReader, wt int, v *AttrOrConst) error {
	return decv_helios_gameplay_AttrOrConst_83(r, wt, v)
}

func zero_helios_gameplay_Quantization_84() Quantization { return NewQuantization() }

func def_helios_gameplay_Quantization_84(v Quantization) bool {
	return v.isDefault()
}

func encv_helios_gameplay_Quantization_84(b []byte, v Quantization) []byte {
	b, mk := beginLen(b)
	b = v.appendFields(b)
	return endLen(b, mk)
}

func decv_helios_gameplay_Quantization_84(r *wireReader, wt int, v *Quantization) error {
	if wt != wireLen {
		return wireMismatch("Quantization", wt, wireLen)
	}
	sub, err := r.message()
	if err != nil {
		return err
	}
	return v.readFields(sub)
}

func enc_helios_gameplay_Quantization_84(b []byte, id uint32, v Quantization) []byte {
	b = appendTag(b, id, wireLen)
	return encv_helios_gameplay_Quantization_84(b, v)
}

func dec_helios_gameplay_Quantization_84(r *wireReader, wt int, v *Quantization) error {
	return decv_helios_gameplay_Quantization_84(r, wt, v)
}

func zero_Ref_helios_gameplay_EffectDef__85() EffectRef { return EffectRef(0) }

func def_Ref_helios_gameplay_EffectDef__85(v EffectRef) bool {
	return v == 0
}

func encv_Ref_helios_gameplay_EffectDef__85(b []byte, v EffectRef) []byte {
	return appendFixed64(b, uint64(v))
}

func decv_Ref_helios_gameplay_EffectDef__85(r *wireReader, wt int, v *EffectRef) error {
	x, err := readFixed64Field(r, wt, "record reference")
	*v = EffectRef(x)
	return err
}

func enc_Ref_helios_gameplay_EffectDef__85(b []byte, id uint32, v EffectRef) []byte {
	b = appendTag(b, id, wireI64)
	return encv_Ref_helios_gameplay_EffectDef__85(b, v)
}

func dec_Ref_helios_gameplay_EffectDef__85(r *wireReader, wt int, v *EffectRef) error {
	return decv_Ref_helios_gameplay_EffectDef__85(r, wt, v)
}

func zero_helios_gameplay_ModifierDef_86() ModifierDef { return NewModifierDef() }

func def_helios_gameplay_ModifierDef_86(v ModifierDef) bool {
	return v.isDefault()
}

func encv_helios_gameplay_ModifierDef_86(b []byte, v ModifierDef) []byte {
	b, mk := beginLen(b)
	b = v.appendFields(b)
	return endLen(b, mk)
}

func decv_helios_gameplay_ModifierDef_86(r *wireReader, wt int, v *ModifierDef) error {
	if wt != wireLen {
		return wireMismatch("ModifierDef", wt, wireLen)
	}
	sub, err := r.message()
	if err != nil {
		return err
	}
	return v.readFields(sub)
}

func enc_helios_gameplay_ModifierDef_86(b []byte, id uint32, v ModifierDef) []byte {
	b = appendTag(b, id, wireLen)
	return encv_helios_gameplay_ModifierDef_86(b, v)
}

func dec_helios_gameplay_ModifierDef_86(r *wireReader, wt int, v *ModifierDef) error {
	return decv_helios_gameplay_ModifierDef_86(r, wt, v)
}

func zero_helios_gameplay_ExecutionRef_87() ExecutionRef { return NewExecutionRef() }

func def_helios_gameplay_ExecutionRef_87(v ExecutionRef) bool {
	return v.isDefault()
}

func encv_helios_gameplay_ExecutionRef_87(b []byte, v ExecutionRef) []byte {
	return v.appendValue(b)
}

func decv_helios_gameplay_ExecutionRef_87(r *wireReader, wt int, v *ExecutionRef) error {
	return v.readValue(r, wt)
}

func enc_helios_gameplay_ExecutionRef_87(b []byte, id uint32, v ExecutionRef) []byte {
	b = appendTag(b, id, wireLen)
	return encv_helios_gameplay_ExecutionRef_87(b, v)
}

func dec_helios_gameplay_ExecutionRef_87(r *wireReader, wt int, v *ExecutionRef) error {
	return decv_helios_gameplay_ExecutionRef_87(r, wt, v)
}

func zero_helios_gameplay_CueBinding_88() CueBinding { return NewCueBinding() }

func def_helios_gameplay_CueBinding_88(v CueBinding) bool {
	return v.isDefault()
}

func encv_helios_gameplay_CueBinding_88(b []byte, v CueBinding) []byte {
	b, mk := beginLen(b)
	b = v.appendFields(b)
	return endLen(b, mk)
}

func decv_helios_gameplay_CueBinding_88(r *wireReader, wt int, v *CueBinding) error {
	if wt != wireLen {
		return wireMismatch("CueBinding", wt, wireLen)
	}
	sub, err := r.message()
	if err != nil {
		return err
	}
	return v.readFields(sub)
}

func enc_helios_gameplay_CueBinding_88(b []byte, id uint32, v CueBinding) []byte {
	b = appendTag(b, id, wireLen)
	return encv_helios_gameplay_CueBinding_88(b, v)
}

func dec_helios_gameplay_CueBinding_88(r *wireReader, wt int, v *CueBinding) error {
	return decv_helios_gameplay_CueBinding_88(r, wt, v)
}

func zero_helios_gameplay_AttrMinimum_89() AttrMinimum { return NewAttrMinimum() }

func def_helios_gameplay_AttrMinimum_89(v AttrMinimum) bool {
	return v.isDefault()
}

func encv_helios_gameplay_AttrMinimum_89(b []byte, v AttrMinimum) []byte {
	b, mk := beginLen(b)
	b = v.appendFields(b)
	return endLen(b, mk)
}

func decv_helios_gameplay_AttrMinimum_89(r *wireReader, wt int, v *AttrMinimum) error {
	if wt != wireLen {
		return wireMismatch("AttrMinimum", wt, wireLen)
	}
	sub, err := r.message()
	if err != nil {
		return err
	}
	return v.readFields(sub)
}

func enc_helios_gameplay_AttrMinimum_89(b []byte, id uint32, v AttrMinimum) []byte {
	b = appendTag(b, id, wireLen)
	return encv_helios_gameplay_AttrMinimum_89(b, v)
}

func dec_helios_gameplay_AttrMinimum_89(r *wireReader, wt int, v *AttrMinimum) error {
	return decv_helios_gameplay_AttrMinimum_89(r, wt, v)
}

func zero_helios_gameplay_SlotDescriptor_90() SlotDescriptor { return NewSlotDescriptor() }

func def_helios_gameplay_SlotDescriptor_90(v SlotDescriptor) bool {
	return v.isDefault()
}

func encv_helios_gameplay_SlotDescriptor_90(b []byte, v SlotDescriptor) []byte {
	b, mk := beginLen(b)
	b = v.appendFields(b)
	return endLen(b, mk)
}

func decv_helios_gameplay_SlotDescriptor_90(r *wireReader, wt int, v *SlotDescriptor) error {
	if wt != wireLen {
		return wireMismatch("SlotDescriptor", wt, wireLen)
	}
	sub, err := r.message()
	if err != nil {
		return err
	}
	return v.readFields(sub)
}

func enc_helios_gameplay_SlotDescriptor_90(b []byte, id uint32, v SlotDescriptor) []byte {
	b = appendTag(b, id, wireLen)
	return encv_helios_gameplay_SlotDescriptor_90(b, v)
}

func dec_helios_gameplay_SlotDescriptor_90(r *wireReader, wt int, v *SlotDescriptor) error {
	return decv_helios_gameplay_SlotDescriptor_90(r, wt, v)
}

func zero_helios_gameplay_ItemState_91() ItemState { return ItemStateOffline }

func def_helios_gameplay_ItemState_91(v ItemState) bool {
	return v == ItemStateOffline
}

func encv_helios_gameplay_ItemState_91(b []byte, v ItemState) []byte {
	return appendVarint(b, uint64(v))
}

func decv_helios_gameplay_ItemState_91(r *wireReader, wt int, v *ItemState) error {
	x, err := readUnsigned(r, wt, math.MaxUint8)
	*v = ItemState(x)
	return err
}

func enc_helios_gameplay_ItemState_91(b []byte, id uint32, v ItemState) []byte {
	b = appendTag(b, id, wireVarint)
	return encv_helios_gameplay_ItemState_91(b, v)
}

func dec_helios_gameplay_ItemState_91(r *wireReader, wt int, v *ItemState) error {
	return decv_helios_gameplay_ItemState_91(r, wt, v)
}

func zero_list_Ref_helios_gameplay_EffectDef___92() []EffectRef { return ([]EffectRef)(nil) }

func def_list_Ref_helios_gameplay_EffectDef___92(v []EffectRef) bool {
	return len(v) == 0
}

func enc_list_Ref_helios_gameplay_EffectDef___92(b []byte, id uint32, v []EffectRef) []byte {
	if len(v) == 0 {
		return b
	}
	b = appendTag(b, id, wireLen)
	b, mk := beginLen(b)
	for _, e := range v {
		b = encv_Ref_helios_gameplay_EffectDef__85(b, e)
	}
	return endLen(b, mk)
}

func dec_list_Ref_helios_gameplay_EffectDef___92(r *wireReader, wt int, v *[]EffectRef) error {
	if wt == wireLen {
		p, err := r.lenBytes()
		if err != nil {
			return err
		}
		sub := &wireReader{data: p, depth: r.depth}
		for !sub.atEnd() {
			e := zero_Ref_helios_gameplay_EffectDef__85()
			if err := decv_Ref_helios_gameplay_EffectDef__85(sub, wireI64, &e); err != nil {
				return err
			}
			*v = append(*v, e)
		}
		return nil
	}
	e := zero_Ref_helios_gameplay_EffectDef__85()
	if err := decv_Ref_helios_gameplay_EffectDef__85(r, wt, &e); err != nil {
		return err
	}
	*v = append(*v, e)
	return nil
}

func zero_helios_gameplay_SocketEntry_93() SocketEntry { return NewSocketEntry() }

func def_helios_gameplay_SocketEntry_93(v SocketEntry) bool {
	return v.isDefault()
}

func encv_helios_gameplay_SocketEntry_93(b []byte, v SocketEntry) []byte {
	b, mk := beginLen(b)
	b = v.appendFields(b)
	return endLen(b, mk)
}

func decv_helios_gameplay_SocketEntry_93(r *wireReader, wt int, v *SocketEntry) error {
	if wt != wireLen {
		return wireMismatch("SocketEntry", wt, wireLen)
	}
	sub, err := r.message()
	if err != nil {
		return err
	}
	return v.readFields(sub)
}

func enc_helios_gameplay_SocketEntry_93(b []byte, id uint32, v SocketEntry) []byte {
	b = appendTag(b, id, wireLen)
	return encv_helios_gameplay_SocketEntry_93(b, v)
}

func dec_helios_gameplay_SocketEntry_93(r *wireReader, wt int, v *SocketEntry) error {
	return decv_helios_gameplay_SocketEntry_93(r, wt, v)
}

func zero_helios_gameplay_ContainerSpec_94() ContainerSpec { return NewContainerSpec() }

func def_helios_gameplay_ContainerSpec_94(v ContainerSpec) bool {
	return v.isDefault()
}

func encv_helios_gameplay_ContainerSpec_94(b []byte, v ContainerSpec) []byte {
	b, mk := beginLen(b)
	b = v.appendFields(b)
	return endLen(b, mk)
}

func decv_helios_gameplay_ContainerSpec_94(r *wireReader, wt int, v *ContainerSpec) error {
	if wt != wireLen {
		return wireMismatch("ContainerSpec", wt, wireLen)
	}
	sub, err := r.message()
	if err != nil {
		return err
	}
	return v.readFields(sub)
}

func enc_helios_gameplay_ContainerSpec_94(b []byte, id uint32, v ContainerSpec) []byte {
	b = appendTag(b, id, wireLen)
	return encv_helios_gameplay_ContainerSpec_94(b, v)
}

func dec_helios_gameplay_ContainerSpec_94(r *wireReader, wt int, v *ContainerSpec) error {
	return decv_helios_gameplay_ContainerSpec_94(r, wt, v)
}

func zero_helios_gameplay_ItemPortSpec_95() ItemPortSpec { return NewItemPortSpec() }

func def_helios_gameplay_ItemPortSpec_95(v ItemPortSpec) bool {
	return v.isDefault()
}

func encv_helios_gameplay_ItemPortSpec_95(b []byte, v ItemPortSpec) []byte {
	b, mk := beginLen(b)
	b = v.appendFields(b)
	return endLen(b, mk)
}

func decv_helios_gameplay_ItemPortSpec_95(r *wireReader, wt int, v *ItemPortSpec) error {
	if wt != wireLen {
		return wireMismatch("ItemPortSpec", wt, wireLen)
	}
	sub, err := r.message()
	if err != nil {
		return err
	}
	return v.readFields(sub)
}

func enc_helios_gameplay_ItemPortSpec_95(b []byte, id uint32, v ItemPortSpec) []byte {
	b = appendTag(b, id, wireLen)
	return encv_helios_gameplay_ItemPortSpec_95(b, v)
}

func dec_helios_gameplay_ItemPortSpec_95(r *wireReader, wt int, v *ItemPortSpec) error {
	return decv_helios_gameplay_ItemPortSpec_95(r, wt, v)
}

func zero_helios_gameplay_DecaySpec_96() DecaySpec { return NewDecaySpec() }

func def_helios_gameplay_DecaySpec_96(v DecaySpec) bool {
	return v.isDefault()
}

func encv_helios_gameplay_DecaySpec_96(b []byte, v DecaySpec) []byte {
	b, mk := beginLen(b)
	b = v.appendFields(b)
	return endLen(b, mk)
}

func decv_helios_gameplay_DecaySpec_96(r *wireReader, wt int, v *DecaySpec) error {
	if wt != wireLen {
		return wireMismatch("DecaySpec", wt, wireLen)
	}
	sub, err := r.message()
	if err != nil {
		return err
	}
	return v.readFields(sub)
}

func enc_helios_gameplay_DecaySpec_96(b []byte, id uint32, v DecaySpec) []byte {
	b = appendTag(b, id, wireLen)
	return encv_helios_gameplay_DecaySpec_96(b, v)
}

func dec_helios_gameplay_DecaySpec_96(r *wireReader, wt int, v *DecaySpec) error {
	return decv_helios_gameplay_DecaySpec_96(r, wt, v)
}

func zero_helios_gameplay_CraftStamp_97() CraftStamp { return NewCraftStamp() }

func def_helios_gameplay_CraftStamp_97(v CraftStamp) bool {
	return v.isDefault()
}

func encv_helios_gameplay_CraftStamp_97(b []byte, v CraftStamp) []byte {
	b, mk := beginLen(b)
	b = v.appendFields(b)
	return endLen(b, mk)
}

func decv_helios_gameplay_CraftStamp_97(r *wireReader, wt int, v *CraftStamp) error {
	if wt != wireLen {
		return wireMismatch("CraftStamp", wt, wireLen)
	}
	sub, err := r.message()
	if err != nil {
		return err
	}
	return v.readFields(sub)
}

func enc_helios_gameplay_CraftStamp_97(b []byte, id uint32, v CraftStamp) []byte {
	b = appendTag(b, id, wireLen)
	return encv_helios_gameplay_CraftStamp_97(b, v)
}

func dec_helios_gameplay_CraftStamp_97(r *wireReader, wt int, v *CraftStamp) error {
	return decv_helios_gameplay_CraftStamp_97(r, wt, v)
}

func zero_string_98() string { return "" }

func def_string_98(v string) bool {
	return v == ""
}

func encv_string_98(b []byte, v string) []byte {
	return appendString(b, v)
}

func decv_string_98(r *wireReader, wt int, v *string) error {
	x, err := readStringField(r, wt)
	*v = x
	return err
}

func enc_string_98(b []byte, id uint32, v string) []byte {
	b = appendTag(b, id, wireLen)
	return encv_string_98(b, v)
}

func dec_string_98(r *wireReader, wt int, v *string) error {
	return decv_string_98(r, wt, v)
}

func zero_helios_gameplay_Xform_99() Xform { return NewXform() }

func def_helios_gameplay_Xform_99(v Xform) bool {
	return v.isDefault()
}

func encv_helios_gameplay_Xform_99(b []byte, v Xform) []byte {
	b, mk := beginLen(b)
	b = v.appendFields(b)
	return endLen(b, mk)
}

func decv_helios_gameplay_Xform_99(r *wireReader, wt int, v *Xform) error {
	if wt != wireLen {
		return wireMismatch("Xform", wt, wireLen)
	}
	sub, err := r.message()
	if err != nil {
		return err
	}
	return v.readFields(sub)
}

func enc_helios_gameplay_Xform_99(b []byte, id uint32, v Xform) []byte {
	b = appendTag(b, id, wireLen)
	return encv_helios_gameplay_Xform_99(b, v)
}

func dec_helios_gameplay_Xform_99(r *wireReader, wt int, v *Xform) error {
	return decv_helios_gameplay_Xform_99(r, wt, v)
}

func zero_helios_gameplay_FaucetCap_100() FaucetCap { return NewFaucetCap() }

func def_helios_gameplay_FaucetCap_100(v FaucetCap) bool {
	return v.isDefault()
}

func encv_helios_gameplay_FaucetCap_100(b []byte, v FaucetCap) []byte {
	b, mk := beginLen(b)
	b = v.appendFields(b)
	return endLen(b, mk)
}

func decv_helios_gameplay_FaucetCap_100(r *wireReader, wt int, v *FaucetCap) error {
	if wt != wireLen {
		return wireMismatch("FaucetCap", wt, wireLen)
	}
	sub, err := r.message()
	if err != nil {
		return err
	}
	return v.readFields(sub)
}

func enc_helios_gameplay_FaucetCap_100(b []byte, id uint32, v FaucetCap) []byte {
	b = appendTag(b, id, wireLen)
	return encv_helios_gameplay_FaucetCap_100(b, v)
}

func dec_helios_gameplay_FaucetCap_100(r *wireReader, wt int, v *FaucetCap) error {
	return decv_helios_gameplay_FaucetCap_100(r, wt, v)
}

