// Code generated by helios-schemac from gameplay/items.hschema. DO NOT EDIT.

package gamedef

import (
	"encoding/json"
	"fmt"
	"math"
)

var _ = json.Marshal
var _ = fmt.Errorf
var _ = math.MaxInt8

type ItemState uint8

const (
	ItemStateOffline ItemState = 0
	ItemStateOnline ItemState = 1
	ItemStateActive ItemState = 2
	ItemStateOverloaded ItemState = 3
)

var namesItemState = []enumName{{"Offline", 0}, {"Online", 1}, {"Active", 2}, {"Overloaded", 3}, }

func (v ItemState) MarshalJSON() ([]byte, error) { return enumToJSON(namesItemState, int64(v)) }
func (v *ItemState) UnmarshalJSON(b []byte) error {
	x, err := enumFromJSON(namesItemState, b)
	*v = ItemState(x)
	return err
}
func (v ItemState) MarshalText() ([]byte, error) { return enumToText(namesItemState, int64(v)), nil }
func (v *ItemState) UnmarshalText(b []byte) error {
	x, err := enumFromText(namesItemState, string(b))
	*v = ItemState(x)
	return err
}

type BindRule uint8

const (
	BindRuleNone BindRule = 0
	BindRuleOnPickup BindRule = 1
	BindRuleOnEquip BindRule = 2
	BindRuleAccount BindRule = 3
)

var namesBindRule = []enumName{{"None", 0}, {"OnPickup", 1}, {"OnEquip", 2}, {"Account", 3}, }

func (v BindRule) MarshalJSON() ([]byte, error) { return enumToJSON(namesBindRule, int64(v)) }
func (v *BindRule) UnmarshalJSON(b []byte) error {
	x, err := enumFromJSON(namesBindRule, b)
	*v = BindRule(x)
	return err
}
func (v BindRule) MarshalText() ([]byte, error) { return enumToText(namesBindRule, int64(v)), nil }
func (v *BindRule) UnmarshalText(b []byte) error {
	x, err := enumFromText(namesBindRule, string(b))
	*v = BindRule(x)
	return err
}

type OwnerKind uint8

const (
	OwnerKindCharacter OwnerKind = 0
	OwnerKindCorporation OwnerKind = 1
	OwnerKindAccount OwnerKind = 2
	OwnerKindSystem OwnerKind = 3
	OwnerKindEscrow OwnerKind = 4
)

var namesOwnerKind = []enumName{{"Character", 0}, {"Corporation", 1}, {"Account", 2}, {"System", 3}, {"Escrow", 4}, }

func (v OwnerKind) MarshalJSON() ([]byte, error) { return enumToJSON(namesOwnerKind, int64(v)) }
func (v *OwnerKind) UnmarshalJSON(b []byte) error {
	x, err := enumFromJSON(namesOwnerKind, b)
	*v = OwnerKind(x)
	return err
}
func (v OwnerKind) MarshalText() ([]byte, error) { return enumToText(namesOwnerKind, int64(v)), nil }
func (v *OwnerKind) UnmarshalText(b []byte) error {
	x, err := enumFromText(namesOwnerKind, string(b))
	*v = OwnerKind(x)
	return err
}

// Every item has exactly one location: another item, an entity, a hangar or space (06 §2).
type LocationKind uint8

const (
	LocationKindItem LocationKind = 0
	LocationKindEntity LocationKind = 1
	LocationKindHangar LocationKind = 2
	LocationKindSpace LocationKind = 3
)

var namesLocationKind = []enumName{{"Item", 0}, {"Entity", 1}, {"Hangar", 2}, {"Space", 3}, }

func (v LocationKind) MarshalJSON() ([]byte, error) { return enumToJSON(namesLocationKind, int64(v)) }
func (v *LocationKind) UnmarshalJSON(b []byte) error {
	x, err := enumFromJSON(namesLocationKind, b)
	*v = LocationKind(x)
	return err
}
func (v LocationKind) MarshalText() ([]byte, error) { return enumToText(namesLocationKind, int64(v)), nil }
func (v *LocationKind) UnmarshalText(b []byte) error {
	x, err := enumFromText(namesLocationKind, string(b))
	*v = LocationKind(x)
	return err
}

// A socket (06 §2, Destiny sockets and plugs). Plugs are ItemDefs tagged Item.Plug.*.
type SocketEntry struct {
	// Socket type; plugs must match it.
	Type string `json:"type"`
	// Plug inserted when the item is created.
	InitialPlug *ItemRef `json:"initialPlug,omitempty"`
	// PlugSetDef names (a PlugSetDef record type arrives with sockets in Phase 2).
	RandomizedPlugSet string `json:"randomizedPlugSet"`
	// PlugSetDef of plugs the player may swap in freely.
	ReusablePlugSet string `json:"reusablePlugSet"`
	// Plugs rolled from the randomized set at grant time.
	RollCount uint8 `json:"rollCount"`
}

// NewSocketEntry returns a SocketEntry with every field at its schema default.
func NewSocketEntry() SocketEntry {
	return SocketEntry{Type: zero_Name_0(), RandomizedPlugSet: zero_Name_0(), ReusablePlugSet: zero_Name_0(), RollCount: zero_u8_3(), }
}

func (m *SocketEntry) isDefault() bool {
	return def_Name_0(m.Type) &&
		def_Ref_helios_gameplay_ItemDef___50(m.InitialPlug) &&
		def_Name_0(m.RandomizedPlugSet) &&
		def_Name_0(m.ReusablePlugSet) &&
		def_u8_3(m.RollCount)
}

func (m *SocketEntry) appendFields(b []byte) []byte {
	if !(def_Name_0(m.Type)) {
		b = enc_Name_0(b, 1, m.Type)
	}
	if !(def_Ref_helios_gameplay_ItemDef___50(m.InitialPlug)) {
		b = enc_Ref_helios_gameplay_ItemDef___50(b, 2, m.InitialPlug)
	}
	if !(def_Name_0(m.RandomizedPlugSet)) {
		b = enc_Name_0(b, 3, m.RandomizedPlugSet)
	}
	if !(def_Name_0(m.ReusablePlugSet)) {
		b = enc_Name_0(b, 4, m.ReusablePlugSet)
	}
	if !(def_u8_3(m.RollCount)) {
		b = enc_u8_3(b, 5, m.RollCount)
	}
	return b
}

func (m *SocketEntry) readFields(r *wireReader) error {
	for !r.atEnd() {
		id, wt, err := r.tag()
		if err != nil {
			return err
		}
		switch id {
			case 1:
				err = dec_Name_0(r, wt, &m.Type)
			case 2:
				err = dec_Ref_helios_gameplay_ItemDef___50(r, wt, &m.InitialPlug)
			case 3:
				err = dec_Name_0(r, wt, &m.RandomizedPlugSet)
			case 4:
				err = dec_Name_0(r, wt, &m.ReusablePlugSet)
			case 5:
				err = dec_u8_3(r, wt, &m.RollCount)
			default:
				err = r.skip(wt)
		}
		if err != nil {
			return err
		}
	}
	return nil
}

// MarshalHelios encodes the tagged binary message (identical bytes to the C++ codec).
func (m *SocketEntry) MarshalHelios() []byte { return m.appendFields(nil) }

// UnmarshalHelios decodes a tagged message; missing fields take their schema defaults.
func (m *SocketEntry) UnmarshalHelios(b []byte) error {
	*m = NewSocketEntry()
	return m.readFields(newWireReader(b))
}

// UnmarshalJSON reads JSON (e.g. canonical JSONC written by the C++ codec); missing fields keep defaults.
func (m *SocketEntry) UnmarshalJSON(b []byte) error {
	type plain SocketEntry
	p := plain(NewSocketEntry())
	if err := json.Unmarshal(b, &p); err != nil {
		return err
	}
	*m = SocketEntry(p)
	return nil
}

// A minimum attribute value of an equip requirement.
type AttrMinimum struct {
	// Attribute to check.
	Attr AttributeRef `json:"attr"`
	// Minimum final value.
	Min float64 `json:"min"`
}

// NewAttrMinimum returns a AttrMinimum with every field at its schema default.
func NewAttrMinimum() AttrMinimum {
	return AttrMinimum{Attr: zero_Ref_helios_gameplay_AttributeDef__13(), Min: zero_f64_2(), }
}

func (m *AttrMinimum) isDefault() bool {
	return def_Ref_helios_gameplay_AttributeDef__13(m.Attr) &&
		def_f64_2(m.Min)
}

func (m *AttrMinimum) appendFields(b []byte) []byte {
	if !(def_Ref_helios_gameplay_AttributeDef__13(m.Attr)) {
		b = enc_Ref_helios_gameplay_AttributeDef__13(b, 1, m.Attr)
	}
	if !(def_f64_2(m.Min)) {
		b = enc_f64_2(b, 2, m.Min)
	}
	return b
}

func (m *AttrMinimum) readFields(r *wireReader) error {
	for !r.atEnd() {
		id, wt, err := r.tag()
		if err != nil {
			return err
		}
		switch id {
			case 1:
				err = dec_Ref_helios_gameplay_AttributeDef__13(r, wt, &m.Attr)
			case 2:
				err = dec_f64_2(r, wt, &m.Min)
			default:
				err = r.skip(wt)
		}
		if err != nil {
			return err
		}
	}
	return nil
}

// MarshalHelios encodes the tagged binary message (identical bytes to the C++ codec).
func (m *AttrMinimum) MarshalHelios() []byte { return m.appendFields(nil) }

// UnmarshalHelios decodes a tagged message; missing fields take their schema defaults.
func (m *AttrMinimum) UnmarshalHelios(b []byte) error {
	*m = NewAttrMinimum()
	return m.readFields(newWireReader(b))
}

// UnmarshalJSON reads JSON (e.g. canonical JSONC written by the C++ codec); missing fields keep defaults.
func (m *AttrMinimum) UnmarshalJSON(b []byte) error {
	type plain AttrMinimum
	p := plain(NewAttrMinimum())
	if err := json.Unmarshal(b, &p); err != nil {
		return err
	}
	*m = AttrMinimum(p)
	return nil
}

// Requirements to equip or use an item: tags and attribute minimums (skills, level).
type Requirement struct {
	// Required tags of the user.
	Tags *TagQuery `json:"tags,omitempty"`
	// Required attribute minimums (skills, level).
	Attrs []AttrMinimum `json:"attrs,omitempty"`
}

// NewRequirement returns a Requirement with every field at its schema default.
func NewRequirement() Requirement {
	return Requirement{}
}

func (m *Requirement) isDefault() bool {
	return def_TagQuery__11(m.Tags) &&
		def_list_helios_gameplay_AttrMinimum__51(m.Attrs)
}

func (m *Requirement) appendFields(b []byte) []byte {
	if !(def_TagQuery__11(m.Tags)) {
		b = enc_TagQuery__11(b, 1, m.Tags)
	}
	if !(def_list_helios_gameplay_AttrMinimum__51(m.Attrs)) {
		b = enc_list_helios_gameplay_AttrMinimum__51(b, 2, m.Attrs)
	}
	return b
}

func (m *Requirement) readFields(r *wireReader) error {
	for !r.atEnd() {
		id, wt, err := r.tag()
		if err != nil {
			return err
		}
		switch id {
			case 1:
				err = dec_TagQuery__11(r, wt, &m.Tags)
			case 2:
				err = dec_list_helios_gameplay_AttrMinimum__51(r, wt, &m.Attrs)
			default:
				err = r.skip(wt)
		}
		if err != nil {
			return err
		}
	}
	return nil
}

// MarshalHelios encodes the tagged binary message (identical bytes to the C++ codec).
func (m *Requirement) MarshalHelios() []byte { return m.appendFields(nil) }

// UnmarshalHelios decodes a tagged message; missing fields take their schema defaults.
func (m *Requirement) UnmarshalHelios(b []byte) error {
	*m = NewRequirement()
	return m.readFields(newWireReader(b))
}

// UnmarshalJSON reads JSON (e.g. canonical JSONC written by the C++ codec); missing fields keep defaults.
func (m *Requirement) UnmarshalJSON(b []byte) error {
	type plain Requirement
	p := plain(NewRequirement())
	if err := json.Unmarshal(b, &p); err != nil {
		return err
	}
	*m = Requirement(p)
	return nil
}

// A slot of a container (06 §2 slot descriptors).
type SlotDescriptor struct {
	// Slot name.
	Slot string `json:"slot"`
	// Items the slot accepts.
	Accepts *TagQuery `json:"accepts,omitempty"`
}

// NewSlotDescriptor returns a SlotDescriptor with every field at its schema default.
func NewSlotDescriptor() SlotDescriptor {
	return SlotDescriptor{Slot: zero_Name_0(), }
}

func (m *SlotDescriptor) isDefault() bool {
	return def_Name_0(m.Slot) &&
		def_TagQuery__11(m.Accepts)
}

func (m *SlotDescriptor) appendFields(b []byte) []byte {
	if !(def_Name_0(m.Slot)) {
		b = enc_Name_0(b, 1, m.Slot)
	}
	if !(def_TagQuery__11(m.Accepts)) {
		b = enc_TagQuery__11(b, 2, m.Accepts)
	}
	return b
}

func (m *SlotDescriptor) readFields(r *wireReader) error {
	for !r.atEnd() {
		id, wt, err := r.tag()
		if err != nil {
			return err
		}
		switch id {
			case 1:
				err = dec_Name_0(r, wt, &m.Slot)
			case 2:
				err = dec_TagQuery__11(r, wt, &m.Accepts)
			default:
				err = r.skip(wt)
		}
		if err != nil {
			return err
		}
	}
	return nil
}

// MarshalHelios encodes the tagged binary message (identical bytes to the C++ codec).
func (m *SlotDescriptor) MarshalHelios() []byte { return m.appendFields(nil) }

// UnmarshalHelios decodes a tagged message; missing fields take their schema defaults.
func (m *SlotDescriptor) UnmarshalHelios(b []byte) error {
	*m = NewSlotDescriptor()
	return m.readFields(newWireReader(b))
}

// UnmarshalJSON reads JSON (e.g. canonical JSONC written by the C++ codec); missing fields keep defaults.
func (m *SlotDescriptor) UnmarshalJSON(b []byte) error {
	type plain SlotDescriptor
	p := plain(NewSlotDescriptor())
	if err := json.Unmarshal(b, &p); err != nil {
		return err
	}
	*m = SlotDescriptor(p)
	return nil
}

// Makes an item a container: capacity (volume and count), allowed contents and slots (06 §2).
type ContainerSpec struct {
	// Volume capacity.
	MaxVolume float32 `json:"maxVolume"`
	// Item-count capacity (0 = unlimited).
	MaxCount uint32 `json:"maxCount"`
	// Items the container accepts.
	Allowed *TagQuery `json:"allowed,omitempty"`
	// Named slots (equipment layouts).
	Slots []SlotDescriptor `json:"slots,omitempty"`
	// Access policy name (owner, corporation division, public).
	Access string `json:"access"`
}

// NewContainerSpec returns a ContainerSpec with every field at its schema default.
func NewContainerSpec() ContainerSpec {
	return ContainerSpec{MaxVolume: zero_f32_52(), MaxCount: zero_u32_53(), Access: zero_Name_0(), }
}

func (m *ContainerSpec) isDefault() bool {
	return def_f32_52(m.MaxVolume) &&
		def_u32_53(m.MaxCount) &&
		def_TagQuery__11(m.Allowed) &&
		def_list_helios_gameplay_SlotDescriptor__54(m.Slots) &&
		def_Name_0(m.Access)
}

func (m *ContainerSpec) appendFields(b []byte) []byte {
	if !(def_f32_52(m.MaxVolume)) {
		b = enc_f32_52(b, 1, m.MaxVolume)
	}
	if !(def_u32_53(m.MaxCount)) {
		b = enc_u32_53(b, 2, m.MaxCount)
	}
	if !(def_TagQuery__11(m.Allowed)) {
		b = enc_TagQuery__11(b, 3, m.Allowed)
	}
	if !(def_list_helios_gameplay_SlotDescriptor__54(m.Slots)) {
		b = enc_list_helios_gameplay_SlotDescriptor__54(b, 4, m.Slots)
	}
	if !(def_Name_0(m.Access)) {
		b = enc_Name_0(b, 5, m.Access)
	}
	return b
}

func (m *ContainerSpec) readFields(r *wireReader) error {
	for !r.atEnd() {
		id, wt, err := r.tag()
		if err != nil {
			return err
		}
		switch id {
			case 1:
				err = dec_f32_52(r, wt, &m.MaxVolume)
			case 2:
				err = dec_u32_53(r, wt, &m.MaxCount)
			case 3:
				err = dec_TagQuery__11(r, wt, &m.Allowed)
			case 4:
				err = dec_list_helios_gameplay_SlotDescriptor__54(r, wt, &m.Slots)
			case 5:
				err = dec_Name_0(r, wt, &m.Access)
			default:
				err = r.skip(wt)
		}
		if err != nil {
			return err
		}
	}
	return nil
}

// MarshalHelios encodes the tagged binary message (identical bytes to the C++ codec).
func (m *ContainerSpec) MarshalHelios() []byte { return m.appendFields(nil) }

// UnmarshalHelios decodes a tagged message; missing fields take their schema defaults.
func (m *ContainerSpec) UnmarshalHelios(b []byte) error {
	*m = NewContainerSpec()
	return m.readFields(newWireReader(b))
}

// UnmarshalJSON reads JSON (e.g. canonical JSONC written by the C++ codec); missing fields keep defaults.
func (m *ContainerSpec) UnmarshalJSON(b []byte) error {
	type plain ContainerSpec
	p := plain(NewContainerSpec())
	if err := json.Unmarshal(b, &p); err != nil {
		return err
	}
	*m = ContainerSpec(p)
	return nil
}

// An item port on a ship or vehicle (06 §8.4).
type ItemPortSpec struct {
	// Port type (weapon, shield, cooler...).
	PortType string `json:"portType"`
	// Smallest item size the port takes.
	MinSize uint8 `json:"minSize"`
	// Largest item size the port takes.
	MaxSize uint8 `json:"maxSize"`
	// Items the port accepts.
	Accepts *TagQuery `json:"accepts,omitempty"`
}

// NewItemPortSpec returns a ItemPortSpec with every field at its schema default.
func NewItemPortSpec() ItemPortSpec {
	return ItemPortSpec{PortType: zero_Name_0(), MinSize: zero_u8_3(), MaxSize: zero_u8_3(), }
}

func (m *ItemPortSpec) isDefault() bool {
	return def_Name_0(m.PortType) &&
		def_u8_3(m.MinSize) &&
		def_u8_3(m.MaxSize) &&
		def_TagQuery__11(m.Accepts)
}

func (m *ItemPortSpec) appendFields(b []byte) []byte {
	if !(def_Name_0(m.PortType)) {
		b = enc_Name_0(b, 1, m.PortType)
	}
	if !(def_u8_3(m.MinSize)) {
		b = enc_u8_3(b, 2, m.MinSize)
	}
	if !(def_u8_3(m.MaxSize)) {
		b = enc_u8_3(b, 3, m.MaxSize)
	}
	if !(def_TagQuery__11(m.Accepts)) {
		b = enc_TagQuery__11(b, 4, m.Accepts)
	}
	return b
}

func (m *ItemPortSpec) readFields(r *wireReader) error {
	for !r.atEnd() {
		id, wt, err := r.tag()
		if err != nil {
			return err
		}
		switch id {
			case 1:
				err = dec_Name_0(r, wt, &m.PortType)
			case 2:
				err = dec_u8_3(r, wt, &m.MinSize)
			case 3:
				err = dec_u8_3(r, wt, &m.MaxSize)
			case 4:
				err = dec_TagQuery__11(r, wt, &m.Accepts)
			default:
				err = r.skip(wt)
		}
		if err != nil {
			return err
		}
	}
	return nil
}

// MarshalHelios encodes the tagged binary message (identical bytes to the C++ codec).
func (m *ItemPortSpec) MarshalHelios() []byte { return m.appendFields(nil) }

// UnmarshalHelios decodes a tagged message; missing fields take their schema defaults.
func (m *ItemPortSpec) UnmarshalHelios(b []byte) error {
	*m = NewItemPortSpec()
	return m.readFields(newWireReader(b))
}

// UnmarshalJSON reads JSON (e.g. canonical JSONC written by the C++ codec); missing fields keep defaults.
func (m *ItemPortSpec) UnmarshalJSON(b []byte) error {
	type plain ItemPortSpec
	p := plain(NewItemPortSpec())
	if err := json.Unmarshal(b, &p); err != nil {
		return err
	}
	*m = ItemPortSpec(p)
	return nil
}

// Durability loss per use and per hour (06 §2 decay).
type DecaySpec struct {
	// Durability of a new item.
	MaxDurability float32 `json:"maxDurability"`
	// Loss per use.
	PerUse float32 `json:"perUse"`
	// Loss per hour of use.
	PerHour float32 `json:"perHour"`
}

var dfltDecaySpecMaxDurability = float32(1)
// NewDecaySpec returns a DecaySpec with every field at its schema default.
func NewDecaySpec() DecaySpec {
	return DecaySpec{MaxDurability: dfltDecaySpecMaxDurability, PerUse: zero_f32_52(), PerHour: zero_f32_52(), }
}

func (m *DecaySpec) isDefault() bool {
	return f32Bits(m.MaxDurability, dfltDecaySpecMaxDurability) &&
		def_f32_52(m.PerUse) &&
		def_f32_52(m.PerHour)
}

func (m *DecaySpec) appendFields(b []byte) []byte {
	if !(f32Bits(m.MaxDurability, dfltDecaySpecMaxDurability)) {
		b = enc_f32_52(b, 1, m.MaxDurability)
	}
	if !(def_f32_52(m.PerUse)) {
		b = enc_f32_52(b, 2, m.PerUse)
	}
	if !(def_f32_52(m.PerHour)) {
		b = enc_f32_52(b, 3, m.PerHour)
	}
	return b
}

func (m *DecaySpec) readFields(r *wireReader) error {
	for !r.atEnd() {
		id, wt, err := r.tag()
		if err != nil {
			return err
		}
		switch id {
			case 1:
				err = dec_f32_52(r, wt, &m.MaxDurability)
			case 2:
				err = dec_f32_52(r, wt, &m.PerUse)
			case 3:
				err = dec_f32_52(r, wt, &m.PerHour)
			default:
				err = r.skip(wt)
		}
		if err != nil {
			return err
		}
	}
	return nil
}

// MarshalHelios encodes the tagged binary message (identical bytes to the C++ codec).
func (m *DecaySpec) MarshalHelios() []byte { return m.appendFields(nil) }

// UnmarshalHelios decodes a tagged message; missing fields take their schema defaults.
func (m *DecaySpec) UnmarshalHelios(b []byte) error {
	*m = NewDecaySpec()
	return m.readFields(newWireReader(b))
}

// UnmarshalJSON reads JSON (e.g. canonical JSONC written by the C++ codec); missing fields keep defaults.
func (m *DecaySpec) UnmarshalJSON(b []byte) error {
	type plain DecaySpec
	p := plain(NewDecaySpec())
	if err := json.Unmarshal(b, &p); err != nil {
		return err
	}
	*m = DecaySpec(p)
	return nil
}

// An item template (06 §2; DataForge-style typed record).
type ItemDef struct {
	// Display name.
	Name LocString `json:"name"`
	// Tags of the item (Item.Weapon.Laser).
	Tags TagSet `json:"tags"`
	// Largest stack; 1 for items with per-instance state.
	StackMax uint32 `json:"stackMax"`
	// Volume of one unit.
	Volume float32 `json:"volume"`
	// Mass of one unit.
	Mass float32 `json:"mass"`
	// Base attribute values of the item.
	BaseAttrs map[AttributeRef]float64 `json:"baseAttrs,omitempty"`
	// Effects applied per Dogma state (Offline/Online/Active/Overloaded).
	StateEffects map[ItemState][]EffectRef `json:"stateEffects,omitempty"`
	// The item occupies ALL slots of ONE arrangement (SWG); slot names until a SlotDef exists.
	Arrangements [][]string `json:"arrangements,omitempty"`
	// Sockets for plugs.
	Sockets []SocketEntry `json:"sockets,omitempty"`
	// Requirement to equip or use.
	EquipReq Requirement `json:"equipReq"`
	// Makes the item a container.
	Container *ContainerSpec `json:"container,omitempty"`
	// Makes the item an item port.
	Port *ItemPortSpec `json:"port,omitempty"`
	// Binding rule (soulbound, account-bound).
	Bind BindRule `json:"bind"`
	// Durability loss.
	Decay *DecaySpec `json:"decay,omitempty"`
	// InsuranceClassDef name (Phase 4); empty = uninsurable.
	Insurance string `json:"insurance"`
	// LifetimePolicyDef name (05 §1.17 lifetime policies).
	Lifetime string `json:"lifetime"`
	// Prefab spawned for the item in the world.
	Appearance AssetRef `json:"appearance"`
	// Inventory icon.
	Icon AssetRef `json:"icon"`
}

var dfltItemDefStackMax = uint32(1)
var dfltItemDefBind = BindRuleNone
// NewItemDef returns a ItemDef with every field at its schema default.
func NewItemDef() ItemDef {
	return ItemDef{Name: zero_LocString_4(), Tags: zero_TagSet_40(), StackMax: dfltItemDefStackMax, Volume: zero_f32_52(), Mass: zero_f32_52(), EquipReq: zero_helios_gameplay_Requirement_55(), Bind: dfltItemDefBind, Insurance: zero_Name_0(), Lifetime: zero_Name_0(), Appearance: zero_AssetRef_Prefab__56(), Icon: zero_AssetRef_Texture__57(), }
}

func (m *ItemDef) isDefault() bool {
	return def_LocString_4(m.Name) &&
		def_TagSet_40(m.Tags) &&
		m.StackMax == dfltItemDefStackMax &&
		def_f32_52(m.Volume) &&
		def_f32_52(m.Mass) &&
		def_p_Ref_helios_gameplay_AttributeDef__f64__58(m.BaseAttrs) &&
		def_te_list_Ref_helios_gameplay_EffectDef____59(m.StateEffects) &&
		def_list_list_Name___60(m.Arrangements) &&
		def_list_helios_gameplay_SocketEntry__61(m.Sockets) &&
		def_helios_gameplay_Requirement_55(m.EquipReq) &&
		def_helios_gameplay_ContainerSpec__62(m.Container) &&
		def_helios_gameplay_ItemPortSpec__63(m.Port) &&
		m.Bind == dfltItemDefBind &&
		def_helios_gameplay_DecaySpec__64(m.Decay) &&
		def_Name_0(m.Insurance) &&
		def_Name_0(m.Lifetime) &&
		def_AssetRef_Prefab__56(m.Appearance) &&
		def_AssetRef_Texture__57(m.Icon)
}

func (m *ItemDef) appendFields(b []byte) []byte {
	if !(def_LocString_4(m.Name)) {
		b = enc_LocString_4(b, 1, m.Name)
	}
	if !(def_TagSet_40(m.Tags)) {
		b = enc_TagSet_40(b, 2, m.Tags)
	}
	if !(m.StackMax == dfltItemDefStackMax) {
		b = enc_u32_53(b, 3, m.StackMax)
	}
	if !(def_f32_52(m.Volume)) {
		b = enc_f32_52(b, 4, m.Volume)
	}
	if !(def_f32_52(m.Mass)) {
		b = enc_f32_52(b, 5, m.Mass)
	}
	if !(def_p_Ref_helios_gameplay_AttributeDef__f64__58(m.BaseAttrs)) {
		b = enc_p_Ref_helios_gameplay_AttributeDef__f64__58(b, 6, m.BaseAttrs)
	}
	if !(def_te_list_Ref_helios_gameplay_EffectDef____59(m.StateEffects)) {
		b = enc_te_list_Ref_helios_gameplay_EffectDef____59(b, 7, m.StateEffects)
	}
	if !(def_list_list_Name___60(m.Arrangements)) {
		b = enc_list_list_Name___60(b, 8, m.Arrangements)
	}
	if !(def_list_helios_gameplay_SocketEntry__61(m.Sockets)) {
		b = enc_list_helios_gameplay_SocketEntry__61(b, 9, m.Sockets)
	}
	if !(def_helios_gameplay_Requirement_55(m.EquipReq)) {
		b = enc_helios_gameplay_Requirement_55(b, 10, m.EquipReq)
	}
	if !(def_helios_gameplay_ContainerSpec__62(m.Container)) {
		b = enc_helios_gameplay_ContainerSpec__62(b, 11, m.Container)
	}
	if !(def_helios_gameplay_ItemPortSpec__63(m.Port)) {
		b = enc_helios_gameplay_ItemPortSpec__63(b, 12, m.Port)
	}
	if !(m.Bind == dfltItemDefBind) {
		b = enc_helios_gameplay_BindRule_65(b, 13, m.Bind)
	}
	if !(def_helios_gameplay_DecaySpec__64(m.Decay)) {
		b = enc_helios_gameplay_DecaySpec__64(b, 14, m.Decay)
	}
	if !(def_Name_0(m.Insurance)) {
		b = enc_Name_0(b, 15, m.Insurance)
	}
	if !(def_Name_0(m.Lifetime)) {
		b = enc_Name_0(b, 16, m.Lifetime)
	}
	if !(def_AssetRef_Prefab__56(m.Appearance)) {
		b = enc_AssetRef_Prefab__56(b, 17, m.Appearance)
	}
	if !(def_AssetRef_Texture__57(m.Icon)) {
		b = enc_AssetRef_Texture__57(b, 18, m.Icon)
	}
	return b
}

func (m *ItemDef) readFields(r *wireReader) error {
	for !r.atEnd() {
		id, wt, err := r.tag()
		if err != nil {
			return err
		}
		switch id {
			case 1:
				err = dec_LocString_4(r, wt, &m.Name)
			case 2:
				err = dec_TagSet_40(r, wt, &m.Tags)
			case 3:
				err = dec_u32_53(r, wt, &m.StackMax)
			case 4:
				err = dec_f32_52(r, wt, &m.Volume)
			case 5:
				err = dec_f32_52(r, wt, &m.Mass)
			case 6:
				err = dec_p_Ref_helios_gameplay_AttributeDef__f64__58(r, wt, &m.BaseAttrs)
			case 7:
				err = dec_te_list_Ref_helios_gameplay_EffectDef____59(r, wt, &m.StateEffects)
			case 8:
				err = dec_list_list_Name___60(r, wt, &m.Arrangements)
			case 9:
				err = dec_list_helios_gameplay_SocketEntry__61(r, wt, &m.Sockets)
			case 10:
				err = dec_helios_gameplay_Requirement_55(r, wt, &m.EquipReq)
			case 11:
				err = dec_helios_gameplay_ContainerSpec__62(r, wt, &m.Container)
			case 12:
				err = dec_helios_gameplay_ItemPortSpec__63(r, wt, &m.Port)
			case 13:
				err = dec_helios_gameplay_BindRule_65(r, wt, &m.Bind)
			case 14:
				err = dec_helios_gameplay_DecaySpec__64(r, wt, &m.Decay)
			case 15:
				err = dec_Name_0(r, wt, &m.Insurance)
			case 16:
				err = dec_Name_0(r, wt, &m.Lifetime)
			case 17:
				err = dec_AssetRef_Prefab__56(r, wt, &m.Appearance)
			case 18:
				err = dec_AssetRef_Texture__57(r, wt, &m.Icon)
			default:
				err = r.skip(wt)
		}
		if err != nil {
			return err
		}
	}
	return nil
}

// MarshalHelios encodes the tagged binary message (identical bytes to the C++ codec).
func (m *ItemDef) MarshalHelios() []byte { return m.appendFields(nil) }

// UnmarshalHelios decodes a tagged message; missing fields take their schema defaults.
func (m *ItemDef) UnmarshalHelios(b []byte) error {
	*m = NewItemDef()
	return m.readFields(newWireReader(b))
}

// UnmarshalJSON reads JSON (e.g. canonical JSONC written by the C++ codec); missing fields keep defaults.
func (m *ItemDef) UnmarshalJSON(b []byte) error {
	type plain ItemDef
	p := plain(NewItemDef())
	if err := json.Unmarshal(b, &p); err != nil {
		return err
	}
	*m = ItemDef(p)
	return nil
}

// ItemRef references a ItemDef record by RecordId.
type ItemRef uint64

type OwnerRef struct {
	// Kind of owner.
	Kind OwnerKind `json:"kind"`
	// Owner id (character, corporation, account, ...).
	Id uint64 `json:"id"`
}

// NewOwnerRef returns a OwnerRef with every field at its schema default.
func NewOwnerRef() OwnerRef {
	return OwnerRef{Kind: zero_helios_gameplay_OwnerKind_66(), Id: zero_u64_67(), }
}

func (m *OwnerRef) isDefault() bool {
	return def_helios_gameplay_OwnerKind_66(m.Kind) &&
		def_u64_67(m.Id)
}

func (m *OwnerRef) appendFields(b []byte) []byte {
	if !(def_helios_gameplay_OwnerKind_66(m.Kind)) {
		b = enc_helios_gameplay_OwnerKind_66(b, 1, m.Kind)
	}
	if !(def_u64_67(m.Id)) {
		b = enc_u64_67(b, 2, m.Id)
	}
	return b
}

func (m *OwnerRef) readFields(r *wireReader) error {
	for !r.atEnd() {
		id, wt, err := r.tag()
		if err != nil {
			return err
		}
		switch id {
			case 1:
				err = dec_helios_gameplay_OwnerKind_66(r, wt, &m.Kind)
			case 2:
				err = dec_u64_67(r, wt, &m.Id)
			default:
				err = r.skip(wt)
		}
		if err != nil {
			return err
		}
	}
	return nil
}

// MarshalHelios encodes the tagged binary message (identical bytes to the C++ codec).
func (m *OwnerRef) MarshalHelios() []byte { return m.appendFields(nil) }

// UnmarshalHelios decodes a tagged message; missing fields take their schema defaults.
func (m *OwnerRef) UnmarshalHelios(b []byte) error {
	*m = NewOwnerRef()
	return m.readFields(newWireReader(b))
}

// UnmarshalJSON reads JSON (e.g. canonical JSONC written by the C++ codec); missing fields keep defaults.
func (m *OwnerRef) UnmarshalJSON(b []byte) error {
	type plain OwnerRef
	p := plain(NewOwnerRef())
	if err := json.Unmarshal(b, &p); err != nil {
		return err
	}
	*m = OwnerRef(p)
	return nil
}

type LocationRef struct {
	// Kind of location.
	Kind LocationKind `json:"kind"`
	// Location id (container item, entity, hangar, space region).
	Id uint64 `json:"id"`
}

// NewLocationRef returns a LocationRef with every field at its schema default.
func NewLocationRef() LocationRef {
	return LocationRef{Kind: zero_helios_gameplay_LocationKind_68(), Id: zero_u64_67(), }
}

func (m *LocationRef) isDefault() bool {
	return def_helios_gameplay_LocationKind_68(m.Kind) &&
		def_u64_67(m.Id)
}

func (m *LocationRef) appendFields(b []byte) []byte {
	if !(def_helios_gameplay_LocationKind_68(m.Kind)) {
		b = enc_helios_gameplay_LocationKind_68(b, 1, m.Kind)
	}
	if !(def_u64_67(m.Id)) {
		b = enc_u64_67(b, 2, m.Id)
	}
	return b
}

func (m *LocationRef) readFields(r *wireReader) error {
	for !r.atEnd() {
		id, wt, err := r.tag()
		if err != nil {
			return err
		}
		switch id {
			case 1:
				err = dec_helios_gameplay_LocationKind_68(r, wt, &m.Kind)
			case 2:
				err = dec_u64_67(r, wt, &m.Id)
			default:
				err = r.skip(wt)
		}
		if err != nil {
			return err
		}
	}
	return nil
}

// MarshalHelios encodes the tagged binary message (identical bytes to the C++ codec).
func (m *LocationRef) MarshalHelios() []byte { return m.appendFields(nil) }

// UnmarshalHelios decodes a tagged message; missing fields take their schema defaults.
func (m *LocationRef) UnmarshalHelios(b []byte) error {
	*m = NewLocationRef()
	return m.readFields(newWireReader(b))
}

// UnmarshalJSON reads JSON (e.g. canonical JSONC written by the C++ codec); missing fields keep defaults.
func (m *LocationRef) UnmarshalJSON(b []byte) error {
	type plain LocationRef
	p := plain(NewLocationRef())
	if err := json.Unmarshal(b, &p); err != nil {
		return err
	}
	*m = LocationRef(p)
	return nil
}

// Who crafted an item (06 §3); the crafter's name is resolved from the id at display time.
type CraftStamp struct {
	// Character id of the crafter.
	CrafterId uint64 `json:"crafterId"`
	// Schematic used.
	Schematic string `json:"schematic"`
	// Crafted quality.
	Quality float32 `json:"quality"`
	// Serial number of the craft.
	Serial uint64 `json:"serial"`
}

// NewCraftStamp returns a CraftStamp with every field at its schema default.
func NewCraftStamp() CraftStamp {
	return CraftStamp{CrafterId: zero_u64_67(), Schematic: zero_Name_0(), Quality: zero_f32_52(), Serial: zero_u64_67(), }
}

func (m *CraftStamp) isDefault() bool {
	return def_u64_67(m.CrafterId) &&
		def_Name_0(m.Schematic) &&
		def_f32_52(m.Quality) &&
		def_u64_67(m.Serial)
}

func (m *CraftStamp) appendFields(b []byte) []byte {
	if !(def_u64_67(m.CrafterId)) {
		b = enc_u64_67(b, 1, m.CrafterId)
	}
	if !(def_Name_0(m.Schematic)) {
		b = enc_Name_0(b, 2, m.Schematic)
	}
	if !(def_f32_52(m.Quality)) {
		b = enc_f32_52(b, 3, m.Quality)
	}
	if !(def_u64_67(m.Serial)) {
		b = enc_u64_67(b, 4, m.Serial)
	}
	return b
}

func (m *CraftStamp) readFields(r *wireReader) error {
	for !r.atEnd() {
		id, wt, err := r.tag()
		if err != nil {
			return err
		}
		switch id {
			case 1:
				err = dec_u64_67(r, wt, &m.CrafterId)
			case 2:
				err = dec_Name_0(r, wt, &m.Schematic)
			case 3:
				err = dec_f32_52(r, wt, &m.Quality)
			case 4:
				err = dec_u64_67(r, wt, &m.Serial)
			default:
				err = r.skip(wt)
		}
		if err != nil {
			return err
		}
	}
	return nil
}

// MarshalHelios encodes the tagged binary message (identical bytes to the C++ codec).
func (m *CraftStamp) MarshalHelios() []byte { return m.appendFields(nil) }

// UnmarshalHelios decodes a tagged message; missing fields take their schema defaults.
func (m *CraftStamp) UnmarshalHelios(b []byte) error {
	*m = NewCraftStamp()
	return m.readFields(newWireReader(b))
}

// UnmarshalJSON reads JSON (e.g. canonical JSONC written by the C++ codec); missing fields keep defaults.
func (m *CraftStamp) UnmarshalJSON(b []byte) error {
	type plain CraftStamp
	p := plain(NewCraftStamp())
	if err := json.Unmarshal(b, &p); err != nil {
		return err
	}
	*m = CraftStamp(p)
	return nil
}

// Placement of a physicalized item (Phase 5 cargo).
type Xform struct {
	// Frame-local position.
	Position DVec3 `json:"position"`
	// Orientation.
	Rotation Quat `json:"rotation"`
}

// NewXform returns a Xform with every field at its schema default.
func NewXform() Xform {
	return Xform{Position: zero_vec3d_69(), Rotation: zero_quatf_70(), }
}

func (m *Xform) isDefault() bool {
	return def_vec3d_69(m.Position) &&
		def_quatf_70(m.Rotation)
}

func (m *Xform) appendFields(b []byte) []byte {
	if !(def_vec3d_69(m.Position)) {
		b = enc_vec3d_69(b, 1, m.Position)
	}
	if !(def_quatf_70(m.Rotation)) {
		b = enc_quatf_70(b, 2, m.Rotation)
	}
	return b
}

func (m *Xform) readFields(r *wireReader) error {
	for !r.atEnd() {
		id, wt, err := r.tag()
		if err != nil {
			return err
		}
		switch id {
			case 1:
				err = dec_vec3d_69(r, wt, &m.Position)
			case 2:
				err = dec_quatf_70(r, wt, &m.Rotation)
			default:
				err = r.skip(wt)
		}
		if err != nil {
			return err
		}
	}
	return nil
}

// MarshalHelios encodes the tagged binary message (identical bytes to the C++ codec).
func (m *Xform) MarshalHelios() []byte { return m.appendFields(nil) }

// UnmarshalHelios decodes a tagged message; missing fields take their schema defaults.
func (m *Xform) UnmarshalHelios(b []byte) error {
	*m = NewXform()
	return m.readFields(newWireReader(b))
}

// UnmarshalJSON reads JSON (e.g. canonical JSONC written by the C++ codec); missing fields keep defaults.
func (m *Xform) UnmarshalJSON(b []byte) error {
	type plain Xform
	p := plain(NewXform())
	if err := json.Unmarshal(b, &p); err != nil {
		return err
	}
	*m = Xform(p)
	return nil
}

// Mutable per-instance state (06 §2 ItemInstance.payload; JSONB in the ledger).
type ItemPayload struct {
	// Inserted plugs, per socket.
	Plugs []ItemRef `json:"plugs,omitempty"`
	// Rolled attribute values.
	Rolled map[AttributeRef]float64 `json:"rolled,omitempty"`
	// Crafter stamp of crafted items.
	Crafted *CraftStamp `json:"crafted,omitempty"`
	// RollAudit id (seeded, auditable rolls; 06 §2).
	RollAudit *uint64 `json:"rollAudit,omitempty"`
	// Current durability.
	Durability float32 `json:"durability"`
	// Player-given name.
	CustomName *string `json:"customName,omitempty"`
	// Placement when physicalized.
	Transform *Xform `json:"transform,omitempty"`
}

var dfltItemPayloadDurability = float32(1)
// NewItemPayload returns a ItemPayload with every field at its schema default.
func NewItemPayload() ItemPayload {
	return ItemPayload{Durability: dfltItemPayloadDurability, }
}

func (m *ItemPayload) isDefault() bool {
	return def_list_Ref_helios_gameplay_ItemDef___71(m.Plugs) &&
		def_p_Ref_helios_gameplay_AttributeDef__f64__58(m.Rolled) &&
		def_helios_gameplay_CraftStamp__72(m.Crafted) &&
		def_u64__73(m.RollAudit) &&
		f32Bits(m.Durability, dfltItemPayloadDurability) &&
		def_string__74(m.CustomName) &&
		def_helios_gameplay_Xform__75(m.Transform)
}

func (m *ItemPayload) appendFields(b []byte) []byte {
	if !(def_list_Ref_helios_gameplay_ItemDef___71(m.Plugs)) {
		b = enc_list_Ref_helios_gameplay_ItemDef___71(b, 1, m.Plugs)
	}
	if !(def_p_Ref_helios_gameplay_AttributeDef__f64__58(m.Rolled)) {
		b = enc_p_Ref_helios_gameplay_AttributeDef__f64__58(b, 2, m.Rolled)
	}
	if !(def_helios_gameplay_CraftStamp__72(m.Crafted)) {
		b = enc_helios_gameplay_CraftStamp__72(b, 3, m.Crafted)
	}
	if !(def_u64__73(m.RollAudit)) {
		b = enc_u64__73(b, 4, m.RollAudit)
	}
	if !(f32Bits(m.Durability, dfltItemPayloadDurability)) {
		b = enc_f32_52(b, 5, m.Durability)
	}
	if !(def_string__74(m.CustomName)) {
		b = enc_string__74(b, 6, m.CustomName)
	}
	if !(def_helios_gameplay_Xform__75(m.Transform)) {
		b = enc_helios_gameplay_Xform__75(b, 7, m.Transform)
	}
	return b
}

func (m *ItemPayload) readFields(r *wireReader) error {
	for !r.atEnd() {
		id, wt, err := r.tag()
		if err != nil {
			return err
		}
		switch id {
			case 1:
				err = dec_list_Ref_helios_gameplay_ItemDef___71(r, wt, &m.Plugs)
			case 2:
				err = dec_p_Ref_helios_gameplay_AttributeDef__f64__58(r, wt, &m.Rolled)
			case 3:
				err = dec_helios_gameplay_CraftStamp__72(r, wt, &m.Crafted)
			case 4:
				err = dec_u64__73(r, wt, &m.RollAudit)
			case 5:
				err = dec_f32_52(r, wt, &m.Durability)
			case 6:
				err = dec_string__74(r, wt, &m.CustomName)
			case 7:
				err = dec_helios_gameplay_Xform__75(r, wt, &m.Transform)
			default:
				err = r.skip(wt)
		}
		if err != nil {
			return err
		}
	}
	return nil
}

// MarshalHelios encodes the tagged binary message (identical bytes to the C++ codec).
func (m *ItemPayload) MarshalHelios() []byte { return m.appendFields(nil) }

// UnmarshalHelios decodes a tagged message; missing fields take their schema defaults.
func (m *ItemPayload) UnmarshalHelios(b []byte) error {
	*m = NewItemPayload()
	return m.readFields(newWireReader(b))
}

// UnmarshalJSON reads JSON (e.g. canonical JSONC written by the C++ codec); missing fields keep defaults.
func (m *ItemPayload) UnmarshalJSON(b []byte) error {
	type plain ItemPayload
	p := plain(NewItemPayload())
	if err := json.Unmarshal(b, &p); err != nil {
		return err
	}
	*m = ItemPayload(p)
	return nil
}

// An item instance: a ledger row (05 §1.6) with an EVE-style location tree.
type ItemInstance struct {
	// Block-allocated item id (05 §1.4.5).
	ItemId uint64 `json:"itemId"`
	// The item template.
	Def ItemRef `json:"def"`
	// Current owner.
	Owner OwnerRef `json:"owner"`
	// Current location.
	Location LocationRef `json:"location"`
	// Slot or hangar flag inside the location (EVE location tree).
	Flag uint16 `json:"flag"`
	// Stack size.
	Quantity uint32 `json:"quantity"`
	// Optimistic-concurrency version of the ledger row.
	Version uint64 `json:"version"`
	// Authority-group fence epoch while in custody.
	FenceEpoch uint64 `json:"fenceEpoch"`
	// Per-instance state.
	Payload ItemPayload `json:"payload"`
}

var dfltItemInstanceQuantity = uint32(1)
// NewItemInstance returns a ItemInstance with every field at its schema default.
func NewItemInstance() ItemInstance {
	return ItemInstance{ItemId: zero_u64_67(), Def: zero_Ref_helios_gameplay_ItemDef__76(), Owner: zero_helios_gameplay_OwnerRef_77(), Location: zero_helios_gameplay_LocationRef_78(), Flag: zero_u16_17(), Quantity: dfltItemInstanceQuantity, Version: zero_u64_67(), FenceEpoch: zero_u64_67(), Payload: zero_helios_gameplay_ItemPayload_79(), }
}

func (m *ItemInstance) isDefault() bool {
	return def_u64_67(m.ItemId) &&
		def_Ref_helios_gameplay_ItemDef__76(m.Def) &&
		def_helios_gameplay_OwnerRef_77(m.Owner) &&
		def_helios_gameplay_LocationRef_78(m.Location) &&
		def_u16_17(m.Flag) &&
		m.Quantity == dfltItemInstanceQuantity &&
		def_u64_67(m.Version) &&
		def_u64_67(m.FenceEpoch) &&
		def_helios_gameplay_ItemPayload_79(m.Payload)
}

func (m *ItemInstance) appendFields(b []byte) []byte {
	if !(def_u64_67(m.ItemId)) {
		b = enc_u64_67(b, 1, m.ItemId)
	}
	if !(def_Ref_helios_gameplay_ItemDef__76(m.Def)) {
		b = enc_Ref_helios_gameplay_ItemDef__76(b, 2, m.Def)
	}
	if !(def_helios_gameplay_OwnerRef_77(m.Owner)) {
		b = enc_helios_gameplay_OwnerRef_77(b, 3, m.Owner)
	}
	if !(def_helios_gameplay_LocationRef_78(m.Location)) {
		b = enc_helios_gameplay_LocationRef_78(b, 4, m.Location)
	}
	if !(def_u16_17(m.Flag)) {
		b = enc_u16_17(b, 5, m.Flag)
	}
	if !(m.Quantity == dfltItemInstanceQuantity) {
		b = enc_u32_53(b, 6, m.Quantity)
	}
	if !(def_u64_67(m.Version)) {
		b = enc_u64_67(b, 7, m.Version)
	}
	if !(def_u64_67(m.FenceEpoch)) {
		b = enc_u64_67(b, 8, m.FenceEpoch)
	}
	if !(def_helios_gameplay_ItemPayload_79(m.Payload)) {
		b = enc_helios_gameplay_ItemPayload_79(b, 9, m.Payload)
	}
	return b
}

func (m *ItemInstance) readFields(r *wireReader) error {
	for !r.atEnd() {
		id, wt, err := r.tag()
		if err != nil {
			return err
		}
		switch id {
			case 1:
				err = dec_u64_67(r, wt, &m.ItemId)
			case 2:
				err = dec_Ref_helios_gameplay_ItemDef__76(r, wt, &m.Def)
			case 3:
				err = dec_helios_gameplay_OwnerRef_77(r, wt, &m.Owner)
			case 4:
				err = dec_helios_gameplay_LocationRef_78(r, wt, &m.Location)
			case 5:
				err = dec_u16_17(r, wt, &m.Flag)
			case 6:
				err = dec_u32_53(r, wt, &m.Quantity)
			case 7:
				err = dec_u64_67(r, wt, &m.Version)
			case 8:
				err = dec_u64_67(r, wt, &m.FenceEpoch)
			case 9:
				err = dec_helios_gameplay_ItemPayload_79(r, wt, &m.Payload)
			default:
				err = r.skip(wt)
		}
		if err != nil {
			return err
		}
	}
	return nil
}

// MarshalHelios encodes the tagged binary message (identical bytes to the C++ codec).
func (m *ItemInstance) MarshalHelios() []byte { return m.appendFields(nil) }

// UnmarshalHelios decodes a tagged message; missing fields take their schema defaults.
func (m *ItemInstance) UnmarshalHelios(b []byte) error {
	*m = NewItemInstance()
	return m.readFields(newWireReader(b))
}

// UnmarshalJSON reads JSON (e.g. canonical JSONC written by the C++ codec); missing fields keep defaults.
func (m *ItemInstance) UnmarshalJSON(b []byte) error {
	type plain ItemInstance
	p := plain(NewItemInstance())
	if err := json.Unmarshal(b, &p); err != nil {
		return err
	}
	*m = ItemInstance(p)
	return nil
}

