// Code generated by helios-schemac from gameplay/tags.hschema. DO NOT EDIT.

package gamedef

import (
	"encoding/json"
	"fmt"
	"math"
)

var _ = json.Marshal
var _ = fmt.Errorf
var _ = math.MaxInt8

type Audience uint8

const (
	AudienceServer Audience = 0
	AudienceOwner Audience = 1
	AudienceAll Audience = 2
)

var namesAudience = []enumName{{"Server", 0}, {"Owner", 1}, {"All", 2}, }

func (v Audience) MarshalJSON() ([]byte, error) { return enumToJSON(namesAudience, int64(v)) }
func (v *Audience) UnmarshalJSON(b []byte) error {
	x, err := enumFromJSON(namesAudience, b)
	*v = Audience(x)
	return err
}
func (v Audience) MarshalText() ([]byte, error) { return enumToText(namesAudience, int64(v)), nil }
func (v *Audience) UnmarshalText(b []byte) error {
	x, err := enumFromText(namesAudience, string(b))
	*v = Audience(x)
	return err
}

// A gameplay tag declaration (06 §1.1). One record per tag; ancestors are implied, so declaring
// "State.Debuff.Stun" also declares "State.Debuff" and "State". The registry interns tags to dense
// u16 TagIndex values in canonical (segment-wise sorted) order, so ids depend only on the set of
// names, never on load order.
type TagDef struct {
	// Full dotted name; segments are [A-Za-z_][A-Za-z0-9_]* ("Ship.Class.Frigate").
	Tag string `json:"tag"`
	// Audience of the tag when an entity holds it explicitly (06 §1.6: explicit tags replicate per
	// declaration, as index deltas).
	Replicate Audience `json:"replicate"`
}

var dfltTagDefReplicate = AudienceServer
// NewTagDef returns a TagDef with every field at its schema default.
func NewTagDef() TagDef {
	return TagDef{Tag: zero_Name_0(), Replicate: dfltTagDefReplicate, }
}

func (m *TagDef) isDefault() bool {
	return def_Name_0(m.Tag) &&
		m.Replicate == dfltTagDefReplicate
}

func (m *TagDef) appendFields(b []byte) []byte {
	if !(def_Name_0(m.Tag)) {
		b = enc_Name_0(b, 1, m.Tag)
	}
	if !(m.Replicate == dfltTagDefReplicate) {
		b = enc_helios_gameplay_Audience_1(b, 2, m.Replicate)
	}
	return b
}

func (m *TagDef) readFields(r *wireReader) error {
	for !r.atEnd() {
		id, wt, err := r.tag()
		if err != nil {
			return err
		}
		switch id {
			case 1:
				err = dec_Name_0(r, wt, &m.Tag)
			case 2:
				err = dec_helios_gameplay_Audience_1(r, wt, &m.Replicate)
			default:
				err = r.skip(wt)
		}
		if err != nil {
			return err
		}
	}
	return nil
}

// MarshalHelios encodes the tagged binary message (identical bytes to the C++ codec).
func (m *TagDef) MarshalHelios() []byte { return m.appendFields(nil) }

// UnmarshalHelios decodes a tagged message; missing fields take their schema defaults.
func (m *TagDef) UnmarshalHelios(b []byte) error {
	*m = NewTagDef()
	return m.readFields(newWireReader(b))
}

// UnmarshalJSON reads JSON (e.g. canonical JSONC written by the C++ codec); missing fields keep defaults.
func (m *TagDef) UnmarshalJSON(b []byte) error {
	type plain TagDef
	p := plain(NewTagDef())
	if err := json.Unmarshal(b, &p); err != nil {
		return err
	}
	*m = TagDef(p)
	return nil
}

// TagRef references a TagDef record by RecordId.
type TagRef uint64

