# Slang shader compilation (ADR-003, docs/plan/03-rendering.md §1.7).
#
#   include(HeliosShaders)
#   helios_shaders(<target>
#       FILES <a.slang> [<b.slang> ...]     # one SPIR-V module per file
#       [NAMESPACE <c++::namespace>]         # default: <target>_shaders
#       [INCLUDE_DIRS <dir> ...]             # extra import/include roots (shaders/ is always one)
#       [DEFINES <NAME[=VALUE]> ...]
#       [FLAGS <extra slangc flags> ...])
#
# Entry points are declared in each file with `[shader("vertex")]`, `[shader("fragment")]`,
# `[shader("compute")]`, ...: slangc compiles every declared entry point of a file into a single
# SPIR-V 1.6 module and keeps their source names (`-fvk-use-entrypoint-name`), so a pipeline
# selects them by name (e.g. "vsMain"/"psMain").
#
# At build time each file becomes `<binary-dir>/<target>_shaders/<stem>.spv` (dependencies on
# imported modules come from slangc's depfile) and is embedded into <target> as a word array.
# The generated header `<target>_shaders.h` (on <target>'s private include path) declares
#
#   namespace <ns> {
#   std::span<const std::uint32_t> <stem>() noexcept;              // one per file (C identifier of the stem)
#   std::span<const std::uint32_t> find(std::string_view stem) noexcept;  // empty if unknown
#   std::span<const std::string_view> names() noexcept;
#   }
#
# Code conventions baked into the flags (see shaders/README.md): column-major matrices (same
# memory layout as helios::math, `mul(M, v)` == `M * v`), scalar block layout for push constants
# and buffers (C++ structs map 1:1 with natural alignment), bindless heap aliases in set 0.
#
# The compiler comes from tools/prebuilt/fetch_slang.cmake (pinned, SHA-256 verified) or from
# HELIOS_SLANG_ROOT. This file doubles as the build-time embedding script (cmake -P mode).

# ---------------------------------------------------------------------------------------------
# Script mode: embed one .spv file as a C++ source.
#   cmake -DHELIOS_EMBED_INPUT=<spv> -DHELIOS_EMBED_OUTPUT=<cpp> -DHELIOS_EMBED_NAMESPACE=<ns>
#         -DHELIOS_EMBED_SYMBOL=<fn> -DHELIOS_EMBED_HEADER=<header> -P HeliosShaders.cmake
# ---------------------------------------------------------------------------------------------
if(CMAKE_SCRIPT_MODE_FILE AND DEFINED HELIOS_EMBED_INPUT)
  file(READ "${HELIOS_EMBED_INPUT}" hex HEX)
  string(LENGTH "${hex}" hex_length)
  math(EXPR byte_count "${hex_length} / 2")
  math(EXPR remainder "${byte_count} % 4")
  if(byte_count EQUAL 0 OR NOT remainder EQUAL 0)
    message(FATAL_ERROR "${HELIOS_EMBED_INPUT}: ${byte_count} bytes is not a SPIR-V word stream")
  endif()
  string(SUBSTRING "${hex}" 0 8 magic)
  if(NOT magic STREQUAL "03022307")
    message(FATAL_ERROR "${HELIOS_EMBED_INPUT}: missing SPIR-V magic number (got ${magic})")
  endif()
  # Little-endian bytes -> 32-bit words, eight per line.
  string(REGEX REPLACE "(..)(..)(..)(..)" "0x\\4\\3\\2\\1u," words "${hex}")
  set(w "0x[0-9a-f]+u,")  # CMake regexes have no {n} quantifier
  string(REGEX REPLACE "(${w}${w}${w}${w}${w}${w}${w}${w})" "\\1\n    " words "${words}")
  math(EXPR word_count "${byte_count} / 4")
  get_filename_component(input_name "${HELIOS_EMBED_INPUT}" NAME)
  file(WRITE "${HELIOS_EMBED_OUTPUT}.tmp"
"// Generated by cmake/HeliosShaders.cmake from ${input_name}. Do not edit.
#include \"${HELIOS_EMBED_HEADER}\"

namespace ${HELIOS_EMBED_NAMESPACE} {
namespace {
alignas(16) const std::uint32_t kWords[${word_count}] = {
    ${words}
};
} // namespace

std::span<const std::uint32_t> ${HELIOS_EMBED_SYMBOL}() noexcept { return {kWords, ${word_count}}; }
} // namespace ${HELIOS_EMBED_NAMESPACE}
")
  # Only touch the output when it changed so dependents do not rebuild needlessly.
  file(COPY_FILE "${HELIOS_EMBED_OUTPUT}.tmp" "${HELIOS_EMBED_OUTPUT}" ONLY_IF_DIFFERENT)
  file(REMOVE "${HELIOS_EMBED_OUTPUT}.tmp")
  return()
endif()

# Everything below runs once per build tree; the results live in global properties because
# include_guard(GLOBAL) skips this file in every other directory that includes it.
include_guard(GLOBAL)

option(HELIOS_SHADER_DEBUG_INFO "Compile shaders with -g2 -O0 (source-level debugging in RenderDoc/Nsight)" OFF)
# Import tracking uses slangc's depfile. Should a generator/platform ever mis-parse it, turn this off
# to fall back to depending on every .slang file under the import roots (coarser, always correct).
option(HELIOS_SHADER_DEPFILES "Track Slang imports through slangc depfiles" ON)

# Resolve slangc once per configure (the bootstrap itself is a fast stamp check when cached).
include("${CMAKE_CURRENT_LIST_DIR}/../tools/prebuilt/fetch_slang.cmake")
set(HELIOS_SLANG_ROOT "" CACHE PATH "Unpacked Slang release to use instead of the pinned download")
helios_fetch_slang(HELIOS_SLANG_RESOLVED_ROOT)
helios_slang_compiler_path("${HELIOS_SLANG_RESOLVED_ROOT}" HELIOS_SLANGC)
execute_process(COMMAND "${HELIOS_SLANGC}" -v OUTPUT_VARIABLE slangc_version ERROR_VARIABLE slangc_version
                RESULT_VARIABLE slangc_result OUTPUT_STRIP_TRAILING_WHITESPACE ERROR_STRIP_TRAILING_WHITESPACE)
if(NOT slangc_result EQUAL 0)
  message(FATAL_ERROR "slangc at ${HELIOS_SLANGC} does not run (${slangc_result}): ${slangc_version}")
endif()
if(NOT HELIOS_SLANG_ROOT AND NOT DEFINED ENV{HELIOS_SLANG_ROOT} AND NOT slangc_version STREQUAL HELIOS_SLANG_VERSION)
  message(FATAL_ERROR "Pinned slangc reports version '${slangc_version}', expected ${HELIOS_SLANG_VERSION}")
endif()
message(STATUS "Slang: ${HELIOS_SLANGC} (${slangc_version})")
set_property(GLOBAL PROPERTY HELIOS_SLANGC "${HELIOS_SLANGC}")

# Flags shared by every Helios shader. Kept in one place so the C++ side (engine/rhi) and the
# shaders agree on layouts:
#   -fvk-use-entrypoint-name   keep "vsMain"/"psMain"/... as SPIR-V entry names (many per module)
#   -matrix-layout-column-major  memory layout of helios::math::Mat4
#   -fvk-use-scalar-layout     scalar block layout (requires Vulkan 1.2 scalarBlockLayout)
#   -warnings-disable 41012    "profile implicitly upgraded" for capabilities we require anyway
#   -warnings-disable 39001    bindless heap arrays alias on purpose (shaders/core/bindless.slang)
set_property(GLOBAL PROPERTY HELIOS_SLANG_COMMON_FLAGS
  -target spirv -profile spirv_1_6 -fvk-use-entrypoint-name -matrix-layout-column-major
  -fvk-use-scalar-layout -warnings-disable 41012,39001)

function(helios_shaders target)
  cmake_parse_arguments(S "" "NAMESPACE" "FILES;INCLUDE_DIRS;DEFINES;FLAGS" ${ARGN})
  if(NOT TARGET ${target})
    message(FATAL_ERROR "helios_shaders: '${target}' is not a target")
  endif()
  if(NOT S_FILES)
    message(FATAL_ERROR "helios_shaders(${target}): FILES is empty")
  endif()
  get_target_property(already ${target} HELIOS_HAS_SHADERS)
  if(already)
    message(FATAL_ERROR "helios_shaders(${target}) may only be called once per target")
  endif()
  set_target_properties(${target} PROPERTIES HELIOS_HAS_SHADERS TRUE)

  get_property(slangc GLOBAL PROPERTY HELIOS_SLANGC)
  get_property(common_flags GLOBAL PROPERTY HELIOS_SLANG_COMMON_FLAGS)
  set(embed_script "${CMAKE_CURRENT_FUNCTION_LIST_FILE}")
  get_filename_component(shader_root "${CMAKE_CURRENT_FUNCTION_LIST_DIR}/../shaders" ABSOLUTE)
  if(NOT slangc)
    message(FATAL_ERROR "helios_shaders: slangc was not resolved (include(HeliosShaders) first)")
  endif()

  set(ns "${S_NAMESPACE}")
  if(NOT ns)
    string(MAKE_C_IDENTIFIER "${target}_shaders" ns)
  endif()

  set(out_dir "${CMAKE_CURRENT_BINARY_DIR}/${target}_shaders")
  set(include_dir "${out_dir}/include")
  set(header "${include_dir}/${target}_shaders.h")
  file(MAKE_DIRECTORY "${out_dir}" "${include_dir}")

  set(include_flags -I "${shader_root}")
  set(import_roots "${shader_root}")
  foreach(dir ${S_INCLUDE_DIRS})
    get_filename_component(dir "${dir}" ABSOLUTE)
    list(APPEND include_flags -I "${dir}")
    list(APPEND import_roots "${dir}")
  endforeach()
  set(extra_depends "")
  if(NOT HELIOS_SHADER_DEPFILES)
    foreach(root ${import_roots})
      file(GLOB_RECURSE root_modules CONFIGURE_DEPENDS "${root}/*.slang")
      list(APPEND extra_depends ${root_modules})
    endforeach()
  endif()
  set(define_flags "")
  foreach(def ${S_DEFINES})
    list(APPEND define_flags "-D${def}")
  endforeach()
  if(HELIOS_SHADER_DEBUG_INFO)
    set(opt_flags -g2 -O0)
  else()
    set(opt_flags -O2)
  endif()

  set(generated_sources "")
  set(decls "")
  set(entries "")
  set(names "")
  set(stems "")
  foreach(file ${S_FILES})
    get_filename_component(src "${file}" ABSOLUTE)
    if(NOT EXISTS "${src}")
      message(FATAL_ERROR "helios_shaders(${target}): ${src} does not exist")
    endif()
    get_filename_component(stem "${src}" NAME_WE)
    string(MAKE_C_IDENTIFIER "${stem}" symbol)
    if(symbol IN_LIST stems)
      message(FATAL_ERROR "helios_shaders(${target}): two files map to the symbol '${symbol}'")
    endif()
    list(APPEND stems "${symbol}")

    set(spv "${out_dir}/${stem}.spv")
    set(dep "${out_dir}/${stem}.spv.d")
    set(cpp "${out_dir}/${stem}.spv.cpp")
    if(HELIOS_SHADER_DEPFILES)
      set(depfile_args DEPFILE "${dep}")
      set(depfile_flags -depfile "${dep}")
    else()
      set(depfile_args "")
      set(depfile_flags "")
    endif()
    add_custom_command(
      OUTPUT "${spv}"
      COMMAND "${slangc}" "${src}" ${common_flags} ${opt_flags} ${include_flags}
              ${define_flags} ${S_FLAGS} -o "${spv}" ${depfile_flags}
      DEPENDS "${src}" "${slangc}" ${extra_depends}
      ${depfile_args}
      COMMENT "Slang ${stem}.slang -> SPIR-V (${target})"
      VERBATIM)
    add_custom_command(
      OUTPUT "${cpp}"
      COMMAND "${CMAKE_COMMAND}" "-DHELIOS_EMBED_INPUT=${spv}" "-DHELIOS_EMBED_OUTPUT=${cpp}"
              "-DHELIOS_EMBED_NAMESPACE=${ns}" "-DHELIOS_EMBED_SYMBOL=${symbol}"
              "-DHELIOS_EMBED_HEADER=${target}_shaders.h" -P "${embed_script}"
      DEPENDS "${spv}" "${embed_script}"
      COMMENT "Embedding ${stem}.spv (${target})"
      VERBATIM)
    list(APPEND generated_sources "${cpp}")
    string(APPEND decls "/// SPIR-V words of ${stem}.slang (all entry points declared in that file).\n")
    string(APPEND decls "std::span<const std::uint32_t> ${symbol}() noexcept;\n")
    # find()/names() use the file stem as written ("post-fx"), the accessor its C identifier.
    string(APPEND entries "        {\"${stem}\", &${symbol}},\n")
    string(APPEND names "        \"${stem}\",\n")
  endforeach()

  file(CONFIGURE OUTPUT "${header}" @ONLY CONTENT
"// Generated by cmake/HeliosShaders.cmake for target ${target}. Do not edit.
// Embedded SPIR-V modules (Slang -> SPIR-V 1.6). Thread-safe: all data is immutable.
#pragma once

#include <cstdint>
#include <span>
#include <string_view>

namespace ${ns} {
${decls}
/// Module by file stem (\"triangle\" for triangle.slang); empty span if unknown.
std::span<const std::uint32_t> find(std::string_view stem) noexcept;
/// Stems of every embedded module, in FILES order.
std::span<const std::string_view> names() noexcept;
} // namespace ${ns}
")
  set(registry "${out_dir}/registry.cpp")
  file(CONFIGURE OUTPUT "${registry}" @ONLY CONTENT
"// Generated by cmake/HeliosShaders.cmake for target ${target}. Do not edit.
#include \"${target}_shaders.h\"

namespace ${ns} {
namespace {
struct Entry {
    std::string_view name;
    std::span<const std::uint32_t> (*fn)() noexcept;
};
constexpr Entry kEntries[] = {
${entries}};
constexpr std::string_view kNames[] = {
${names}};
} // namespace

std::span<const std::uint32_t> find(std::string_view stem) noexcept {
    for (const Entry& entry : kEntries) {
        if (entry.name == stem) return entry.fn();
    }
    return {};
}

std::span<const std::string_view> names() noexcept { return kNames; }
} // namespace ${ns}
")
  target_sources(${target} PRIVATE ${generated_sources} "${registry}" "${header}")
  target_include_directories(${target} PRIVATE "${include_dir}")
  source_group("Generated Shaders" FILES ${generated_sources} "${registry}" "${header}")
  source_group("Shaders" FILES ${S_FILES})
  # Keep the .slang sources visible in IDEs without compiling them as C++.
  target_sources(${target} PRIVATE ${S_FILES})
  set_source_files_properties(${S_FILES} PROPERTIES HEADER_FILE_ONLY TRUE)
endfunction()
