# Configure-time module-graph checks (02 §1.1, WP-0.2, RT-09 layer part).
#
# helios_finalize_build() is scheduled by HeliosModule.cmake to run at the end of the top-level
# CMakeLists.txt, when every target exists. It:
#   1. checks the module graph (layers, peers, cycles, HELIOS_MODULE_ORDER, HEADLESS, EDITOR_ONLY);
#   2. checks the executables' roles (no EDITOR_ONLY in client/server images, HEADLESS-only servers);
#   3. registers the repository lints in tools/lint (licences, IP names, ISA audit) as CTests.
# Violations are collected and reported together in one FATAL_ERROR whose lines start with
# "helios layering:" (the fixture tests in tools/lint/tests/layering match on that text).

include_guard(GLOBAL)

# Splits "$<head:body>" at the first ':' outside nested generator expressions. Sets <out>_head and
# <out>_body, or <out>_head to "" when `text` is not a single generator expression.
function(_helios_split_genex text out)
  set(${out}_head "" PARENT_SCOPE)
  set(${out}_body "" PARENT_SCOPE)
  if(NOT text MATCHES "^\\$<" OR NOT text MATCHES ">$")
    return()
  endif()
  string(LENGTH "${text}" len)
  math(EXPR innerLen "${len} - 3")
  if(innerLen LESS 1)
    return()
  endif()
  string(SUBSTRING "${text}" 2 ${innerLen} inner)
  set(depth 0)
  set(i 0)
  math(EXPR last "${innerLen} - 1")
  while(i LESS_EQUAL last)
    string(SUBSTRING "${inner}" ${i} 1 c)
    if(c STREQUAL "$")
      math(EXPR j "${i} + 1")
      if(j LESS_EQUAL last)
        string(SUBSTRING "${inner}" ${j} 1 c2)
        if(c2 STREQUAL "<")
          math(EXPR depth "${depth} + 1")
          set(i ${j})
        endif()
      endif()
    elseif(c STREQUAL ">")
      math(EXPR depth "${depth} - 1")
    elseif(c STREQUAL ":" AND depth EQUAL 0)
      string(SUBSTRING "${inner}" 0 ${i} head)
      math(EXPR b "${i} + 1")
      string(SUBSTRING "${inner}" ${b} -1 body)
      set(${out}_head "${head}" PARENT_SCOPE)
      set(${out}_body "${body}" PARENT_SCOPE)
      return()
    endif()
    math(EXPR i "${i} + 1")
  endwhile()
endfunction()

# Splits `text` at the commas outside nested generator expressions ("$<AND:a,b>,x,y" -> 3 parts).
function(_helios_split_top_commas text out)
  set(parts "")
  set(cur "")
  set(depth 0)
  string(LENGTH "${text}" len)
  set(i 0)
  while(i LESS len)
    string(SUBSTRING "${text}" ${i} 1 c)
    if(c STREQUAL "$")
      math(EXPR j "${i} + 1")
      if(j LESS len)
        string(SUBSTRING "${text}" ${j} 1 c2)
        if(c2 STREQUAL "<")
          math(EXPR depth "${depth} + 1")
        endif()
      endif()
      string(APPEND cur "${c}")
    elseif(c STREQUAL ">")
      math(EXPR depth "${depth} - 1")
      string(APPEND cur "${c}")
    elseif(c STREQUAL "," AND depth EQUAL 0)
      list(APPEND parts "${cur}")
      set(cur "")
    else()
      string(APPEND cur "${c}")
    endif()
    math(EXPR i "${i} + 1")
  endwhile()
  list(APPEND parts "${cur}")
  set(${out} "${parts}" PARENT_SCOPE)
endfunction()

# Resolves one LINK_LIBRARIES / INTERFACE_LINK_LIBRARIES item to real target names (aliases
# resolved), looking through the generator expressions CMake and module code wrap dependencies in:
# $<LINK_ONLY:x>, $<BUILD_INTERFACE:x>, $<BUILD_LOCAL_INTERFACE:x>, $<TARGET_NAME_IF_EXISTS:x>,
# $<COMPILE_ONLY:x>, $<LINK_LIBRARY:feature,x,...>, $<LINK_GROUP:feature,x,...>,
# $<IF:cond,x,y> (both branches) and conditions $<cond:x>. A condition counts as true (a dependency that exists in some configuration is still a
# dependency), except a literal 0. $<INSTALL_INTERFACE:...> never applies to the build tree. Items
# that are not targets (system libraries, flags) resolve to nothing.
function(_helios_resolve_link_item item out)
  set(result "")
  set(name "${item}")
  if(name MATCHES "^::@")
    set(${out} "" PARENT_SCOPE)
    return()
  endif()
  if(name MATCHES "^\\$<")
    _helios_split_genex("${name}" g)
    if(g_head STREQUAL "" OR g_head MATCHES "^(INSTALL_INTERFACE|0)$")
      set(${out} "" PARENT_SCOPE)
      return()
    endif()
    set(candidates "")
    if(g_head MATCHES "^(LINK_LIBRARY|LINK_GROUP)$")
      _helios_split_top_commas("${g_body}" parts)
      list(POP_FRONT parts) # the feature name
      set(candidates ${parts})
    elseif(g_head STREQUAL "IF")
      _helios_split_top_commas("${g_body}" parts) # condition, then-value, else-value: both count
      list(POP_FRONT parts)
      set(candidates ${parts})
    elseif(g_head MATCHES "^(LINK_ONLY|BUILD_INTERFACE|BUILD_LOCAL_INTERFACE|TARGET_NAME_IF_EXISTS|COMPILE_ONLY|1)$"
           OR g_head MATCHES "^\\$<")
      set(candidates "${g_body}")
    endif()
    foreach(c IN LISTS candidates)
      _helios_resolve_link_item("${c}" r)
      list(APPEND result ${r})
    endforeach()
    set(${out} "${result}" PARENT_SCOPE)
    return()
  endif()
  if(NOT TARGET "${name}")
    set(${out} "" PARENT_SCOPE)
    return()
  endif()
  get_target_property(aliased "${name}" ALIASED_TARGET)
  if(aliased)
    set(name "${aliased}")
  endif()
  set(${out} "${name}" PARENT_SCOPE)
endfunction()

# Direct link dependencies (PUBLIC, PRIVATE and INTERFACE) of a target, as real target names.
function(_helios_direct_deps tgt out)
  get_property(cached GLOBAL PROPERTY "_HELIOS_DIRECT_${tgt}" SET)
  if(cached)
    get_property(deps GLOBAL PROPERTY "_HELIOS_DIRECT_${tgt}")
    set(${out} "${deps}" PARENT_SCOPE)
    return()
  endif()
  set(raw "")
  get_target_property(type "${tgt}" TYPE)
  get_target_property(imported "${tgt}" IMPORTED)
  if(NOT type STREQUAL "INTERFACE_LIBRARY" AND NOT imported)
    get_target_property(ll "${tgt}" LINK_LIBRARIES)
    if(ll)
      list(APPEND raw ${ll})
    endif()
  endif()
  get_target_property(ill "${tgt}" INTERFACE_LINK_LIBRARIES)
  if(ill)
    list(APPEND raw ${ill})
  endif()
  set(deps "")
  foreach(item IN LISTS raw)
    _helios_resolve_link_item("${item}" resolved)
    foreach(dep IN LISTS resolved)
      if(NOT dep STREQUAL tgt)
        list(APPEND deps "${dep}")
      endif()
    endforeach()
  endforeach()
  list(REMOVE_DUPLICATES deps)
  set_property(GLOBAL PROPERTY "_HELIOS_DIRECT_${tgt}" "${deps}")
  set(${out} "${deps}" PARENT_SCOPE)
endfunction()

# Breadth-first search from `from`; sets `out` to the dependency path "a -> b -> c" reaching any
# target for which `predicate` (a function taking <target> <outVar>) is true, or "" if none does.
function(_helios_find_path from predicate out)
  set(queue "${from}")
  set(seen "${from}")
  set_property(GLOBAL PROPERTY "_HELIOS_PARENT_${from}" "")
  while(queue)
    list(POP_FRONT queue cur)
    _helios_direct_deps("${cur}" deps)
    foreach(d IN LISTS deps)
      if(d IN_LIST seen)
        continue()
      endif()
      list(APPEND seen "${d}")
      set_property(GLOBAL PROPERTY "_HELIOS_PARENT_${d}" "${cur}")
      cmake_language(CALL ${predicate} "${d}" hit)
      if(hit)
        set(path "${d}")
        set(node "${d}")
        while(NOT node STREQUAL from)
          get_property(node GLOBAL PROPERTY "_HELIOS_PARENT_${node}")
          set(path "${node} -> ${path}")
        endwhile()
        set(${out} "${path}" PARENT_SCOPE)
        return()
      endif()
      list(APPEND queue "${d}")
    endforeach()
  endwhile()
  set(${out} "" PARENT_SCOPE)
endfunction()

function(_helios_is_module tgt out)
  get_target_property(m "${tgt}" HELIOS_MODULE_NAME)
  if(m)
    set(${out} ON PARENT_SCOPE)
  else()
    set(${out} OFF PARENT_SCOPE)
  endif()
endfunction()

# Predicates for _helios_find_path.
function(_helios_pred_not_headless tgt out)
  set(hit OFF)
  get_target_property(m "${tgt}" HELIOS_MODULE_NAME)
  if(m)
    get_target_property(h "${tgt}" HELIOS_HEADLESS)
    if(NOT h)
      set(hit ON)
    endif()
  endif()
  get_property(gfx GLOBAL PROPERTY HELIOS_GRAPHICS_THIRD_PARTY)
  if(tgt IN_LIST gfx)
    set(hit ON)
  endif()
  set(${out} ${hit} PARENT_SCOPE)
endfunction()

function(_helios_pred_editor_only tgt out)
  set(hit OFF)
  get_target_property(m "${tgt}" HELIOS_MODULE_NAME)
  if(m)
    get_target_property(e "${tgt}" HELIOS_EDITOR_ONLY)
    if(e)
      set(hit ON)
    endif()
  endif()
  set(${out} ${hit} PARENT_SCOPE)
endfunction()

# Direct module -> module edges (through non-module targets such as tp_* libraries modules never
# reach other modules, so direct edges are the module graph).
function(_helios_module_deps tgt out)
  _helios_direct_deps("${tgt}" deps)
  set(mods "")
  foreach(d IN LISTS deps)
    get_target_property(m "${d}" HELIOS_MODULE_NAME)
    if(m)
      list(APPEND mods "${d}")
    endif()
  endforeach()
  set(${out} "${mods}" PARENT_SCOPE)
endfunction()

# Depth-first cycle search over the module graph. Appends "a -> b -> a" strings to `errorsVar`.
function(_helios_cycle_visit tgt stackVar errorsVar)
  set(stack ${${stackVar}})
  set(errors ${${errorsVar}})
  list(APPEND stack "${tgt}")
  set_property(GLOBAL PROPERTY "_HELIOS_COLOR_${tgt}" grey)
  _helios_module_deps("${tgt}" deps)
  foreach(d IN LISTS deps)
    get_property(color GLOBAL PROPERTY "_HELIOS_COLOR_${d}")
    if(color STREQUAL "grey")
      list(FIND stack "${d}" at)
      list(SUBLIST stack ${at} -1 cyc)
      list(APPEND cyc "${d}")
      string(REPLACE ";" " -> " cycText "${cyc}")
      list(APPEND errors "helios layering: dependency cycle between modules: ${cycText}")
    elseif(NOT color STREQUAL "black")
      _helios_cycle_visit("${d}" stack errors)
    endif()
  endforeach()
  set_property(GLOBAL PROPERTY "_HELIOS_COLOR_${tgt}" black)
  list(POP_BACK stack)
  set(${stackVar} "${stack}" PARENT_SCOPE)
  set(${errorsVar} "${errors}" PARENT_SCOPE)
endfunction()

function(helios_check_module_graph)
  get_property(modules GLOBAL PROPERTY HELIOS_MODULE_TARGETS)
  get_property(apps GLOBAL PROPERTY HELIOS_APP_TARGETS)
  get_property(order GLOBAL PROPERTY HELIOS_MODULE_ORDER)
  set(errors "")

  # --- Per-module rules -----------------------------------------------------------------------
  foreach(tgt IN LISTS modules)
    get_target_property(name "${tgt}" HELIOS_MODULE_NAME)
    get_target_property(layer "${tgt}" HELIOS_LAYER)
    get_target_property(headless "${tgt}" HELIOS_HEADLESS)
    get_target_property(editorOnly "${tgt}" HELIOS_EDITOR_ONLY)
    get_target_property(peers "${tgt}" HELIOS_PEERS)
    if(NOT peers)
      set(peers "")
    endif()
    _helios_module_deps("${tgt}" deps)
    foreach(d IN LISTS deps)
      get_target_property(dname "${d}" HELIOS_MODULE_NAME)
      get_target_property(dlayer "${d}" HELIOS_LAYER)
      get_target_property(dEditorOnly "${d}" HELIOS_EDITOR_ONLY)
      if(dlayer GREATER layer)
        list(APPEND errors "helios layering: module '${name}' (layer ${layer}) depends upward on '${dname}' (layer ${dlayer})")
      elseif(dlayer EQUAL layer AND NOT dname IN_LIST peers)
        list(APPEND errors "helios layering: module '${name}' depends on same-layer module '${dname}' (layer ${layer}), which is not a listed peer; add it to PEERS in engine/CMakeLists.txt only if 02 §1.1 allows it")
      endif()
      if(dEditorOnly AND NOT editorOnly)
        list(APPEND errors "helios layering: module '${name}' is not EDITOR_ONLY but depends on EDITOR_ONLY module '${dname}'")
      endif()
    endforeach()
    if(headless)
      _helios_find_path("${tgt}" _helios_pred_not_headless path)
      if(path)
        list(APPEND errors "helios layering: HEADLESS module '${name}' reaches a non-HEADLESS module or graphics library: ${path}")
      endif()
    endif()
    # HELIOS_MODULE_ORDER must be a topological order of the modules it lists.
    list(FIND order "${name}" myIndex)
    if(myIndex GREATER -1)
      foreach(d IN LISTS deps)
        get_target_property(dname "${d}" HELIOS_MODULE_NAME)
        list(FIND order "${dname}" depIndex)
        if(depIndex GREATER myIndex)
          list(APPEND errors "helios layering: HELIOS_MODULE_ORDER lists '${name}' before its dependency '${dname}'")
        endif()
      endforeach()
    endif()
  endforeach()

  # --- Cycles ---------------------------------------------------------------------------------
  foreach(tgt IN LISTS modules)
    get_property(color GLOBAL PROPERTY "_HELIOS_COLOR_${tgt}")
    if(NOT color)
      set(stack "")
      _helios_cycle_visit("${tgt}" stack errors)
    endif()
  endforeach()

  # --- Executables ----------------------------------------------------------------------------
  get_property(noEditorRoles GLOBAL PROPERTY HELIOS_ROLES_NO_EDITOR_ONLY)
  get_property(headlessRoles GLOBAL PROPERTY HELIOS_ROLES_HEADLESS_ONLY)
  foreach(app IN LISTS apps)
    get_target_property(role "${app}" HELIOS_APP_ROLE)
    if(role IN_LIST noEditorRoles)
      _helios_find_path("${app}" _helios_pred_editor_only path)
      if(path)
        list(APPEND errors "helios layering: ${role} executable '${app}' links an EDITOR_ONLY module: ${path}")
      endif()
    endif()
    if(role IN_LIST headlessRoles)
      _helios_find_path("${app}" _helios_pred_not_headless path)
      if(path)
        list(APPEND errors "helios layering: ${role} executable '${app}' may link only HEADLESS modules, but reaches: ${path}")
      endif()
    endif()
  endforeach()

  if(errors)
    list(REMOVE_DUPLICATES errors)
    list(LENGTH errors count)
    string(REPLACE ";" "\n  " text "${errors}")
    message(FATAL_ERROR "Module layering check failed (${count} violation(s); rules in docs/plan/02-engine-runtime.md §1.1):\n  ${text}\n")
  endif()
  list(LENGTH modules moduleCount)
  list(LENGTH apps appCount)
  message(STATUS "Helios layering: ${moduleCount} modules and ${appCount} executables checked")
endfunction()

function(helios_finalize_build)
  helios_check_module_graph()
  # Repository lints (licences, IP names, ISA audit) as CTests. Only for the Helios tree itself; the
  # fixture projects under tools/lint/tests include this file too.
  if(HELIOS_BUILD_TESTS AND EXISTS "${CMAKE_SOURCE_DIR}/tools/lint/lint_tests.cmake"
     AND EXISTS "${CMAKE_SOURCE_DIR}/engine/CMakeLists.txt")
    include("${CMAKE_SOURCE_DIR}/tools/lint/lint_tests.cmake")
  endif()
endfunction()
