# Windows executable manifest (ADR-011, 02 §2.1).
#
# helios_windows_manifest(<target>)
#   Embeds engine/platform/win/helios.manifest into a Windows executable: UTF-8 active code page,
#   PerMonitorV2 DPI awareness, longPathAware, Windows 10/11 supportedOS and asInvoker. No-op on other
#   platforms and when called twice. helios_executable() and helios_test() call it for every target;
#   executables created with plain add_executable() should call it themselves.
#   * MSVC and clang-cl: the manifest is a source file, which CMake hands to the linker (/MANIFESTINPUT)
#     and merges with mt; /MANIFESTUAC:NO keeps the linker from adding a second trustInfo block.
#   * MinGW: a generated resource script embeds it as RT_MANIFEST resource 1 (windres).

include_guard(GLOBAL)

set_property(GLOBAL PROPERTY HELIOS_WINDOWS_MANIFEST
  "${CMAKE_CURRENT_LIST_DIR}/../engine/platform/win/helios.manifest")

if(MINGW)
  enable_language(RC)
endif()

function(helios_windows_manifest target)
  if(NOT WIN32 OR NOT (MSVC OR MINGW))
    return()
  endif()
  get_target_property(done ${target} HELIOS_MANIFEST_EMBEDDED)
  if(done)
    return()
  endif()
  get_property(manifest GLOBAL PROPERTY HELIOS_WINDOWS_MANIFEST)
  get_filename_component(manifest "${manifest}" ABSOLUTE)
  if(MSVC)
    target_sources(${target} PRIVATE "${manifest}")
    target_link_options(${target} PRIVATE /MANIFESTUAC:NO)
  else()
    set(rc "${CMAKE_BINARY_DIR}/helios_generated/helios_manifest.rc")
    get_property(written GLOBAL PROPERTY _HELIOS_MANIFEST_RC_WRITTEN)
    if(NOT written)
      # 1 = CREATEPROCESS_MANIFEST_RESOURCE_ID, 24 = RT_MANIFEST. Absolute path: windres resolves
      # relative names against its working directory, not the script's.
      file(WRITE "${rc}" "// Generated by cmake/HeliosWindows.cmake\n1 24 \"${manifest}\"\n")
      set_property(GLOBAL PROPERTY _HELIOS_MANIFEST_RC_WRITTEN ON)
    endif()
    target_sources(${target} PRIVATE "${rc}")
    set_source_files_properties("${rc}" TARGET_DIRECTORY ${target} PROPERTIES OBJECT_DEPENDS "${manifest}")
  endif()
  set_target_properties(${target} PROPERTIES HELIOS_MANIFEST_EMBEDDED ON)
endfunction()
