package planted

// Review regressions (WP-0.19 round 1): a type parameter with a float type set, and a "Code
// generated" marker after the package clause, which does not make the file generated.

// Code generated by nobody. DO NOT EDIT.

type float interface{ ~float32 | ~float64 }

func mulAddGeneric[T ~float64](a, b, c T) T {
	return a*b + c // want "unconverted-mul"
}

func mulAddUnion[T float](a, b, c T) T {
	return a*b + c // want "unconverted-mul"
}

// A conversion to a type parameter does not count as a rounding point.
func convertedGeneric[T ~float64](a, b, c T) T {
	return T(a*b) + c // want "unconverted-mul"
}

func convertedConcrete(a, b, c float64) float64 {
	return float64(a*b) + c // allowed
}
