// Code generated by helios-schemac. DO NOT EDIT.
//
// Helios schema runtime for Go: the tagged wire format (protobuf wire format with schema-lock
// field ids as field numbers, docs/plan/02-engine-runtime.md §3.7) and the vocabulary types the
// schema language names. Encodings are byte-identical to engine/reflect (C++); see
// tools/schemac/README.md "Wire format".

package heliosruntime

import (
	"bytes"
	"cmp"
	"encoding/binary"
	"encoding/json"
	"errors"
	"fmt"
	"math"
	"slices"
	"strconv"
	"strings"
	"unicode/utf8"
)

// ---------------------------------------------------------------------------------------------
// Wire writer
// ---------------------------------------------------------------------------------------------

const (
	wireVarint = 0
	wireI64    = 1
	wireLen    = 2
	wireI32    = 5
)

const maxTaggedDepth = 64

func varintSize(v uint64) int {
	n := 1
	for v >= 0x80 {
		v >>= 7
		n++
	}
	return n
}

func appendVarint(b []byte, v uint64) []byte {
	for v >= 0x80 {
		b = append(b, byte(v)|0x80)
		v >>= 7
	}
	return append(b, byte(v))
}

func zigzagEncode(v int64) uint64 { return uint64(v<<1) ^ uint64(v>>63) }
func zigzagDecode(v uint64) int64 { return int64(v>>1) ^ -int64(v&1) }

func appendZigzag(b []byte, v int64) []byte        { return appendVarint(b, zigzagEncode(v)) }
func appendTag(b []byte, id uint32, wt int) []byte { return appendVarint(b, uint64(id)<<3|uint64(wt)) }
func appendFixed32(b []byte, v uint32) []byte      { return binary.LittleEndian.AppendUint32(b, v) }
func appendFixed64(b []byte, v uint64) []byte      { return binary.LittleEndian.AppendUint64(b, v) }
func appendF32(b []byte, v float32) []byte         { return appendFixed32(b, math.Float32bits(v)) }
func appendF64(b []byte, v float64) []byte         { return appendFixed64(b, math.Float64bits(v)) }
func appendBool(b []byte, v bool) []byte {
	if v {
		return append(b, 1)
	}
	return append(b, 0)
}

func appendBytes(b []byte, v []byte) []byte {
	b = appendVarint(b, uint64(len(v)))
	return append(b, v...)
}

func appendString(b []byte, v string) []byte {
	b = appendVarint(b, uint64(len(v)))
	return append(b, v...)
}

// beginLen reserves a one-byte length prefix for a payload of unknown size; endLen patches it
// with the minimal varint (moving the payload when the length needs more than one byte).
func beginLen(b []byte) ([]byte, int) {
	b = append(b, 0)
	return b, len(b)
}

func endLen(b []byte, mark int) []byte {
	n := uint64(len(b) - mark)
	size := varintSize(n)
	if size > 1 {
		b = append(b, make([]byte, size-1)...)
		copy(b[mark+size-1:], b[mark:len(b)-(size-1)])
	}
	p := mark - 1
	for i := 0; i < size; i++ {
		c := byte(n & 0x7f)
		n >>= 7
		if i+1 < size {
			c |= 0x80
		}
		b[p+i] = c
	}
	return b
}

func appendF32Tuple(b []byte, v []float32) []byte {
	b = appendVarint(b, uint64(4*len(v)))
	for _, x := range v {
		b = appendF32(b, x)
	}
	return b
}

func appendF64Tuple(b []byte, v []float64) []byte {
	b = appendVarint(b, uint64(8*len(v)))
	for _, x := range v {
		b = appendF64(b, x)
	}
	return b
}

// ---------------------------------------------------------------------------------------------
// Wire reader (bounds-checked; malformed input is an error, never a panic)
// ---------------------------------------------------------------------------------------------

// ErrCorrupt reports malformed tagged data.
var ErrCorrupt = errors.New("helios: corrupt tagged data")

type wireReader struct {
	data  []byte
	pos   int
	depth int
}

func newWireReader(b []byte) *wireReader { return &wireReader{data: b} }

func (r *wireReader) atEnd() bool { return r.pos >= len(r.data) }

func (r *wireReader) varint() (uint64, error) {
	var result uint64
	for shift := uint(0); shift < 64; shift += 7 {
		if r.pos >= len(r.data) {
			return 0, fmt.Errorf("%w: truncated varint", ErrCorrupt)
		}
		c := r.data[r.pos]
		r.pos++
		if shift == 63 && c > 1 {
			return 0, fmt.Errorf("%w: varint overflows 64 bits", ErrCorrupt)
		}
		result |= uint64(c&0x7f) << shift
		if c&0x80 == 0 {
			return result, nil
		}
	}
	return 0, fmt.Errorf("%w: varint longer than 10 bytes", ErrCorrupt)
}

func (r *wireReader) fixed32() (uint32, error) {
	if len(r.data)-r.pos < 4 {
		return 0, fmt.Errorf("%w: truncated fixed32", ErrCorrupt)
	}
	v := binary.LittleEndian.Uint32(r.data[r.pos:])
	r.pos += 4
	return v, nil
}

func (r *wireReader) fixed64() (uint64, error) {
	if len(r.data)-r.pos < 8 {
		return 0, fmt.Errorf("%w: truncated fixed64", ErrCorrupt)
	}
	v := binary.LittleEndian.Uint64(r.data[r.pos:])
	r.pos += 8
	return v, nil
}

func (r *wireReader) lenBytes() ([]byte, error) {
	n, err := r.varint()
	if err != nil {
		return nil, err
	}
	if n > uint64(len(r.data)-r.pos) {
		return nil, fmt.Errorf("%w: length %d exceeds remaining %d bytes", ErrCorrupt, n, len(r.data)-r.pos)
	}
	out := r.data[r.pos : r.pos+int(n)]
	r.pos += int(n)
	return out, nil
}

// message returns a reader over a length-delimited nested message.
func (r *wireReader) message() (*wireReader, error) {
	if r.depth+1 > maxTaggedDepth {
		return nil, errors.New("helios: tagged nesting too deep")
	}
	p, err := r.lenBytes()
	if err != nil {
		return nil, err
	}
	return &wireReader{data: p, depth: r.depth + 1}, nil
}

func (r *wireReader) tag() (uint32, int, error) {
	key, err := r.varint()
	if err != nil {
		return 0, 0, err
	}
	id := key >> 3
	wt := int(key & 7)
	if id == 0 || id > (1<<29)-1 {
		return 0, 0, fmt.Errorf("%w: invalid field number %d", ErrCorrupt, id)
	}
	if wt != wireVarint && wt != wireI64 && wt != wireLen && wt != wireI32 {
		return 0, 0, fmt.Errorf("%w: unsupported wire type %d", ErrCorrupt, wt)
	}
	return uint32(id), wt, nil
}

func (r *wireReader) skip(wt int) error {
	switch wt {
	case wireVarint:
		_, err := r.varint()
		return err
	case wireI64:
		_, err := r.fixed64()
		return err
	case wireI32:
		_, err := r.fixed32()
		return err
	case wireLen:
		_, err := r.lenBytes()
		return err
	}
	return fmt.Errorf("%w: unsupported wire type %d", ErrCorrupt, wt)
}

func wireMismatch(what string, got, want int) error {
	return fmt.Errorf("%w: %s: wire type %d, expected %d", ErrCorrupt, what, got, want)
}

func readVarintField(r *wireReader, wt int, what string) (uint64, error) {
	if wt != wireVarint {
		return 0, wireMismatch(what, wt, wireVarint)
	}
	return r.varint()
}

func readUnsigned(r *wireReader, wt int, max uint64) (uint64, error) {
	v, err := readVarintField(r, wt, "integer")
	if err != nil {
		return 0, err
	}
	if v > max {
		return 0, fmt.Errorf("helios: integer value %d out of range", v)
	}
	return v, nil
}

func readSigned(r *wireReader, wt int, min, max int64) (int64, error) {
	raw, err := readVarintField(r, wt, "integer")
	if err != nil {
		return 0, err
	}
	v := zigzagDecode(raw)
	if v < min || v > max {
		return 0, fmt.Errorf("helios: integer value %d out of range", v)
	}
	return v, nil
}

func readF32(r *wireReader, wt int) (float32, error) {
	if wt != wireI32 {
		return 0, wireMismatch("f32", wt, wireI32)
	}
	v, err := r.fixed32()
	return math.Float32frombits(v), err
}

// readF64 also accepts I32 (f32 -> f64 widening keeps the field id).
func readF64(r *wireReader, wt int) (float64, error) {
	if wt == wireI32 {
		v, err := r.fixed32()
		return float64(math.Float32frombits(v)), err
	}
	if wt != wireI64 {
		return 0, wireMismatch("f64", wt, wireI64)
	}
	v, err := r.fixed64()
	return math.Float64frombits(v), err
}

func readFixed64Field(r *wireReader, wt int, what string) (uint64, error) {
	if wt != wireI64 {
		return 0, wireMismatch(what, wt, wireI64)
	}
	return r.fixed64()
}

func readStringField(r *wireReader, wt int) (string, error) {
	if wt != wireLen {
		return "", wireMismatch("string", wt, wireLen)
	}
	p, err := r.lenBytes()
	if err != nil {
		return "", err
	}
	// Text is UTF-8 everywhere; reject bad bytes like the C++ reader (and protobuf) do.
	if !utf8.Valid(p) {
		return "", fmt.Errorf("%w: string: invalid UTF-8", ErrCorrupt)
	}
	return string(p), nil
}

func readF32Tuple(r *wireReader, wt int, out []float32) error {
	if wt != wireLen {
		return wireMismatch("float tuple", wt, wireLen)
	}
	p, err := r.lenBytes()
	if err != nil {
		return err
	}
	if len(p) != 4*len(out) {
		return fmt.Errorf("%w: float tuple: %d bytes, expected %d", ErrCorrupt, len(p), 4*len(out))
	}
	for i := range out {
		out[i] = math.Float32frombits(binary.LittleEndian.Uint32(p[4*i:]))
	}
	return nil
}

func readF64Tuple(r *wireReader, wt int, out []float64) error {
	if wt != wireLen {
		return wireMismatch("float tuple", wt, wireLen)
	}
	p, err := r.lenBytes()
	if err != nil {
		return err
	}
	if len(p) != 8*len(out) {
		return fmt.Errorf("%w: float tuple: %d bytes, expected %d", ErrCorrupt, len(p), 8*len(out))
	}
	for i := range out {
		out[i] = math.Float64frombits(binary.LittleEndian.Uint64(p[8*i:]))
	}
	return nil
}

// ---------------------------------------------------------------------------------------------
// Bitwise float helpers (equality and defaults compare bits, like the C++ codecs)
// ---------------------------------------------------------------------------------------------

func f32Bits(a, b float32) bool { return math.Float32bits(a) == math.Float32bits(b) }
func f64Bits(a, b float64) bool { return math.Float64bits(a) == math.Float64bits(b) }

func f32TupleBits(a, b []float32) bool {
	for i := range a {
		if !f32Bits(a[i], b[i]) {
			return false
		}
	}
	return true
}

func f64TupleBits(a, b []float64) bool {
	for i := range a {
		if !f64Bits(a[i], b[i]) {
			return false
		}
	}
	return true
}

// ---------------------------------------------------------------------------------------------
// Canonical ordering of map keys and set elements
// ---------------------------------------------------------------------------------------------

func sortedKeys[K cmp.Ordered, V any](m map[K]V) []K {
	keys := make([]K, 0, len(m))
	for k := range m {
		keys = append(keys, k)
	}
	slices.Sort(keys)
	return keys
}

func sortedGuidKeys[V any](m map[Guid]V) []Guid {
	keys := make([]Guid, 0, len(m))
	for k := range m {
		keys = append(keys, k)
	}
	slices.SortFunc(keys, func(a, b Guid) int { return bytes.Compare(a[:], b[:]) })
	return keys
}

// sortedSet returns the canonical (sorted, duplicate-free) element order of a set; a Go slice may
// hold duplicates, a C++ std::set cannot, and both must encode identically.
func sortedSet[T cmp.Ordered](s []T) []T {
	out := slices.Clone(s)
	slices.Sort(out)
	return slices.Compact(out)
}

func sortedGuidSet(s []Guid) []Guid {
	out := slices.Clone(s)
	slices.SortFunc(out, func(a, b Guid) int { return bytes.Compare(a[:], b[:]) })
	return slices.Compact(out)
}

// ---------------------------------------------------------------------------------------------
// Vocabulary types
// ---------------------------------------------------------------------------------------------

// Guid is a 128-bit identifier in canonical (big-endian) byte order.
type Guid [16]byte

func (g Guid) String() string {
	h := fmt.Sprintf("%x", g[:])
	return h[0:8] + "-" + h[8:12] + "-" + h[12:16] + "-" + h[16:20] + "-" + h[20:32]
}

// ParseGuid accepts "xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx", 32 hex digits, surrounding braces and a
// "guid:" prefix (the forms helios::Guid::parse accepts).
func ParseGuid(s string) (Guid, error) {
	var g Guid
	s = strings.TrimPrefix(s, "guid:")
	if len(s) >= 2 && s[0] == '{' && s[len(s)-1] == '}' {
		s = s[1 : len(s)-1]
	}
	if len(s) == 36 {
		if s[8] != '-' || s[13] != '-' || s[18] != '-' || s[23] != '-' {
			return g, fmt.Errorf("helios: invalid GUID %q", s)
		}
		s = s[0:8] + s[9:13] + s[14:18] + s[19:23] + s[24:]
	}
	if len(s) != 32 {
		return g, fmt.Errorf("helios: invalid GUID %q", s)
	}
	for i := 0; i < 16; i++ {
		v, err := strconv.ParseUint(s[2*i:2*i+2], 16, 8)
		if err != nil {
			return g, fmt.Errorf("helios: invalid GUID %q", s)
		}
		g[i] = byte(v)
	}
	return g, nil
}

func (g Guid) MarshalText() ([]byte, error) { return []byte(g.String()), nil }
func (g *Guid) UnmarshalText(b []byte) error {
	v, err := ParseGuid(string(b))
	if err != nil {
		return err
	}
	*g = v
	return nil
}

func readGuid(r *wireReader, wt int) (Guid, error) {
	var g Guid
	if wt != wireLen {
		return g, wireMismatch("Guid", wt, wireLen)
	}
	p, err := r.lenBytes()
	if err != nil {
		return g, err
	}
	if len(p) != 16 {
		return g, fmt.Errorf("%w: Guid: %d bytes, expected 16", ErrCorrupt, len(p))
	}
	copy(g[:], p)
	return g, nil
}

// Math tuples (x, y, z[, w]); quaternions and colours default to (0, 0, 0, 1).
type (
	Vec2     [2]float32
	Vec3     [3]float32
	Vec4     [4]float32
	DVec3    [3]float64
	Quat     [4]float32
	DQuat    [4]float64
	RGBA     [4]float32 // schema `color`
	WorldPos [3]float64
)

// EntityId is the global, persistent 64-bit entity identifier. JSON: "ent:<decimal>" (02 §3.7);
// numbers are accepted too. Map keys stay plain decimal text.
type EntityId uint64

func (e EntityId) MarshalJSON() ([]byte, error) {
	return []byte("\"ent:" + strconv.FormatUint(uint64(e), 10) + "\""), nil
}

func (e *EntityId) UnmarshalJSON(b []byte) error {
	if len(b) > 0 && b[0] == '"' {
		var s string
		if err := json.Unmarshal(b, &s); err != nil {
			return err
		}
		v, err := strconv.ParseUint(strings.TrimPrefix(s, "ent:"), 10, 64)
		if err != nil {
			return fmt.Errorf("helios: invalid entity id %q", s)
		}
		*e = EntityId(v)
		return nil
	}
	var v uint64
	if err := json.Unmarshal(b, &v); err != nil {
		return err
	}
	*e = EntityId(v)
	return nil
}

// NetHandle is a zone-scoped 24-bit index + 8-bit generation.
type NetHandle uint32

// Tick is a simulation tick.
type Tick = uint64

// RecordId is a 63-bit record identifier minted once and stored in the record source.
type RecordId = uint64

// LocString is a localization key. JSON: "loc:<key>" (02 §3.7; the prefix is optional when reading).
type LocString string

func (l LocString) MarshalJSON() ([]byte, error) { return json.Marshal("loc:" + string(l)) }

func (l *LocString) UnmarshalJSON(b []byte) error {
	var s string
	if err := json.Unmarshal(b, &s); err != nil {
		return err
	}
	*l = LocString(strings.TrimPrefix(s, "loc:"))
	return nil
}

// TagQuery and HxlExpr are text in JSON and on the wire.
type (
	TagQuery = string
	HxlExpr  = string
)

// renameJSONKeys rewrites the members of a JSON object named by an @was alias to their current
// field names (the current name wins when both are present).
func renameJSONKeys(b []byte, renames map[string]string) ([]byte, error) {
	var obj map[string]json.RawMessage
	if err := json.Unmarshal(b, &obj); err != nil || obj == nil {
		return b, nil // not an object: let the struct decoder report it
	}
	changed := false
	for old, cur := range renames {
		if v, ok := obj[old]; ok {
			if _, has := obj[cur]; !has {
				obj[cur] = v
			}
			delete(obj, old)
			changed = true
		}
	}
	if !changed {
		return b, nil
	}
	return json.Marshal(obj)
}

// U8List is list<u8> / set<u8>. encoding/json would write a []uint8 as a base64 string; the
// schema JSON form is an array of numbers (the C++ runtime reads and writes that), so U8List
// marshals as an array and accepts both forms when reading.
type U8List []uint8

func (l U8List) MarshalJSON() ([]byte, error) {
	if l == nil {
		return []byte("[]"), nil
	}
	b := make([]byte, 0, 2+4*len(l))
	b = append(b, '[')
	for i, v := range l {
		if i > 0 {
			b = append(b, ',')
		}
		b = strconv.AppendUint(b, uint64(v), 10)
	}
	return append(b, ']'), nil
}

func (l *U8List) UnmarshalJSON(b []byte) error {
	if len(b) > 0 && b[0] == '"' {
		var raw []byte
		if err := json.Unmarshal(b, &raw); err != nil {
			return err
		}
		*l = U8List(raw)
		return nil
	}
	var nums []uint8
	if err := json.Unmarshal(b, &nums); err != nil {
		return err
	}
	*l = U8List(nums)
	return nil
}

// TagSet holds tag names sorted byte-wise and unique.
type TagSet []string

// tagSetAdd inserts a tag keeping the set sorted and unique.
func tagSetAdd(t TagSet, tag string) TagSet {
	i, found := slices.BinarySearch(t, tag)
	if found {
		return t
	}
	return slices.Insert(t, i, tag)
}

// AssetRef references an asset by its content GUID. JSON: "guid:<guid>" (02 §3.7).
type AssetRef Guid

func (a AssetRef) MarshalText() ([]byte, error)  { return []byte("guid:" + Guid(a).String()), nil }
func (a *AssetRef) UnmarshalText(b []byte) error { return (*Guid)(a).UnmarshalText(b) }

// Duration is a signed span in nanoseconds (like time.Duration). JSON: "500ms", "30d", ...
type Duration int64

var durationUnits = []struct {
	suffix string
	nanos  int64
}{{"d", 86400000000000}, {"h", 3600000000000}, {"m", 60000000000}, {"s", 1000000000}, {"ms", 1000000}, {"us", 1000}, {"ns", 1}}

func (d Duration) String() string {
	if d == 0 {
		return "0s"
	}
	for _, u := range durationUnits {
		if int64(d)%u.nanos == 0 {
			return strconv.FormatInt(int64(d)/u.nanos, 10) + u.suffix
		}
	}
	return strconv.FormatInt(int64(d), 10) + "ns"
}

// ParseDuration parses "<number><unit>" with units d, h, m, s, ms, us, ns (decimals allowed).
func ParseDuration(s string) (Duration, error) {
	orig := s
	neg := strings.HasPrefix(s, "-")
	s = strings.TrimPrefix(s, "-")
	i := 0
	for i < len(s) && (s[i] >= '0' && s[i] <= '9' || s[i] == '.') {
		i++
	}
	num, suffix := s[:i], s[i:]
	var unit int64
	for _, u := range durationUnits {
		if u.suffix == suffix {
			unit = u.nanos
		}
	}
	if num == "" || num == "." || unit == 0 {
		return 0, fmt.Errorf("helios: invalid duration %q", orig)
	}
	intPart, fracPart, _ := strings.Cut(num, ".")
	if strings.Contains(fracPart, ".") {
		return 0, fmt.Errorf("helios: invalid duration %q", orig)
	}
	var whole uint64
	if intPart != "" {
		v, err := strconv.ParseUint(intPart, 10, 64)
		if err != nil {
			return 0, fmt.Errorf("helios: invalid duration %q", orig)
		}
		whole = v
	}
	if whole > uint64(math.MaxInt64)/uint64(unit) {
		return 0, fmt.Errorf("helios: duration %q overflows", orig)
	}
	total := whole * uint64(unit)
	scale := uint64(unit)
	var frac uint64
	for _, c := range fracPart {
		digit := uint64(c - '0')
		if scale%10 == 0 {
			scale /= 10
			frac += digit * scale
		} else {
			n := digit * scale
			frac += n / 10
			if n%10 >= 5 {
				frac++
			}
			break
		}
	}
	total += frac
	if total > uint64(math.MaxInt64) {
		return 0, fmt.Errorf("helios: duration %q overflows", orig)
	}
	if neg {
		return Duration(-int64(total)), nil
	}
	return Duration(total), nil
}

func (d Duration) MarshalJSON() ([]byte, error) { return json.Marshal(d.String()) }
func (d *Duration) UnmarshalJSON(b []byte) error {
	var s string
	if err := json.Unmarshal(b, &s); err == nil {
		v, err := ParseDuration(s)
		if err != nil {
			return err
		}
		*d = v
		return nil
	}
	var seconds float64
	if err := json.Unmarshal(b, &seconds); err != nil || math.Abs(seconds) >= 9.2e9 {
		return fmt.Errorf("helios: duration must be a string like \"500ms\" or a number of seconds (|s| < 9.2e9)")
	}
	*d = Duration(math.Round(seconds * 1e9))
	return nil
}

// Keyed is an element of a keyed list: a stable GUID key plus the value ("$key" in JSON).
type Keyed[T any] struct {
	Key   Guid
	Value T
}

func (k Keyed[T]) MarshalJSON() ([]byte, error) {
	body, err := json.Marshal(k.Value)
	if err != nil {
		return nil, err
	}
	head := `{"$key":"` + k.Key.String() + `"`
	if len(body) <= 2 {
		return []byte(head + "}"), nil
	}
	return []byte(head + "," + string(body[1:])), nil
}

func (k *Keyed[T]) UnmarshalJSON(b []byte) error {
	var head struct {
		Key *Guid `json:"$key"`
	}
	if err := json.Unmarshal(b, &head); err != nil {
		return err
	}
	if head.Key == nil {
		return errors.New("helios: keyed list element without \"$key\"")
	}
	k.Key = *head.Key
	return json.Unmarshal(b, &k.Value)
}

// ---------------------------------------------------------------------------------------------
// Enums and flags
// ---------------------------------------------------------------------------------------------

type enumName struct {
	name  string
	value int64
}

func enumToJSON(names []enumName, v int64) ([]byte, error) {
	for _, n := range names {
		if n.value == v {
			return json.Marshal(n.name)
		}
	}
	return []byte(strconv.FormatInt(v, 10)), nil
}

func enumToText(names []enumName, v int64) []byte {
	for _, n := range names {
		if n.value == v {
			return []byte(n.name)
		}
	}
	return []byte(strconv.FormatInt(v, 10))
}

func enumFromText(names []enumName, s string) (int64, error) {
	for _, n := range names {
		if n.name == s {
			return n.value, nil
		}
	}
	if v, err := strconv.ParseInt(s, 10, 64); err == nil {
		return v, nil
	}
	return 0, fmt.Errorf("helios: unknown enum value %q", s)
}

func enumFromJSON(names []enumName, b []byte) (int64, error) {
	var s string
	if err := json.Unmarshal(b, &s); err == nil {
		return enumFromText(names, s)
	}
	var v int64
	if err := json.Unmarshal(b, &v); err != nil {
		return 0, fmt.Errorf("helios: enum value must be a name or an integer")
	}
	return v, nil
}

func flagsToJSON(names []enumName, v uint64) ([]byte, error) {
	parts := []any{}
	remaining := v
	for _, n := range names {
		bit := uint64(n.value)
		if bit != 0 && bit&(bit-1) == 0 && remaining&bit != 0 {
			parts = append(parts, n.name)
			remaining &^= bit
		}
	}
	if remaining != 0 {
		parts = append(parts, remaining)
	}
	return json.Marshal(parts)
}

func flagsFromJSON(names []enumName, b []byte) (uint64, error) {
	var bits uint64
	if err := json.Unmarshal(b, &bits); err == nil {
		return bits, nil
	}
	var items []json.RawMessage
	if err := json.Unmarshal(b, &items); err != nil {
		return 0, fmt.Errorf("helios: flags must be an array of names")
	}
	for _, item := range items {
		v, err := enumFromJSON(names, item)
		if err != nil {
			return 0, err
		}
		bits |= uint64(v)
	}
	return bits, nil
}

func ptrTo[T any](v T) *T { return &v }
